// ============================================================
//  add_syk_e.js – Sykepleie: mange flere oppgaver i anatomi, farmakologi, smittevern, klinisk, sykdomslære og lover/etikk,
//  og regnegeneratorer for minuttvolum, MAP, væskebalanse, halveringstid, blodsukker og energibehov.
// ============================================================
(() => {
// ================= Anatomi og fysiologi =================
BIQ("SANA", 0, [
 ["Hva er homeostase?", ["Kroppens evne til å holde et stabilt indre miljø", "Celledeling", "En sykdom", "Blodtrykket"], "For eksempel temperatur, blodsukker og pH holdes innenfor snevre grenser.", "What is homeostasis?", ["The body's ability to keep a stable internal environment", "Cell division", "A disease", "The blood pressure"], "For example temperature, blood sugar and pH are kept within narrow limits."],
 ["Hvilken vevstype kler innsiden av blodårer og organer?", ["Epitelvev", "Muskelvev", "Nervevev", "Bindevev"], "Epitel dekker overflater, både ute og inne.", "Which tissue type lines the inside of blood vessels and organs?", ["Epithelial tissue", "Muscle tissue", "Nervous tissue", "Connective tissue"], "Epithelium covers surfaces, both outside and inside."],
 ["Hva er normal kroppstemperatur, omtrent?", { n: 37, tol: 0.5, u: "°C" }, "Rundt 36,5–37,5 °C, lavest om morgenen.", "Roughly what is normal body temperature?", null, "Around 36.5–37.5 °C, lowest in the morning."],
 ["Hva skjer ved negativ tilbakekobling når temperaturen stiger?", ["Kroppen svetter og utvider blodårene i huden", "Kroppen skjelver", "Temperaturen stiger mer", "Ingenting"], "Responsen motvirker avviket.", "What happens in negative feedback when the temperature rises?", ["The body sweats and dilates skin blood vessels", "The body shivers", "The temperature rises further", "Nothing"], "The response counteracts the deviation."]
]);
BIQ("SANA", 1, [
 ["Hvilket hjertekammer pumper blod ut i kroppens store kretsløp?", ["Venstre ventrikkel", "Høyre ventrikkel", "Venstre atrium", "Høyre atrium"], "Venstre ventrikkel har tykkest vegg fordi den pumper ut i aorta.", "Which heart chamber pumps blood into the systemic circulation?", ["The left ventricle", "The right ventricle", "The left atrium", "The right atrium"], "The left ventricle has the thickest wall because it pumps into the aorta."],
 ["Hvor starter den elektriske impulsen i et friskt hjerte?", ["Sinusknuten", "AV-knuten", "Purkinjefibrene", "Aortaklaffen"], "Sinusknuten er hjertets naturlige pacemaker.", "Where does the electrical impulse start in a healthy heart?", ["The sinus node", "The AV node", "The Purkinje fibres", "The aortic valve"], "The sinus node is the heart's natural pacemaker."],
 ["Hvilke blodårer fører oksygenrikt blod fra lungene til hjertet?", ["Lungevenene", "Lungearteriene", "Hulvenene", "Aorta"], "Unntaket fra regelen: her er det venene som fører oksygenrikt blod.", "Which blood vessels carry oxygen-rich blood from the lungs to the heart?", ["The pulmonary veins", "The pulmonary arteries", "The venae cavae", "The aorta"], "The exception to the rule: here the veins carry oxygen-rich blood."],
 ["Hjertefrekvens 70/min og slagvolum 70 mL. Hva er minuttvolumet?", { n: 4.9, tol: 0.01, u: "L/min" }, "$70 \\cdot 70 = 4900$ mL/min $= 4{,}9$ L/min.", "Heart rate 70/min and stroke volume 70 mL. What is the cardiac output?", null, "$70 \\cdot 70 = 4900$ mL/min $= 4.9$ L/min."],
 ["Blodtrykk 120/80. Hva er middelarterietrykket (MAP), omtrent?", { n: 93, tol: 1, u: "mmHg" }, "$\\text{MAP} \\approx 80 + \\tfrac13(120 - 80) = 93$ mmHg.", "Blood pressure 120/80. Roughly what is the mean arterial pressure (MAP)?", null, "$\\text{MAP} \\approx 80 + \\tfrac13(120 - 80) = 93$ mmHg."]
]);
GEN("SANA", 1,
 () => { const hr = R.p([55, 60, 70, 80, 90, 110, 130]), sv = R.p([50, 60, 70, 80, 90]), co = hr * sv / 1000;
   return [T(`Hjertefrekvensen er ${hr}/min og slagvolumet ${sv} mL. Hva er minuttvolumet?`, `The heart rate is ${hr}/min and the stroke volume ${sv} mL. What is the cardiac output?`), { n: co, tol: 0.01, u: "L/min" },
     T(`$\\text{MV} = \\text{HF} \\cdot \\text{SV} = ${hr} \\cdot ${sv} = ${hr * sv}$ mL/min $= ${mf(co, 2)}$ L/min.`, `$\\text{CO} = \\text{HR} \\cdot \\text{SV} = ${hr} \\cdot ${sv} = ${hr * sv}$ mL/min $= ${mf(co, 2)}$ L/min.`)]; },
 () => { const s = R.p([90, 100, 110, 120, 140, 160, 180]), d = R.p([50, 60, 70, 80, 90, 100]), map = d + (s - d) / 3;
   return [T(`Blodtrykket er ${s}/${d} mmHg. Hva er middelarterietrykket (MAP)?`, `The blood pressure is ${s}/${d} mmHg. What is the mean arterial pressure (MAP)?`), { n: map, tol: 1, u: "mmHg" },
     T(`$\\text{MAP} = D + \\tfrac13(S - D) = ${d} + \\tfrac13 \\cdot ${s - d} = ${mf(map, 0)}$ mmHg. ${map < 65 ? "Under 65 mmHg kan gi for dårlig organperfusjon." : ""}`, `$\\text{MAP} = D + \\tfrac13(S - D) = ${d} + \\tfrac13 \\cdot ${s - d} = ${mf(map, 0)}$ mmHg. ${map < 65 ? "Below 65 mmHg can give poor organ perfusion." : ""}`)]; }
);
BIQ("SANA", 2, [
 ["Hvor skjer gassutvekslingen i lungene?", ["I alveolene", "I bronkiene", "I luftrøret", "I strupen"], "Alveolene har tynne vegger og et enormt areal (ca. 70 m²).", "Where does gas exchange take place in the lungs?", ["In the alveoli", "In the bronchi", "In the trachea", "In the larynx"], "The alveoli have thin walls and a huge area (about 70 m²)."],
 ["Hva er normal respirasjonsfrekvens hos voksne i hvile?", ["12–20 per minutt", "4–8 per minutt", "30–40 per minutt", "60–80 per minutt"], "Over 20 kan være tegn på sykdom (NEWS2 gir poeng fra 21).", "What is the normal resting respiratory rate in adults?", ["12–20 per minute", "4–8 per minute", "30–40 per minute", "60–80 per minute"], "Above 20 can be a sign of illness (NEWS2 scores from 21)."],
 ["Hva styrer pustedriften mest hos friske?", ["CO₂-nivået i blodet", "O₂-nivået", "Blodsukkeret", "Kroppstemperaturen"], "Stigende CO₂ (og fallende pH) øker pustedriften.", "What mainly drives breathing in healthy people?", ["The CO₂ level in the blood", "The O₂ level", "The blood sugar", "The body temperature"], "Rising CO₂ (and falling pH) increases the drive to breathe."],
 ["Hva er normal SpO₂ hos en frisk voksen?", ["96–100 %", "80–85 %", "70–75 %", "50 %"], "Under 92 % gir NEWS2 poeng (skala 1).", "What is normal SpO₂ in a healthy adult?", ["96–100 %", "80–85 %", "70–75 %", "50 %"], "Below 92 % scores in NEWS2 (scale 1)."]
]);
GEN("SANA", 2,
 () => { const rr = R.p([12, 14, 16, 20, 25, 30]), vt = R.p([400, 450, 500, 600]), mv = rr * vt / 1000;
   return [T(`Respirasjonsfrekvensen er ${rr}/min og tidalvolumet ${vt} mL. Hva er minuttventilasjonen?`, `The respiratory rate is ${rr}/min and the tidal volume ${vt} mL. What is the minute ventilation?`), { n: mv, tol: 0.01, u: "L/min" },
     T(`$${rr} \\cdot ${vt} = ${rr * vt}$ mL/min $= ${mf(mv, 2)}$ L/min.`, `$${rr} \\cdot ${vt} = ${rr * vt}$ mL/min $= ${mf(mv, 2)}$ L/min.`)]; }
);
BIQ("SANA", 3, [
 ["Hva består sentralnervesystemet av?", ["Hjernen og ryggmargen", "Hjernen og nervene i armene", "Alle nerver", "Bare hjernen"], "Resten er det perifere nervesystemet.", "What does the central nervous system consist of?", ["The brain and the spinal cord", "The brain and the nerves in the arms", "All nerves", "Only the brain"], "The rest is the peripheral nervous system."],
 ["Hva gjør det sympatiske nervesystemet?", ["Forbereder kroppen på «kamp eller flukt»", "Roer ned og fremmer fordøyelsen", "Styrer viljestyrte muskler", "Lager hormoner"], "Høyere puls, større pupiller, mer blod til musklene.", "What does the sympathetic nervous system do?", ["Prepares the body for \"fight or flight\"", "Calms down and promotes digestion", "Controls voluntary muscles", "Makes hormones"], "Higher pulse, larger pupils, more blood to the muscles."],
 ["Hvilken hjernedel styrer balanse og koordinasjon?", ["Lillehjernen", "Storhjernen", "Hjernestammen", "Hypofysen"], "Lillehjernen (cerebellum) finjusterer bevegelser.", "Which part of the brain controls balance and coordination?", ["The cerebellum", "The cerebrum", "The brainstem", "The pituitary gland"], "The cerebellum fine-tunes movements."],
 ["Hva er normal verdi på Glasgow Coma Scale (GCS)?", { n: 15, tol: 0, u: "" }, "GCS går fra 3 til 15. 8 eller lavere tyder på alvorlig redusert bevissthet.", "What is the normal Glasgow Coma Scale (GCS) score?", null, "GCS goes from 3 to 15. 8 or lower suggests severely reduced consciousness."]
]);
BIQ("SANA", 4, [
 ["Hva er nefronet?", ["Nyrens funksjonelle enhet", "En type blodcelle", "En del av leveren", "Et hormon"], "Hver nyre har omtrent én million nefroner som filtrerer blodet.", "What is the nephron?", ["The functional unit of the kidney", "A type of blood cell", "A part of the liver", "A hormone"], "Each kidney has about one million nephrons that filter the blood."],
 ["Hva er normal urinproduksjon hos voksne, omtrent?", ["1–2 liter per døgn", "5 liter per døgn", "100 mL per døgn", "10 liter per døgn"], "Under 0,5 mL/kg/t over tid kan tyde på nyresvikt eller dehydrering.", "Roughly what is normal urine output in adults?", ["1–2 litres per day", "5 litres per day", "100 mL per day", "10 litres per day"], "Below 0.5 mL/kg/h over time may suggest kidney failure or dehydration."],
 ["Hvilket elektrolytt er viktigst for hjerterytmen?", ["Kalium", "Jern", "Jod", "Sink"], "Både for høy og for lav kalium kan gi farlige arytmier.", "Which electrolyte is most important for the heart rhythm?", ["Potassium", "Iron", "Iodine", "Zinc"], "Both too high and too low potassium can cause dangerous arrhythmias."],
 ["Hva gjør ADH (antidiuretisk hormon)?", ["Får nyrene til å holde tilbake vann", "Øker urinmengden", "Senker blodsukkeret", "Øker pulsen"], "Ved lite væske i kroppen skilles det ut mer ADH, og urinen blir mer konsentrert.", "What does ADH (antidiuretic hormone) do?", ["Makes the kidneys retain water", "Increases urine volume", "Lowers blood sugar", "Increases the pulse"], "When the body has little fluid, more ADH is released, and the urine becomes more concentrated."]
]);
GEN("SANA", 4,
 () => { const kg = R.p([50, 60, 70, 80, 90, 100]), h = R.p([4, 6, 8, 12]), ml = R.p([80, 120, 150, 200, 300, 400]), rate = ml / kg / h;
   return [T(`En pasient på ${kg} kg har laget ${ml} mL urin de siste ${h} timene. Hvor mange mL/kg/t er det?`, `A ${kg} kg patient has produced ${ml} mL of urine in the last ${h} hours. How many mL/kg/h is that?`), { n: rate, tol: 0.01, u: "mL/kg/t" },
     T(`$\\dfrac{${ml}}{${kg} \\cdot ${h}} = ${mf(rate, 2)}$ mL/kg/t. ${rate < 0.5 ? "Under 0,5: for lite, varsle lege." : "Over 0,5: innenfor."}`, `$\\dfrac{${ml}}{${kg} \\cdot ${h}} = ${mf(rate, 2)}$ mL/kg/h. ${rate < 0.5 ? "Below 0.5: too little, inform the doctor." : "Above 0.5: acceptable."}`)]; }
);
BIQ("SANA", 5, [
 ["Hvor tas mesteparten av næringsstoffene opp?", ["I tynntarmen", "I magesekken", "I tykktarmen", "I spiserøret"], "Tynntarmen har tarmtotter som gir et enormt areal.", "Where are most nutrients absorbed?", ["In the small intestine", "In the stomach", "In the large intestine", "In the oesophagus"], "The small intestine has villi that give a huge area."],
 ["Hva er tykktarmens viktigste oppgave?", ["Ta opp vann og salter", "Fordøye protein", "Lage galle", "Lage insulin"], "Tarminnholdet blir fastere på veien gjennom tykktarmen.", "What is the main job of the large intestine?", ["Absorb water and salts", "Digest protein", "Make bile", "Make insulin"], "The contents become firmer on the way through the large intestine."],
 ["Hvor lages galle?", ["I leveren", "I galleblæren", "I bukspyttkjertelen", "I magesekken"], "Galleblæren lagrer bare gallen.", "Where is bile made?", ["In the liver", "In the gallbladder", "In the pancreas", "In the stomach"], "The gallbladder only stores bile."],
 ["Hvor mange kcal gir 1 gram fett, omtrent?", { n: 9, tol: 0, u: "kcal" }, "Fett gir 9 kcal/g, karbohydrat og protein omtrent 4 kcal/g.", "Roughly how many kcal does 1 gram of fat give?", null, "Fat gives 9 kcal/g, carbohydrate and protein about 4 kcal/g."]
]);
// ================= Farmakologi =================
BIQ("SFARM", 0, [
 ["Hvor lang tid tar det omtrent å nå steady state?", ["4–5 halveringstider", "1 halveringstid", "10 halveringstider", "Én dose"], "Etter 4–5 halveringstider er konsentrasjonen over 90 % av steady state.", "Roughly how long does it take to reach steady state?", ["4–5 half-lives", "1 half-life", "10 half-lives", "One dose"], "After 4–5 half-lives the concentration is over 90 % of steady state."],
 ["Hva er førstepassasjemetabolisme?", ["At leveren bryter ned en del av legemidlet før det når blodet", "At legemidlet skilles ut i urinen", "Første dose", "Allergi"], "Gjelder legemidler tatt gjennom munnen. Derfor er orale doser ofte høyere enn intravenøse.", "What is first-pass metabolism?", ["The liver breaking down part of the drug before it reaches the blood", "The drug being excreted in urine", "The first dose", "Allergy"], "It applies to drugs taken by mouth. That is why oral doses are often higher than intravenous ones."],
 ["Hvilket organ skiller ut de fleste legemidler?", ["Nyrene", "Lungene", "Huden", "Hjertet"], "Ved nedsatt nyrefunksjon må mange doser reduseres.", "Which organ excretes most drugs?", ["The kidneys", "The lungs", "The skin", "The heart"], "With reduced kidney function many doses must be lowered."],
 ["Halveringstiden er 6 timer. Hvor mye er igjen etter 24 timer?", { n: 6.25, tol: 0.01, u: "%" }, "4 halveringstider: $100 \\cdot 0{,}5^4 = 6{,}25$ %.", "The half-life is 6 hours. How much is left after 24 hours?", null, "4 half-lives: $100 \\cdot 0.5^4 = 6.25$ %."]
]);
GEN("SFARM", 0,
 () => { const T12 = R.p([2, 4, 6, 8, 12]), n = R.i(1, 6), dose = R.p([100, 200, 500, 1000]), left = dose * 0.5 ** n;
   return [T(`Et legemiddel har halveringstid ${T12} timer. Pasienten får ${dose} mg. Hvor mye er igjen i kroppen etter ${n * T12} timer?`, `A drug has a half-life of ${T12} hours. The patient gets ${dose} mg. How much is left in the body after ${n * T12} hours?`), { n: left, tol: rel(left, 0.01), u: "mg" },
     T(`${n} halveringstider: $${dose} \\cdot 0{,}5^{${n}} = ${mf(left, 2)}$ mg.`, `${n} half-lives: $${dose} \\cdot 0.5^{${n}} = ${mf(left, 2)}$ mg.`)]; },
 () => { const T12 = R.p([3, 6, 8, 12, 24, 36]), ss = 5 * T12;
   return [T(`Et legemiddel har halveringstid ${T12} timer og gis jevnlig. Omtrent hvor mange timer tar det å nå steady state (5 halveringstider)?`, `A drug has a half-life of ${T12} hours and is given regularly. Roughly how many hours does it take to reach steady state (5 half-lives)?`), { n: ss, tol: 0, u: T("timer", "hours") },
     T(`$5 \\cdot ${T12} = ${ss}$ timer.`, `$5 \\cdot ${T12} = ${ss}$ hours.`)]; }
);
BIQ("SFARM", 1, [
 ["Hva er en agonist?", ["Et stoff som binder seg til reseptoren og aktiverer den", "Et stoff som blokkerer reseptoren", "En bivirkning", "En type tablett"], "Morfin er en agonist på opioidreseptorer.", "What is an agonist?", ["A substance that binds to the receptor and activates it", "A substance that blocks the receptor", "A side effect", "A type of tablet"], "Morphine is an agonist at opioid receptors."],
 ["Hva er naloksons virkning?", ["Opioidantagonist som opphever overdose", "Smertestillende", "Sovemiddel", "Antibiotikum"], "Nalokson fortrenger opioider fra reseptorene.", "What is naloxone's action?", ["Opioid antagonist that reverses overdose", "Painkiller", "Sleeping pill", "Antibiotic"], "Naloxone displaces opioids from the receptors."],
 ["Hva betyr et smalt terapeutisk vindu?", ["Liten forskjell mellom virksom og giftig dose", "Legemidlet virker bare om morgenen", "Legemidlet er billig", "Legemidlet har ingen bivirkninger"], "Eksempler: digoksin, litium, warfarin. Krever nøye kontroll.", "What does a narrow therapeutic window mean?", ["Small difference between effective and toxic dose", "The drug only works in the morning", "The drug is cheap", "The drug has no side effects"], "Examples: digoxin, lithium, warfarin. Requires close monitoring."],
 ["Hva er en vanlig bivirkning av opioider?", ["Obstipasjon", "Diaré", "Høyt blodtrykk", "Økt pustefrekvens"], "Opioider bremser tarmen, og de kan også gi respirasjonsdepresjon.", "What is a common side effect of opioids?", ["Constipation", "Diarrhoea", "High blood pressure", "Increased respiratory rate"], "Opioids slow the gut, and they can also cause respiratory depression."]
]);
BIQ("SFARM", 2, [
 ["Hvilken legemiddelgruppe er furosemid?", ["Diuretika (vanndrivende)", "Antibiotika", "Opioider", "Betablokkere"], "Brukes ved hjertesvikt og ødemer. Kan gi lav kalium.", "Which drug group is furosemide?", ["Diuretics (water tablets)", "Antibiotics", "Opioids", "Beta blockers"], "Used in heart failure and oedema. Can cause low potassium."],
 ["Hva gjør betablokkere?", ["Senker puls og blodtrykk", "Øker puls", "Dreper bakterier", "Senker blodsukkeret"], "De blokkerer effekten av adrenalin på hjertet.", "What do beta blockers do?", ["Lower pulse and blood pressure", "Increase pulse", "Kill bacteria", "Lower blood sugar"], "They block the effect of adrenaline on the heart."],
 ["Hvilket legemiddel brukes mot anafylaksi?", ["Adrenalin", "Paracetamol", "Insulin", "Morfin"], "Adrenalin intramuskulært er førstevalg ved anafylaktisk sjokk.", "Which drug is used for anaphylaxis?", ["Adrenaline", "Paracetamol", "Insulin", "Morphine"], "Intramuscular adrenaline is first choice in anaphylactic shock."],
 ["Hva er maksimal døgndose paracetamol for en frisk voksen?", ["4 g", "10 g", "1 g", "20 g"], "Høyere doser kan gi alvorlig leverskade. Lavere maks ved lav vekt, alkohol eller leversykdom.", "What is the maximum daily dose of paracetamol for a healthy adult?", ["4 g", "10 g", "1 g", "20 g"], "Higher doses can cause severe liver damage. Lower maximum with low weight, alcohol or liver disease."]
]);
BIQ("SFARM", 3, [
 ["Hva er de «5 R-ene» ved legemiddelhåndtering?", ["Riktig pasient, legemiddel, dose, administrasjonsmåte og tid", "Rask, rolig, ren, riktig, rapport", "Rett rom, rett seng", "Ingen av delene"], "Sjekk alle fem hver gang for å unngå feil.", "What are the \"5 rights\" of medication administration?", ["Right patient, drug, dose, route and time", "Fast, calm, clean, correct, report", "Right room, right bed", "None of these"], "Check all five every time to avoid errors."],
 ["Hvordan oppbevares de fleste legemidler?", ["Tørt, mørkt og ved romtemperatur, innelåst", "I kjøleskap alltid", "I sollys", "I badet"], "Noen, som insulin i bruk og vaksiner, har egne krav.", "How are most drugs stored?", ["Dry, dark and at room temperature, locked away", "Always in the fridge", "In sunlight", "In the bathroom"], "Some, like insulin in use and vaccines, have their own requirements."],
 ["Hva skal du gjøre hvis du oppdager en legemiddelfeil?", ["Varsle ansvarlig lege, observere pasienten og melde avviket", "Ingenting hvis det gikk bra", "Skjule det", "Gi en ny dose"], "Åpen avviksmelding er viktig for pasientsikkerheten.", "What should you do if you discover a medication error?", ["Inform the responsible doctor, observe the patient and report the incident", "Nothing if it went well", "Hide it", "Give another dose"], "Open incident reporting is important for patient safety."],
 ["Kan depottabletter knuses?", ["Nei, da kan hele dosen frigjøres på én gang", "Ja, alltid", "Bare hvis pasienten ber om det", "Ja, i vann"], "Knusing kan gi overdose og ødelegge depotvirkningen.", "Can extended-release tablets be crushed?", ["No, the whole dose may then be released at once", "Yes, always", "Only if the patient asks", "Yes, in water"], "Crushing can cause overdose and destroy the extended release."]
]);
// ================= Mikrobiologi og smittevern =================
BIQ("SMIK", 0, [
 ["Hva er forskjellen på bakterier og virus?", ["Bakterier er levende celler, virus trenger en vertscelle for å formere seg", "Virus er større", "Bakterier har ikke DNA", "Ingen forskjell"], "Derfor virker antibiotika mot bakterier, men ikke virus.", "What is the difference between bacteria and viruses?", ["Bacteria are living cells, viruses need a host cell to multiply", "Viruses are larger", "Bacteria have no DNA", "No difference"], "That is why antibiotics work against bacteria but not viruses."],
 ["Hva er normalflora?", ["Mikrober som naturlig lever på og i kroppen", "Sykdomsbakterier", "Blomster på sykehus", "Soppinfeksjoner"], "Normalfloraen beskytter mot sykdomsfremkallende mikrober.", "What is normal flora?", ["Microbes that naturally live on and in the body", "Disease-causing bacteria", "Flowers in hospitals", "Fungal infections"], "The normal flora protects against disease-causing microbes."],
 ["Hvilken mikrobe forårsaker oftest urinveisinfeksjon?", ["E. coli", "Influensavirus", "Candida", "Tuberkelbasillen"], "E. coli fra tarmen er den vanligste årsaken.", "Which microbe most often causes urinary tract infections?", ["E. coli", "Influenza virus", "Candida", "The tubercle bacillus"], "E. coli from the gut is the most common cause."]
]);
GEN("SMIK", 0,
 () => { const dt = R.p([20, 30]), h = R.p([2, 3, 4, 6]), n = 2 ** (h * 60 / dt);
   return [T(`En bakterie deler seg hvert ${dt}. minutt under gode forhold. Hvor mange bakterier blir én bakterie til etter ${h} timer?`, `A bacterium divides every ${dt} minutes under good conditions. How many bacteria does one become after ${h} hours?`), { n, tol: 0, u: "" },
     T(`${h * 60 / dt} delinger: $2^{${h * 60 / dt}} = ${nf(n, 0)}$. Derfor er rask håndtering av mat og sår viktig.`, `${h * 60 / dt} divisions: $2^{${h * 60 / dt}} = ${nf(n, 0)}$. That is why prompt handling of food and wounds matters.`)]; }
);
BIQ("SMIK", 1, [
 ["Hva er det viktigste enkelttiltaket for å hindre smitte på sykehus?", ["Håndhygiene", "Munnbind hele tiden", "Antibiotika til alle", "Isolering av alle"], "Hånddesinfeksjon før og etter pasientkontakt bryter smittekjeden.", "What is the single most important measure to prevent infection in hospitals?", ["Hand hygiene", "Masks all the time", "Antibiotics for everyone", "Isolating everyone"], "Hand disinfection before and after patient contact breaks the chain of infection."],
 ["Når skal du bruke hansker?", ["Ved risiko for kontakt med blod, kroppsvæsker eller slimhinner", "Alltid", "Aldri", "Bare når du spiser"], "Hansker erstatter ikke håndhygiene: desinfiser før og etter.", "When should you use gloves?", ["When there is a risk of contact with blood, body fluids or mucous membranes", "Always", "Never", "Only when eating"], "Gloves do not replace hand hygiene: disinfect before and after."],
 ["Hvilke ledd har smittekjeden?", ["Smittestoff, smittekilde, smittevei og mottakelig vert", "Bakterie, virus, sopp", "Pasient, lege, sykepleier", "Hoste, nys, feber"], "Bryter du ett ledd, stopper smitten.", "What links does the chain of infection have?", ["Pathogen, source, route of transmission and susceptible host", "Bacterium, virus, fungus", "Patient, doctor, nurse", "Cough, sneeze, fever"], "Break one link and the infection stops."],
 ["Hva er dråpesmitte?", ["Smitte via store dråper fra hoste og nys over kort avstand", "Smitte via blod", "Smitte via mat", "Smitte via insekter"], "Influensa smitter hovedsakelig som dråpesmitte (under 1–2 meter).", "What is droplet transmission?", ["Spread via large droplets from coughs and sneezes over short distances", "Spread via blood", "Spread via food", "Spread via insects"], "Influenza spreads mainly by droplets (under 1–2 metres)."]
]);
BIQ("SMIK", 2, [
 ["Hva er MRSA?", ["Gule stafylokokker som er resistente mot vanlige penicilliner", "Et virus", "En vaksine", "En sopp"], "Meticillinresistente *Staphylococcus aureus*.", "What is MRSA?", ["Staphylococcus aureus resistant to common penicillins", "A virus", "A vaccine", "A fungus"], "Meticillin-resistant *Staphylococcus aureus*."],
 ["Hvorfor er det viktig å fullføre en antibiotikakur?", ["Det minsker risikoen for at bakterier overlever og blir resistente", "For å få bivirkninger", "Det er ikke viktig", "For å bli immun"], "Følg alltid legens forskrivning.", "Why is it important to finish a course of antibiotics?", ["It reduces the risk that bacteria survive and become resistant", "To get side effects", "It isn't important", "To become immune"], "Always follow the doctor's prescription."],
 ["Hvilken antibiotikagruppe er penicillin?", ["Betalaktamer", "Aminoglykosider", "Makrolider", "Kinoloner"], "Betalaktamer hindrer bakteriene i å bygge celleveggen.", "Which antibiotic group is penicillin?", ["Beta-lactams", "Aminoglycosides", "Macrolides", "Quinolones"], "Beta-lactams stop the bacteria from building their cell wall."]
]);
// ================= Klinisk sykepleie =================
BIQ("SKLIN", 0, [
 ["Hva er normal hvilepuls hos voksne?", ["50–90 slag per minutt", "20–40", "100–140", "140–180"], "NEWS2 gir poeng under 51 og over 90.", "What is a normal resting pulse in adults?", ["50–90 beats per minute", "20–40", "100–140", "140–180"], "NEWS2 scores below 51 and above 90."],
 ["Hvilket systolisk blodtrykk gir 3 poeng i NEWS2?", ["90 mmHg eller lavere", "120 mmHg", "130 mmHg", "110 mmHg"], "Lavt blodtrykk kan være tegn på sjokk.", "Which systolic blood pressure gives 3 points in NEWS2?", ["90 mmHg or lower", "120 mmHg", "130 mmHg", "110 mmHg"], "Low blood pressure can be a sign of shock."],
 ["Hvor lenge bør du telle respirasjonsfrekvensen?", ["Et helt minutt", "5 sekunder", "10 sekunder", "Det er ikke nødvendig"], "Pusten er uregelmessig, så et helt minutt gir sikrere tall.", "How long should you count the respiratory rate?", ["A whole minute", "5 seconds", "10 seconds", "It is not necessary"], "Breathing is irregular, so a whole minute gives a more reliable count."],
 ["Pasienten har temperatur 38,6 °C. Hva kalles det?", ["Feber", "Hypotermi", "Normal", "Sjokk"], "Over 38 °C regnes som feber.", "The patient's temperature is 38.6 °C. What is that called?", ["Fever", "Hypothermia", "Normal", "Shock"], "Above 38 °C is considered fever."]
]);
BIQ("SKLIN", 1, [
 ["Hva står ABCDE for i vurderingen av en akutt syk pasient?", ["Luftvei, pust, sirkulasjon, bevissthet, eksponering", "Alder, blod, cellestatus, diagnose, energi", "Alarm, behandling, kontroll, dokumentasjon, evaluering", "Ingen av delene"], "Airway, Breathing, Circulation, Disability, Exposure – i den rekkefølgen.", "What does ABCDE stand for in assessing an acutely ill patient?", ["Airway, breathing, circulation, disability, exposure", "Age, blood, cell status, diagnosis, energy", "Alarm, treatment, control, documentation, evaluation", "None of these"], "Airway, Breathing, Circulation, Disability, Exposure – in that order."],
 ["NEWS2 er 7. Hva skal gjøres?", ["Akutt vurdering av lege/akutteam og kontinuerlig overvåking", "Ny måling om 12 timer", "Ingenting", "Pasienten kan skrives ut"], "7 eller mer er høy risiko.", "NEWS2 is 7. What should be done?", ["Emergency assessment by doctor/rapid response team and continuous monitoring", "New measurement in 12 hours", "Nothing", "The patient can be discharged"], "7 or more is high risk."],
 ["Hva er ISBAR?", ["En struktur for muntlig rapport", "Et legemiddel", "En skala for smerte", "En type sjokk"], "Identifikasjon, Situasjon, Bakgrunn, Aktuell vurdering, Råd.", "What is ISBAR?", ["A structure for verbal handover", "A drug", "A pain scale", "A type of shock"], "Identify, Situation, Background, Assessment, Recommendation."]
]);
BIQ("SKLIN", 2, [
 ["Hva er BMI for en person på 80 kg og 1,80 m?", { n: 24.7, tol: 0.05, u: "kg/m²" }, "$\\dfrac{80}{1{,}8^2} = 24{,}7$.", "What is the BMI of a person weighing 80 kg who is 1.80 m tall?", null, "$\\dfrac{80}{1.8^2} = 24.7$."],
 ["Omtrent hvor mye væske trenger en voksen per døgn?", ["30–35 mL per kg", "5 mL per kg", "100 mL per kg", "1 L totalt"], "En pasient på 70 kg trenger rundt 2–2,5 liter.", "Roughly how much fluid does an adult need per day?", ["30–35 mL per kg", "5 mL per kg", "100 mL per kg", "1 L in total"], "A 70 kg patient needs about 2–2.5 litres."],
 ["Hva er tegn på dehydrering?", ["Tørre slimhinner, lite og mørk urin, høy puls", "Mye lys urin", "Ødemer i beina", "Lav puls"], "Eldre har svekket tørstefølelse og er spesielt utsatt.", "What are signs of dehydration?", ["Dry mucous membranes, little dark urine, high pulse", "Lots of pale urine", "Oedema in the legs", "Low pulse"], "Elderly people have a weaker sense of thirst and are especially at risk."]
]);
GEN("SKLIN", 2,
 () => { const inn = [R.p([500, 800, 1000, 1200]), R.p([0, 500, 1000, 1500])], out = [R.p([800, 1200, 1500, 2000]), R.p([0, 100, 200, 400])], bal = inn[0] + inn[1] - out[0] - out[1];
   return [T(`Siste døgn har pasienten drukket ${inn[0]} mL og fått ${inn[1]} mL intravenøst. Urin: ${out[0]} mL, oppkast/dren: ${out[1]} mL. Hva er væskebalansen (uten perspiratio)?`, `In the last 24 hours the patient drank ${inn[0]} mL and received ${inn[1]} mL intravenously. Urine: ${out[0]} mL, vomit/drain: ${out[1]} mL. What is the fluid balance (excluding insensible loss)?`), { n: bal, tol: 0, u: "mL" },
     T(`Inn $${inn[0] + inn[1]}$ mL minus ut $${out[0] + out[1]}$ mL $= ${bal}$ mL. ${bal < 0 ? "Negativ balanse." : "Positiv balanse."}`, `In $${inn[0] + inn[1]}$ mL minus out $${out[0] + out[1]}$ mL $= ${bal}$ mL. ${bal < 0 ? "Negative balance." : "Positive balance."}`)]; },
 () => { const kg = R.p([45, 55, 60, 70, 80, 95]), f = R.p([25, 30, 35]), kcal = kg * f;
   return [T(`En pasient på ${kg} kg har et beregnet energibehov på ${f} kcal/kg per døgn. Hvor mange kcal trenger pasienten?`, `A ${kg} kg patient has an estimated energy need of ${f} kcal/kg per day. How many kcal does the patient need?`), { n: kcal, tol: 0, u: "kcal" },
     T(`$${kg} \\cdot ${f} = ${kcal}$ kcal per døgn.`, `$${kg} \\cdot ${f} = ${kcal}$ kcal per day.`)]; }
);
// ================= Sykdomslære =================
BIQ("SSYK", 0, [
 ["Hva er vanligste årsak til hjerteinfarkt?", ["En blodpropp i en kransarterie", "Høy puls", "Lavt blodsukker", "Infeksjon"], "Aterosklerotisk plakk sprekker, og det dannes en propp som stenger blodtilførselen.", "What is the most common cause of a heart attack?", ["A blood clot in a coronary artery", "High pulse", "Low blood sugar", "Infection"], "An atherosclerotic plaque ruptures, and a clot forms that blocks the blood supply."],
 ["Hvilket symptom er typisk ved venstresidig hjertesvikt?", ["Tung pust (lungestuvning)", "Hevelse i beina først", "Gulsott", "Utslett"], "Blodet hoper seg opp bakover i lungene.", "Which symptom is typical of left-sided heart failure?", ["Shortness of breath (pulmonary congestion)", "Swollen legs first", "Jaundice", "Rash"], "Blood backs up into the lungs."],
 ["Hva er atrieflimmer?", ["Uregelmessig, rask aktivitet i forkamrene", "En hjerteklaff som lekker", "Et hjerteinfarkt", "Normal hjerterytme"], "Gir økt risiko for blodpropp og hjerneslag.", "What is atrial fibrillation?", ["Irregular, rapid activity in the atria", "A leaking heart valve", "A heart attack", "Normal heart rhythm"], "It increases the risk of blood clots and stroke."],
 ["Hva regnes som høyt blodtrykk hos voksne (målt hos lege)?", ["140/90 mmHg eller høyere", "120/80 mmHg", "100/60 mmHg", "130/85 mmHg"], "Hypertensjon øker risikoen for hjerneslag og hjerteinfarkt.", "What is considered high blood pressure in adults (measured at the doctor's)?", ["140/90 mmHg or higher", "120/80 mmHg", "100/60 mmHg", "130/85 mmHg"], "Hypertension increases the risk of stroke and heart attack."]
]);
BIQ("SSYK", 1, [
 ["Hva kjennetegner KOLS?", ["Varig nedsatt luftstrøm, ofte etter røyking", "Plutselig og helt reversibel tetthet", "En bakterieinfeksjon", "En hjertesykdom"], "Kronisk obstruktiv lungesykdom. Astma er derimot i stor grad reversibel.", "What characterises COPD?", ["Permanently reduced airflow, often after smoking", "Sudden and fully reversible tightness", "A bacterial infection", "A heart disease"], "Chronic obstructive pulmonary disease. Asthma, by contrast, is largely reversible."],
 ["Hvorfor må man være forsiktig med mye oksygen til noen KOLS-pasienter?", ["De kan ha CO₂-retensjon, og mye O₂ kan svekke pustedriften", "Oksygen er giftig for alle", "De tåler ikke plastslanger", "Det er ingen grunn"], "Mål ofte SpO₂ 88–92 % for disse (NEWS2 skala 2).", "Why must one be careful with a lot of oxygen for some COPD patients?", ["They may have CO₂ retention, and a lot of O₂ can weaken the drive to breathe", "Oxygen is toxic for everyone", "They cannot tolerate plastic tubes", "There is no reason"], "Often aim for SpO₂ 88–92 % for these patients (NEWS2 scale 2)."],
 ["Hva er typiske symptomer på lungebetennelse?", ["Feber, hoste, tung pust og brystsmerter", "Hodepine alene", "Utslett", "Leddsmerter"], "Hos eldre kan forvirring være eneste tegn.", "What are typical symptoms of pneumonia?", ["Fever, cough, shortness of breath and chest pain", "Headache alone", "Rash", "Joint pain"], "In the elderly, confusion may be the only sign."]
]);
BIQ("SSYK", 2, [
 ["Hva er forskjellen på diabetes type 1 og type 2?", ["Type 1: kroppen lager ikke insulin. Type 2: nedsatt insulinvirkning", "Type 2 rammer bare barn", "Type 1 skyldes alltid livsstil", "Ingen forskjell"], "Type 1 er autoimmun og krever insulin fra start.", "What is the difference between type 1 and type 2 diabetes?", ["Type 1: the body makes no insulin. Type 2: reduced insulin effect", "Type 2 only affects children", "Type 1 is always due to lifestyle", "No difference"], "Type 1 is autoimmune and requires insulin from the start."],
 ["Hva er normalt fastende blodsukker?", ["4–6 mmol/L", "10–15 mmol/L", "1–2 mmol/L", "20 mmol/L"], "Fastende 7,0 eller høyere på to målinger gir diabetesdiagnose.", "What is normal fasting blood glucose?", ["4–6 mmol/L", "10–15 mmol/L", "1–2 mmol/L", "20 mmol/L"], "Fasting 7.0 or higher on two measurements gives a diabetes diagnosis."],
 ["Pasienten er svett, skjelven og forvirret. Blodsukker 2,8. Hva gjør du først?", ["Gir raske karbohydrater (sukker) hvis pasienten kan svelge", "Gir insulin", "Venter og måler igjen i morgen", "Gir vann"], "Hypoglykemi behandles med sukker. Er pasienten bevisstløs: glukagon eller intravenøs glukose.", "The patient is sweaty, shaky and confused. Blood glucose 2.8. What do you do first?", ["Give fast carbohydrates (sugar) if the patient can swallow", "Give insulin", "Wait and measure again tomorrow", "Give water"], "Hypoglycaemia is treated with sugar. If unconscious: glucagon or intravenous glucose."],
 ["Hva er HbA1c et mål på?", ["Gjennomsnittlig blodsukker de siste 2–3 månedene", "Blodsukker akkurat nå", "Kolesterol", "Nyrefunksjon"], "Glukose fester seg til hemoglobinet i de røde blodcellene.", "What does HbA1c measure?", ["Average blood glucose over the last 2–3 months", "Blood glucose right now", "Cholesterol", "Kidney function"], "Glucose attaches to the haemoglobin in red blood cells."]
]);
GEN("SSYK", 2,
 () => { const mmol = R.p([3, 4.5, 5.5, 7, 10, 15, 22]), mg = mmol * 18;
   return [T(`Et blodsukker på ${nf(mmol)} mmol/L. Hva er det i mg/dL (brukt i mange utenlandske kilder)?`, `A blood glucose of ${nf(mmol)} mmol/L. What is it in mg/dL (used in many foreign sources)?`), { n: mg, tol: 1, u: "mg/dL" },
     T(`Gang med 18: $${mf(mmol)} \\cdot 18 = ${mf(mg, 0)}$ mg/dL.`, `Multiply by 18: $${mf(mmol)} \\cdot 18 = ${mf(mg, 0)}$ mg/dL.`)]; }
);
BIQ("SSYK", 3, [
 ["Hva er sepsis?", ["Livstruende organsvikt på grunn av en feilregulert respons på infeksjon", "En vanlig forkjølelse", "En allergi", "En hjertesykdom"], "Tidlig antibiotika og væske redder liv. Tid er avgjørende.", "What is sepsis?", ["Life-threatening organ failure due to a dysregulated response to infection", "A common cold", "An allergy", "A heart disease"], "Early antibiotics and fluids save lives. Time is crucial."],
 ["Hva er de tre kriteriene i qSOFA?", ["RF ≥ 22, endret bevissthet og systolisk BT ≤ 100", "Feber, hoste og utslett", "Puls, temperatur og vekt", "Blodsukker, HbA1c og BMI"], "To eller flere gir mistanke om sepsis med høy risiko.", "What are the three criteria in qSOFA?", ["RR ≥ 22, altered mental state and systolic BP ≤ 100", "Fever, cough and rash", "Pulse, temperature and weight", "Blood sugar, HbA1c and BMI"], "Two or more suggest high-risk sepsis."],
 ["Hvorfor tas blodkultur før antibiotika startes?", ["For å finne bakterien før antibiotikaen dreper den", "Det er ikke nødvendig", "For å måle blodsukker", "For å finne blodtypen"], "Men antibiotika skal ikke utsettes lenge ved alvorlig sepsis.", "Why are blood cultures taken before starting antibiotics?", ["To identify the bacterium before the antibiotic kills it", "It is not necessary", "To measure blood sugar", "To find the blood type"], "But antibiotics must not be delayed long in severe sepsis."]
]);
GEN("SSYK", 3,
 () => { const rr = R.p([16, 20, 22, 26, 30]), gcs = R.p([15, 15, 14, 12]), sbp = R.p([140, 120, 100, 90, 85]), score = (rr >= 22) + (gcs < 15) + (sbp <= 100);
   return [T(`Respirasjonsfrekvens ${rr}/min, GCS ${gcs}, systolisk blodtrykk ${sbp} mmHg. Hva er qSOFA-skåren?`, `Respiratory rate ${rr}/min, GCS ${gcs}, systolic blood pressure ${sbp} mmHg. What is the qSOFA score?`), { n: score, tol: 0, u: "" },
     T(`RF ≥ 22: ${rr >= 22 ? "1" : "0"}, endret bevissthet (GCS < 15): ${gcs < 15 ? "1" : "0"}, BT ≤ 100: ${sbp <= 100 ? "1" : "0"}. Sum: ${score}. ${score >= 2 ? "Høy risiko: varsle lege straks." : ""}`, `RR ≥ 22: ${rr >= 22 ? "1" : "0"}, altered mentation (GCS < 15): ${gcs < 15 ? "1" : "0"}, BP ≤ 100: ${sbp <= 100 ? "1" : "0"}. Total: ${score}. ${score >= 2 ? "High risk: inform the doctor immediately." : ""}`)]; }
);
BIQ("SSYK", 4, [
 ["Hva står FAST for ved mistanke om hjerneslag?", ["Face, Arm, Speech, Time", "Feber, Angst, Smerte, Tretthet", "Fall, Anfall, Svimmelhet, Tåke", "Ingen av delene"], "Skjevt ansikt, svak arm, utydelig tale: ring 113 straks.", "What does FAST stand for when stroke is suspected?", ["Face, Arm, Speech, Time", "Fever, Anxiety, Sickness, Tiredness", "Fall, Attack, Syncope, Trauma", "None of these"], "Drooping face, weak arm, slurred speech: call the emergency number immediately."],
 ["Hvorfor er tid så viktig ved hjerneslag?", ["Hjerneceller dør raskt, og trombolyse virker bare de første timene", "Det er ikke viktig", "Pasienten blir sulten", "For å rekke å ta blodprøver"], "«Tid er hjerne».", "Why is time so important in stroke?", ["Brain cells die quickly, and thrombolysis only works in the first hours", "It isn't important", "The patient gets hungry", "To have time for blood tests"], "\"Time is brain\"."],
 ["Et hjerneslag i venstre hjernehalvdel gir oftest lammelse i …", ["høyre side av kroppen", "venstre side", "begge sider", "bare ansiktet"], "Nervebanene krysser. Venstre side styrer også oftest språket.", "A stroke in the left hemisphere most often causes paralysis on …", ["the right side of the body", "the left side", "both sides", "only the face"], "The nerve pathways cross. The left side also usually controls language."]
]);
// ================= Lover, etikk og kommunikasjon =================
BIQ("SLOV", 0, [
 ["Hvem har taushetsplikt etter helsepersonelloven?", ["Alt helsepersonell, også studenter i praksis", "Bare leger", "Bare sykepleiere", "Ingen"], "Taushetsplikten gjelder også etter at du har sluttet.", "Who has a duty of confidentiality under the Health Personnel Act?", ["All health personnel, including students on placement", "Only doctors", "Only nurses", "Nobody"], "The duty of confidentiality also applies after you have left."],
 ["Når har helsepersonell opplysningsplikt til barnevernet?", ["Ved grunn til å tro at et barn blir mishandlet eller utsatt for alvorlig omsorgssvikt", "Aldri", "Bare når foreldrene samtykker", "Bare hvis barnet ber om det"], "Opplysningsplikten går foran taushetsplikten.", "When do health personnel have a duty to inform child welfare services?", ["When there is reason to believe a child is abused or seriously neglected", "Never", "Only when the parents consent", "Only if the child asks"], "The duty to inform overrides confidentiality."],
 ["Hva betyr forsvarlighetskravet?", ["Helsepersonell skal arbeide faglig forsvarlig og kjenne sine grenser", "Man må alltid gjøre alt pasienten ber om", "Man må ha forsikring", "Man må jobbe fort"], "Helsepersonelloven § 4.", "What does the requirement of professional responsibility mean?", ["Health personnel must work in a professionally sound way and know their limits", "You must always do everything the patient asks", "You must have insurance", "You must work fast"], "Section 4 of the Health Personnel Act."]
]);
BIQ("SLOV", 1, [
 ["Hva er informert samtykke?", ["Pasienten får nødvendig informasjon og sier ja til helsehjelpen", "Legen bestemmer alt", "Pårørende bestemmer", "Pasienten skriver under uten å lese"], "Hovedregelen i pasient- og brukerrettighetsloven.", "What is informed consent?", ["The patient gets the necessary information and agrees to the care", "The doctor decides everything", "The relatives decide", "The patient signs without reading"], "The main rule in the Patient and User Rights Act."],
 ["Fra hvilken alder kan man som hovedregel samtykke selv til helsehjelp i Norge?", { n: 16, tol: 0, u: T("år", "years") }, "Den helserettslige myndighetsalderen er 16 år.", "From what age can one, as a rule, consent to health care oneself in Norway?", null, "The age of majority for health care is 16 years."],
 ["Har pasienten rett til å se journalen sin?", ["Ja, med noen få unntak", "Nei, aldri", "Bare med advokat", "Bare etter døden"], "Pasienten kan også be om retting av feil.", "Does the patient have the right to see their records?", ["Yes, with a few exceptions", "No, never", "Only with a lawyer", "Only after death"], "The patient can also request that errors be corrected."]
]);
BIQ("SLOV", 2, [
 ["Hva er autonomiprinsippet?", ["Respekt for pasientens rett til å bestemme selv", "Å gjøre godt", "Ikke å skade", "Rettferdig fordeling"], "De fire prinsippene: autonomi, velgjørenhet, ikke-skade og rettferdighet.", "What is the principle of autonomy?", ["Respect for the patient's right to decide for themselves", "Doing good", "Not doing harm", "Fair distribution"], "The four principles: autonomy, beneficence, non-maleficence and justice."],
 ["Hva er paternalisme i helsetjenesten?", ["At helsepersonell overstyrer pasienten «til hans eget beste»", "Å ha barn", "Å følge loven", "Teamarbeid"], "Kan være nødvendig i noen tilfeller, men må begrunnes godt.", "What is paternalism in health care?", ["Health personnel overriding the patient \"for their own good\"", "Having children", "Following the law", "Teamwork"], "It may be necessary in some cases, but must be well justified."],
 ["Hvilken sykepleieteoretiker er kjent for teorien om egenomsorg?", ["Dorothea Orem", "Florence Nightingale", "Kari Martinsen", "Joyce Travelbee"], "Travelbee er kjent for menneske-til-menneske-forholdet, Nightingale for miljøets betydning.", "Which nursing theorist is known for the self-care theory?", ["Dorothea Orem", "Florence Nightingale", "Kari Martinsen", "Joyce Travelbee"], "Travelbee is known for the human-to-human relationship, Nightingale for the importance of the environment."]
]);
BIQ("SLOV", 3, [
 ["Hva kjennetegner aktiv lytting?", ["Du viser interesse, oppsummerer og stiller åpne spørsmål", "Du venter på å snakke selv", "Du ser på telefonen", "Du gir råd med en gang"], "Åpne spørsmål: «Hvordan har du det?» i stedet for «Har du det bra?».", "What characterises active listening?", ["You show interest, summarise and ask open questions", "You wait for your turn to speak", "You look at your phone", "You give advice straight away"], "Open questions: \"How are you feeling?\" instead of \"Are you feeling fine?\"."],
 ["Hvorfor er god dokumentasjon viktig?", ["Pasientsikkerhet, kontinuitet og juridisk krav", "Bare for statistikk", "Det er ikke viktig", "For å bruke tid"], "Det som ikke er dokumentert, er juridisk sett ikke gjort.", "Why is good documentation important?", ["Patient safety, continuity and a legal requirement", "Only for statistics", "It isn't important", "To use up time"], "What is not documented has legally not been done."],
 ["Hva er et åpent spørsmål?", ["«Hvordan opplever du smertene?»", "«Har du vondt?»", "«Er det bedre nå?»", "«Vil du ha en tablett?»"], "Åpne spørsmål kan ikke besvares med ja eller nei.", "What is an open question?", ["\"How do you experience the pain?\"", "\"Are you in pain?\"", "\"Is it better now?\"", "\"Do you want a tablet?\""], "Open questions cannot be answered with yes or no."]
]);
})();
