// ============================================================
//  add_forer3.js – tredje pakke med førerkortspørsmål (lastes etter add_forer2.js).
//  Spørsmålene legges bakerst i hver kategori, så lagret statistikk («enhet:indeks») beholder betydningen.
//  Format som DQ: [bilde|null, nbSpm, [RIKTIG, feil, feil, feil], nbForklaring, enSpm, [RIGHT, …], enForklaring]
// ============================================================
(() => {
const N = (q, o, e, qe, oe, ee) => [null, q, o, e, qe, oe, ee];
// ---------- BIL 0: Vikeplikt og forkjørsrett ----------
DQ("FKB", 0, [
 N("Du kjører på en forkjørsveg og kommer til et kryss. Hva gjelder?", ["Trafikk fra sidevegene har vikeplikt for deg, men du må likevel være oppmerksom", "Du må vike for trafikk fra høyre", "Du må alltid stanse i krysset", "Alle i krysset har lik rett"],
  "På forkjørsveg har trafikken fra sidevegene vikeplikt. Du skal likevel være klar til å stanse hvis noen ikke overholder den.",
  "You are driving on a priority road and reach a junction. What applies?", ["Traffic from the side roads must give way to you, but stay alert", "You must give way to traffic from the right", "You must always stop at the junction", "Everyone at the junction has equal rights"],
  "On a priority road traffic from side roads must give way. You must still be ready to stop if someone fails to."),
 N("I et uregulert T-kryss kjører du på den gjennomgående vegen. En bil kommer fra sidevegen på høyre side. Hvem har vikeplikt?", ["Du – høyreregelen gjelder også i T-kryss", "Bilen fra sidevegen", "Den som kjører fortest", "Ingen, det er et T-kryss"],
  "Høyreregelen gjelder i alle kryss uten skilt, lys eller oppmerking – også når du kjører på den «største» vegen i et T-kryss.",
  "In an unmarked T-junction you are on the through road. A car comes from the side road on your right. Who must give way?", ["You – the right-hand rule also applies at T-junctions", "The car from the side road", "Whoever is faster", "Nobody, it is a T-junction"],
  "The right-hand rule applies at every junction without signs, lights or markings – even when you are on the 'main' road of a T-junction."),
 N("Du skal svinge til høyre, og en syklist i sykkelfeltet til høyre for deg skal rett fram. Hvem har vikeplikt?", ["Du må vike for syklisten", "Syklisten må vike for deg", "Den som kommer først", "Ingen, sykkelfeltet er ikke en del av vegen"],
  "Når du svinger, skal du gi fri veg for syklende i sykkelfeltet som skal rett fram. Sjekk speil og blindsone før du svinger.",
  "You are turning right, and a cyclist in the cycle lane on your right is going straight. Who must give way?", ["You must give way to the cyclist", "The cyclist must give way to you", "Whoever arrives first", "Nobody, the cycle lane is not part of the road"],
  "When turning you must give way to cyclists in the cycle lane going straight on. Check your mirror and blind spot before turning."),
 N("Du kjører ut fra en gågate og inn på en vanlig veg. Hva gjelder?", ["Du har vikeplikt for all trafikk", "Høyreregelen gjelder", "Du har forkjørsrett", "Du må bare vike for gående"],
  "Utkjøringsregelen: den som kjører ut fra gågate, gangveg, fortau, parkeringsplass eller lignende, har vikeplikt for alle.",
  "You drive out of a pedestrian street onto a normal road. What applies?", ["You must give way to all traffic", "The right-hand rule applies", "You have priority", "You only give way to pedestrians"],
  "The exit rule: drivers coming from a pedestrian street, footpath, pavement, car park or similar must give way to everyone."),
 N("Hva er forskjellen på et stoppskilt og et vikepliktskilt?", ["Ved stoppskilt skal du alltid stanse helt ved stopplinjen, også når vegen er fri", "Det er ingen forskjell", "Stoppskiltet gjelder bare om natten", "Ved vikepliktskilt må du alltid stanse helt"],
  "Begge gir vikeplikt, men stoppskiltet krever i tillegg full stans – selv om det ikke kommer noen.",
  "What is the difference between a stop sign and a give-way sign?", ["At a stop sign you must always come to a full stop at the line, even if the road is clear", "There is no difference", "The stop sign only applies at night", "At a give-way sign you must always stop completely"],
  "Both mean you must give way, but the stop sign also requires a full stop – even when nobody is coming."),
 N("Du har vikeplikt og skal inn på en veg med mye trafikk. Hva er riktig?", ["Vent på en luke som er så stor at ingen må bremse for deg", "Kjør inn når noen blinker med lysene", "Kjør sakte ut så de andre ser deg", "Tut og kjør inn"],
  "Vikeplikt betyr at den du skal vike for, ikke skal måtte endre fart eller retning brått.",
  "You must give way and are joining a busy road. What is right?", ["Wait for a gap big enough that nobody has to brake for you", "Pull out when someone flashes their lights", "Edge out slowly so others see you", "Sound the horn and pull out"],
  "Giving way means the other road users should not have to change speed or direction suddenly."),
 N("Du har grønt lys. En ambulanse med blålys og sirene kommer inn i krysset fra siden. Hva gjør du?", ["Gir fri veg – utrykningskjøretøyet går foran, selv om du har grønt", "Kjører, fordi du har grønt lys", "Tuter for å varsle ambulansen", "Rygger"],
  "Utrykningskjøretøy som bruker blålys og sirene, skal få fri veg uansett hva lyset viser.",
  "You have a green light. An ambulance with blue lights and siren enters the junction from the side. What do you do?", ["Give way – the emergency vehicle goes first even though you have green", "Drive on, because you have green", "Sound your horn to warn the ambulance", "Reverse"],
  "Emergency vehicles using blue lights and siren must be given way whatever the traffic lights show."),
 N("I et lyskryss som virker: gjelder høyreregelen mellom bilene?", ["Nei, lyset bestemmer. Men svinger du, må du vike for gående og møtende", "Ja, alltid", "Bare om natten", "Bare for syklister"],
  "Når lyset virker, er det lyset som regulerer. Svinger du, har du likevel vikeplikt for gående som krysser og for møtende som kjører rett fram.",
  "At working traffic lights, does the right-hand rule apply between cars?", ["No, the lights decide. But when turning you give way to pedestrians and oncoming traffic", "Yes, always", "Only at night", "Only for cyclists"],
  "When lights are working, they control the junction. When turning you must still give way to crossing pedestrians and oncoming traffic going straight."),
 N("Du kjører inn i en rundkjøring. Hvem har du vikeplikt for?", ["De som allerede kjører i rundkjøringen", "De som kommer fra høyre bak deg", "Ingen", "Bare busser"],
  "Ved innkjøring til rundkjøringer står det vikepliktskilt. Trafikken inne i rundkjøringen kommer fra venstre for deg og har forkjørsrett.",
  "You are entering a roundabout. Who must you give way to?", ["Those already driving in the roundabout", "Those coming from the right behind you", "Nobody", "Only buses"],
  "There are give-way signs at the entries. Traffic in the roundabout comes from your left and has priority."),
 N("En syklist kommer fra en gang- og sykkelveg og ut i kjørebanen foran deg. Hvem har vikeplikt?", ["Syklisten", "Du", "Den som kommer fra høyre", "Ingen"],
  "Utkjøringsregelen gjelder også syklister: den som kommer fra gang- og sykkelveg, har vikeplikt. Vær likevel forberedt på at det ikke alltid skjer.",
  "A cyclist comes from a footpath/cycle path into the road in front of you. Who must give way?", ["The cyclist", "You", "Whoever comes from the right", "Nobody"],
  "The exit rule also applies to cyclists: anyone coming from a footpath/cycle path must give way. Still be ready in case they don't.")
]);
// ---------- BIL 1: Skilt og vegoppmerking ----------
DQ("FKB", 1, [
 N("Hvilken rekkefølge gjelder når tegn og regler sier forskjellige ting?", ["Politiets tegn – trafikklys – skilt – vegoppmerking – trafikkregler", "Skilt – politi – lys – regler", "Trafikkregler – skilt – lys – politi", "Vegoppmerking – skilt – politi – lys"],
  "Politiets tegn går foran alt. Deretter lys, skilt, oppmerking og til slutt de generelle trafikkreglene.",
  "Which order applies when signals and rules say different things?", ["Police signals – traffic lights – signs – road markings – traffic rules", "Signs – police – lights – rules", "Traffic rules – signs – lights – police", "Markings – signs – police – lights"],
  "Police signals override everything. Then lights, signs, markings and finally the general traffic rules."),
 N("Et parkeringsskilt har underskiltet «2 t». Hva betyr det?", ["Du kan parkere i høyst 2 timer", "Parkering koster 2 kroner", "Parkering er forbudt i 2 timer", "Du må parkere minst 2 timer"],
  "Underskiltet begrenser hvor lenge du kan stå. Ofte må du bruke parkeringsskive eller betale.",
  "A parking sign has the plate '2 h'. What does it mean?", ["You may park for at most 2 hours", "Parking costs 2 kroner", "Parking is banned for 2 hours", "You must park at least 2 hours"],
  "The plate limits how long you may stay. Often you must use a parking disc or pay."),
 N("Hva betyr et skravert sperrefelt i vegbanen?", ["Du skal ikke kjøre i det", "Det er et ekstra kjørefelt", "Det er en parkeringsplass", "Det er bare for busser"],
  "Sperrefelt er oppmerking du ikke skal kjøre i. Det brukes for eksempel ved av- og påkjøringer og trafikkøyer.",
  "What does a hatched area in the road mean?", ["You must not drive in it", "It is an extra lane", "It is a parking space", "It is for buses only"],
  "A hatched area must not be driven in. It is used for example at slip roads and traffic islands."),
 N("Hva betyr pilene som er malt i kjørefeltene før et kryss?", ["Hvilken retning du skal kjøre hvis du ligger i det feltet", "Bare en anbefaling", "Hvor fort du kan kjøre", "At feltet er stengt"],
  "Feltpilene viser påbudt kjøreretning for feltet. Velg riktig felt i god tid.",
  "What do arrows painted in the lanes before a junction mean?", ["Which direction you must go if you are in that lane", "Only a recommendation", "How fast you may drive", "That the lane is closed"],
  "Lane arrows show the required direction for that lane. Choose the right lane in good time."),
 N("Hva betyr en hvit tverrgående linje ved et trafikklys?", ["Stopplinje – her skal du stanse for rødt", "Gangfelt", "Fartsdump", "Slutt på kryss"],
  "Stopplinjen viser hvor du skal stanse når lyset er rødt eller ved stoppskilt.",
  "What does a white line across the lane at traffic lights mean?", ["Stop line – stop here at red", "Pedestrian crossing", "Speed bump", "End of junction"],
  "The stop line shows where to stop at a red light or a stop sign."),
 N("Du ser skiltet «Fartsgrensesone 30». Hvor lenge gjelder fartsgrensen?", ["I hele området til du ser et skilt om at sonen slutter", "Til neste kryss", "Bare 100 meter", "Bare om dagen"],
  "En sone gjelder for alle vegene i området, også etter kryss, helt til sonen er skiltet slutt.",
  "You see the sign 'Speed limit zone 30'. How long does the limit apply?", ["In the whole area until a sign shows the zone ends", "Until the next junction", "Only for 100 metres", "Only by day"],
  "A zone covers all roads in the area, also after junctions, until the end of the zone is signed."),
 N("Fra hvor gjelder en ny fartsgrense?", ["Fra skiltet", "100 meter etter skiltet", "Fra neste kryss", "Når du ser neste skilt"],
  "Fartsgrensen gjelder fra der skiltet står. Senk farten før du kommer dit.",
  "From where does a new speed limit apply?", ["From the sign", "100 metres after the sign", "From the next junction", "When you see the next sign"],
  "The limit applies from where the sign stands. Slow down before you reach it."),
 N("Hva betyr et opplysningsskilt med hvitt «H» på blå bunn?", ["Sykehus", "Hotell", "Holdeplass", "Hovedveg"],
  "H på blått skilt viser veg til sykehus. Kjør hensynsfullt i området.",
  "What does an information sign with a white 'H' on blue mean?", ["Hospital", "Hotel", "Bus stop", "Main road"],
  "An H on a blue sign shows the way to a hospital. Drive considerately in the area.")
]);
DQ("FKB", 1, [
 ["sving_hoyre", "Hva betyr dette skiltet?", ["Farlig sving til høyre", "Farlig sving til venstre", "Glatt kjørebane", "Ujevn veg"], "Skarp sving til høyre. Senk farten før svingen.", "What does this sign mean?", ["Dangerous bend to the right", "Dangerous bend to the left", "Slippery road", "Uneven road"], "Sharp bend to the right. Slow down before the bend."],
 ["sving_venstre", "Hva betyr dette skiltet?", ["Farlig sving til venstre", "Farlig sving til høyre", "Trafikklys", "Smalere veg"], "Skarp sving til venstre. Senk farten før svingen.", "What does this sign mean?", ["Dangerous bend to the left", "Dangerous bend to the right", "Traffic lights", "Road narrows"], "Sharp bend to the left. Slow down before the bend."],
 ["farlige_svinger", "Hva betyr dette skiltet?", ["Farlige svinger", "Elg", "Smalere veg", "Møtende trafikk"], "Flere farlige svinger etter hverandre, den første til høyre.", "What does this sign mean?", ["Dangerous bends", "Elk", "Road narrows", "Two-way traffic"], "Several dangerous bends, the first to the right."],
 ["smalere_veg", "Hva betyr dette skiltet?", ["Smalere veg", "Farlig sving til venstre", "Møtende trafikk", "Ujevn veg"], "Vegen blir smalere. Vær klar til å slippe frem møtende.", "What does this sign mean?", ["Road narrows", "Dangerous bend to the left", "Two-way traffic", "Uneven road"], "The road narrows. Be ready to let oncoming traffic through."],
 ["ujevn_veg", "Hva betyr dette skiltet?", ["Ujevn veg", "Glatt kjørebane", "Rundkjøring", "Farlige svinger"], "Ujevnheter eller humper i vegen. Senk farten.", "What does this sign mean?", ["Uneven road", "Slippery road", "Roundabout ahead", "Dangerous bends"], "Bumps or uneven surface ahead. Slow down."],
 ["trafikklys_fare", "Hva betyr dette skiltet?", ["Trafikklys", "Glatt kjørebane", "Farlig sving til høyre", "Farlig sving til venstre"], "Varsler om lyskryss du kanskje ikke ser i tide.", "What does this sign mean?", ["Traffic lights", "Slippery road", "Dangerous bend to the right", "Dangerous bend to the left"], "Warns of traffic lights you may not see in time."],
 ["motende_trafikk", "Hva betyr dette skiltet?", ["Møtende trafikk", "Barn", "Farlig sving til høyre", "Rundkjøring"], "Trafikk i begge retninger, ofte etter en strekning med envegskjøring.", "What does this sign mean?", ["Two-way traffic", "Children", "Dangerous bend to the right", "Roundabout ahead"], "Traffic in both directions, often after a one-way section."],
 ["vegkryss", "Hva betyr dette skiltet?", ["Vegkryss", "Barn", "Ujevn veg", "Elg"], "Kryss der høyreregelen gjelder: vik for trafikk fra høyre.", "What does this sign mean?", ["Crossroads", "Children", "Uneven road", "Elk"], "Junction where the right-hand rule applies: give way to traffic from the right."],
 ["forkjorskryss", "Hva betyr dette skiltet?", ["Forkjørskryss", "Farlig sving til venstre", "Farlige svinger", "Farlig sving til høyre"], "Kryss der du har forkjørsrett. Trafikk fra sidevegene har vikeplikt.", "What does this sign mean?", ["Junction with priority", "Dangerous bend to the left", "Dangerous bends", "Dangerous bend to the right"], "Junction where you have priority. Traffic from side roads must give way."],
 ["rundkjoring_fare", "Hva betyr dette skiltet?", ["Rundkjøring", "Forkjørskryss", "Barn", "Møtende trafikk"], "Varsler om rundkjøring. Vik for trafikk som allerede er i rundkjøringen.", "What does this sign mean?", ["Roundabout ahead", "Junction with priority", "Children", "Two-way traffic"], "Warns of a roundabout. Give way to traffic already in it."],
 ["fart30", "Hva betyr dette skiltet?", ["Fartsgrense 30", "Fartsgrense 70", "Fartsgrense 80", "Fartsgrense 40"], "Høyeste tillatte fart er 30 km/t, ofte ved skoler og boligområder.", "What does this sign mean?", ["Speed limit 30", "Speed limit 70", "Speed limit 80", "Speed limit 40"], "The maximum speed is 30 km/h, often near schools and homes."],
 ["fart40", "Hva betyr dette skiltet?", ["Fartsgrense 40", "Fartsgrense 90", "Fartsgrense 80", "Fartsgrense 110"], "Høyeste tillatte fart er 40 km/t.", "What does this sign mean?", ["Speed limit 40", "Speed limit 90", "Speed limit 80", "Speed limit 110"], "The maximum speed is 40 km/h."],
 ["fart70", "Hva betyr dette skiltet?", ["Fartsgrense 70", "Fartsgrense 90", "Fartsgrense 80", "Fartsgrense 110"], "Høyeste tillatte fart er 70 km/t.", "What does this sign mean?", ["Speed limit 70", "Speed limit 90", "Speed limit 80", "Speed limit 110"], "The maximum speed is 70 km/h."],
 ["fart80", "Hva betyr dette skiltet?", ["Fartsgrense 80", "Fartsgrense 40", "Fartsgrense 110", "Fartsgrense 90"], "Høyeste tillatte fart er 80 km/t.", "What does this sign mean?", ["Speed limit 80", "Speed limit 40", "Speed limit 110", "Speed limit 90"], "The maximum speed is 80 km/h."],
 ["fart90", "Hva betyr dette skiltet?", ["Fartsgrense 90", "Fartsgrense 80", "Fartsgrense 30", "Fartsgrense 40"], "Høyeste tillatte fart er 90 km/t.", "What does this sign mean?", ["Speed limit 90", "Speed limit 80", "Speed limit 30", "Speed limit 40"], "The maximum speed is 90 km/h."],
 ["fart100", "Hva betyr dette skiltet?", ["Fartsgrense 100", "Fartsgrense 110", "Fartsgrense 80", "Fartsgrense 70"], "Høyeste tillatte fart er 100 km/t, typisk på motorveg.", "What does this sign mean?", ["Speed limit 100", "Speed limit 110", "Speed limit 80", "Speed limit 70"], "The maximum speed is 100 km/h, typically on motorways."],
 ["fart110", "Hva betyr dette skiltet?", ["Fartsgrense 110", "Fartsgrense 100", "Fartsgrense 30", "Fartsgrense 80"], "Høyeste fartsgrense i Norge, på enkelte motorveger.", "What does this sign mean?", ["Speed limit 110", "Speed limit 100", "Speed limit 30", "Speed limit 80"], "The highest speed limit in Norway, on some motorways."],
 ["forbudt_kjoretoy", "Hva betyr dette skiltet?", ["Forbudt for alle kjøretøy", "Forbikjøring forbudt", "Fartsgrense 40", "Fartsgrense 100"], "Ingen kjøretøy får kjøre her, i noen av retningene.", "What does this sign mean?", ["No vehicles", "No overtaking", "Speed limit 40", "Speed limit 100"], "No vehicles may drive here, in either direction."],
 ["svinge_hoyre_forbudt", "Hva betyr dette skiltet?", ["Forbudt å svinge til høyre", "Fartsgrense 110", "Innkjøring forbudt", "Parkering forbudt"], "Du får ikke svinge til høyre i krysset.", "What does this sign mean?", ["No right turn", "Speed limit 110", "No entry", "No parking"], "You may not turn right at the junction."],
 ["svinge_venstre_forbudt", "Hva betyr dette skiltet?", ["Forbudt å svinge til venstre", "Fartsgrense 110", "Parkering forbudt", "Fartsgrense 40"], "Du får ikke svinge til venstre i krysset.", "What does this sign mean?", ["No left turn", "Speed limit 110", "No parking", "Speed limit 40"], "You may not turn left at the junction."],
 ["vending_forbudt", "Hva betyr dette skiltet?", ["Forbudt å vende", "Forbudt å svinge til venstre", "Innkjøring forbudt", "Fartsgrense 90"], "Du får ikke snu og kjøre tilbake samme veg.", "What does this sign mean?", ["No U-turn", "No left turn", "No entry", "Speed limit 90"], "You may not turn round and drive back."],
 ["slutt_fart60", "Hva betyr dette skiltet?", ["Slutt på fartsgrense 60", "Fartsgrense 80", "Parkering forbudt", "Forbikjøring forbudt"], "Den særskilte fartsgrensen gjelder ikke lenger. Da gjelder den generelle (50 eller 80 km/t).", "What does this sign mean?", ["End of speed limit 60", "Speed limit 80", "No parking", "No overtaking"], "The special limit no longer applies. The general limit (50 or 80 km/h) applies."],
 ["pabud_venstre", "Hva betyr dette skiltet?", ["Påbudt kjøreretning til venstre", "Påbudt kjørefelt", "Rundkjøring", "Påbudt kjøreretning til høyre"], "Du skal svinge til venstre.", "What does this sign mean?", ["Turn left", "Keep right", "Roundabout", "Turn right"], "You must turn left."],
 ["pabud_rett", "Hva betyr dette skiltet?", ["Påbudt kjøreretning rett fram", "Påbudt kjørefelt", "Påbudt kjøreretning til høyre", "Påbudt kjøreretning til venstre"], "Du skal kjøre rett fram.", "What does this sign mean?", ["Straight ahead only", "Keep right", "Turn right", "Turn left"], "You must drive straight ahead."],
 ["pabud_kjorefelt", "Hva betyr dette skiltet?", ["Påbudt kjørefelt", "Påbudt kjøreretning til høyre", "Rundkjøring", "Påbudt kjøreretning rett fram"], "Du skal passere på den siden pilen viser, for eksempel forbi en trafikkøy.", "What does this sign mean?", ["Keep right", "Turn right", "Roundabout", "Straight ahead only"], "You must pass on the side the arrow shows, for example past a traffic island."],
 ["envegskjoring", "Hva betyr dette skiltet?", ["Envegskjøring", "Motorveg", "Møteplass", "Blindveg"], "All trafikk går i pilens retning.", "What does this sign mean?", ["One-way street", "Motorway", "Passing place", "Dead end"], "All traffic goes in the direction of the arrow."],
 ["motorveg", "Hva betyr dette skiltet?", ["Motorveg", "Parkering", "Møteplass", "Blindveg"], "Egne regler: blant annet forbudt å stanse, rygge og snu, og forbudt for gående og syklende.", "What does this sign mean?", ["Motorway", "Parking", "Passing place", "Dead end"], "Special rules: among others no stopping, reversing or turning, and no pedestrians or cyclists."],
 ["motorveg_slutt", "Hva betyr dette skiltet?", ["Slutt på motorveg", "Møteplass", "Envegskjøring", "Tunnel"], "Motorvegens regler gjelder ikke lenger.", "What does this sign mean?", ["End of motorway", "Passing place", "One-way street", "Tunnel"], "Motorway rules no longer apply."],
 ["tunnel", "Hva betyr dette skiltet?", ["Tunnel", "Parkering", "Slutt på motorveg", "Blindveg"], "Tunnel framover. Bruk nærlys, og hold god avstand.", "What does this sign mean?", ["Tunnel", "Parking", "End of motorway", "Dead end"], "Tunnel ahead. Use dipped headlights and keep a good distance."],
 ["moteplass", "Hva betyr dette skiltet?", ["Møteplass", "Gangfelt", "Blindveg", "Slutt på motorveg"], "Utvidelse på smal veg der kjøretøy kan møte hverandre. Den skal ikke brukes til parkering.", "What does this sign mean?", ["Passing place", "Pedestrian crossing", "Dead end", "End of motorway"], "A widening on a narrow road where vehicles can pass each other. Not for parking."]
]);
// ---------- BIL 2: Fart, avstand og stopplengde ----------
DQ("FKB", 2, [
 N("Bremselengden er 8 m i 40 km/t. Omtrent hvor lang er den i 80 km/t på samme føre?", ["32 m", "16 m", "24 m", "64 m"],
  "Bremselengden øker med kvadratet av farten: dobbel fart gir fire ganger så lang bremselengde.",
  "The braking distance is 8 m at 40 km/h. About how long is it at 80 km/h on the same surface?", ["32 m", "16 m", "24 m", "64 m"],
  "Braking distance grows with the square of the speed: double the speed gives four times the distance."),
 N("Omtrent hvor mange meter kjører du per sekund i 50 km/t?", ["14 m", "5 m", "25 m", "50 m"],
  "50 km/t delt på 3,6 er omtrent 14 meter per sekund.",
  "About how many metres do you travel per second at 50 km/h?", ["14 m", "5 m", "25 m", "50 m"],
  "50 km/h divided by 3.6 is about 14 metres per second."),
 N("Omtrent hvor mange meter kjører du per sekund i 100 km/t?", ["28 m", "10 m", "50 m", "100 m"],
  "100 km/t delt på 3,6 er omtrent 28 meter per sekund – nesten en fotballbane på fire sekunder.",
  "About how many metres do you travel per second at 100 km/h?", ["28 m", "10 m", "50 m", "100 m"],
  "100 km/h divided by 3.6 is about 28 metres per second – almost a football pitch in four seconds."),
 N("En bil i 50 km/t stanser akkurat foran et barn. Omtrent hvor fort kjører en bil som startet i 60 km/t når den kommer til det samme stedet?", ["Omtrent 40 km/t", "Omtrent 10 km/t", "Den har også stanset", "Omtrent 60 km/t"],
  "Med 1 sekund reaksjonstid har bilen i 60 km/t brukt mer av stopplengden på reaksjonen og har fortsatt mye fart der den andre har stanset.",
  "A car at 50 km/h stops just before a child. About how fast is a car that started at 60 km/h going when it reaches the same spot?", ["About 40 km/h", "About 10 km/h", "It has also stopped", "About 60 km/h"],
  "With 1 second reaction time, the car at 60 km/h spends more of its stopping distance reacting and still has a lot of speed where the other has stopped."),
 N("Hvordan kan du måle avstanden til bilen foran i sekunder?", ["Tell fra bilen foran passerer et fast punkt til du passerer det samme punktet", "Se på speedometeret", "Tell hvor mange biler som møter deg", "Se hvor stor bilen foran ser ut"],
  "Velg en stolpe eller et skilt. Når bilen foran passerer, teller du «tusen-og-en, tusen-og-to, tusen-og-tre».",
  "How can you measure the gap to the car ahead in seconds?", ["Count from when the car ahead passes a fixed point until you pass it", "Look at the speedometer", "Count oncoming cars", "Judge how big the car ahead looks"],
  "Pick a post or sign. When the car ahead passes it, count 'one thousand and one, one thousand and two, one thousand and three'."),
 N("Hva betyr det å tilpasse farten etter forholdene?", ["Du skal kunne stanse på den delen av vegen du ser er fri", "Du skal alltid kjøre i fartsgrensen", "Du skal kjøre like fort som de andre", "Du skal kjøre saktere enn fartsgrensen hele tiden"],
  "Fartsgrensen er den høyeste tillatte farten ved gode forhold. Sikt, føre, trafikk og vær kan kreve lavere fart.",
  "What does adapting your speed to the conditions mean?", ["You must be able to stop within the part of the road you can see is clear", "Always drive at the limit", "Drive as fast as the others", "Always drive below the limit"],
  "The limit is the maximum allowed speed in good conditions. Visibility, surface, traffic and weather may require lower speed."),
 N("Hvor lang reaksjonstid regner man vanligvis med for en opplagt fører?", ["Omtrent 1 sekund", "Omtrent 0,1 sekund", "Omtrent 5 sekunder", "Omtrent 10 sekunder"],
  "En opplagt og oppmerksom fører bruker rundt 1 sekund. Trøtthet, rus og mobilbruk gjør den mye lengre.",
  "What reaction time is usually assumed for an alert driver?", ["About 1 second", "About 0.1 second", "About 5 seconds", "About 10 seconds"],
  "An alert, attentive driver takes about 1 second. Fatigue, intoxication and phone use make it much longer."),
 N("Hvorfor øker skadene på en fotgjenger så mye når farten øker fra 30 til 50 km/t?", ["Bevegelsesenergien øker med kvadratet av farten", "Bilen blir tyngre", "Fotgjengeren ser bilen dårligere", "Bremsene blir varme"],
  "Energien i støtet er nesten tre ganger så stor i 50 km/t som i 30 km/t, og i tillegg rekker du ofte ikke å bremse.",
  "Why do injuries to a pedestrian rise so much when speed goes from 30 to 50 km/h?", ["Kinetic energy grows with the square of the speed", "The car gets heavier", "The pedestrian sees the car less well", "The brakes get hot"],
  "The impact energy at 50 km/h is almost three times that at 30, and you often don't even manage to brake."),
 N("Du kjører i 60 km/t og har reaksjonstid 1 sekund. Hvor lang er reaksjonslengden?", ["Omtrent 17 m", "Omtrent 6 m", "Omtrent 60 m", "Omtrent 30 m"],
  "60 / 3,6 ≈ 16,7 m per sekund. På 1 sekund kjører du altså omtrent 17 m før du i det hele tatt begynner å bremse.",
  "You are driving at 60 km/h with a 1-second reaction time. How long is the reaction distance?", ["About 17 m", "About 6 m", "About 60 m", "About 30 m"],
  "60 / 3.6 ≈ 16.7 m per second. In 1 second you travel about 17 m before you even start braking."),
 N("Hvorfor er det farlig å kjøre tett på bilen foran i høy fart?", ["Du får ikke tid til å reagere og bremse hvis den bremser brått", "Du bruker mer bensin", "Det er bare farlig i mørket", "Det er ikke farlig hvis du har ABS"],
  "Reaksjonslengden din «spises» av den korte avstanden. Hold minst 3 sekunder, mer på glatt veg.",
  "Why is it dangerous to tailgate at high speed?", ["You won't have time to react and brake if it brakes suddenly", "You use more fuel", "It is only dangerous in the dark", "It is not dangerous with ABS"],
  "Your reaction distance is eaten up by the short gap. Keep at least 3 seconds, more on slippery roads.")
]);
// ---------- BIL 3: Plassering, feltskifte og forbikjøring ----------
DQ("FKB", 3, [
 N("Hvor er det forbudt å kjøre forbi, selv om det ikke er skiltet?", ["Like før og i et gangfelt", "På en rett strekning med god sikt", "På motorveg", "Når du kjører i 80 km/t"],
  "Det er blant annet forbudt å kjøre forbi like før og i gangfelt, like før bakketopper og i uoversiktlige svinger.",
  "Where is overtaking forbidden, even without a sign?", ["Just before and on a pedestrian crossing", "On a straight with good visibility", "On a motorway", "When driving at 80 km/h"],
  "Overtaking is forbidden among other places just before and on crossings, before hilltops and on blind bends."),
 N("Når kan du kjøre forbi i et vegkryss?", ["Når trafikken fra sidevegene har vikeplikt, eller du kjører forbi på høyre side", "Aldri", "Alltid hvis det er god sikt", "Bare om natten"],
  "Forbikjøring like før og i kryss er forbudt, med mindre kryssende trafikk har vikeplikt (for eksempel på forkjørsveg) eller du passerer på høyre side av en som svinger til venstre.",
  "When may you overtake at a junction?", ["When traffic from the side roads must give way, or you pass on the right", "Never", "Always if visibility is good", "Only at night"],
  "Overtaking just before and in junctions is forbidden unless crossing traffic must give way (e.g. on a priority road) or you pass on the right of someone turning left."),
 N("Hvor kan du ikke parkere på en veg med sperrelinje?", ["Der det er mindre enn 3 meter mellom bilen og sperrelinja", "Hvor som helst langs sperrelinja", "Bare ved bussholdeplasser", "Ingen steder er forbudt"],
  "Det skal være minst 3 meter fri veg mellom det parkerte kjøretøyet og sperrelinja, så andre slipper forbi uten å krysse linja.",
  "Where may you not park on a road with a solid centre line?", ["Where there is less than 3 metres between the car and the line", "Anywhere along the line", "Only at bus stops", "Nowhere is forbidden"],
  "There must be at least 3 metres of free road between the parked vehicle and the solid line, so others can pass without crossing it."),
 N("Du skal svinge til venstre i et kryss med to venstresvingefelt. Hvordan kjører du?", ["Hold deg i samme felt gjennom hele svingen", "Velg fritt felt ute i krysset", "Skift felt midt i krysset", "Kjør over i høyre felt etter svingen uansett"],
  "Kjør i en jevn bue og kom ut i tilsvarende felt, så du ikke krysser foran bilen ved siden av.",
  "You are turning left at a junction with two left-turn lanes. How do you drive?", ["Stay in the same lane throughout the turn", "Pick any lane in the junction", "Change lane in the middle of the junction", "Always move to the right lane after the turn"],
  "Drive a smooth arc and come out in the matching lane, so you don't cut across the car beside you."),
 N("Du kjører inn på motorvegen fra et akselerasjonsfelt. Hva gjør du?", ["Øker farten til omtrent samme som trafikken og fletter inn i en luke", "Stanser i enden av feltet og venter", "Kjører sakte inn så andre ser deg", "Kjører rett over i venstre felt"],
  "Akselerasjonsfeltet er der for at du skal få opp farten. Blink, finn en luke og flett inn uten å tvinge andre til å bremse.",
  "You join the motorway from an acceleration lane. What do you do?", ["Speed up to about the traffic's speed and merge into a gap", "Stop at the end of the lane and wait", "Drive in slowly so others see you", "Move straight into the left lane"],
  "The acceleration lane is there to build up speed. Signal, find a gap and merge without forcing others to brake."),
 N("Du har kjørt forbi avkjøringen du skulle ta på motorvegen. Hva gjør du?", ["Kjører videre til neste avkjøring", "Rygger tilbake på skulderen", "Snur i midtdeleren", "Stanser og venter"],
  "Det er forbudt å rygge, snu og stanse på motorveg. Ta neste avkjøring og kjør tilbake.",
  "You have missed your exit on the motorway. What do you do?", ["Continue to the next exit", "Reverse along the hard shoulder", "Turn in the central reserve", "Stop and wait"],
  "Reversing, turning and stopping are forbidden on motorways. Take the next exit and drive back."),
 N("Hvor plasserer du deg i en rundkjøring med to felt når du skal ta første avkjøring?", ["I høyre felt", "I venstre felt", "Midt mellom feltene", "Det spiller ingen rolle"],
  "Skal du ut i første avkjøring, ligger du i høyre felt og blinker høyre før du kjører ut.",
  "Where do you position yourself in a two-lane roundabout when taking the first exit?", ["In the right lane", "In the left lane", "Between the lanes", "It doesn't matter"],
  "For the first exit, stay in the right lane and signal right before leaving."),
 N("Hvorfor skal du ikke kjøre forbi like før en bakketopp?", ["Du ser ikke møtende trafikk i tide", "Bilen mister fart i motbakke", "Det er alltid forbudt å kjøre forbi utenfor tettbygd strøk", "Bakketopper er glatte"],
  "Over bakketoppen kan det komme møtende trafikk som verken du eller de ser før det er for sent.",
  "Why must you not overtake just before a hilltop?", ["You cannot see oncoming traffic in time", "The car loses speed uphill", "Overtaking outside built-up areas is always forbidden", "Hilltops are slippery"],
  "Oncoming traffic may appear over the crest that neither you nor they can see until it is too late."),
 N("Du skal parkere i en nedoverbakke langs fortauet. Hva bør du gjøre med hjulene?", ["Vri forhjulene inn mot fortauskanten", "Vri forhjulene ut mot vegen", "La dem stå rett", "Det spiller ingen rolle"],
  "Hvis bilen begynner å rulle, stopper fortauskanten den. Bruk alltid parkeringsbremsen også.",
  "You are parking downhill by the kerb. What should you do with the wheels?", ["Turn the front wheels towards the kerb", "Turn them out towards the road", "Leave them straight", "It doesn't matter"],
  "If the car starts to roll, the kerb will stop it. Always use the parking brake as well."),
 N("Hvorfor skal du ta skulderblikk før du skifter felt?", ["Speilene viser ikke blindsonen ved siden av bilen", "Det er bare påbudt på motorveg", "For å se om det er politi", "For å sjekke bakdøra"],
  "En bil, motorsykkel eller sykkel kan skjule seg i blindsonen. Skulderblikket er siste sjekk før du flytter deg.",
  "Why must you look over your shoulder before changing lanes?", ["The mirrors don't show the blind spot beside the car", "It is only required on motorways", "To check for police", "To check the back door"],
  "A car, motorcycle or bicycle can hide in the blind spot. The shoulder check is the final check before you move.")
]);
// ---------- BIL 4: Lys, signaler og trafikklys ----------
DQ("FKB", 4, [
 N("Hvilket lys bruker du i en opplyst tunnel?", ["Nærlys", "Bare kjørelys (DRL)", "Fjernlys", "Tåkelys"],
  "Bruk nærlys i tunnel. Kjørelys lyser ofte ikke bak, og fjernlys blender.",
  "Which lights do you use in a lit tunnel?", ["Dipped headlights", "Only daytime running lights", "Main beam", "Fog lights"],
  "Use dipped headlights in tunnels. DRLs often don't light the rear, and main beam dazzles."),
 N("Det blinker rødt lys ved en jernbaneovergang. Hva gjør du?", ["Stanser og venter til lyset slutter å blinke", "Kjører over raskt", "Kjører over hvis du ikke ser toget", "Tuter og kjører"],
  "Rødt blinkende lys betyr at tog kommer. Du skal stanse, også om bommene ikke er nede ennå.",
  "Red lights flash at a level crossing. What do you do?", ["Stop and wait until they stop flashing", "Cross quickly", "Cross if you can't see a train", "Sound the horn and go"],
  "Flashing red means a train is coming. Stop, even if the barriers are not down yet."),
 N("Bilen har automatisk kjørelys (DRL). Holder det når det er mørkt?", ["Nei, i mørket må du bruke nærlys", "Ja, kjørelys er nok", "Ja, hvis det er gatelys", "Bare hvis det ikke regner"],
  "Kjørelyset er svakere og lyser ofte ikke bak. I mørke, tåke og regn skal du ha på nærlys.",
  "The car has automatic daytime running lights. Is that enough in the dark?", ["No, in the dark you must use dipped headlights", "Yes, DRLs are enough", "Yes, if there are streetlights", "Only if it's not raining"],
  "DRLs are weaker and often don't light the rear. In darkness, fog and rain use dipped headlights."),
 N("Et bergingskjøretøy med gule blinklys står i vegkanten. Hva gjør du?", ["Senker farten og passerer med god avstand", "Kjører forbi i samme fart", "Stanser og venter", "Tuter for å varsle"],
  "Gule blinklys varsler om fare eller arbeid i vegen. Senk farten og vis hensyn til dem som jobber.",
  "A recovery vehicle with flashing amber lights is at the roadside. What do you do?", ["Slow down and pass with a good gap", "Pass at the same speed", "Stop and wait", "Sound the horn"],
  "Amber flashing lights warn of danger or work in the road. Slow down and show consideration for those working."),
 N("Når kan du bruke tåkelys foran?", ["I tåke, snøvær eller kraftig regn", "Alltid om natten", "Som erstatning for nærlys", "Når du vil bli sett bedre om dagen"],
  "Tåkelys er laget for dårlig sikt. Brukt ellers kan det blende andre.",
  "When may you use front fog lights?", ["In fog, snow or heavy rain", "Always at night", "Instead of dipped headlights", "To be seen better by day"],
  "Fog lights are designed for poor visibility. Used otherwise they can dazzle others."),
 N("Du kjører bak en annen bil i mørket. Hvilket lys bruker du?", ["Nærlys", "Fjernlys", "Parkeringslys", "Tåkebaklys"],
  "Fjernlyset blender føreren foran gjennom speilene. Blend ned når du nærmer deg bakfra.",
  "You are driving behind another car in the dark. Which lights do you use?", ["Dipped headlights", "Main beam", "Parking lights", "Rear fog light"],
  "Main beam dazzles the driver ahead through their mirrors. Dip when approaching from behind."),
 N("Hvorfor bør du blinke i god tid før du svinger?", ["Så andre trafikanter rekker å forstå hva du skal gjøre", "Fordi blinklyset trenger tid til å varme opp", "Det er bare nødvendig i kryss med lys", "For å vise at bilen virker"],
  "Blinklyset er et varsel. Kommer det for sent, rekker ikke andre å tilpasse seg.",
  "Why should you signal in good time before turning?", ["So other road users have time to understand what you'll do", "Because the indicator needs to warm up", "Only needed at lights", "To show the car works"],
  "The indicator is a warning. If it comes too late, others can't adjust."),
 N("En lyspære i den ene frontlykta har gått. Hva gjør du?", ["Bytter den så snart som mulig", "Kjører som vanlig til neste EU-kontroll", "Bruker fjernlys i stedet", "Det er ikke viktig om dagen"],
  "Med bare én lykt kan bilen forveksles med en motorsykkel, og du ser dårligere. Bytt pæra med en gang.",
  "One headlight bulb has failed. What do you do?", ["Replace it as soon as possible", "Drive normally until the next MOT", "Use main beam instead", "It doesn't matter by day"],
  "With one light the car can be mistaken for a motorcycle, and you see less. Replace the bulb at once.")
]);
// ---------- BIL 5: Myke trafikanter og samspill ----------
DQ("FKB", 5, [
 N("Du svinger inn i en sideveg, og gående krysser den vegen du svinger inn på. Hva gjelder?", ["Du skal la dem gå uhindret over", "De må vente på deg", "Du kan kjøre hvis det ikke er gangfelt", "Du tuter og kjører"],
  "Når du svinger, skal du gi gående som krysser vegen du skal inn på, anledning til å gå uhindret – også uten gangfelt.",
  "You turn into a side road, and pedestrians are crossing the road you are turning into. What applies?", ["You must let them cross unhindered", "They must wait for you", "You may go if there's no crossing", "You sound the horn and go"],
  "When turning you must let pedestrians crossing the road you are entering cross unhindered – even without a crossing."),
 N("Hvorfor er rygging ekstra farlig når det er barn i nærheten?", ["Små barn kan være helt skjult bak bilen", "Barn hører ikke motoren", "Ryggelys blender barn", "Det er ikke farligere"],
  "Et lite barn rett bak bilen syns verken i speil eller bakrute. Gå rundt bilen og se før du rygger.",
  "Why is reversing extra dangerous with children nearby?", ["Small children can be completely hidden behind the car", "Children can't hear the engine", "Reversing lights dazzle children", "It isn't more dangerous"],
  "A small child right behind the car can't be seen in mirrors or the rear window. Walk round and check before reversing."),
 N("En syklist strekker ut venstre arm. Hva betyr det?", ["Syklisten skal svinge til venstre", "Syklisten skal stanse", "Syklisten hilser", "Syklisten vil at du skal kjøre forbi"],
  "Syklister viser at de skal svinge ved å strekke ut armen til den siden de skal.",
  "A cyclist holds out their left arm. What does it mean?", ["The cyclist is turning left", "The cyclist is stopping", "The cyclist is waving", "The cyclist wants you to overtake"],
  "Cyclists show that they will turn by holding out the arm on that side."),
 N("Du skal passere en buss som står ved holdeplassen. Hva gjør du?", ["Senker farten – gående kan komme ut foran bussen", "Kjører forbi i vanlig fart", "Tuter for å varsle passasjerene", "Kjører tett inntil bussen"],
  "Passasjerer som har gått av, krysser ofte vegen rett foran bussen der de er skjult.",
  "You are passing a bus at a stop. What do you do?", ["Slow down – pedestrians may step out in front of the bus", "Pass at normal speed", "Sound the horn to warn passengers", "Pass close to the bus"],
  "Passengers who have got off often cross right in front of the bus where they are hidden."),
 N("Hvorfor er det lurt å få øyekontakt med en fotgjenger?", ["For å forsikre deg om at hen har sett deg", "Fordi det er påbudt", "For å vise at du har hastverk", "For å be hen vente"],
  "Øyekontakt gjør samspillet tryggere. Men ikke stol blindt på det – vær klar til å stanse.",
  "Why is it a good idea to make eye contact with a pedestrian?", ["To make sure they have seen you", "Because it's required", "To show you're in a hurry", "To ask them to wait"],
  "Eye contact makes interaction safer. But don't rely on it blindly – be ready to stop."),
 N("Hvorfor har barn under ca. 12 år vanskelig for å klare seg i trafikken?", ["De har vansker med å bedømme fart og avstand", "De hører dårligere enn voksne", "De er alltid uoppmerksomme med vilje", "De kjenner ikke fargene på trafikklyset"],
  "Barn ser trafikken annerledes: de er lave, har smalere oversikt og bedømmer fart og avstand dårligere.",
  "Why do children under about 12 struggle in traffic?", ["They find it hard to judge speed and distance", "They hear worse than adults", "They are deliberately inattentive", "They don't know the colours of traffic lights"],
  "Children see traffic differently: they are short, have a narrower view and judge speed and distance less well."),
 N("Du kjører bak en syklist i en smal gate med møtende trafikk. Hva gjør du?", ["Venter bak til du kan passere med god avstand", "Kjører forbi tett inntil", "Tuter så syklisten flytter seg", "Kjører opp på fortauet for å komme forbi"],
  "Det er bedre å bruke noen sekunder ekstra enn å presse deg forbi. Anbefalt sideavstand er minst 1,5 meter.",
  "You are behind a cyclist in a narrow street with oncoming traffic. What do you do?", ["Wait behind until you can pass with a good gap", "Squeeze past closely", "Sound the horn so the cyclist moves", "Drive onto the pavement to pass"],
  "Better to spend a few seconds than to squeeze past. The recommended clearance is at least 1.5 metres."),
 N("En person med elsparkesykkel kjører i kjørebanen. Hvordan regnes den i trafikken?", ["Omtrent som en sykkel", "Som en motorsykkel", "Som en fotgjenger", "Den får ikke være i kjørebanen"],
  "Elsparkesykler følger i hovedsak reglene for sykkel. Vær forberedt på at de kan endre retning raskt.",
  "Someone on an e-scooter is riding in the road. How is it treated in traffic?", ["Much like a bicycle", "Like a motorcycle", "Like a pedestrian", "It may not be in the road"],
  "E-scooters mainly follow the rules for bicycles. Be prepared for them to change direction quickly.")
]);
// ---------- BIL 6: Rus, trøtthet og oppmerksomhet ----------
DQ("FKB", 6, [
 N("Hva sier vegtrafikkloven om å kjøre når du er veldig trøtt?", ["Det er forbudt å kjøre når du er så uopplagt at du ikke kan kjøre trygt", "Det er lov hvis du har kjøpt kaffe", "Det er bare forbudt om natten", "Loven sier ingenting om trøtthet"],
  "Ingen må kjøre når de er syke, trøtte eller påvirket slik at de ikke kan kjøre på en trygg måte.",
  "What does the Road Traffic Act say about driving when very tired?", ["You must not drive when too tired to drive safely", "It's allowed if you've bought coffee", "It's only forbidden at night", "The law says nothing about tiredness"],
  "Nobody may drive when ill, tired or impaired so that they cannot drive safely."),
 N("Hvilke legemidler kan påvirke kjøreevnen?", ["Mange, for eksempel sovemedisiner, sterke smertestillende og enkelte allergimedisiner", "Bare narkotika", "Ingen reseptfrie medisiner", "Bare medisiner tatt samme dag som du er syk"],
  "Se etter den røde varseltrekanten på pakningen og spør lege eller apotek.",
  "Which medicines can affect driving ability?", ["Many, e.g. sleeping pills, strong painkillers and some allergy medicines", "Only illegal drugs", "No over-the-counter medicines", "Only ones taken on a sick day"],
  "Look for the red warning triangle on the pack and ask a doctor or pharmacist."),
 N("Finnes det faste grenser for andre rusmidler enn alkohol i Norge?", ["Ja, for mange vanlige stoffer, på samme måte som promillegrensen", "Nei, bare for alkohol", "Bare for cannabis", "Bare for yrkessjåfører"],
  "Norge har lovfestede grenser for en rekke narkotiske stoffer og legemidler, i tillegg til den generelle regelen om påvirket kjøring.",
  "Are there fixed limits for drugs other than alcohol in Norway?", ["Yes, for many common substances, like the alcohol limit", "No, only alcohol", "Only cannabis", "Only for professional drivers"],
  "Norway has legal limits for a number of drugs and medicines, in addition to the general rule on impaired driving."),
 N("Hva gjør alkohol med synet ditt?", ["Synsfeltet snevres inn, og det blir vanskeligere å bedømme avstand", "Du ser skarpere", "Du blir mindre blendet", "Ingenting under 1 promille"],
  "Allerede ved lav promille svekkes oppmerksomheten og evnen til å se det som skjer ute på sidene.",
  "What does alcohol do to your vision?", ["Your field of view narrows and judging distance gets harder", "You see more sharply", "You are less dazzled", "Nothing below 1 per mille"],
  "Even at low levels attention and the ability to see what happens at the sides are reduced."),
 N("Hva er lurt før en lang biltur?", ["Sove godt og planlegge pauser, for eksempel hver andre time", "Kjøre om natten når det er lite trafikk", "Drikke energidrikk og kjøre uten stopp", "Ha høy musikk for å holde deg våken"],
  "Trøtthet er en stor ulykkesårsak. Planlagte pauser og nok søvn er det som hjelper.",
  "What is wise before a long drive?", ["Sleep well and plan breaks, e.g. every two hours", "Drive at night when traffic is light", "Drink energy drinks and drive non-stop", "Play loud music to stay awake"],
  "Fatigue is a major cause of crashes. Planned breaks and enough sleep are what help."),
 N("Når bør du legge inn adressen i navigasjonen?", ["Før du begynner å kjøre", "Mens du kjører sakte", "Ved rødt lys", "Når du er usikker på vegen underveis"],
  "Å betjene skjermen tar blikket og oppmerksomheten bort fra vegen. Stans på et trygt sted hvis du må endre noe.",
  "When should you enter the address in the satnav?", ["Before you start driving", "While driving slowly", "At a red light", "When unsure of the way en route"],
  "Operating the screen takes your eyes and attention off the road. Stop somewhere safe if you need to change it."),
 N("Du skal sitte på med en venn som tydelig har drukket. Hva gjør du?", ["Lar være å sitte på og prøver å hindre at hen kjører", "Sitter på og passer på", "Sitter på hvis turen er kort", "Ber hen kjøre sakte"],
  "Ruskjøring setter alle i bilen og andre trafikanter i fare. Finn en annen måte å komme deg hjem på.",
  "You are about to get a lift with a friend who has clearly been drinking. What do you do?", ["Don't get in, and try to stop them driving", "Get in and keep an eye on them", "Get in if the trip is short", "Ask them to drive slowly"],
  "Drink-driving endangers everyone in the car and other road users. Find another way home."),
 N("Hva er uoppmerksomhetsblindhet?", ["Du ser i en retning, men legger ikke merke til det som skjer der", "At du blir blendet av sola", "At du ikke ser i mørket", "At du har dårlig syn"],
  "Når tankene er et annet sted, for eksempel i en telefonsamtale, kan du «se uten å se» – også en syklist rett foran deg.",
  "What is inattentional blindness?", ["You look in a direction but don't notice what happens there", "Being dazzled by the sun", "Not seeing in the dark", "Having poor eyesight"],
  "When your mind is elsewhere, for example on a phone call, you can 'look without seeing' – even a cyclist right in front of you.")
]);
// ---------- BIL 7: Kjøretøyet, last og tilhenger ----------
DQ("FKB", 7, [
 N("Når kan du bruke piggdekk i Sør-Norge?", ["Fra 1. november til første søndag etter 2. påskedag", "Hele året", "Bare i desember og januar", "Fra 1. september til 1. juni"],
  "I Nordland, Troms og Finnmark er perioden lengre. Utenfor perioden er piggdekk lov bare hvis føret krever det.",
  "When may you use studded tyres in southern Norway?", ["From 1 November to the first Sunday after Easter Monday", "All year", "Only December and January", "From 1 September to 1 June"],
  "In Nordland, Troms and Finnmark the period is longer. Outside the period studs are allowed only if conditions require it."),
 N("Hva er nyttelast?", ["Hvor mye last og passasjerer bilen kan ha – tillatt totalvekt minus egenvekt", "Hvor mye bilen veier tom", "Hvor tung tilhenger du kan ha", "Hvor mye som får plass i bagasjerommet"],
  "Nyttelasten står i vognkortet. Overlast gir lengre bremselengde og dårligere styring.",
  "What is payload?", ["How much load and passengers the car may carry – max weight minus kerb weight", "What the car weighs empty", "How heavy a trailer you may tow", "How much fits in the boot"],
  "Payload is in the registration document. Overloading gives longer braking and poorer handling."),
 N("Hvor finner du bilens tillatte totalvekt og hvor tung tilhenger den kan trekke?", ["I vognkortet", "På dekket", "I førerkortet", "På frontruta"],
  "Vognkortet viser blant annet egenvekt, tillatt totalvekt og tillatt tilhengervekt med og uten brems.",
  "Where do you find the car's max weight and how heavy a trailer it can tow?", ["In the registration document", "On the tyre", "On the driving licence", "On the windscreen"],
  "The registration document shows kerb weight, max weight and trailer limits with and without brakes."),
 N("Hvor høyt bør hodestøtten stå?", ["Øverkanten omtrent i høyde med toppen av hodet", "Så lavt som mulig", "Ved nakken", "Det spiller ingen rolle"],
  "En riktig innstilt hodestøtte reduserer faren for nakkeslengskade ved påkjørsel bakfra.",
  "How high should the head restraint be?", ["Its top at about the top of your head", "As low as possible", "At the neck", "It doesn't matter"],
  "A correctly set head restraint reduces the risk of whiplash in a rear-end collision."),
 N("Hvorfor er løs last farlig i en kollisjon?", ["Den kan slynges framover med en kraft mange ganger sin egen vekt", "Den gjør bilen tyngre", "Den kan skrape setene", "Den er bare farlig i høy fart"],
  "I et krasj blir løse gjenstander til prosjektiler. En vannflaske eller et nettbrett kan gjøre stor skade.",
  "Why is loose cargo dangerous in a collision?", ["It can be hurled forward with a force many times its weight", "It makes the car heavier", "It can scratch the seats", "It's only dangerous at high speed"],
  "In a crash loose objects become projectiles. A water bottle or a tablet can do serious harm."),
 N("Hva betyr en varsellampe formet som et dekk med utropstegn?", ["Lavt dekktrykk i ett eller flere dekk", "Dekkene er slitt ned", "Det er glatt ute", "Det er tid for dekkskift"],
  "Sjekk og pump dekkene så snart som mulig. Lavt trykk gir dårligere veggrep og høyere forbruk.",
  "What does a warning light shaped like a tyre with an exclamation mark mean?", ["Low pressure in one or more tyres", "The tyres are worn out", "It is slippery outside", "Time to change tyres"],
  "Check and inflate the tyres as soon as possible. Low pressure means less grip and higher consumption."),
 N("Hvordan påvirker en tung tilhenger kjøringen?", ["Lengre bremselengde, større svingradius og saktere akselerasjon", "Bilen bremser bedre", "Ingen forskjell", "Bilen blir mer stabil i sidevind"],
  "Hold større avstand, kjør i lavere fart og ta svingene videre.",
  "How does a heavy trailer affect driving?", ["Longer braking, wider turns and slower acceleration", "The car brakes better", "No difference", "The car is more stable in crosswinds"],
  "Keep a longer gap, drive slower and take bends wider."),
 N("Tilhengeren begynner å slingre. Hva gjør du?", ["Slipper gassen forsiktig og holder rattet stødig til slingringen gir seg", "Gir mer gass", "Bremser hardt og svinger", "Rykker i rattet fra side til side"],
  "Slingring stopper som regel når farten går ned. Brå bremsing og rattbevegelser kan gjøre det verre. Last tungt over akslingen.",
  "The trailer starts to sway. What do you do?", ["Ease off the accelerator and hold the wheel steady until it settles", "Accelerate", "Brake hard and steer", "Jerk the wheel from side to side"],
  "Sway usually stops as speed drops. Sudden braking and steering can make it worse. Load heavy items over the axle."),
 N("Hva kreves for å kjøre med en tilhenger som gjør at vogntoget blir tyngre enn klasse B tillater?", ["Førerkort klasse BE (eller utvidet B, B96)", "Ingenting ekstra", "Bare at tilhengeren har bremser", "Klasse C"],
  "Med klasse B kan vogntoget ha begrenset totalvekt. Tyngre tilhenger krever B96 eller BE.",
  "What is required to tow a trailer that makes the combination heavier than class B allows?", ["Licence class BE (or extended B, B96)", "Nothing extra", "Only that the trailer has brakes", "Class C"],
  "With class B the combination has a limited total weight. A heavier trailer requires B96 or BE.")
]);
// ---------- BIL 8: Vinter, mørke og vanskelige forhold ----------
DQ("FKB", 8, [
 N("Hvordan kjører du ned en bratt og glatt bakke?", ["Senk farten og velg lavt gir før bakken", "Gir gass for å komme fort ned", "Kjører i fri", "Bremser hardt nede i bakken"],
  "Det er mye lettere å holde farten lav enn å få den ned når du først har kommet i gang på glatta.",
  "How do you drive down a steep, slippery hill?", ["Slow down and select a low gear before the hill", "Accelerate to get down quickly", "Coast in neutral", "Brake hard at the bottom"],
  "It is much easier to keep speed low than to reduce it once you're moving on ice."),
 N("Hvordan starter du på glatt føre?", ["Med forsiktig gass, så hjulene ikke spinner", "Med full gass", "Med håndbrekket på", "Med rattet vridd helt ut"],
  "Spinner hjulene, mister du veggrepet. Med manuelt gir kan det hjelpe å starte i andre gir.",
  "How do you pull away on a slippery surface?", ["With gentle throttle so the wheels don't spin", "With full throttle", "With the handbrake on", "With the wheel on full lock"],
  "Spinning wheels lose grip. With a manual gearbox, starting in second can help."),
 N("Du blir sittende fast i snøvær på fjellet. Hva gjør du?", ["Blir i bilen, holder eksosrøret fritt for snø og ringer etter hjelp", "Går til fots for å finne hjelp", "Lar motoren gå med eksosen dekket av snø", "Sover med vinduene lukket og motoren i gang"],
  "Eksos som kommer inn i bilen kan gi kullosforgiftning. Ha varme klær, mat og drikke med på vinterturer.",
  "You get stuck in snow on a mountain pass. What do you do?", ["Stay in the car, keep the exhaust clear of snow and call for help", "Walk to find help", "Run the engine with the exhaust blocked by snow", "Sleep with windows shut and engine running"],
  "Exhaust entering the car can cause carbon monoxide poisoning. Bring warm clothes, food and drink on winter trips."),
 N("Hva er kolonnekjøring?", ["Kjøring i kø bak brøytebil over en fjellovergang som ellers er stengt", "Kjøring i rushtrafikk", "Når flere biler kjører forbi samtidig", "Kjøring med tilhenger"],
  "Følg brøytebilen, hold avstand og stans ikke underveis. Det er ofte strengt vær når det er kolonne.",
  "What is convoy driving?", ["Driving in line behind a snowplough over an otherwise closed mountain pass", "Rush-hour driving", "Several cars overtaking at once", "Towing a trailer"],
  "Follow the plough, keep your distance and don't stop on the way. The weather is often severe when there's a convoy."),
 N("Hvorfor er det ekstra glatt når temperaturen er rundt 0 °C?", ["Det kan ligge et tynt lag vann oppå isen", "Isen er tykkest da", "Salt virker ikke over null", "Det er ikke glattere da"],
  "Våt is er glattere enn kald, tørr is. Vær ekstra forsiktig når temperaturen ligger rundt null.",
  "Why is it extra slippery around 0 °C?", ["There may be a thin layer of water on the ice", "The ice is thickest then", "Salt doesn't work above zero", "It isn't more slippery"],
  "Wet ice is more slippery than cold, dry ice. Be extra careful when the temperature is around zero."),
 N("Hvordan bremser du hardt på glatta i en bil uten ABS?", ["Bremser så hardt du kan uten at hjulene låser seg", "Tråkker bremsen helt inn og holder", "Drar i håndbrekket", "Bremser ikke, bare styrer"],
  "Låste hjul gir ingen styring og ofte lengre bremselengde. Slipp litt opp hvis hjulene låser.",
  "How do you brake hard on ice in a car without ABS?", ["Brake as hard as possible without locking the wheels", "Press the pedal fully and hold", "Pull the handbrake", "Don't brake, just steer"],
  "Locked wheels give no steering and often longer braking. Ease off a little if the wheels lock."),
 N("Hvor fort kan du kjøre i mørket med nærlys?", ["Så fort at du kan stanse innenfor det lyset rekker", "Alltid i fartsgrensen", "Like fort som om dagen", "Så fort du vil hvis det er gatelys"],
  "Nærlyset rekker kort. Du må kunne stanse for det du plutselig ser i lyskjeglen.",
  "How fast may you drive in the dark on dipped headlights?", ["Fast enough only to stop within the range of your lights", "Always at the limit", "As fast as by day", "As fast as you like with streetlights"],
  "Dipped headlights have a short range. You must be able to stop for what suddenly appears in the beam."),
 N("Bilen bak blender deg gjennom innvendig speil. Hva gjør du?", ["Vipper speilet til nattstilling", "Bremser for å varsle", "Slår på fjernlys", "Kjører fortere"],
  "De fleste innvendige speil har en nattstilling (eller blendes automatisk ned).",
  "The car behind dazzles you through the rear-view mirror. What do you do?", ["Switch the mirror to night mode", "Brake to warn them", "Turn on main beam", "Speed up"],
  "Most interior mirrors have a night setting (or dim automatically)."),
 N("Hvorfor dugger rutene innvendig, og hva gjør du?", ["Fuktig luft kondenserer – bruk vifte, varme og gjerne aircondition mot frontruta", "Det er frost – skrap innvendig", "Det skyldes motoren – kjør fortere", "Det er normalt, kjør som vanlig"],
  "Aircondition tørker lufta. Kjør ikke før du ser godt ut av alle ruter.",
  "Why do the windows mist up inside, and what do you do?", ["Humid air condenses – use the fan, heat and ideally air conditioning on the windscreen", "It's frost – scrape inside", "It's the engine – drive faster", "It's normal, drive on"],
  "Air conditioning dries the air. Don't drive until you can see clearly through all windows.")
]);
// ---------- BIL 9: Ulykker og førstehjelp ----------
DQ("FKB", 9, [
 N("Hvor dypt skal du trykke ved brystkompresjoner på en voksen?", ["5–6 cm", "1–2 cm", "10–12 cm", "Så lett som mulig"],
  "Trykk midt på brystet, 5–6 cm ned, og slipp helt opp mellom hvert trykk.",
  "How deep should chest compressions be on an adult?", ["5–6 cm", "1–2 cm", "10–12 cm", "As light as possible"],
  "Press in the middle of the chest, 5–6 cm deep, and release fully between compressions."),
 N("Hvor raskt skal du gi brystkompresjoner?", ["100–120 i minuttet", "20–30 i minuttet", "200 i minuttet", "Så sakte du klarer"],
  "Omtrent to trykk i sekundet. Tempoet til «Stayin' Alive» passer godt.",
  "How fast should you give chest compressions?", ["100–120 per minute", "20–30 per minute", "200 per minute", "As slowly as you can"],
  "About two per second. The tempo of 'Stayin' Alive' fits well."),
 N("En motorsyklist er bevisstløs og puster ikke. Hva gjør du med hjelmen?", ["Tar den forsiktig av, så du kan åpne luftveiene og gi HLR", "Lar den alltid sitte på", "Bare åpner visiret", "Venter på ambulansen"],
  "Frie luftveier og HLR går foran alt. Støtt hodet og nakken, og ta hjelmen av forsiktig – helst to personer.",
  "A motorcyclist is unconscious and not breathing. What do you do with the helmet?", ["Remove it carefully so you can open the airway and give CPR", "Always leave it on", "Only open the visor", "Wait for the ambulance"],
  "An open airway and CPR come first. Support the head and neck and remove the helmet carefully – ideally two people."),
 N("En person har satt noe fast i halsen og klarer ikke å hoste eller puste. Hva gjør du?", ["Gir inntil 5 slag mellom skulderbladene og deretter inntil 5 kraftige støt mot magen", "Gir vann å drikke", "Legger personen i stabilt sideleie", "Venter til det løsner av seg selv"],
  "Veksle mellom slag på ryggen og magestøt (Heimlich). Blir personen bevisstløs, ring 113 og start HLR.",
  "Someone has choked and cannot cough or breathe. What do you do?", ["Give up to 5 back blows and then up to 5 abdominal thrusts", "Give water to drink", "Put them in the recovery position", "Wait for it to clear"],
  "Alternate back blows and abdominal thrusts (Heimlich). If they lose consciousness, call 113 and start CPR."),
 N("Det brenner i en bil etter en ulykke. Hva gjør du?", ["Får alle ut, går på trygg avstand og ringer 110", "Åpner panseret for å se", "Prøver å slukke med vann fra en flaske", "Blir sittende i bilen"],
  "Ring 110 ved brann. Har du brannslukningsapparat og det er trygt, kan du forsøke å slokke en liten brann.",
  "A car is on fire after a crash. What do you do?", ["Get everyone out, move to a safe distance and call 110", "Open the bonnet to look", "Try to put it out with a water bottle", "Stay in the car"],
  "Call 110 for fire. If you have an extinguisher and it is safe, you may try to put out a small fire."),
 N("Du rygger borti en parkert bil og eieren er ikke der. Hva må du gjøre?", ["Gi beskjed til eieren eller politiet", "Kjøre videre hvis skaden er liten", "Legge igjen en lapp uten navn", "Ingenting"],
  "Den som er innblandet i et uhell, skal sørge for at den skadelidte får vite hvem du er – ellers kontakter du politiet.",
  "You reverse into a parked car and the owner isn't there. What must you do?", ["Inform the owner or the police", "Drive on if the damage is small", "Leave an anonymous note", "Nothing"],
  "Anyone involved in an accident must make sure the injured party learns who they are – otherwise contact the police."),
 N("Hva er en europeisk skademelding?", ["Et skjema begge parter fyller ut sammen etter et uhell", "En bot fra politiet", "En melding til Statens vegvesen", "En forsikring for utlandet"],
  "Skademeldingen beskriver hva som skjedde og sendes til forsikringsselskapene. Ha et eksemplar i bilen.",
  "What is a European accident statement?", ["A form both parties fill in together after an accident", "A police fine", "A report to the road authority", "Insurance for abroad"],
  "The statement describes what happened and goes to the insurers. Keep a copy in the car."),
 N("Hva bør du fortelle når du ringer 113?", ["Hvor du er, hva som har skjedd og hvor mange som er skadd", "Bare navnet ditt", "Bilmerket", "Hvem som har skyld"],
  "Det viktigste er nøyaktig sted. Følg rådene du får, og ikke legg på før operatøren sier det.",
  "What should you tell 113 when you call?", ["Where you are, what happened and how many are injured", "Just your name", "The make of car", "Who is to blame"],
  "The most important is the exact location. Follow the advice you get and don't hang up until told."),
 N("Ulykken skjedde rett etter en uoversiktlig sving. Hvor setter du varseltrekanten?", ["Godt før svingen, så de som kommer får varsel i tide", "Rett bak bilen", "I selve svingen", "Foran bilen"],
  "Trekanten skal varsle i god tid. På veg med høy fart bør den stå 150–250 m før ulykkesstedet.",
  "The accident happened just after a blind bend. Where do you place the warning triangle?", ["Well before the bend, so approaching traffic is warned in time", "Right behind the car", "In the bend itself", "In front of the car"],
  "The triangle must warn in good time. On fast roads it should be 150–250 m before the scene.")
]);
// ---------- BIL 10: Miljø og økonomisk kjøring ----------
DQ("FKB", 10, [
 N("Hvorfor øker takboks og takstativ forbruket?", ["De øker luftmotstanden", "De gjør bilen lavere", "De gir bedre veggrep", "De påvirker ikke forbruket"],
  "Luftmotstanden betyr mye i høy fart. Ta av takstativet når du ikke bruker det.",
  "Why do roof boxes and racks increase consumption?", ["They increase air resistance", "They make the car lower", "They improve grip", "They don't affect consumption"],
  "Air resistance matters a lot at speed. Remove the rack when not in use."),
 N("Hvorfor er korte turer med kald motor dårlig for miljøet?", ["Motoren bruker mer og slipper ut mer de første minuttene", "Motoren bruker mindre når den er kald", "Det er bare dårlig for bilen", "Det er ingen forskjell"],
  "En kald motor og katalysator renser dårligere. Gå eller sykle korte turer når du kan.",
  "Why are short trips with a cold engine bad for the environment?", ["The engine uses and emits more in the first minutes", "A cold engine uses less", "It's only bad for the car", "There's no difference"],
  "A cold engine and catalytic converter clean less. Walk or cycle short trips when you can."),
 N("Hvorfor sparer du drivstoff på å se langt fram?", ["Du kan kjøre jevnt og unngå unødvendig bremsing og akselerasjon", "Motoren går kaldere", "Du ser flere bensinstasjoner", "Det sparer ikke drivstoff"],
  "Hver gang du bremser, går energi tapt som varme. Slipp gassen tidlig når du ser at du må stanse.",
  "Why does looking far ahead save fuel?", ["You can drive smoothly and avoid needless braking and acceleration", "The engine runs cooler", "You see more petrol stations", "It doesn't save fuel"],
  "Each time you brake energy is lost as heat. Lift off early when you see you must stop."),
 N("Hva er en god vane for batteriet i en elbil i hverdagen?", ["Lade til rundt 80 % og ikke kjøre helt tomt", "Alltid lade til 100 %", "Alltid kjøre til 0 % før lading", "Bare hurtiglade"],
  "Litiumbatterier har det best i mellomområdet. Lad fullt før lange turer.",
  "What is a good everyday habit for an EV battery?", ["Charge to about 80% and don't run it empty", "Always charge to 100%", "Always run to 0% before charging", "Only fast-charge"],
  "Lithium batteries are happiest in the middle range. Charge fully before long trips."),
 N("Hvordan påvirker åpne vinduer forbruket i høy fart?", ["Forbruket øker fordi luftmotstanden blir større", "Forbruket synker", "Ingen påvirkning", "Bare elbiler påvirkes"],
  "I høy fart kan åpne vinduer gi like mye ekstra forbruk som aircondition.",
  "How do open windows affect consumption at high speed?", ["Consumption rises because drag increases", "Consumption falls", "No effect", "Only EVs are affected"],
  "At high speed open windows can add as much consumption as air conditioning."),
 N("Hvorfor bør du ikke kjøre rundt med tung last du ikke trenger?", ["Mer vekt gir høyere forbruk", "Det gir bedre veggrep og er lurt", "Det påvirker bare bremsene", "Det er ulovlig"],
  "Jo tyngre bilen er, jo mer energi går med til å akselerere den.",
  "Why shouldn't you carry heavy loads you don't need?", ["More weight means higher consumption", "It gives better grip and is smart", "It only affects the brakes", "It is illegal"],
  "The heavier the car, the more energy it takes to accelerate it.")
]);
// ---------- BIL 11: Førerkort, prøvetid og regler ----------
DQ("FKB", 11, [
 N("Hvor lang tid har du på teoriprøven for klasse B?", ["90 minutter", "30 minutter", "45 minutter", "3 timer"],
  "Du får 45 spørsmål og 90 minutter. Det holder godt hvis du har øvd.",
  "How long do you have for the class B theory test?", ["90 minutes", "30 minutes", "45 minutes", "3 hours"],
  "You get 45 questions and 90 minutes. That's plenty if you've practised."),
 N("Hva inneholder trafikalt grunnkurs?", ["Grunnleggende trafikkunnskap, førstehjelp og mørkekjøringsdemonstrasjon", "Bare førstehjelp", "Kjøring på glattbane", "Selve førerprøven"],
  "Trafikalt grunnkurs må være fullført før du kan øvelseskjøre. Mørkekjøringen gjennomføres som en del av opplæringen.",
  "What does the basic traffic course include?", ["Basic traffic knowledge, first aid and a night-driving demonstration", "Only first aid", "Skid-pan driving", "The driving test itself"],
  "The basic traffic course must be done before you can practise. Night driving is part of the training."),
 N("Hva skjer med prikkene i prikkbelastningen etter en stund?", ["Hver prikk slettes etter 3 år", "De varer livet ut", "De slettes etter 3 måneder", "De slettes når du fyller 25"],
  "Prikker teller i tre år. Får du 8 prikker i løpet av tre år, mister du førerretten i 6 måneder.",
  "What happens to penalty points over time?", ["Each point is deleted after 3 years", "They last for life", "They're deleted after 3 months", "They're deleted at age 25"],
  "Points count for three years. 8 points within three years means losing your licence for 6 months."),
 N("Du mister førerretten i prøvetiden. Hva må du gjøre for å få den tilbake?", ["Ta ny førerprøve, både teori og praktisk", "Bare vente", "Betale en bot", "Ta et kurs i førstehjelp"],
  "Tap av førerretten i prøvetiden betyr at du må ta hele førerprøven på nytt.",
  "You lose your licence during the probation period. What must you do to get it back?", ["Retake the driving test, both theory and practical", "Just wait", "Pay a fine", "Take a first-aid course"],
  "Losing the licence during probation means retaking the full driving test."),
 N("Hvorfor har nye førere prøvetid?", ["Nye førere har høyere ulykkesrisiko de første årene", "For å tjene penger på bøter", "Fordi bilen er ny", "For å lære seg å parkere"],
  "Risikoen er høyest rett etter førerprøven. Strengere reaksjoner i prøvetiden skal motivere til forsiktig kjøring.",
  "Why do new drivers have a probation period?", ["New drivers have higher crash risk in the first years", "To earn money from fines", "Because the car is new", "To learn to park"],
  "Risk is highest just after the test. Stricter penalties during probation encourage careful driving."),
 N("Hva er trinn 4 i føreropplæringen?", ["Avsluttende opplæring, blant annet sikkerhetskurs på veg", "Trafikalt grunnkurs", "Glattkjøring", "Teoriprøven"],
  "Trinn 4 forbereder deg på å kjøre alene, med blant annet planlegging og kjøring på landeveg.",
  "What is stage 4 of driver training?", ["Final training, including a road safety course", "The basic traffic course", "Skid training", "The theory test"],
  "Stage 4 prepares you for driving alone, including planning and driving on rural roads.")
]);
// ---------- MC 0–7 ----------
DQ("FKMC", 0, [
 N("Hvorfor bør hjelmen byttes etter et kraftig slag?", ["Skummet inni kan være skadet selv om skallet ser helt ut", "Den blir for liten", "Fargen falmer", "Det er påbudt hvert år"],
  "Det støtdempende skummet presses sammen ved et slag og beskytter dårligere neste gang.",
  "Why should a helmet be replaced after a hard impact?", ["The foam inside may be damaged even if the shell looks fine", "It becomes too small", "The colour fades", "It's required every year"],
  "The shock-absorbing foam is compressed by an impact and protects less next time."),
 N("Hva er en airbagvest for motorsyklister?", ["En vest som blåses opp ved fall og beskytter overkroppen", "En vest med refleks", "En vest med varme", "En regnjakke"],
  "Airbagvesten utløses av en snor eller elektronikk og beskytter nakke, rygg og bryst.",
  "What is a motorcycle airbag vest?", ["A vest that inflates in a fall to protect the upper body", "A reflective vest", "A heated vest", "A rain jacket"],
  "The vest is triggered by a cord or electronics and protects neck, back and chest."),
 N("Hvorfor er det lurt å velge en hjelm i lys farge?", ["Du blir lettere sett av andre trafikanter", "Den er lettere", "Den holder bedre på varmen", "Det er påbudt"],
  "Hodet er ofte det første andre ser av deg. Lyse og fluoriserende farger øker synligheten.",
  "Why is a light-coloured helmet a good idea?", ["Other road users see you more easily", "It's lighter", "It keeps you warmer", "It's required"],
  "Your head is often the first thing others see. Light and fluorescent colours increase visibility.")
]);
DQ("FKMC", 1, [
 N("Hvordan kjører du over jernbaneskinner eller trikkeskinner?", ["Så vinkelrett som mulig, uten å bremse eller svinge på skinnene", "Langs skinnene", "Med kraftig brems", "I høy fart"],
  "Skinner er glatte, særlig når de er våte. Hjulet kan sette seg fast i sporet hvis du kjører langs dem.",
  "How do you cross railway or tram tracks?", ["As close to a right angle as possible, without braking or steering on the rails", "Along the rails", "Braking hard", "At high speed"],
  "Rails are slippery, especially when wet. The wheel can get stuck in the groove if you ride along them."),
 N("Hvorfor bør du klemme knærne inntil tanken?", ["Det gir bedre kontroll og avlaster armene", "Det holder deg varm", "Det er bare for passasjerer", "For å spare drivstoff"],
  "Med knærne mot tanken kan du styre med kroppen og holde lett grep om styret.",
  "Why should you grip the tank with your knees?", ["It gives better control and takes load off your arms", "It keeps you warm", "It's only for passengers", "To save fuel"],
  "With your knees on the tank you can steer with your body and hold the bars lightly."),
 N("Hva er clutchens friksjonspunkt?", ["Punktet der clutchen begynner å overføre kraft", "Når clutchen er helt inne", "Når motoren stanser", "Når du girer ned"],
  "Ved lav fart og i trange svinger styrer du farten fint med clutchen rundt friksjonspunktet.",
  "What is the clutch's friction point?", ["The point where the clutch starts to transmit power", "When the clutch is fully in", "When the engine stalls", "When you shift down"],
  "At low speed and in tight turns you control speed finely with the clutch around the friction point.")
]);
DQ("FKMC", 2, [
 N("Hva er kombinerte bremser (CBS) på motorsykkel?", ["Én bremsespak eller pedal virker på begge hjul", "Bremser som bare virker på bakhjulet", "Bremser uten ABS", "Motorbrems"],
  "Med CBS fordeles bremsekraften automatisk mellom hjulene. Lær hvordan din motorsykkel virker.",
  "What are combined brakes (CBS) on a motorcycle?", ["One lever or pedal acts on both wheels", "Brakes only on the rear wheel", "Brakes without ABS", "Engine braking"],
  "With CBS the braking force is shared automatically between the wheels. Learn how your bike works."),
 N("Hvorfor bør du øve på nødbrems?", ["Så du reagerer riktig og bremser kraftig nok når det gjelder", "Det er bare nødvendig på bane", "Det sliter ut bremsene unødig", "Fordi ABS gjør jobben uansett"],
  "Mange bremser for forsiktig i en nødsituasjon. Øv på en trygg plass til det sitter.",
  "Why should you practise emergency braking?", ["So you react correctly and brake hard enough when it counts", "It's only needed on a track", "It wears the brakes needlessly", "Because ABS does the job anyway"],
  "Many brake too gently in an emergency. Practise in a safe place until it's automatic."),
 N("Hvorfor skal du unngå å bremse på vegmerking i regn?", ["Malingen er glatt når den er våt", "Malingen er ru", "Det er ulovlig", "Malingen skader dekket"],
  "Hvite linjer, kumlokk og skinner gir lite veggrep i regn. Gjør bremsingen før eller etter.",
  "Why avoid braking on road markings in the rain?", ["The paint is slippery when wet", "The paint is rough", "It's illegal", "The paint damages the tyre"],
  "White lines, manhole covers and rails offer little grip in rain. Brake before or after them.")
]);
DQ("FKMC", 3, [
 N("Hva menes med kjørelinjen gjennom en sving?", ["Linjen som gir best oversikt og størst sikkerhetsmargin", "Den korteste vegen rundt", "Midtlinjen", "Linjen som gir høyest fart"],
  "På veg handler kjørelinjen om sikt og marginer, ikke om å kjøre fortest mulig.",
  "What is meant by the line through a bend?", ["The line that gives the best view and largest safety margin", "The shortest way round", "The centre line", "The line that gives the highest speed"],
  "On the road the line is about visibility and margins, not going as fast as possible."),
 N("Du møter et tungt kjøretøy i en sving. Hva gjør du?", ["Senk farten og hold godt til høyre i feltet", "Legg deg nær midtlinjen", "Øk farten for å komme fort forbi", "Stans midt i svingen"],
  "Lange kjøretøy kan ta stor plass i svingene og lage sug og vind.",
  "You meet a heavy vehicle on a bend. What do you do?", ["Slow down and keep well to the right of your lane", "Move close to the centre line", "Speed up to pass quickly", "Stop in the middle of the bend"],
  "Long vehicles can use a lot of the road in bends and create suction and wind.")
]);
DQ("FKMC", 4, [
 N("Kan du være sikker på at en bilist som ser mot deg, har sett deg?", ["Nei – vær klar til å bremse eller svinge unna", "Ja, alltid", "Ja, hvis det er dagslys", "Ja, hvis du har nærlys på"],
  "Mange MC-ulykker skjer fordi bilister «ser uten å se» motorsykkelen. Planlegg en fluktveg.",
  "Can you be sure a driver looking your way has seen you?", ["No – be ready to brake or swerve", "Yes, always", "Yes, in daylight", "Yes, if your headlight is on"],
  "Many motorcycle crashes happen because drivers 'look without seeing' the bike. Plan an escape route."),
 N("Hvorfor er det lurt å unngå å ligge lenge rett ved siden av en bil i nabofeltet?", ["Du kan være i blindsonen til bilføreren", "Det er ulovlig", "Du får dårligere veggrep", "Bilen lager mye støy"],
  "Plasser deg der føreren kan se deg i speilene, eller kjør forbi bestemt.",
  "Why avoid riding alongside a car in the next lane for long?", ["You may be in the driver's blind spot", "It's illegal", "You get less grip", "The car makes a lot of noise"],
  "Position yourself where the driver can see you in the mirrors, or overtake decisively.")
]);
DQ("FKMC", 5, [
 N("Hvordan kjører du over et vått kumlokk?", ["Rett over, uten å bremse, akselerere eller svinge", "Med kraftig brems", "I en skarp sving", "Med mye gass"],
  "Kumlokk er glatte når de er våte. Hold motorsykkelen rett og jevn over dem.",
  "How do you ride over a wet manhole cover?", ["Straight over without braking, accelerating or turning", "Braking hard", "In a sharp turn", "With lots of throttle"],
  "Manhole covers are slippery when wet. Keep the bike upright and steady over them."),
 N("Du kjører over en høy bru med sterk sidevind. Hva gjør du?", ["Senker farten, holder løst grep og er klar for vindkast", "Holder hardt i styret og øker farten", "Legger deg nær midtlinjen", "Stanser midt på brua"],
  "Et stramt grep gjør at vindkastene overføres til styret. Slapp av i armene og la motorsykkelen bevege seg litt.",
  "You ride over a high bridge in a strong crosswind. What do you do?", ["Slow down, keep a light grip and be ready for gusts", "Grip the bars hard and speed up", "Move near the centre line", "Stop on the bridge"],
  "A tight grip transfers gusts to the bars. Relax your arms and let the bike move a little.")
]);
DQ("FKMC", 6, [
 N("Hva kan være tegn på at bremseklossene er slitt?", ["Hvinende lyd og dårligere bremseeffekt", "At motoren går ujevnt", "At lyset blir svakere", "At kjedet strammes"],
  "Sjekk tykkelsen på klossene jevnlig. Slitte klosser kan også skade bremseskiven.",
  "What can be signs of worn brake pads?", ["Squealing and weaker braking", "The engine running unevenly", "Dimmer lights", "The chain tightening"],
  "Check pad thickness regularly. Worn pads can also damage the disc."),
 N("Hvorfor skal du sjekke oljenivået jevnlig?", ["For lite olje kan gi motorskade", "Olje påvirker bremsene", "For å få bedre lys", "Det er bare nødvendig om vinteren"],
  "Sjekk på flatt underlag etter instruksjonsboka, og fyll på ved behov.",
  "Why check the oil level regularly?", ["Too little oil can damage the engine", "Oil affects the brakes", "For better lights", "Only needed in winter"],
  "Check on level ground as the manual says, and top up when needed.")
]);
DQ("FKMC", 7, [
 N("Hva skjer med styringen når du har tung bagasje langt bak?", ["Forhjulet blir lettere, og styringen kan bli ustabil", "Styringen blir tyngre og mer stabil", "Ingenting", "Bremsene blir bedre"],
  "Plasser tung last lavt og nær midten av motorsykkelen. Juster fjæringen og dekktrykket.",
  "What happens to the steering with heavy luggage far back?", ["The front gets lighter and steering can become unstable", "Steering gets heavier and more stable", "Nothing", "The brakes improve"],
  "Place heavy loads low and near the centre of the bike. Adjust the suspension and tyre pressure."),
 N("Hvor skal passasjeren holde seg fast?", ["Rundt føreren eller i passasjerhåndtakene", "I styret", "I bagasjen", "Ingen steder"],
  "Passasjeren skal sitte stille, holde seg fast og følge førerens bevegelser.",
  "Where should the passenger hold on?", ["Around the rider or on the passenger grab handles", "On the handlebars", "On the luggage", "Nowhere"],
  "The passenger should sit still, hold on and follow the rider's movements.")
]);
})();
