// ============================================================
//  add_forer2.js – flere spørsmål til førerkortet (lastes etter add_forer.js).
//  Spørsmålene legges bakerst i hver kategori, så lagret statistikk («enhet:indeks») beholder betydningen.
//  MC-enhetene 8–13 deler spørsmålene med bil (SHAREUNIT), så nye bilspørsmål i delte kategorier kommer med der også.
//  Format som DQ i add_forer.js: [bilde|null, nbSpm, [RIKTIG, feil, feil, feil], nbForklaring, enSpm, [RIGHT, …], enForklaring]
// ============================================================
(() => {
// ---------- BIL 0: Vikeplikt og forkjørsrett ----------
DQ("FKB", 0, [
 [null, "Du kjører ut fra en gårdsplass og over fortauet. Hvem har du vikeplikt for?", ["Alle, også gående på fortauet", "Bare biler fra høyre", "Bare biler fra venstre", "Ingen, fortauet er ikke en veg"],
  "Den som kjører ut fra en avkjørsel (gårdsplass, parkeringsplass, bensinstasjon) har vikeplikt for all trafikk, også gående og syklende på fortauet.",
  "You drive out of a driveway and across the pavement. Who must you give way to?", ["Everyone, including pedestrians on the pavement", "Only cars from the right", "Only cars from the left", "Nobody, the pavement is not a road"],
  "Whoever drives out of a private exit (driveway, car park, petrol station) must give way to all traffic, including pedestrians and cyclists on the pavement."],
 [null, "To veger uten skilt krysser hverandre. Den ene er en smal grusveg, den andre en bred asfaltveg. Hva gjelder?", ["Høyreregelen, uansett vegdekke og bredde", "Asfaltvegen har alltid forkjørsrett", "Grusvegen har alltid vikeplikt", "Den som kjører fortest har forkjørsrett"],
  "Bredden og vegdekket avgjør ikke vikeplikten. Uten skilt gjelder høyreregelen (men ikke for den som kommer fra en avkjørsel).",
  "Two roads without signs cross. One is a narrow gravel road, the other a wide tarmac road. What applies?", ["The right-hand rule, whatever the surface or width", "The tarmac road always has priority", "The gravel road always gives way", "Whoever drives fastest has priority"],
  "Width and surface do not decide right of way. Without signs the right-hand rule applies (except for traffic leaving a private exit)."],
 [null, "En trikk kommer fra venstre i et kryss uten skilt. Hvem har vikeplikt?", ["Du, kjørende har vikeplikt for sporvogn", "Trikken, fordi den kommer fra venstre", "Den som kommer først", "Ingen har vikeplikt"],
  "Kjørende har vikeplikt for sporvogn (trikk), også når den kommer fra venstre, med mindre skilt sier noe annet.",
  "A tram comes from the left at a junction without signs. Who must give way?", ["You, drivers give way to trams", "The tram, because it comes from the left", "Whoever arrives first", "Nobody has to give way"],
  "Drivers must give way to trams, even from the left, unless signs say otherwise."],
 [null, "Hvordan viser du tydelig at du skal overholde vikeplikten?", ["Ved å senke farten i god tid", "Ved å blinke med fjernlyset", "Ved å kjøre helt fram til krysset i full fart og bråbremse", "Ved å tute"],
  "Den du har vikeplikt for, skal ikke være i tvil. Senk farten i god tid, så ser andre at du vil vike.",
  "How do you clearly show that you will give way?", ["By slowing down in good time", "By flashing your high beam", "By driving up to the junction at full speed and braking hard", "By sounding the horn"],
  "The other road user should not be in doubt. Slow down early so others can see you will give way."],
 [null, "Du har parkert langs fortauskanten og skal kjøre ut i trafikken. Hvem har vikeplikt?", ["Du, for all trafikk på vegen", "Bilene bak deg, fordi du blinker", "Den som kommer fra høyre", "Ingen"],
  "Den som kjører ut fra vegkanten eller en parkeringsplass, har vikeplikt for all trafikk. Blinklyset gir deg ingen rett.",
  "You are parked at the kerb and want to pull out into traffic. Who must give way?", ["You, to all traffic on the road", "The cars behind you, because you indicate", "Whoever comes from the right", "Nobody"],
  "Whoever pulls out from the roadside or a parking place gives way to all traffic. Indicating gives you no right."],
 [null, "En syklist i kjørebanen kommer fra høyre i et kryss uten skilt. Hva gjelder?", ["Høyreregelen: du har vikeplikt for syklisten", "Syklister har alltid vikeplikt for biler", "Du har forkjørsrett fordi bilen er større", "Syklisten må gå av sykkelen"],
  "Syklister i kjørebanen er kjørende, og høyreregelen gjelder for dem også.",
  "A cyclist in the carriageway comes from the right at a junction without signs. What applies?", ["The right-hand rule: you give way to the cyclist", "Cyclists always give way to cars", "You have priority because the car is bigger", "The cyclist must dismount"],
  "Cyclists in the carriageway are drivers, and the right-hand rule applies to them too."],
 ["stopp", "Du kommer til et stoppskilt og ser at det ikke kommer noen. Hva gjør du?", ["Stanser helt ved stopplinjen likevel", "Kjører sakte forbi uten å stanse", "Stanser bare hvis det kommer biler", "Tuter og kjører"],
  "Ved stoppskilt skal du alltid stanse helt, selv om vegen er tom. Deretter har du vikeplikt.",
  "You reach a stop sign and see nobody coming. What do you do?", ["Stop completely at the stop line anyway", "Roll slowly past without stopping", "Stop only if cars are coming", "Sound the horn and go"],
  "At a stop sign you must always stop completely, even if the road is empty. Then you give way."],
 [null, "Du skal svinge til venstre, og den møtende bilen skal svinge til høyre inn i samme veg. Hvem har vikeplikt?", ["Du, som svinger til venstre", "Den møtende, som svinger til høyre", "Den som kom først", "Ingen, dere svinger i hvert deres felt"],
  "Den som svinger til venstre, har vikeplikt for møtende trafikk, også møtende som svinger til høyre inn i samme veg.",
  "You are turning left, and the oncoming car is turning right into the same road. Who must give way?", ["You, turning left", "The oncoming car turning right", "Whoever arrived first", "Nobody, you turn into separate lanes"],
  "Whoever turns left gives way to oncoming traffic, including oncoming traffic turning right into the same road."],
]);
// ---------- BIL 1: Skilt og vegoppmerking ----------
DQ("FKB", 1, [
 [null, "Hva betyr et rundt skilt med rød kant og helt hvit bunn uten symbol?", ["Forbudt for alle kjøretøy i begge retninger", "Parkering forbudt", "Fartsgrense", "Vikeplikt"],
  "Den hvite runde skiven med rød kant betyr at all kjøring med motorvogn er forbudt i begge retninger.",
  "What does a round sign with a red border and an entirely white face mean?", ["No vehicles in either direction", "No parking", "Speed limit", "Give way"],
  "The white round sign with a red border means no motor vehicles in either direction."],
 [null, "Hva betyr en hvit stiplet linje mellom to felt med trafikk i samme retning?", ["Kjørefeltlinje som du kan krysse når det er trygt", "Sperrelinje", "Vikepliktlinje", "Stopplinje"],
  "Hvit oppmerking skiller felt i samme retning. Den stiplede linjen kan krysses ved feltskifte.",
  "What does a white broken line between two lanes in the same direction mean?", ["Lane line that you may cross when safe", "No-crossing line", "Give-way line", "Stop line"],
  "White markings separate lanes in the same direction. The broken line may be crossed when changing lanes."],
 [null, "Midt i vegen er det en heltrukket og en stiplet linje ved siden av hverandre. Hva gjelder?", ["Du kan krysse fra den siden der den stiplede linjen er", "Ingen kan krysse", "Begge sider kan krysse fritt", "Bare tunge kjøretøy kan krysse"],
  "Ved dobbel linje gjelder linjen nærmest deg. Er den stiplet, kan du krysse. Er den heltrukket, kan du ikke.",
  "In the middle of the road there is a solid and a broken line side by side. What applies?", ["You may cross from the side with the broken line", "Nobody may cross", "Both sides may cross freely", "Only heavy vehicles may cross"],
  "With a double line, the line nearest you applies. If it is broken you may cross, if solid you may not."],
 ["vikeplikt", "Under vikepliktskiltet står et underskilt med «150 m». Hva betyr det?", ["Vikeplikten gjelder 150 meter lenger fram", "Vikeplikten gjelder bare de neste 150 meterne", "Fartsgrense 150", "Køen er 150 meter"],
  "Et avstandsskilt under et skilt forteller hvor langt det er fram til stedet skiltet gjelder.",
  "Under the give-way sign there is a plate saying '150 m'. What does it mean?", ["The give-way point is 150 metres ahead", "Give way only for the next 150 metres", "Speed limit 150", "The queue is 150 metres"],
  "A distance plate tells you how far it is to the point the sign refers to."],
 ["lys_gronn", "Trafikklyset viser grønt, men det står et vikepliktskilt ved krysset. Hva gjelder?", ["Trafikklyset", "Vikepliktskiltet", "Høyreregelen", "Den som kommer først"],
  "Rekkefølgen er politi, trafikklys, skilt, oppmerking og til slutt de generelle reglene. Lyset går foran skiltet når det virker.",
  "The traffic light shows green, but there is a give-way sign at the junction. What applies?", ["The traffic light", "The give-way sign", "The right-hand rule", "Whoever arrives first"],
  "The order is police, traffic lights, signs, markings and finally the general rules. The light overrides the sign while it works."],
 ["lys_blink", "Trafikklyset er slått av eller blinker gult. Hva gjelder da?", ["Skiltene i krysset, eller høyreregelen hvis det ikke er skilt", "Du har alltid forkjørsrett", "Du skal alltid stanse helt", "Trafikk fra venstre har forkjørsrett"],
  "Når lyset er ute av drift eller blinker gult, gjelder skilt og oppmerking, og ellers høyreregelen.",
  "The traffic light is off or flashing amber. What applies?", ["The signs at the junction, or the right-hand rule without signs", "You always have priority", "You must always stop completely", "Traffic from the left has priority"],
  "When the light is out of order or flashing amber, signs and markings apply, otherwise the right-hand rule."],
 [null, "Hvilken farge har oppmerkingen som skiller kjøreretningene?", ["Gul", "Hvit", "Blå", "Rød"],
  "Gul oppmerking skiller trafikk i motsatt retning. Hvit oppmerking skiller felt i samme retning og markerer kanten.",
  "What colour is the marking that separates directions of traffic?", ["Yellow", "White", "Blue", "Red"],
  "Yellow markings separate traffic in opposite directions. White markings separate lanes in the same direction and mark the edge."],
]);
// ---------- BIL 2: Fart, avstand og stopplengde ----------
DQ("FKB", 2, [
 [null, "Du veier 75 kg og har på belte. Omtrent hvor tung blir kroppen i et krasj i 50 km/t?", ["Rundt 2 tonn, omtrent som en bil", "Rundt 150 kg", "Det samme som ellers, 75 kg", "Rundt 50 tonn"],
  "Kroppen bremses over noen titalls centimeter. Det gir en kraft på omtrent 25 ganger kroppsvekten, rundt 1,8 tonn.",
  "You weigh 75 kg and wear a belt. Roughly how heavy does your body get in a crash at 50 km/h?", ["About 2 tonnes, roughly a car", "About 150 kg", "The same as usual, 75 kg", "About 50 tonnes"],
  "The body stops over a few tens of centimetres. That gives a force of about 25 times body weight, around 1.8 tonnes."],
 [null, "Hva skjer med kreftene i et krasj når farten dobles?", ["De blir omtrent fire ganger så store", "De dobles", "De blir like store", "De halveres"],
  "Bevegelsesenergien vokser med kvadratet av farten. Dobbel fart gir fire ganger så store krefter.",
  "What happens to the forces in a crash when the speed doubles?", ["They become about four times as large", "They double", "They stay the same", "They halve"],
  "Kinetic energy grows with the square of speed. Double the speed gives four times the force."],
 [null, "Hvorfor er det livsfarlig å holde et barn på fanget i bil?", ["I et krasj tilsvarer barnet flere tonn, ingen klarer å holde igjen", "Barnet ser ikke ut", "Det er bare ulovlig, ikke farlig", "Barnet kan bli bilsykt"],
  "Et barn på 20 kg i 50 km/t tilsvarer omtrent 2 tonn i et krasj. Barn skal alltid sikres i eget sete.",
  "Why is it life-threatening to hold a child on your lap in a car?", ["In a crash the child equals several tonnes and nobody can hold on", "The child cannot see out", "It is only illegal, not dangerous", "The child may get carsick"],
  "A 20 kg child at 50 km/h equals about 2 tonnes in a crash. Children must always be restrained in their own seat."],
 [null, "Hvorfor blir kreftene mye større uten belte?", ["Kroppen stopper på noen få centimeter mot rattet eller ruta i stedet for over beltet og knusesonen", "Bilen kjører fortere uten belte", "Beltet gjør deg lettere", "Det blir de ikke"],
  "Jo kortere strekning kroppen bremses på, desto større kraft. Uten belte blir strekningen kanskje en firedel så lang, og kraften fire ganger så stor.",
  "Why are the forces much larger without a belt?", ["The body stops within a few centimetres against the wheel or windscreen instead of over the belt and crumple zone", "The car goes faster without a belt", "The belt makes you lighter", "They are not"],
  "The shorter the distance the body stops over, the larger the force. Without a belt that distance may be a quarter as long, and the force four times as large."],
 ["tilhenger", "Hva er høyeste tillatte fart for personbil med tilhenger med bremser?", ["80 km/t", "60 km/t", "90 km/t", "100 km/t"],
  "Med bremset tilhenger er høyeste fart 80 km/t (60 km/t uten bremser), selv om skiltet viser mer.",
  "What is the maximum speed for a car with a braked trailer?", ["80 km/h", "60 km/h", "90 km/h", "100 km/h"],
  "With a braked trailer the maximum is 80 km/h (60 km/h unbraked), even where the sign shows more."],
 [null, "Bremselengden er 14 meter i 50 km/t. Omtrent hvor lang er den i 100 km/t på samme føre?", ["56 meter", "28 meter", "42 meter", "100 meter"],
  "Bremselengden øker med kvadratet av farten. Dobbel fart gir fire ganger så lang bremselengde: 4 · 14 = 56 m.",
  "Braking distance is 14 metres at 50 km/h. Roughly how long is it at 100 km/h on the same surface?", ["56 metres", "28 metres", "42 metres", "100 metres"],
  "Braking distance grows with the square of speed. Double the speed gives four times the distance: 4 · 14 = 56 m."],
 [null, "Hva er den høyeste fartsgrensen på norske veger?", ["110 km/t", "100 km/t", "120 km/t", "130 km/t"],
  "Enkelte motorveger er skiltet med 110 km/t. Det er den høyeste fartsgrensen i Norge.",
  "What is the highest speed limit on Norwegian roads?", ["110 km/h", "100 km/h", "120 km/h", "130 km/h"],
  "Some motorways are signed 110 km/h. That is the highest limit in Norway."],
 [null, "Hva skjer med synsfeltet ditt når farten øker?", ["Det blir smalere", "Det blir bredere", "Det endrer seg ikke", "Du ser bedre til sidene"],
  "I høy fart konsentrerer blikket seg langt fram, og du oppfatter mindre av det som skjer til sidene.",
  "What happens to your field of vision as speed increases?", ["It narrows", "It widens", "It does not change", "You see better to the sides"],
  "At high speed your gaze focuses far ahead, and you notice less of what happens at the sides."],
 [null, "Du kjører i 90 km/t og har reaksjonstid 1 sekund. Hvor langt kjører du før du begynner å bremse?", ["25 meter", "9 meter", "50 meter", "90 meter"],
  "90 km/t er 25 m/s. På ett sekunds reaksjonstid kjører du altså 25 meter før bremsene virker.",
  "You drive at 90 km/h with 1 second reaction time. How far do you travel before you start braking?", ["25 metres", "9 metres", "50 metres", "90 metres"],
  "90 km/h is 25 m/s. In one second of reaction time you travel 25 metres before the brakes act."],
 [null, "Det er glatt føre. Hva gjør du med avstanden til bilen foran?", ["Øker den betydelig", "Holder 3 sekunder som vanlig", "Kjører tettere så du ser bremselysene bedre", "Avstanden betyr ikke noe på glatta"],
  "På glatt føre kan bremselengden bli mange ganger lengre. Øk avstanden kraftig.",
  "The road is slippery. What do you do with the distance to the car in front?", ["Increase it considerably", "Keep 3 seconds as usual", "Drive closer to see the brake lights better", "Distance does not matter on ice"],
  "On a slippery road the braking distance can be many times longer. Increase the gap a lot."],
]);
// ---------- BIL 3: Plassering, feltskifte og forbikjøring ----------
DQ("FKB", 3, [
 [null, "Hvor plasserer du deg når du skal svinge til høyre?", ["Nær høyre kant av kjørebanen", "Midt i vegen", "Nær midtlinjen", "Helt til venstre"],
  "Før høyresving holder du deg nær høyre kant, så andre forstår hva du skal og ikke kan komme opp på innsiden.",
  "Where do you position yourself before turning right?", ["Close to the right edge of the carriageway", "In the middle of the road", "Close to the centre line", "Far to the left"],
  "Before turning right you keep close to the right edge so others understand and cannot come up on the inside."],
 [null, "Utenfor tettbygd strøk er det to felt i din kjøreretning. Hvilket felt bruker du normalt?", ["Høyre felt, og venstre felt ved forbikjøring", "Venstre felt", "Det feltet med minst trafikk", "Midt mellom feltene"],
  "Utenfor tettbygd strøk skal du holde deg i høyre felt og bruke venstre felt til forbikjøring.",
  "Outside built-up areas there are two lanes in your direction. Which lane do you normally use?", ["The right lane, and the left lane for overtaking", "The left lane", "The lane with least traffic", "Between the lanes"],
  "Outside built-up areas you keep to the right lane and use the left lane for overtaking."],
 [null, "Hvem kan kjøre i kollektivfeltet?", ["Buss og drosje, og andre bare der skilt tillater det", "Alle i rushtiden", "Alle som skal svinge til høyre om 1 km", "Bare lastebiler"],
  "Kollektivfeltet er for buss og drosje. Andre, for eksempel elbiler med passasjer, kan bare bruke det når skiltingen sier det.",
  "Who may drive in the bus lane?", ["Buses and taxis, and others only where signs allow", "Everyone at rush hour", "Anyone turning right within 1 km", "Only lorries"],
  "The bus lane is for buses and taxis. Others, such as electric cars with passengers, may only use it where signs allow."],
 [null, "Hvor nær et kryss kan du parkere?", ["Ikke nærmere enn 5 meter fra kryssende kjørebanes kant", "Rett i krysset er greit", "1 meter", "Ingen regel"],
  "Det er forbudt å stanse eller parkere i kryss og nærmere enn 5 meter fra kanten av den kryssende kjørebanen.",
  "How close to a junction may you park?", ["Not closer than 5 metres from the edge of the crossing carriageway", "In the junction is fine", "1 metre", "There is no rule"],
  "Stopping or parking is forbidden in junctions and within 5 metres of the edge of the crossing carriageway."],
 [null, "Du skal rygge ut fra en parkeringsplass. Hva gjelder?", ["Du må forsikre deg om at det kan skje uten fare for andre", "Andre må vike for deg når du rygger", "Du kan rygge hvis du blinker", "Ryggekamera gjør at du ikke trenger å se deg rundt"],
  "Den som rygger, har ansvaret og må se seg godt for. Kamera og sensorer er hjelpemidler, ikke en erstatning.",
  "You are reversing out of a parking space. What applies?", ["You must make sure it can be done without danger to others", "Others must give way when you reverse", "You may reverse if you indicate", "A reversing camera means you need not look around"],
  "Whoever reverses is responsible and must look carefully. Cameras and sensors are aids, not a replacement."],
 [null, "Du møter en bil i en smal sving på en veg uten midtlinje. Hva gjør du?", ["Senker farten og holder godt til høyre", "Holder midt i vegen", "Øker farten for å komme fortest forbi", "Blinker med fjernlyset"],
  "På smale veger skal begge holde godt til høyre og tilpasse farten, så dere kan passere trygt.",
  "You meet a car on a narrow bend on a road without a centre line. What do you do?", ["Slow down and keep well to the right", "Keep to the middle", "Speed up to pass quickly", "Flash your high beam"],
  "On narrow roads both should keep well to the right and adapt their speed so you can pass safely."],
]);
// ---------- BIL 4: Lys, signaler og trafikklys ----------
DQ("FKB", 4, [
 [null, "Når kan du bruke fjernlys?", ["I mørket når du ikke blender andre", "Alltid i mørket", "Bare på motorveg", "Bare i tåke"],
  "Fjernlys gir best sikt, men du må blende ned for møtende, når du kjører tett bak andre og når du kan blende gående.",
  "When may you use high beam?", ["In the dark when you do not dazzle others", "Always in the dark", "Only on motorways", "Only in fog"],
  "High beam gives the best view, but you must dip it for oncoming traffic, when close behind others and when it can dazzle pedestrians."],
 [null, "Når skal du bruke blinklys?", ["I god tid før du svinger, skifter felt eller kjører ut", "Først når du er midt i svingen", "Bare når det er andre i nærheten", "Bare i rundkjøringer"],
  "Blinklyset skal gi andre beskjed i god tid. Det gir deg likevel ingen rett til å svinge eller skifte felt.",
  "When should you indicate?", ["In good time before turning, changing lanes or pulling out", "Only once you are in the turn", "Only when others are nearby", "Only in roundabouts"],
  "The indicator should warn others in good time. It still gives you no right to turn or change lanes."],
 [null, "Du kommer plutselig til en kø på motorvegen og må bremse kraftig. Hva kan du gjøre for å varsle bilene bak?", ["Slå på nødblinklyset en kort stund", "Tute lenge", "Slå på tåkebaklyset", "Blinke med fjernlyset"],
  "Nødblinklys kan brukes kort for å varsle trafikken bak om kø eller fare foran.",
  "You suddenly reach a queue on the motorway and must brake hard. How can you warn the cars behind?", ["Switch on the hazard lights briefly", "Sound the horn for a long time", "Switch on the rear fog light", "Flash your high beam"],
  "Hazard lights may be used briefly to warn traffic behind of a queue or danger ahead."],
 [null, "Du har parkert langs en veg uten gatelys i mørket. Hvilket lys skal bilen ha?", ["Parkeringslys", "Ingen lys", "Fjernlys", "Tåkelys"],
  "En parkert bil på veg uten belysning skal ha parkeringslys, så andre ser den.",
  "You have parked beside an unlit road in the dark. Which lights should the car have on?", ["Parking lights", "No lights", "High beam", "Fog lights"],
  "A parked car on an unlit road must show parking lights so others can see it."],
 [null, "En brøytebil foran deg har gule blinkende lys. Hva betyr det?", ["Den varsler om arbeid eller fare, og du skal være ekstra forsiktig", "Den gir deg tegn til å kjøre forbi", "Den har forkjørsrett som en ambulanse", "Den skal svinge til høyre"],
  "Gult blinkende lys på kjøretøy brukes for å varsle andre, for eksempel ved brøyting og vegarbeid.",
  "A snowplough ahead of you has flashing amber lights. What does it mean?", ["It warns of work or danger, and you should take extra care", "It signals you to overtake", "It has priority like an ambulance", "It is turning right"],
  "Flashing amber lights on vehicles warn others, for example during snow clearing and roadworks."],
 ["lys_rod", "Trafikklyset viser rødt. Hvor skal du stanse?", ["Ved stopplinjen, eller før lyset hvis det ikke er stopplinje", "Midt i krysset", "Rett etter lyset", "Hvor som helst før krysset"],
  "Ved rødt lys stanser du ved stopplinjen. Er det ingen stopplinje, stanser du før trafikklyset.",
  "The traffic light shows red. Where must you stop?", ["At the stop line, or before the light if there is none", "In the middle of the junction", "Just after the light", "Anywhere before the junction"],
  "At a red light you stop at the stop line. If there is none, you stop before the traffic light."],
]);
// ---------- BIL 5: Myke trafikanter og samspill ----------
DQ("FKB", 5, [
 [null, "En ball triller ut i vegen foran deg. Hva bør du forvente?", ["At et barn kan løpe etter den", "At ballen stopper av seg selv", "Ingenting, kjør videre", "At noen kaster flere baller"],
  "Barn følger ballen uten å se seg for. Senk farten og vær klar til å stanse.",
  "A ball rolls into the road ahead. What should you expect?", ["That a child may run after it", "That the ball stops by itself", "Nothing, drive on", "That someone throws more balls"],
  "Children follow the ball without looking. Slow down and be ready to stop."],
 [null, "På hvilken side av vegen skal gående gå når det ikke er fortau?", ["Venstre side, mot kjøreretningen", "Høyre side, med kjøreretningen", "Midt i vegen", "Hvilken som helst"],
  "Gående bør gå på venstre side, så de ser trafikken som kommer mot dem.",
  "Which side of the road should pedestrians walk on when there is no pavement?", ["The left side, facing traffic", "The right side, with traffic", "In the middle", "Either side"],
  "Pedestrians are advised to walk on the left so they can see the traffic coming towards them."],
 [null, "Kan syklister sykle på fortauet?", ["Ja, når det ikke er til fare eller vesentlig hinder for gående", "Nei, aldri", "Bare barn under 10 år", "Bare om natten"],
  "Det er lov å sykle på fortauet, men syklisten skal ta hensyn og holde lav fart der det er gående.",
  "May cyclists ride on the pavement?", ["Yes, when it does not endanger or seriously hinder pedestrians", "No, never", "Only children under 10", "Only at night"],
  "Cycling on the pavement is allowed, but cyclists must show consideration and keep a low speed near pedestrians."],
 [null, "En eldre person bruker lang tid over gangfeltet. Hva gjør du?", ["Venter tålmodig til personen er trygt over", "Kjører forsiktig rundt personen", "Tuter så personen går fortere", "Kjører når personen er forbi midten"],
  "Du har vikeplikt for gående i gangfeltet til de er trygt over. Vis tålmodighet.",
  "An elderly person takes a long time on the crossing. What do you do?", ["Wait patiently until they are safely across", "Drive carefully around them", "Sound the horn to hurry them", "Go once they are past the middle"],
  "You give way to pedestrians on the crossing until they are safely across. Be patient."],
 [null, "Du ser en flokk sauer ved vegen. Hva gjør du?", ["Senker farten og er klar til å stanse", "Tuter så de går unna", "Holder farten", "Kjører nær kanten for å skremme dem bort"],
  "Dyr er uforutsigbare og kan plutselig gå ut i vegen. Senk farten og kjør rolig forbi.",
  "You see a flock of sheep by the road. What do you do?", ["Slow down and be ready to stop", "Sound the horn so they move", "Keep your speed", "Drive near the edge to scare them away"],
  "Animals are unpredictable and may suddenly step into the road. Slow down and pass calmly."],
 [null, "Hvorfor er barn ekstra utsatt i trafikken?", ["De er små, vanskelige å se og bedømmer fart og avstand dårligere", "De går alltid for fort", "De følger alltid reglene", "De er lette å se"],
  "Barn er lave, ser ikke over biler og har vanskelig for å bedømme hvor fort en bil kommer.",
  "Why are children especially vulnerable in traffic?", ["They are small, hard to see and judge speed and distance poorly", "They always walk too fast", "They always follow the rules", "They are easy to see"],
  "Children are short, cannot see over cars and find it hard to judge how fast a car is approaching."],
]);
// ---------- BIL 6: Rus, trøtthet og oppmerksomhet ----------
DQ("FKB", 6, [
 [null, "Du har 0,9 promille. Omtrent hvor lang tid tar det før alkoholen er ute av kroppen?", ["Omtrent 6 timer", "Omtrent 1 time", "Omtrent 2 timer", "Omtrent 24 timer"],
  "Kroppen forbrenner omtrent 0,15 promille i timen: 0,9 / 0,15 = 6 timer.",
  "Your blood alcohol is 0.9 per mille. Roughly how long until the alcohol is gone?", ["About 6 hours", "About 1 hour", "About 2 hours", "About 24 hours"],
  "The body burns about 0.15 per mille per hour: 0.9 / 0.15 = 6 hours."],
 [null, "Kan du kjøre bil etter å ha brukt cannabis?", ["Nei, det er forbudt, og det er faste grenser for mange rusmidler", "Ja, hvis du føler deg klar", "Ja, etter én time", "Ja, cannabis påvirker ikke kjøringen"],
  "Det er forbudt å kjøre påvirket av rusmidler. For mange stoffer gjelder faste grenser, akkurat som promillegrensen.",
  "May you drive after using cannabis?", ["No, it is forbidden, and there are fixed limits for many drugs", "Yes, if you feel fine", "Yes, after one hour", "Yes, cannabis does not affect driving"],
  "Driving under the influence of drugs is forbidden. Fixed limits apply to many substances, just like the alcohol limit."],
 [null, "Hva er mikrosøvn?", ["At du sovner noen sekunder uten å merke det", "En kort pause på rasteplass", "At du blunker ofte", "En type trøtthet som bare rammer om natten"],
  "Ved mikrosøvn sovner du i noen sekunder. I 80 km/t kjører du over 20 meter i sekundet uten kontroll.",
  "What is microsleep?", ["Falling asleep for a few seconds without noticing", "A short break at a rest area", "Blinking often", "Tiredness that only happens at night"],
  "During microsleep you fall asleep for a few seconds. At 80 km/h you travel over 20 metres a second without control."],
 [null, "Hjelper energidrikk mot trøtthet bak rattet?", ["Bare en kort stund. Det eneste som virker, er søvn", "Ja, den gjør deg helt opplagt i flere timer", "Ja, hvis du drikker to", "Ja, sammen med åpent vindu"],
  "Koffein og åpent vindu hjelper bare kort. Blir du trøtt, må du stoppe og sove eller hvile.",
  "Does an energy drink help against tiredness at the wheel?", ["Only briefly. The only real cure is sleep", "Yes, it keeps you alert for hours", "Yes, if you drink two", "Yes, together with an open window"],
  "Caffeine and an open window help only briefly. If you get tired, stop and sleep or rest."],
 [null, "Politiet ber deg blåse i et alkometer. Kan du nekte?", ["Nei, du har plikt til å medvirke", "Ja, alltid", "Ja, hvis du ikke har drukket", "Ja, hvis du har en advokat"],
  "Føreren har plikt til å medvirke til alkotest når politiet ber om det.",
  "The police ask you to take a breath test. May you refuse?", ["No, you are obliged to cooperate", "Yes, always", "Yes, if you have not been drinking", "Yes, if you have a lawyer"],
  "Drivers are obliged to take a breath test when the police ask."],
 ["mobil", "Er det lov å snakke i mobilen med håndfri løsning mens du kjører?", ["Ja, men det tar oppmerksomhet, så hold samtalen kort eller vent", "Nei, aldri", "Bare under 50 km/t", "Ja, og det distraherer ikke"],
  "Håndfri samtale er lov, men samtalen tar oppmerksomhet fra kjøringen. Vent med krevende samtaler.",
  "Is it legal to talk on a hands-free phone while driving?", ["Yes, but it takes attention, so keep it short or wait", "No, never", "Only below 50 km/h", "Yes, and it is not distracting"],
  "Hands-free calls are legal, but the conversation takes attention from driving. Postpone demanding calls."],
]);
// ---------- BIL 7: Kjøretøyet, last og tilhenger ----------
DQ("FKB", 7, [
 [null, "Hvem har ansvaret for at bilen er i forsvarlig stand når du kjører?", ["Føreren", "Bare eieren", "Verkstedet", "Statens vegvesen"],
  "Føreren skal forsikre seg om at kjøretøyet er i forsvarlig stand før og under kjøringen.",
  "Who is responsible for the car being roadworthy while you drive?", ["The driver", "Only the owner", "The garage", "The road authority"],
  "The driver must make sure the vehicle is roadworthy before and during the trip."],
 [null, "Hvor ofte skal en personbil til EU-kontroll?", ["Første gang innen 4 år, deretter hvert 2. år", "Hvert år", "Hvert 5. år", "Bare når den selges"],
  "Nye personbiler kontrolleres første gang innen fire år, og deretter annethvert år.",
  "How often must a car have its periodic roadworthiness test (EU-kontroll)?", ["First within 4 years, then every 2 years", "Every year", "Every 5 years", "Only when it is sold"],
  "New cars are tested first within four years, and then every second year."],
 [null, "Hva er høyeste tillatte totalvekt for en bil du kan kjøre med klasse B?", ["3500 kg", "2500 kg", "5000 kg", "7500 kg"],
  "Klasse B gjelder bil med tillatt totalvekt inntil 3500 kg.",
  "What is the maximum permitted total weight of a car you may drive with class B?", ["3500 kg", "2500 kg", "5000 kg", "7500 kg"],
  "Class B covers vehicles with a permitted total weight up to 3500 kg."],
 [null, "Hvordan skal last på eller i bilen være sikret?", ["Så den ikke kan forskyve seg, falle av eller skade noen", "Den trenger bare sikring på motorveg", "Bare tung last må sikres", "Last i bagasjerommet trenger aldri sikring"],
  "Løs last kan bli livsfarlig ved bråstopp. All last skal være sikret.",
  "How must load on or in the car be secured?", ["So it cannot shift, fall off or injure anyone", "It only needs securing on motorways", "Only heavy loads need securing", "Load in the boot never needs securing"],
  "Loose load can be deadly in a sudden stop. All load must be secured."],
 [null, "Hvor finner du riktig dekktrykk for bilen?", ["I instruksjonsboka eller på et merke i dørstolpen eller tanklokket", "På dekket står alltid riktig trykk for din bil", "Det er likt for alle biler", "Hos politiet"],
  "Riktig trykk avhenger av bilen og lasten. Det står i instruksjonsboka eller på et merke i bilen.",
  "Where do you find the correct tyre pressure for the car?", ["In the handbook or on a label in the door pillar or fuel flap", "The tyre always shows the right pressure for your car", "It is the same for all cars", "At the police"],
  "The correct pressure depends on the car and its load. It is in the handbook or on a label in the car."],
]);
// ---------- BIL 8: Vinter, mørke og vanskelige forhold ----------
DQ("FKB", 8, [
 [null, "Bakhjulene sklir ut på glatta (bilen overstyrer). Hva gjør du?", ["Styrer dit du vil kjøre og slipper forsiktig av gassen", "Bråbremser", "Styrer motsatt vei av dit du vil", "Gir full gass"],
  "Se og styr dit du vil. Unngå brå bremsing og brå gasspådrag til bilen har fått grep igjen.",
  "The rear wheels slide out on ice (oversteer). What do you do?", ["Steer where you want to go and ease off the throttle gently", "Brake hard", "Steer the opposite way", "Accelerate hard"],
  "Look and steer where you want to go. Avoid sudden braking and throttle until the car grips again."],
 [null, "Bilen går rett fram selv om du svinger (understyring). Hva gjør du?", ["Slipper gassen og reduserer rattutslaget litt", "Svinger enda mer", "Gir mer gass", "Trekker i håndbrekket"],
  "Forhjulene har mistet grep. Slipp gassen og rett litt opp, så får hjulene grep og bilen begynner å svinge igjen.",
  "The car goes straight ahead even though you steer (understeer). What do you do?", ["Ease off the throttle and reduce the steering angle a little", "Steer even more", "Accelerate", "Pull the handbrake"],
  "The front wheels have lost grip. Ease off and straighten a little so they grip and the car turns again."],
 [null, "Hvorfor gir fjernlys dårlig sikt i tett tåke?", ["Lyset reflekteres av tåken og blender deg", "Fjernlyset er for svakt", "Det er forbudt", "Det gir bedre sikt, ikke dårligere"],
  "Tåkedråpene kaster lyset tilbake. Bruk nærlys (og eventuelt tåkelys) og senk farten.",
  "Why does high beam give poor visibility in thick fog?", ["The light reflects off the fog and dazzles you", "High beam is too weak", "It is forbidden", "It gives better visibility, not worse"],
  "Fog droplets reflect the light back. Use dipped beam (and fog lights if fitted) and slow down."],
 ["elg", "Når er faren for vilt i vegen størst?", ["I skumringen og om natten", "Midt på dagen", "Bare om sommeren", "Bare på motorveg"],
  "Hjort og elg er mest aktive i skumringen og i mørket, særlig høst og vinter.",
  "When is the risk of wildlife on the road greatest?", ["At dusk and at night", "At midday", "Only in summer", "Only on motorways"],
  "Deer and moose are most active at dusk and in the dark, especially in autumn and winter."],
 [null, "Hva er svart is?", ["Tynn, blank is som ser ut som våt asfalt", "Is som er farget av salt", "Snø blandet med grus", "Is som bare finnes i tunneler"],
  "Svart is er vanskelig å se og ligner våt veg. Den oppstår ofte rundt 0 °C, på bruer og i skygge.",
  "What is black ice?", ["Thin clear ice that looks like wet tarmac", "Ice coloured by salt", "Snow mixed with gravel", "Ice that only forms in tunnels"],
  "Black ice is hard to see and looks like a wet road. It often forms around 0 °C, on bridges and in shade."],
 [null, "Hva er lurt å ha i bilen om vinteren?", ["Isskrape, kost, varme klær og lommelykt", "Bare solbriller", "Ekstra sommerdekk", "Ingenting, bilen har varme"],
  "Blir du stående, kan det bli kaldt lenge. Utstyr for å rydde bilen og holde deg varm er viktig.",
  "What is wise to carry in the car in winter?", ["Ice scraper, brush, warm clothes and a torch", "Only sunglasses", "Spare summer tyres", "Nothing, the car has heating"],
  "If you get stuck it may be cold for a long time. Gear to clear the car and keep warm is important."],
]);
// ---------- BIL 9: Ulykker og førstehjelp ----------
DQ("FKB", 9, [
 ["varseltrekant", "Hvor langt bak bilen bør varseltrekanten stå på en veg med høy fart?", ["Så langt at andre får varsel i god tid, gjerne 150–250 meter", "Rett bak bilen", "Foran bilen", "Den trengs ikke på dagtid"],
  "Trafikken bak må få tid til å oppdage faren og stanse. Jo høyere fart, desto lenger bak.",
  "How far behind the car should the warning triangle be on a high-speed road?", ["Far enough to warn others in good time, often 150–250 metres", "Right behind the car", "In front of the car", "It is not needed in daylight"],
  "Traffic behind needs time to see the danger and stop. The higher the speed, the further back."],
 [null, "Hvordan behandler du en brannskade?", ["Kjøler med lunkent vann i omtrent 20 minutter", "Smører på smør", "Legger på is direkte", "River av klær som sitter fast"],
  "Kjøl brannskaden med lunkent vann i lang tid. Ikke fjern klær som har brent seg fast.",
  "How do you treat a burn?", ["Cool it with lukewarm water for about 20 minutes", "Apply butter", "Put ice directly on it", "Tear off clothing that is stuck"],
  "Cool the burn with lukewarm water for a long time. Do not remove clothing that has stuck to it."],
 [null, "En skadet person er blek, kaldsvett og urolig (sjokk). Hva gjør du?", ["Legger personen ned, holder henne varm og ringer 113", "Gir personen alkohol", "Lar personen gå rundt", "Gir mye vann å drikke"],
  "Ved sjokk skal personen ligge, holdes varm og få ro. Ring 113.",
  "An injured person is pale, cold and sweaty and restless (shock). What do you do?", ["Lay them down, keep them warm and call 113", "Give them alcohol", "Let them walk around", "Give plenty of water"],
  "In shock the person should lie down, be kept warm and calm. Call 113."],
 [null, "Det finnes en hjertestarter i nærheten av en person med hjertestans. Hva gjør du?", ["Henter og bruker den, og følger talebeskjedene", "Venter på ambulansen før den brukes", "Bruker den bare hvis du er lege", "Bruker den bare hvis personen puster"],
  "Hjertestarteren forteller deg hva du skal gjøre. Bruk den så raskt som mulig, sammen med HLR.",
  "There is a defibrillator near a person in cardiac arrest. What do you do?", ["Fetch and use it, following the voice prompts", "Wait for the ambulance before using it", "Use it only if you are a doctor", "Use it only if the person is breathing"],
  "The defibrillator tells you what to do. Use it as soon as possible, together with CPR."],
 [null, "Du har vært innblandet i en ulykke med personskade. Hva gjelder?", ["Du skal stanse, hjelpe og melde fra til politiet", "Du kan kjøre videre hvis du ikke har skyld", "Det holder å gi navnet ditt til de skadde", "Du skal bare ringe forsikringsselskapet"],
  "Den som er innblandet i en ulykke, skal stanse, hjelpe til og melde fra til politiet når noen er skadet.",
  "You have been involved in an accident with injuries. What applies?", ["You must stop, help and report to the police", "You may drive on if it was not your fault", "Giving your name to the injured is enough", "You only need to call the insurer"],
  "Anyone involved in an accident must stop, help and report to the police when someone is injured."],
 [null, "Hvilket nummer ringer du ved brann?", ["110", "112", "113", "111"],
  "110 er brann, 112 er politi og 113 er medisinsk nødhjelp.",
  "Which number do you call in case of fire?", ["110", "112", "113", "111"],
  "110 is fire, 112 is police and 113 is medical emergency."],
]);
// ---------- BIL 10: Miljø og økonomisk kjøring ----------
DQ("FKB", 10, [
 [null, "Hva skjer med forbruket når du øker farten fra 80 til 110 km/t?", ["Det øker mye, fordi luftmotstanden øker kraftig", "Det synker", "Det er likt", "Det øker bare for elbiler"],
  "Luftmotstanden øker med kvadratet av farten. Høy fart koster mye energi.",
  "What happens to consumption when you increase speed from 80 to 110 km/h?", ["It rises a lot because air resistance increases sharply", "It falls", "It stays the same", "It only rises for electric cars"],
  "Air resistance grows with the square of speed. High speed costs a lot of energy."],
 [null, "Hvorfor får en elbil kortere rekkevidde i kulde?", ["Batteriet yter dårligere, og kupé og batteri må varmes opp", "Fordi vinterdekk er tyngre", "Elbiler påvirkes ikke av kulde", "Fordi det er mørkt"],
  "Kulde svekker batteriet, og oppvarming bruker mye strøm. Forvarm gjerne mens bilen lader.",
  "Why does an electric car get shorter range in the cold?", ["The battery performs worse, and the cabin and battery need heating", "Because winter tyres are heavier", "Electric cars are not affected by cold", "Because it is dark"],
  "Cold weakens the battery, and heating uses a lot of power. Preheat while the car is charging."],
 [null, "Hvorfor er det lurt å bruke motorvarmer om vinteren?", ["Mindre slitasje, lavere forbruk og mindre utslipp ved kaldstart", "Bilen går fortere", "Det er påbudt", "Den lader batteriet på elbilen"],
  "En kald motor slites mer og slipper ut mer. Motorvarmer gjør kaldstarten skånsom.",
  "Why is it wise to use an engine heater in winter?", ["Less wear, lower consumption and fewer emissions at cold start", "The car goes faster", "It is mandatory", "It charges an electric car"],
  "A cold engine wears more and pollutes more. An engine heater makes cold starts gentle."],
 [null, "Hva er en ulempe med piggdekk for miljøet?", ["De sliter asfalten og gir svevestøv", "De øker rekkevidden", "De gir mindre støy", "De har ingen ulemper"],
  "Piggdekk river opp asfalten. Svevestøvet er skadelig å puste inn, særlig i byer.",
  "What is an environmental downside of studded tyres?", ["They wear the tarmac and create airborne dust", "They increase range", "They are quieter", "They have no downsides"],
  "Studs tear up the tarmac. The dust is harmful to breathe, especially in cities."],
 [null, "Hvordan kan du spare drivstoff når du nærmer deg rødt lys?", ["Slippe gassen tidlig og trille mot lyset", "Holde farten og bremse hardt", "Gire ned og gi gass", "Kjøre i nøytral med motoren av"],
  "Ser du langt fram, kan du slippe gassen tidlig og la bilen rulle. Da bruker du mindre drivstoff og bremser.",
  "How can you save fuel when approaching a red light?", ["Release the throttle early and roll towards it", "Keep your speed and brake hard", "Change down and accelerate", "Coast in neutral with the engine off"],
  "Looking far ahead lets you lift off early and roll. You use less fuel and less brake."],
 [null, "Hva er et godt miljøvalg for korte turer i byen?", ["Gå, sykle eller reise kollektivt", "Kjøre bil med kald motor", "Kjøre ekstra runder for å varme motoren", "La motoren gå på tomgang mens du venter"],
  "Korte turer med kald motor gir høyt forbruk og mye utslipp. Gange, sykkel og kollektiv er bedre for miljøet.",
  "What is a good environmental choice for short trips in town?", ["Walk, cycle or use public transport", "Drive with a cold engine", "Drive extra laps to warm the engine", "Idle the engine while you wait"],
  "Short trips with a cold engine mean high consumption and emissions. Walking, cycling and public transport are better."],
]);
// ---------- BIL 11: Førerkort, prøvetid og regler ----------
DQ("FKB", 11, [
 [null, "Hva er spesielt med prikker i prøvetiden?", ["De teller dobbelt", "De teller ikke", "De forsvinner etter 1 måned", "Du kan få 16 prikker"],
  "I prøvetiden (de to første årene) teller hver prikk dobbelt. Det skal lite til før du mister førerretten.",
  "What is special about penalty points during the probation period?", ["They count double", "They do not count", "They disappear after one month", "You can get 16 points"],
  "During the probation period (first two years) each point counts double. It takes little to lose your licence."],
 [null, "Må du ha med førerkortet når du kjører?", ["Ja, du skal ha det med og vise det til politiet når de ber om det", "Nei, det holder at du har det hjemme", "Bare på lange turer", "Bare utenlands"],
  "Føreren skal ha med førerkortet og vise det fram ved kontroll.",
  "Must you carry your driving licence when driving?", ["Yes, and show it to the police when asked", "No, it is enough to have it at home", "Only on long trips", "Only abroad"],
  "The driver must carry the licence and show it at a check."],
 ["lskilt", "Hva gjelder for skiltet «L» ved øvelseskjøring?", ["Det skal være godt synlig bak på bilen", "Det kan ligge i hanskerommet", "Det trengs bare i byen", "Det trengs ikke hvis ledsageren er over 25"],
  "Under øvelseskjøring skal bilen ha et godt synlig L-skilt bak, så andre vet at føreren er under opplæring.",
  "What applies to the 'L' plate when practising?", ["It must be clearly visible at the rear of the car", "It may lie in the glovebox", "It is only needed in town", "It is not needed if the supervisor is over 25"],
  "When practising, the car must have a clearly visible L plate at the rear so others know the driver is learning."],
 [null, "Du har førerkort klasse B. Kan du kjøre motorsykkel i klasse A1?", ["Nei, det krever eget førerkort for A1", "Ja, alltid", "Ja, etter to år", "Ja, hvis du har hjelm"],
  "I Norge gir ikke klasse B rett til å kjøre lett motorsykkel. Du må ta førerkort for klasse A1, A2 eller A.",
  "You have a class B licence. May you ride a class A1 motorcycle?", ["No, A1 requires its own licence", "Yes, always", "Yes, after two years", "Yes, if you wear a helmet"],
  "In Norway class B does not cover light motorcycles. You need a class A1, A2 or A licence."],
]);

// ===================== MC =====================
// ---------- MC 0: MC-klasser, alder og utstyr ----------
DQ("FKMC", 0, [
 [null, "Hvor stor effekt kan en motorsykkel i klasse A1 høyst ha?", ["11 kW", "35 kW", "25 kW", "Ubegrenset"],
  "A1 gjelder lett motorsykkel med slagvolum inntil 125 cm³ og effekt inntil 11 kW.",
  "What is the maximum power of a class A1 motorcycle?", ["11 kW", "35 kW", "25 kW", "Unlimited"],
  "A1 covers light motorcycles up to 125 cm³ and 11 kW."],
 [null, "Hva er kravet til effekt per vekt for en A2-motorsykkel?", ["Høyst 0,2 kW per kg", "Høyst 1 kW per kg", "Minst 0,5 kW per kg", "Det er ingen krav"],
  "A2-sykler kan ha inntil 35 kW og høyst 0,2 kW/kg.",
  "What is the power-to-weight limit for an A2 motorcycle?", ["At most 0.2 kW per kg", "At most 1 kW per kg", "At least 0.5 kW per kg", "There is no limit"],
  "A2 bikes may have up to 35 kW and at most 0.2 kW/kg."],
 [null, "Kan en kraftig motorsykkel strupes ned slik at den kan kjøres med A2?", ["Ja, hvis den opprinnelig ikke har mer enn 70 kW", "Nei, aldri", "Ja, uansett opprinnelig effekt", "Bare med A1"],
  "En sykkel kan strupes til 35 kW for A2, men den kan ikke være avledet fra en modell med mer enn dobbel effekt (70 kW).",
  "Can a powerful motorcycle be restricted so it can be ridden on an A2 licence?", ["Yes, if its original power is no more than 70 kW", "No, never", "Yes, whatever its original power", "Only with A1"],
  "A bike can be restricted to 35 kW for A2, but it must not be derived from a model with more than double that (70 kW)."],
 [null, "Hvilken klasse gir rett til å kjøre alle motorsykler uten effektbegrensning?", ["A", "A2", "A1", "B"],
  "Klasse A har ingen begrensning på effekt. A2 og A1 har grenser.",
  "Which class allows you to ride all motorcycles with no power limit?", ["A", "A2", "A1", "B"],
  "Class A has no power limit. A2 and A1 have limits."],
 [null, "Hvilket verneutstyr anbefales i tillegg til hjelm, jakke og bukse?", ["Ryggskinne, hansker og støvler med ankelbeskyttelse", "Joggesko", "Shorts om sommeren", "Ingenting mer"],
  "Godt verneutstyr reduserer skadene ved velt. Ryggskinne og ordentlige støvler og hansker er viktige.",
  "What protective gear is recommended in addition to helmet, jacket and trousers?", ["Back protector, gloves and boots with ankle protection", "Trainers", "Shorts in summer", "Nothing more"],
  "Good protective gear reduces injuries in a fall. A back protector and proper boots and gloves matter."],
 [null, "Når kan du ha med passasjer på motorsykkelen?", ["Når sykkelen er registrert for passasjer og passasjeren har hjelm", "Alltid", "Bare med klasse A1", "Aldri"],
  "Sykkelen må ha plass og fotstøtter til passasjer og være registrert for det. Passasjeren skal ha hjelm.",
  "When may you carry a passenger on the motorcycle?", ["When the bike is registered for a passenger and the passenger wears a helmet", "Always", "Only with class A1", "Never"],
  "The bike must have a seat and footrests for a passenger and be registered for it. The passenger must wear a helmet."],
]);
// ---------- MC 1: Kjøreteknikk og balanse ----------
DQ("FKMC", 1, [
 [null, "Hvordan starter du i en bratt motbakke?", ["Holder igjen med bakbremsen, finner slirepunktet og gir gass", "Holder igjen med forbremsen og slipper clutchen raskt", "Ruller bakover først", "Gir full gass uten clutch"],
  "Bakbremsen holder sykkelen mens hendene brukes til clutch og gass. Slipp bremsen når clutchen tar.",
  "How do you pull away on a steep uphill?", ["Hold with the rear brake, find the biting point and add throttle", "Hold with the front brake and drop the clutch", "Roll back first", "Full throttle without the clutch"],
  "The rear brake holds the bike while your hands work the clutch and throttle. Release the brake as the clutch bites."],
 [null, "Styret begynner å slingre i høy fart. Hva gjør du?", ["Holder løst i styret og slipper gassen gradvis", "Holder hardt og bremser kraftig", "Gir mer gass", "Står opp på fotstøttene"],
  "Et stramt grep forsterker slingringen. Hold løst, slipp gassen rolig og unngå brå bremsing.",
  "The handlebars start to wobble at high speed. What do you do?", ["Hold the bars loosely and ease off the throttle gradually", "Grip hard and brake hard", "Accelerate", "Stand on the footrests"],
  "A tight grip makes the wobble worse. Hold loosely, ease off gently and avoid sudden braking."],
 [null, "Du må plutselig unngå en hindring. Hvordan gjør du det?", ["Bremser først, slipper bremsen og styrer unna med motstyring", "Bremser og svinger kraftig samtidig", "Lener deg bakover", "Lukker øynene og holder kursen"],
  "Bremsing og kraftig svinging samtidig kan gi fall. Del det opp: brems, slipp, og styr unna.",
  "You suddenly have to avoid an obstacle. How do you do it?", ["Brake first, release, then swerve with countersteering", "Brake and swerve hard at the same time", "Lean back", "Close your eyes and hold course"],
  "Braking and hard swerving together can cause a fall. Split it up: brake, release, then swerve."],
 [null, "Hvordan kjører du best på grus?", ["Med jevn gass, mykt grep og uten brå bevegelser", "Med hard bremsing i svinger", "Med mye krengning", "Med full gass"],
  "Grus gir lite grep. Brå bremsing, gass og styring kan få hjulene til å skli.",
  "How do you ride best on gravel?", ["With steady throttle, a relaxed grip and no sudden moves", "Braking hard in bends", "Leaning a lot", "Full throttle"],
  "Gravel gives little grip. Sudden braking, throttle or steering can make the wheels slide."],
 [null, "Hvordan gjør du en U-sving i lav fart?", ["Bruker slirepunktet og bakbremsen, og ser dit du skal", "Ser ned på forhjulet", "Bruker bare forbremsen", "Holder clutchen helt inne og ruller"],
  "I lav fart styrer du farten med clutch og bakbrems. Hodet og blikket skal vende dit du vil.",
  "How do you make a U-turn at low speed?", ["Use the biting point and rear brake, and look where you are going", "Look down at the front wheel", "Use only the front brake", "Hold the clutch in and coast"],
  "At low speed you control speed with clutch and rear brake. Turn your head and look where you want to go."],
 [null, "Hvorfor skal du holde lett grep om styret?", ["Så sykkelen kan styre seg selv og du kan bruke motstyring presist", "For å spare krefter i armene", "Det er påbudt", "Så du kan vinke til andre"],
  "Stive armer overfører bevegelser til styret og gjør sykkelen ustabil. Et lett grep gir bedre kontroll.",
  "Why should you hold the handlebars lightly?", ["So the bike can steady itself and you can countersteer precisely", "To save arm strength", "It is mandatory", "So you can wave to others"],
  "Stiff arms transfer movements to the bars and make the bike unstable. A light grip gives better control."],
]);
// ---------- MC 2: Bremsing og stopplengde ----------
DQ("FKMC", 2, [
 [null, "Hvorfor kan bakhjulet lettere låse seg ved hard bremsing?", ["Vekten flyttes fram, så bakhjulet får mindre trykk mot vegen", "Bakhjulet er mindre", "Bakbremsen er alltid sterkere", "Det skjer bare med ABS"],
  "Ved hard bremsing presses fronten ned, og bakhjulet blir lett. Da skal det lite til før det låser.",
  "Why can the rear wheel lock more easily under hard braking?", ["Weight shifts forward, so the rear wheel has less grip", "The rear wheel is smaller", "The rear brake is always stronger", "It only happens with ABS"],
  "Under hard braking the front dives and the rear gets light. It then takes little to lock it."],
 [null, "Hvordan bremser du hardt med forbremsen?", ["Bygger opp trykket raskt men gradvis", "Klemmer til alt du kan med én gang", "Pumper raskt", "Bruker bare to fingre lett"],
  "Gi forhjulet tid til å få vekt før full kraft. Trykket bygges raskt, men ikke i et rykk.",
  "How do you brake hard with the front brake?", ["Build up pressure quickly but progressively", "Grab as hard as you can at once", "Pump quickly", "Use two fingers lightly"],
  "Give the front wheel time to load up before full force. Build pressure fast but not in one jerk."],
 [null, "Hvordan påvirker våt veg bremsingen på motorsykkel?", ["Bremselengden blir lengre, og du må bremse mykere", "Den blir kortere", "Den endres ikke", "Du bør bare bruke bakbremsen"],
  "Våt veg gir mindre grep. Brems tidligere og mykere, og hold større avstand.",
  "How does a wet road affect braking on a motorcycle?", ["Braking distance gets longer, and you must brake more gently", "It gets shorter", "It does not change", "You should only use the rear brake"],
  "A wet road gives less grip. Brake earlier and more gently, and keep a bigger gap."],
 [null, "Du bremser med motoren ved å slippe gassen. Hva må du huske?", ["Bremselyset tennes ikke, så bilene bak får ikke varsel", "Det er forbudt", "Det sliter ut bremsene", "Det gir alltid kortest bremselengde"],
  "Motorbrems gir ikke bremselys. Bruk gjerne bremsen litt, så de bak ser at du senker farten.",
  "You slow down with engine braking by closing the throttle. What should you remember?", ["The brake light does not come on, so traffic behind gets no warning", "It is forbidden", "It wears out the brakes", "It always gives the shortest stop"],
  "Engine braking does not light the brake light. Touch the brake so those behind see you are slowing."],
 [null, "Hvor stor del av bremsekraften kommer omtrent fra forbremsen ved hard bremsing på tørr veg?", ["Rundt 70 prosent", "Rundt 10 prosent", "Rundt 30 prosent", "100 prosent"],
  "Vekten flyttes fram, og forbremsen gir mesteparten av bremsekraften. Bruk likevel begge.",
  "Roughly how much of the braking force comes from the front brake in hard braking on a dry road?", ["Around 70 per cent", "Around 10 per cent", "Around 30 per cent", "100 per cent"],
  "Weight shifts forward and the front brake gives most of the stopping power. Still use both."],
]);
// ---------- MC 3: Kurver og plassering ----------
DQ("FKMC", 3, [
 [null, "Hvor plasserer du deg før en høyresving?", ["Mot venstre del av feltet, med god avstand til midtlinjen", "Helt inntil høyre vegkant", "Over midtlinjen", "Midt i feltet uansett"],
  "Ved å starte ute ser du lenger inn i svingen. Hold likevel god avstand til møtende.",
  "Where do you position yourself before a right-hand bend?", ["Towards the left part of the lane, well clear of the centre line", "Tight to the right edge", "Over the centre line", "In the middle of the lane regardless"],
  "Starting wide lets you see further into the bend. Still keep well clear of oncoming traffic."],
 [null, "Du ser ikke hvor svingen ender. Hvilken fart velger du?", ["En fart som gjør at du kan stanse på den strekningen du ser", "Den samme som før svingen", "Høy fart for å komme fort gjennom", "Fartsgrensen uansett sikt"],
  "Svingen kan stramme seg til eller skjule en hindring. Farten må passe sikten.",
  "You cannot see where the bend ends. What speed do you choose?", ["A speed that lets you stop within the distance you can see", "The same as before the bend", "High speed to get through quickly", "The limit regardless of view"],
  "The bend may tighten or hide an obstacle. Your speed must match your view."],
 [null, "Når bør du gjøre unna bremsingen ved en sving?", ["Før svingen, mens sykkelen står rett", "Midt i svingen", "Når du er ute av svingen", "Det spiller ingen rolle"],
  "Mens sykkelen står rett, tåler dekkene mest bremsing. I svingen trengs grepet til å svinge.",
  "When should you finish braking for a bend?", ["Before the bend, while the bike is upright", "In the middle of the bend", "After the bend", "It does not matter"],
  "While upright, the tyres can take the most braking. In the bend the grip is needed for turning."],
 [null, "Det ligger grus i svingen. Hva gjør du?", ["Reduserer krengningen, holder jevn gass og unngår brå bremsing", "Krenger mer", "Bremser hardt i gruset", "Gir full gass"],
  "Mindre krengning og jevn kjøring gir dekkene best mulig grep i gruset.",
  "There is gravel in the bend. What do you do?", ["Reduce lean, keep steady throttle and avoid sudden braking", "Lean more", "Brake hard in the gravel", "Full throttle"],
  "Less lean and smooth riding give the tyres the best possible grip on gravel."],
 [null, "Hvorfor bør du se langt gjennom svingen?", ["Sykkelen følger blikket, og du oppdager farer tidligere", "For å se på utsikten", "Det er påbudt", "Det har ingen betydning"],
  "Du styrer dit du ser. Ser du langt fram, får du en jevnere linje og mer tid til å reagere.",
  "Why should you look far through the bend?", ["The bike follows your eyes, and you spot hazards earlier", "To enjoy the view", "It is mandatory", "It makes no difference"],
  "You steer where you look. Looking far ahead gives a smoother line and more time to react."],
]);
// ---------- MC 4: Synlighet og samspill ----------
DQ("FKMC", 4, [
 [null, "Hvorfor bedømmer bilister ofte farten til en motorsykkel feil?", ["Den smale fronten gjør det vanskelig å bedømme avstand og fart", "Motorsykler kjører alltid sakte", "Bilister ser motorsykler best av alle", "Fordi motorsykler har sterkere lys"],
  "En smal motorsykkel ser ut til å være lenger unna og komme saktere enn den gjør.",
  "Why do drivers often misjudge a motorcycle's speed?", ["The narrow front makes distance and speed hard to judge", "Motorcycles always ride slowly", "Drivers see motorcycles best of all", "Because motorcycles have brighter lights"],
  "A narrow motorcycle seems further away and slower than it really is."],
 [null, "En bil fra en sideveg har stanset og ser i din retning. Kan du stole på at føreren har sett deg?", ["Nei, vær klar til å bremse", "Ja, når bilen har stanset", "Ja, hvis du har lyset på", "Ja, hvis du tuter"],
  "Mange ulykker skjer fordi bilføreren ser rett på motorsykkelen uten å oppfatte den.",
  "A car from a side road has stopped and is looking your way. Can you trust that the driver has seen you?", ["No, be ready to brake", "Yes, once it has stopped", "Yes, if your lights are on", "Yes, if you sound the horn"],
  "Many accidents happen because a driver looks straight at the motorcycle without registering it."],
 [null, "Hvorfor bør du bruke refleks eller refleksdetaljer på kjøreklærne?", ["Så du blir sett i mørket, også når du står stille", "Fordi det er pent", "Det har ingen virkning", "Bare for å bestå teoriprøven"],
  "Refleks fanger opp lyset fra andre kjøretøy og gjør deg synlig, for eksempel om du må stanse langs vegen.",
  "Why should you use reflective details on your riding gear?", ["So you are seen in the dark, also when stopped", "Because it looks nice", "It has no effect", "Only to pass the theory test"],
  "Reflective material catches other vehicles' lights and makes you visible, for example if you stop by the road."],
 [null, "Hvorfor endrer du plassering i feltet underveis?", ["For å se mest mulig og bli sett, og holde avstand til farer", "For å vise deg fram", "For å hindre forbikjøring", "Det skal du aldri gjøre"],
  "Plasseringen tilpasses sikt, vegdekke og trafikk, så du både ser og blir sett.",
  "Why do you change position in the lane as you ride?", ["To see and be seen as well as possible, and keep away from hazards", "To show off", "To prevent overtaking", "You should never do that"],
  "Position is adjusted to view, surface and traffic so you both see and are seen."],
 [null, "Du kjører bak en stor bil og ser ikke speilene dens. Hva betyr det?", ["Føreren ser deg sannsynligvis ikke", "Føreren ser deg godt", "Du er på trygg avstand", "Det betyr ingenting"],
  "Ser du ikke speilene, ser ikke føreren deg. Hold større avstand eller endre plassering.",
  "You are behind a large vehicle and cannot see its mirrors. What does that mean?", ["The driver probably cannot see you", "The driver sees you well", "You are at a safe distance", "Nothing"],
  "If you cannot see the mirrors, the driver cannot see you. Drop back or change position."],
]);
// ---------- MC 5: Veggrep, føre og vær ----------
DQ("FKMC", 5, [
 [null, "Hvor finner du ofte dieselsøl på vegen?", ["Ved bensinstasjoner, rundkjøringer og busstopp", "Midt på rette strekninger", "Bare på grusveger", "Bare i tunneler"],
  "Diesel gjør asfalten svært glatt. Søl er vanlig der tunge kjøretøy fyller og svinger.",
  "Where do you often find diesel spills on the road?", ["At petrol stations, roundabouts and bus stops", "In the middle of straight roads", "Only on gravel roads", "Only in tunnels"],
  "Diesel makes tarmac very slippery. Spills are common where heavy vehicles refuel and turn."],
 [null, "Hvorfor skal du kjøre forsiktig på nye dekk?", ["De er glatte til overflaten er kjørt inn", "De har dårligere bremser", "De er alltid for hardt pumpet", "Det trenger du ikke"],
  "Nye dekk har et glatt lag fra produksjonen. Kjør forsiktig de første milene.",
  "Why should you ride carefully on new tyres?", ["They are slippery until the surface is worn in", "They have worse brakes", "They are always over-inflated", "You need not"],
  "New tyres have a slippery layer from manufacturing. Ride carefully for the first miles."],
 [null, "Hva kan være glatt om høsten?", ["Vått løv på vegen", "Tørr asfalt", "Ny vegoppmerking i sol", "Ingenting"],
  "Vått løv er svært glatt, særlig i svinger og under trær.",
  "What can be slippery in autumn?", ["Wet leaves on the road", "Dry tarmac", "New markings in sunshine", "Nothing"],
  "Wet leaves are very slippery, especially in bends and under trees."],
 [null, "Hvordan kan dype hjulspor i asfalten påvirke motorsykkelen?", ["De kan dra i forhjulet og gjøre styringen ustabil", "De gir bedre grep", "De har ingen virkning", "De gjør bremselengden kortere"],
  "Spor kan styre sykkelen og samle vann. Velg plassering som unngår kantene av sporene.",
  "How can deep ruts in the tarmac affect the motorcycle?", ["They can tug the front wheel and make steering unstable", "They give better grip", "They have no effect", "They shorten braking distance"],
  "Ruts can steer the bike and collect water. Position yourself to avoid the edges of the ruts."],
 [null, "Det regner. Hvor i feltet bør du helst ikke kjøre?", ["På oppmerkingen og midt i feltet der det kan ligge olje", "I hjulsporene til bilene", "Det spiller ingen rolle", "Helt ute på skulderen med grus"],
  "Oppmerking og olje midt i feltet er glatt i regn. Hjulsporene er ofte tørrest og renest.",
  "It is raining. Where in the lane should you avoid riding?", ["On the markings and in the middle where oil collects", "In the cars' wheel tracks", "It does not matter", "Out on the gravel shoulder"],
  "Markings and oil in the middle of the lane are slippery in rain. The wheel tracks are usually driest and cleanest."],
]);
// ---------- MC 6: Vedlikehold og kontroll ----------
DQ("FKMC", 6, [
 [null, "Hvor stor mønsterdybde skal dekkene på en motorsykkel minst ha?", ["1 mm", "1,6 mm", "3 mm", "0,5 mm"],
  "Kravet for motorsykkel er 1 mm, men grepet blir dårligere lenge før det, særlig i regn.",
  "What is the minimum tread depth for motorcycle tyres?", ["1 mm", "1.6 mm", "3 mm", "0.5 mm"],
  "The requirement for motorcycles is 1 mm, but grip deteriorates well before that, especially in rain."],
 [null, "Hvordan sjekker du bremsene før du kjører?", ["Klemmer og trår inn og kjenner at de tar fast, og triller litt og bremser", "Ser på dem", "Det trengs ikke", "Kjører fort og bråbremser i trafikken"],
  "En rask sjekk før start avslører luft i systemet, slitte klosser eller lekkasje.",
  "How do you check the brakes before riding?", ["Squeeze and press to feel them bite, then roll a little and brake", "Look at them", "No need", "Ride fast and brake hard in traffic"],
  "A quick check before riding reveals air in the system, worn pads or leaks."],
 [null, "Hvorfor må bremsevæsken skiftes jevnlig?", ["Den tar opp fuktighet og blir dårligere med tiden", "Den blir tykkere og bremser hardere", "Den fordamper aldri", "Det trengs ikke"],
  "Gammel bremsevæske inneholder vann, kan koke ved hard bruk og gir svampete bremser.",
  "Why must brake fluid be changed regularly?", ["It absorbs moisture and deteriorates over time", "It thickens and brakes harder", "It never evaporates", "It is not needed"],
  "Old brake fluid contains water, can boil under hard use and gives spongy brakes."],
 [null, "Styret rister eller sykkelen trekker til siden. Hva gjør du?", ["Får det sjekket før du kjører videre", "Kjører fortere så det forsvinner", "Ignorerer det", "Holder hardere i styret"],
  "Det kan være feil på dekk, hjullager, styrelager eller fjæring. Få det undersøkt.",
  "The handlebars shake or the bike pulls to one side. What do you do?", ["Get it checked before riding on", "Ride faster so it goes away", "Ignore it", "Grip harder"],
  "It may be a fault in tyres, wheel bearings, steering head or suspension. Have it inspected."],
 [null, "Hvorfor bør lys og blinklys sjekkes før hver tur?", ["Fordi andre må se deg og forstå hva du skal gjøre", "Fordi det er pent", "Bare om natten", "Det trenger du ikke"],
  "Defekte lys gjør deg mindre synlig og andre usikre på hva du skal.",
  "Why should lights and indicators be checked before every ride?", ["Because others must see you and understand what you will do", "Because it looks nice", "Only at night", "You need not"],
  "Faulty lights make you less visible and others unsure of your intentions."],
]);
// ---------- MC 7: Passasjer og last ----------
DQ("FKMC", 7, [
 [null, "Hva bør du justere når du skal ha med passasjer eller tung last?", ["Dekktrykk og fjæring etter instruksjonsboka", "Ingenting", "Bare speilene", "Kjedet skal slakkes"],
  "Mer vekt krever ofte høyere dekktrykk og strammere fjæring. Lyset kan også måtte justeres.",
  "What should you adjust when carrying a passenger or heavy load?", ["Tyre pressure and suspension as per the handbook", "Nothing", "Only the mirrors", "Loosen the chain"],
  "More weight often needs higher tyre pressure and firmer suspension. The headlight may also need adjusting."],
 [null, "Hvordan påvirker tung last motorsykkelen?", ["Den blir tregere å styre og får lengre bremselengde", "Den svinger raskere", "Den bremser bedre", "Den blir mer stabil i alle situasjoner"],
  "Ekstra vekt endrer balansen og gir lengre bremselengde. Kjør mykere og hold større avstand.",
  "How does a heavy load affect the motorcycle?", ["It steers more slowly and has longer braking distance", "It turns faster", "It brakes better", "It is more stable in all situations"],
  "Extra weight changes the balance and lengthens braking. Ride more smoothly and keep a bigger gap."],
 [null, "Hva bør du fortelle en passasjer som aldri har sittet på før?", ["Sitt rolig, len deg med sykkelen og hold føttene på fotstøttene også når vi stanser", "Len deg motsatt vei i svingene", "Sett føttene i bakken når vi stanser", "Stå opp i svingene"],
  "En urolig passasjer kan bringe sykkelen ut av balanse. Avtal gjerne tegn på forhånd.",
  "What should you tell a passenger who has never ridden pillion?", ["Sit still, lean with the bike and keep your feet on the footrests even when we stop", "Lean the opposite way in bends", "Put your feet down when we stop", "Stand up in bends"],
  "A restless passenger can unbalance the bike. Agree on signals beforehand."],
 [null, "Hvor bør du plassere en tankveske?", ["Så den ikke hindrer styringen, synet eller bryterne", "Over speedometeret", "På styret", "Hvor som helst"],
  "Bagasjen må ikke hindre deg i å styre, se instrumentene eller bruke bryterne.",
  "Where should you place a tank bag?", ["So it does not hinder steering, view or switches", "Over the speedometer", "On the handlebars", "Anywhere"],
  "Luggage must not stop you from steering, seeing the instruments or using the switches."],
 [null, "Hvordan påvirker en passasjer akselerasjonen?", ["Sykkelen akselererer saktere, og fronten kan løfte seg lettere", "Den akselererer raskere", "Ingen forskjell", "Bakhjulet låser seg"],
  "Mer vekt bak gjør sykkelen tregere og letter fronten. Gi gass jevnt.",
  "How does a passenger affect acceleration?", ["The bike accelerates more slowly, and the front can lift more easily", "It accelerates faster", "No difference", "The rear wheel locks"],
  "More weight at the rear makes the bike slower and lightens the front. Accelerate smoothly."],
]);
})();
