// ============================================================
//  add_vgs_h.js – Kjemi 1 og Kjemi 2: flere oppgaver og regnegeneratorer (molmasse, konsentrasjon, pH, likevekt, buffer, elektrokjemi)
// ============================================================
(() => {
const AM = { H: 1.008, C: 12.01, N: 14.01, O: 16.00, Na: 22.99, Mg: 24.31, Al: 26.98, S: 32.07, Cl: 35.45, K: 39.10, Ca: 40.08, Fe: 55.85, Cu: 63.55 };
// [formel (visning), sammensetning, navn nb, navn en]
const SUBST = [["H_2O", { H: 2, O: 1 }, "vann", "water"], ["CO_2", { C: 1, O: 2 }, "karbondioksid", "carbon dioxide"], ["NaCl", { Na: 1, Cl: 1 }, "natriumklorid", "sodium chloride"],
  ["NaOH", { Na: 1, O: 1, H: 1 }, "natriumhydroksid", "sodium hydroxide"], ["HCl", { H: 1, Cl: 1 }, "hydrogenklorid", "hydrogen chloride"], ["H_2SO_4", { H: 2, S: 1, O: 4 }, "svovelsyre", "sulfuric acid"],
  ["CaCO_3", { Ca: 1, C: 1, O: 3 }, "kalsiumkarbonat", "calcium carbonate"], ["C_6H_{12}O_6", { C: 6, H: 12, O: 6 }, "glukose", "glucose"], ["NH_3", { N: 1, H: 3 }, "ammoniakk", "ammonia"],
  ["CH_4", { C: 1, H: 4 }, "metan", "methane"], ["C_2H_5OH", { C: 2, H: 6, O: 1 }, "etanol", "ethanol"], ["KCl", { K: 1, Cl: 1 }, "kaliumklorid", "potassium chloride"],
  ["MgO", { Mg: 1, O: 1 }, "magnesiumoksid", "magnesium oxide"], ["CuSO_4", { Cu: 1, S: 1, O: 4 }, "kobbersulfat", "copper sulfate"], ["Fe_2O_3", { Fe: 2, O: 3 }, "jern(III)oksid", "iron(III) oxide"]];
const molar = comp => Object.entries(comp).reduce((s, [e, n]) => s + AM[e] * n, 0);
const compTxt = comp => Object.entries(comp).map(([e, n]) => `${n > 1 ? n + " \\cdot " : ""}${mf(AM[e])}`).join(" + ");

// ================= KJEMI 1 =================
BIQ("VGKJ1", 0, [
 ["Hvor mange protoner har et karbonatom?", { n: 6, tol: 0, u: "" }, "Atomnummeret til karbon er 6, og det er antall protoner.", "How many protons does a carbon atom have?", null, "Carbon's atomic number is 6, which is the number of protons."],
 ["Hvor mange valenselektroner har grunnstoffene i gruppe 17 (halogenene)?", { n: 7, tol: 0, u: "" }, "Gruppe 17 har 7 elektroner i ytterste skall og vil gjerne ta opp ett til.", "How many valence electrons do the elements in group 17 (the halogens) have?", null, "Group 17 has 7 electrons in the outer shell and readily takes up one more."],
 ["Hva er isotoper?", ["Atomer av samme grunnstoff med ulikt antall nøytroner", "Atomer med ulikt antall protoner", "Ioner med ulik ladning", "Molekyler med samme formel"], "C-12 og C-14 er begge karbon (6 protoner), men har 6 og 8 nøytroner.", "What are isotopes?", ["Atoms of the same element with different numbers of neutrons", "Atoms with different numbers of protons", "Ions with different charges", "Molecules with the same formula"], "C-12 and C-14 are both carbon (6 protons), but have 6 and 8 neutrons."],
 ["Hvilket grunnstoff er mest elektronegativt?", ["Fluor", "Natrium", "Karbon", "Jern"], "Elektronegativiteten øker mot høyre og oppover i periodesystemet. Fluor er øverst til høyre.", "Which element is the most electronegative?", ["Fluorine", "Sodium", "Carbon", "Iron"], "Electronegativity increases to the right and upwards in the periodic table. Fluorine is at the top right."],
 ["Hvilken ladning får et magnesiumion?", ["$2+$", "$2-$", "$1+$", "$3+$"], "Mg er i gruppe 2 og gir fra seg 2 elektroner: $\\text{Mg}^{2+}$.", "What charge does a magnesium ion get?", ["$2+$", "$2-$", "$1+$", "$3+$"], "Mg is in group 2 and gives away 2 electrons: $\\text{Mg}^{2+}$."],
 ["Hvor mange nøytroner har $^{23}_{11}\\text{Na}$?", { n: 12, tol: 0, u: "" }, "$23 - 11 = 12$ nøytroner.", "How many neutrons does $^{23}_{11}\\text{Na}$ have?", null, "$23 - 11 = 12$ neutrons."]
]);
GEN("VGKJ1", 0,
 () => { const [el, Z, A] = R.p([["C", 6, 14], ["O", 8, 18], ["Cl", 17, 37], ["U", 92, 235], ["Fe", 26, 56], ["K", 19, 40], ["N", 7, 15], ["Ca", 20, 40]]);
   return [T(`Hvor mange nøytroner har $^{${A}}_{${Z}}\\text{${el}}$?`, `How many neutrons does $^{${A}}_{${Z}}\\text{${el}}$ have?`), { n: A - Z, tol: 0, u: "" },
     T(`Nukleontall minus protontall: $${A} - ${Z} = ${A - Z}$.`, `Nucleon number minus proton number: $${A} - ${Z} = ${A - Z}$.`)]; },
 () => { const [el, Z, q] = R.p([["Na", 11, 1], ["Mg", 12, 2], ["Al", 13, 3], ["O", 8, -2], ["Cl", 17, -1], ["S", 16, -2], ["K", 19, 1], ["Ca", 20, 2], ["F", 9, -1]]), e = Z - q;
   return [T(`Hvor mange elektroner har ionet $\\text{${el}}^{${Math.abs(q) > 1 ? Math.abs(q) : ""}${q > 0 ? "+" : "-"}}$ (atomnummer ${Z})?`, `How many electrons does the ion $\\text{${el}}^{${Math.abs(q) > 1 ? Math.abs(q) : ""}${q > 0 ? "+" : "-"}}$ (atomic number ${Z}) have?`), { n: e, tol: 0, u: "" },
     T(`${Z} protoner, ladning ${q > 0 ? "+" : "−"}${Math.abs(q)}: ${q > 0 ? "mistet" : "tatt opp"} ${Math.abs(q)} elektron${Math.abs(q) > 1 ? "er" : ""}, altså ${e} elektroner.`, `${Z} protons, charge ${q > 0 ? "+" : "−"}${Math.abs(q)}: ${q > 0 ? "lost" : "gained"} ${Math.abs(q)} electron${Math.abs(q) > 1 ? "s" : ""}, i.e. ${e} electrons.`)]; }
);
BIQ("VGKJ1", 1, [
 ["Hvilken binding har vi i $\\text{H}_2\\text{O}$?", ["Polar kovalent binding", "Ionebinding", "Metallbinding", "Upolar kovalent binding"], "O er mye mer elektronegativt enn H, så elektronene trekkes mot O.", "Which bond is found in $\\text{H}_2\\text{O}$?", ["Polar covalent bond", "Ionic bond", "Metallic bond", "Non-polar covalent bond"], "O is much more electronegative than H, so the electrons are pulled towards O."],
 ["Hvorfor har vann så høyt kokepunkt for et så lite molekyl?", ["Hydrogenbindinger mellom molekylene", "Ionebindinger", "Det er tungt", "Det er upolart"], "Hydrogenbindinger er sterke krefter mellom molekyler og må brytes for å koke vannet.", "Why does water have such a high boiling point for such a small molecule?", ["Hydrogen bonds between the molecules", "Ionic bonds", "It is heavy", "It is non-polar"], "Hydrogen bonds are strong forces between molecules and must be broken to boil water."],
 ["Hvilken form har et metanmolekyl ($\\text{CH}_4$)?", ["Tetraeder", "Lineær", "Plan trekant", "Vinklet"], "Fire elektronpar rundt C skyver hverandre ut i et tetraeder med 109,5° vinkler.", "What shape does a methane molecule ($\\text{CH}_4$) have?", ["Tetrahedral", "Linear", "Trigonal planar", "Bent"], "Four electron pairs around C push each other into a tetrahedron with 109.5° angles."],
 ["«Likt løser likt» betyr at …", ["polare stoffer løses i polare løsemidler", "alle stoffer løses i vann", "salter løses i olje", "gasser løses best i varmt vann"], "Sukker løses i vann (begge polare), fett løses i bensin (begge upolare).", "\"Like dissolves like\" means that …", ["polar substances dissolve in polar solvents", "all substances dissolve in water", "salts dissolve in oil", "gases dissolve best in hot water"], "Sugar dissolves in water (both polar), fat dissolves in petrol (both non-polar)."],
 ["Hva slags binding holder NaCl-krystallen sammen?", ["Ionebinding", "Kovalent binding", "Hydrogenbinding", "Van der Waals-krefter"], "$\\text{Na}^+$ og $\\text{Cl}^-$ tiltrekker hverandre elektrostatisk.", "What kind of bond holds the NaCl crystal together?", ["Ionic bond", "Covalent bond", "Hydrogen bond", "Van der Waals forces"], "$\\text{Na}^+$ and $\\text{Cl}^-$ attract each other electrostatically."],
 ["Hvor mange bindingselektroner er det i en dobbeltbinding?", { n: 4, tol: 0, u: "" }, "To elektronpar, altså 4 elektroner.", "How many bonding electrons are in a double bond?", null, "Two electron pairs, i.e. 4 electrons."]
]);
BIQ("VGKJ1", 2, [
 ["Hva er molar masse for vann ($\\text{H}_2\\text{O}$)?", { n: 18.02, tol: 0.02, u: "g/mol" }, "$2 \\cdot 1{,}008 + 16{,}00 = 18{,}02$ g/mol.", "What is the molar mass of water ($\\text{H}_2\\text{O}$)?", null, "$2 \\cdot 1.008 + 16.00 = 18.02$ g/mol."],
 ["Du løser 0,5 mol NaCl i 250 mL vann. Hva er konsentrasjonen?", { n: 2, tol: 0, u: "mol/L" }, "$c = n/V = 0{,}5/0{,}250 = 2$ mol/L.", "You dissolve 0.5 mol NaCl in 250 mL of water. What is the concentration?", null, "$c = n/V = 0.5/0.250 = 2$ mol/L."],
 ["Du fortynner 100 mL 1,0 M løsning til 500 mL. Hva er ny konsentrasjon?", { n: 0.2, tol: 0.001, u: "mol/L" }, "$c_1V_1 = c_2V_2$: $c_2 = 1{,}0 \\cdot 100/500 = 0{,}2$ mol/L.", "You dilute 100 mL of a 1.0 M solution to 500 mL. What is the new concentration?", null, "$c_1V_1 = c_2V_2$: $c_2 = 1.0 \\cdot 100/500 = 0.2$ mol/L."],
 ["Hvor mange molekyler er det i 1 mol?", ["$6{,}02 \\cdot 10^{23}$", "$1{,}6 \\cdot 10^{-19}$", "$22{,}4$", "$1000$"], "Avogadros tall.", "How many molecules are in 1 mol?", ["$6.02 \\cdot 10^{23}$", "$1.6 \\cdot 10^{-19}$", "$22.4$", "$1000$"], "Avogadro's number."],
 ["$2\\text{H}_2 + \\text{O}_2 \\to 2\\text{H}_2\\text{O}$. Hvor mange mol vann gir 3 mol $\\text{H}_2$?", { n: 3, tol: 0, u: "mol" }, "Forholdet $\\text{H}_2 : \\text{H}_2\\text{O} = 2 : 2 = 1 : 1$, så 3 mol.", "$2\\text{H}_2 + \\text{O}_2 \\to 2\\text{H}_2\\text{O}$. How many moles of water do 3 mol of $\\text{H}_2$ give?", null, "The ratio $\\text{H}_2 : \\text{H}_2\\text{O} = 2 : 2 = 1 : 1$, so 3 mol."]
]);
GEN("VGKJ1", 2,
 () => { const [f, comp, nb, en] = R.p(SUBST), M = molar(comp);
   return [T(`Hva er molar masse for ${nb} ($\\mathrm{${f}}$)?`, `What is the molar mass of ${en} ($\\mathrm{${f}}$)?`), { n: M, tol: 0.05, u: "g/mol" },
     T(`$M = ${compTxt(comp)} = ${mf(M, 2)}$ g/mol.`, `$M = ${compTxt(comp)} = ${mf(M, 2)}$ g/mol.`)]; },
 () => { const [f, comp, nb, en] = R.p(SUBST), M = molar(comp), m = R.p([1, 2.5, 5, 10, 18, 25, 50, 100]), n = m / M;
   return [T(`Hvor mange mol er ${nf(m)} g ${nb} ($\\mathrm{${f}}$, $M = ${mf(M, 2)}$ g/mol)?`, `How many moles are ${nf(m)} g of ${en} ($\\mathrm{${f}}$, $M = ${mf(M, 2)}$ g/mol)?`), { n, tol: rel(n, 0.01), u: "mol" },
     T(`$n = \\dfrac{m}{M} = \\dfrac{${mf(m)}}{${mf(M, 2)}} = ${mf(n, 4)}$ mol.`, `$n = \\dfrac{m}{M} = \\dfrac{${mf(m)}}{${mf(M, 2)}} = ${mf(n, 4)}$ mol.`)]; },
 () => { const [f, comp, nb, en] = R.p(SUBST.filter(s => ["NaCl", "NaOH", "KCl", "CuSO_4", "C_6H_{12}O_6"].includes(s[0]))), M = molar(comp), c = R.p([0.1, 0.2, 0.5, 1]), V = R.p([100, 250, 500, 1000]), m = c * V / 1000 * M;
   return [T(`Hvor mange gram ${nb} ($M = ${mf(M, 2)}$ g/mol) må du løse for å lage ${V} mL av en ${nf(c)} M løsning?`, `How many grams of ${en} ($M = ${mf(M, 2)}$ g/mol) must you dissolve to make ${V} mL of a ${nf(c)} M solution?`), { n: m, tol: rel(m, 0.01), u: "g" },
     T(`$n = cV = ${mf(c)} \\cdot ${mf(V / 1000, 3)} = ${mf(c * V / 1000, 4)}$ mol. $m = nM = ${mf(m, 3)}$ g.`, `$n = cV = ${mf(c)} \\cdot ${mf(V / 1000, 3)} = ${mf(c * V / 1000, 4)}$ mol. $m = nM = ${mf(m, 3)}$ g.`)]; },
 () => { const c1 = R.p([0.5, 1, 2, 6]), V1 = R.p([10, 20, 50, 100]), V2 = V1 * R.p([2, 4, 5, 10]), c2 = c1 * V1 / V2;
   return [T(`${V1} mL av en ${nf(c1)} M løsning fortynnes til ${V2} mL. Hva er ny konsentrasjon?`, `${V1} mL of a ${nf(c1)} M solution is diluted to ${V2} mL. What is the new concentration?`), { n: c2, tol: rel(c2, 0.005), u: "mol/L" },
     T(`$c_2 = \\dfrac{c_1V_1}{V_2} = \\dfrac{${mf(c1)} \\cdot ${V1}}{${V2}} = ${mf(c2, 4)}$ mol/L.`, `$c_2 = \\dfrac{c_1V_1}{V_2} = \\dfrac{${mf(c1)} \\cdot ${V1}}{${V2}} = ${mf(c2, 4)}$ mol/L.`)]; }
);
BIQ("VGKJ1", 3, [
 ["Hva er pH i en løsning med $[\\text{H}_3\\text{O}^+] = 10^{-3}$ mol/L?", { n: 3, tol: 0, u: "" }, "$\\text{pH} = -\\lg 10^{-3} = 3$.", "What is the pH of a solution with $[\\text{H}_3\\text{O}^+] = 10^{-3}$ mol/L?", null, "$\\text{pH} = -\\lg 10^{-3} = 3$."],
 ["pH går fra 4 til 2. Hvor mange ganger større er $[\\text{H}_3\\text{O}^+]$?", { n: 100, tol: 0, u: "" }, "Hver pH-enhet er en faktor 10: $10^2 = 100$.", "The pH goes from 4 to 2. How many times larger is $[\\text{H}_3\\text{O}^+]$?", null, "Each pH unit is a factor of 10: $10^2 = 100$."],
 ["Hva er en Brønsted-syre?", ["En protongiver", "En protonmottaker", "En elektrongiver", "Et salt"], "En syre gir fra seg $\\text{H}^+$, en base tar det opp.", "What is a Bronsted acid?", ["A proton donor", "A proton acceptor", "An electron donor", "A salt"], "An acid donates $\\text{H}^+$, a base accepts it."],
 ["Hva er pOH når pH er 9 (ved 25 °C)?", { n: 5, tol: 0, u: "" }, "$\\text{pH} + \\text{pOH} = 14$, så $\\text{pOH} = 5$.", "What is the pOH when the pH is 9 (at 25 °C)?", null, "$\\text{pH} + \\text{pOH} = 14$, so $\\text{pOH} = 5$."],
 ["Hva dannes når en syre nøytraliseres av en base?", ["Salt og vann", "Hydrogengass", "Oksygen", "Bare vann"], "$\\text{HCl} + \\text{NaOH} \\to \\text{NaCl} + \\text{H}_2\\text{O}$.", "What forms when an acid is neutralised by a base?", ["Salt and water", "Hydrogen gas", "Oxygen", "Only water"], "$\\text{HCl} + \\text{NaOH} \\to \\text{NaCl} + \\text{H}_2\\text{O}$."],
 ["Hva er den korresponderende basen til $\\text{NH}_4^+$?", ["$\\text{NH}_3$", "$\\text{NH}_2^-$", "$\\text{H}_3\\text{O}^+$", "$\\text{OH}^-$"], "Syre minus ett proton gir den korresponderende basen.", "What is the conjugate base of $\\text{NH}_4^+$?", ["$\\text{NH}_3$", "$\\text{NH}_2^-$", "$\\text{H}_3\\text{O}^+$", "$\\text{OH}^-$"], "Acid minus one proton gives the conjugate base."]
]);
GEN("VGKJ1", 3,
 () => { const c = R.p([0.1, 0.05, 0.01, 0.02, 0.001, 0.005]), pH = -Math.log10(c);
   return [T(`Hva er pH i ${nf(c, 3)} M saltsyre (HCl, sterk syre)?`, `What is the pH of ${nf(c, 3)} M hydrochloric acid (HCl, a strong acid)?`), { n: pH, tol: 0.01, u: "" },
     T(`Sterk syre protolyserer fullstendig: $[\\text{H}_3\\text{O}^+] = ${mf(c, 3)}$, $\\text{pH} = -\\lg ${mf(c, 3)} = ${mf(pH, 2)}$.`, `A strong acid dissociates completely: $[\\text{H}_3\\text{O}^+] = ${mf(c, 3)}$, $\\text{pH} = -\\lg ${mf(c, 3)} = ${mf(pH, 2)}$.`)]; },
 () => { const c = R.p([0.1, 0.05, 0.01, 0.002]), pOH = -Math.log10(c), pH = 14 - pOH;
   return [T(`Hva er pH i ${nf(c, 3)} M NaOH (sterk base) ved 25 °C?`, `What is the pH of ${nf(c, 3)} M NaOH (a strong base) at 25 °C?`), { n: pH, tol: 0.01, u: "" },
     T(`$[\\text{OH}^-] = ${mf(c, 3)}$, $\\text{pOH} = ${mf(pOH, 2)}$, $\\text{pH} = 14 - ${mf(pOH, 2)} = ${mf(pH, 2)}$.`, `$[\\text{OH}^-] = ${mf(c, 3)}$, $\\text{pOH} = ${mf(pOH, 2)}$, $\\text{pH} = 14 - ${mf(pOH, 2)} = ${mf(pH, 2)}$.`)]; },
 () => { const cA = R.p([0.1, 0.2, 0.5]), VA = R.p([10, 20, 25]), cB = R.p([0.1, 0.2, 0.25]), VB = cA * VA / cB;
   return [T(`Hvor mange mL ${nf(cB)} M NaOH trengs for å nøytralisere ${VA} mL ${nf(cA)} M HCl?`, `How many mL of ${nf(cB)} M NaOH are needed to neutralise ${VA} mL of ${nf(cA)} M HCl?`), { n: VB, tol: 0.05, u: "mL" },
     T(`$n(\\text{HCl}) = ${mf(cA)} \\cdot ${VA} = ${mf(cA * VA)}$ mmol. $V = \\dfrac{${mf(cA * VA)}}{${mf(cB)}} = ${mf(VB, 2)}$ mL.`, `$n(\\text{HCl}) = ${mf(cA)} \\cdot ${VA} = ${mf(cA * VA)}$ mmol. $V = \\dfrac{${mf(cA * VA)}}{${mf(cB)}} = ${mf(VB, 2)}$ mL.`)]; }
);
BIQ("VGKJ1", 4, [
 ["Hva er oksidasjonstallet til O i $\\text{H}_2\\text{O}$?", { n: -2, tol: 0, u: "" }, "Oksygen har nesten alltid $-2$ (unntak: peroksider).", "What is the oxidation number of O in $\\text{H}_2\\text{O}$?", null, "Oxygen almost always has $-2$ (exception: peroxides)."],
 ["Hva er oksidasjonstallet til S i $\\text{H}_2\\text{SO}_4$?", { n: 6, tol: 0, u: "" }, "$2(+1) + x + 4(-2) = 0$ gir $x = +6$.", "What is the oxidation number of S in $\\text{H}_2\\text{SO}_4$?", null, "$2(+1) + x + 4(-2) = 0$ gives $x = +6$."],
 ["I $\\text{Zn} + \\text{Cu}^{2+} \\to \\text{Zn}^{2+} + \\text{Cu}$, hva blir oksidert?", ["Zn", "$\\text{Cu}^{2+}$", "$\\text{Zn}^{2+}$", "Cu"], "Zn gir fra seg elektroner (oksidasjonstallet øker fra 0 til +2).", "In $\\text{Zn} + \\text{Cu}^{2+} \\to \\text{Zn}^{2+} + \\text{Cu}$, what is oxidised?", ["Zn", "$\\text{Cu}^{2+}$", "$\\text{Zn}^{2+}$", "Cu"], "Zn gives away electrons (the oxidation number increases from 0 to +2)."],
 ["Hva er et reduksjonsmiddel?", ["Et stoff som gir fra seg elektroner og selv blir oksidert", "Et stoff som tar opp elektroner", "Oksygen", "En syre"], "Reduksjonsmiddelet reduserer det andre stoffet ved å gi det elektroner.", "What is a reducing agent?", ["A substance that gives away electrons and is itself oxidised", "A substance that accepts electrons", "Oxygen", "An acid"], "The reducing agent reduces the other substance by giving it electrons."],
 ["Hvorfor ruster jern raskere ved kysten?", ["Salt i luften gjør fuktigheten mer ledende", "Det er kaldere", "Det er mindre oksygen", "Sola er sterkere"], "Salt gir ioner som gjør elektrokjemisk korrosjon raskere.", "Why does iron rust faster by the coast?", ["Salt in the air makes the moisture more conductive", "It is colder", "There is less oxygen", "The sun is stronger"], "Salt provides ions that speed up electrochemical corrosion."]
]);
GEN("VGKJ1", 4,
 () => { const [f, el, x, nbT] = R.p([["\\text{CO}_2", "C", 4, ""], ["\\text{NH}_3", "N", -3, ""], ["\\text{HNO}_3", "N", 5, ""], ["\\text{KMnO}_4", "Mn", 7, ""], ["\\text{Fe}_2\\text{O}_3", "Fe", 3, ""], ["\\text{SO}_2", "S", 4, ""], ["\\text{H}_2\\text{S}", "S", -2, ""], ["\\text{Cr}_2\\text{O}_7^{2-}", "Cr", 6, ""], ["\\text{CH}_4", "C", -4, ""], ["\\text{NO}_2", "N", 4, ""]]);
   return [T(`Hva er oksidasjonstallet til ${el} i $${f}$?`, `What is the oxidation number of ${el} in $${f}$?`), { n: x, tol: 0, u: "" },
     T(`H er $+1$, O er $-2$ (og K er $+1$). Summen må bli ladningen til forbindelsen, som gir ${el}: $${x > 0 ? "+" : ""}${x}$.`, `H is $+1$, O is $-2$ (and K is $+1$). The sum must equal the charge of the species, which gives ${el}: $${x > 0 ? "+" : ""}${x}$.`)]; }
);

// ================= KJEMI 2 =================
BIQ("VGKJ2", 0, [
 ["Hva skjer med likevekten $\\text{N}_2 + 3\\text{H}_2 \\rightleftharpoons 2\\text{NH}_3$ når trykket økes?", ["Den forskyves mot høyre", "Den forskyves mot venstre", "Ingenting", "Reaksjonen stopper"], "Le Chateliers prinsipp: økt trykk gir forskyvning mot færre gassmolekyler (4 → 2).", "What happens to the equilibrium $\\text{N}_2 + 3\\text{H}_2 \\rightleftharpoons 2\\text{NH}_3$ when the pressure increases?", ["It shifts to the right", "It shifts to the left", "Nothing", "The reaction stops"], "Le Chatelier's principle: increased pressure shifts towards fewer gas molecules (4 → 2)."],
 ["Hva gjør en katalysator med en likevekt?", ["Den nås raskere, men likevektsposisjonen endres ikke", "Den forskyves mot produktene", "Den forskyves mot reaktantene", "K blir større"], "Katalysatoren senker aktiveringsenergien like mye begge veier.", "What does a catalyst do to an equilibrium?", ["It is reached faster, but the position does not change", "It shifts towards the products", "It shifts towards the reactants", "K becomes larger"], "The catalyst lowers the activation energy equally in both directions."],
 ["$K$ er svært stor. Hva betyr det?", ["Likevekten ligger langt mot produktene", "Reaksjonen går fort", "Likevekten ligger mot reaktantene", "Temperaturen er høy"], "$K = \\dfrac{[\\text{produkter}]}{[\\text{reaktanter}]}$: stor $K$ betyr mye produkt.", "$K$ is very large. What does that mean?", ["The equilibrium lies far towards the products", "The reaction is fast", "The equilibrium lies towards the reactants", "The temperature is high"], "$K = \\dfrac{[\\text{products}]}{[\\text{reactants}]}$: large $K$ means lots of product."],
 ["En eksoterm likevekt varmes opp. Hva skjer?", ["Den forskyves mot reaktantene", "Den forskyves mot produktene", "Ingenting", "K øker"], "Tilført varme «brukes» ved å gå den endoterme veien, altså bakover. $K$ minker.", "An exothermic equilibrium is heated. What happens?", ["It shifts towards the reactants", "It shifts towards the products", "Nothing", "K increases"], "Added heat is \"used\" by going the endothermic way, i.e. backwards. $K$ decreases."]
]);
GEN("VGKJ2", 0,
 () => { const a = R.p([0.1, 0.2, 0.5]), b = R.p([0.1, 0.3, 0.4]), c = R.p([0.2, 0.5, 0.8, 1]), K = c * c / (a * b);
   return [T(`Ved likevekt for $\\text{H}_2 + \\text{I}_2 \\rightleftharpoons 2\\text{HI}$ er $[\\text{H}_2] = ${mf(a)}$, $[\\text{I}_2] = ${mf(b)}$ og $[\\text{HI}] = ${mf(c)}$ mol/L. Hva er $K$?`, `At equilibrium for $\\text{H}_2 + \\text{I}_2 \\rightleftharpoons 2\\text{HI}$, $[\\text{H}_2] = ${mf(a)}$, $[\\text{I}_2] = ${mf(b)}$ and $[\\text{HI}] = ${mf(c)}$ mol/L. What is $K$?`), { n: K, tol: rel(K, 0.01), u: "" },
     T(`$K = \\dfrac{[\\text{HI}]^2}{[\\text{H}_2][\\text{I}_2]} = \\dfrac{${mf(c)}^2}{${mf(a)} \\cdot ${mf(b)}} = ${mf(K, 3)}$.`, `$K = \\dfrac{[\\text{HI}]^2}{[\\text{H}_2][\\text{I}_2]} = \\dfrac{${mf(c)}^2}{${mf(a)} \\cdot ${mf(b)}} = ${mf(K, 3)}$.`)]; },
 () => { const Ka = R.p([1.8e-5, 6.3e-5, 1.3e-5, 4.5e-4]), c = R.p([0.1, 0.05, 0.2, 0.01]), h = Math.sqrt(Ka * c), pH = -Math.log10(h), [e, m] = Ka.toExponential(1).split("e");
   return [T(`Hva er pH i en ${nf(c)} M løsning av en svak syre med $K_a = ${e.replace(".", "{,}")} \\cdot 10^{${+m}}$?`, `What is the pH of a ${nf(c)} M solution of a weak acid with $K_a = ${e} \\cdot 10^{${+m}}$?`), { n: pH, tol: 0.03, u: "" },
     T(`Tilnærming: $[\\text{H}_3\\text{O}^+] = \\sqrt{K_a c} = ${mf(h * 1e3, 3)} \\cdot 10^{-3}$, så $\\text{pH} = ${mf(pH, 2)}$.`, `Approximation: $[\\text{H}_3\\text{O}^+] = \\sqrt{K_a c} = ${mf(h * 1e3, 3)} \\cdot 10^{-3}$, so $\\text{pH} = ${mf(pH, 2)}$.`)]; }
);
BIQ("VGKJ2", 1, [
 ["Hva heter $\\text{CH}_3\\text{CH}_2\\text{CH}_3$?", ["Propan", "Etan", "Butan", "Propen"], "Tre karbonatomer med bare enkeltbindinger: prop + an.", "What is $\\text{CH}_3\\text{CH}_2\\text{CH}_3$ called?", ["Propane", "Ethane", "Butane", "Propene"], "Three carbon atoms with only single bonds: prop + ane."],
 ["Hvilken funksjonell gruppe har en alkohol?", ["$-\\text{OH}$", "$-\\text{COOH}$", "$-\\text{CHO}$", "$-\\text{NH}_2$"], "Alkoholer har en hydroksylgruppe.", "Which functional group does an alcohol have?", ["$-\\text{OH}$", "$-\\text{COOH}$", "$-\\text{CHO}$", "$-\\text{NH}_2$"], "Alcohols have a hydroxyl group."],
 ["Hva dannes når en alkohol reagerer med en karboksylsyre?", ["En ester og vann", "En alken", "Et salt", "En eter"], "Kondensasjonsreaksjon (forestring). Estere lukter ofte godt, som frukt.", "What forms when an alcohol reacts with a carboxylic acid?", ["An ester and water", "An alkene", "A salt", "An ether"], "A condensation reaction (esterification). Esters often smell nice, like fruit."],
 ["Hvilken reaksjonstype er $\\text{CH}_2{=}\\text{CH}_2 + \\text{Br}_2 \\to \\text{CH}_2\\text{Br}\\text{CH}_2\\text{Br}$?", ["Addisjon", "Substitusjon", "Eliminasjon", "Kondensasjon"], "Dobbeltbindingen åpnes, og Br legges til på hver side.", "Which reaction type is $\\text{CH}_2{=}\\text{CH}_2 + \\text{Br}_2 \\to \\text{CH}_2\\text{Br}\\text{CH}_2\\text{Br}$?", ["Addition", "Substitution", "Elimination", "Condensation"], "The double bond opens and Br is added on each side."],
 ["Hva er generell formel for alkaner?", ["$\\text{C}_n\\text{H}_{2n+2}$", "$\\text{C}_n\\text{H}_{2n}$", "$\\text{C}_n\\text{H}_{2n-2}$", "$\\text{C}_n\\text{H}_n$"], "Metan: $\\text{CH}_4$, etan: $\\text{C}_2\\text{H}_6$ …", "What is the general formula for alkanes?", ["$\\text{C}_n\\text{H}_{2n+2}$", "$\\text{C}_n\\text{H}_{2n}$", "$\\text{C}_n\\text{H}_{2n-2}$", "$\\text{C}_n\\text{H}_n$"], "Methane: $\\text{CH}_4$, ethane: $\\text{C}_2\\text{H}_6$ …"],
 ["Hvor mange H-atomer har heksan?", { n: 14, tol: 0, u: "" }, "$\\text{C}_6\\text{H}_{2 \\cdot 6 + 2} = \\text{C}_6\\text{H}_{14}$.", "How many H atoms does hexane have?", null, "$\\text{C}_6\\text{H}_{2 \\cdot 6 + 2} = \\text{C}_6\\text{H}_{14}$."]
]);
GEN("VGKJ2", 1,
 () => { const n = R.i(1, 10), names = ["metan", "etan", "propan", "butan", "pentan", "heksan", "heptan", "oktan", "nonan", "dekan"], en = ["methane", "ethane", "propane", "butane", "pentane", "hexane", "heptane", "octane", "nonane", "decane"];
   return [T(`Hvor mange hydrogenatomer har ${names[n - 1]}?`, `How many hydrogen atoms does ${en[n - 1]} have?`), { n: 2 * n + 2, tol: 0, u: "" },
     T(`Alkan med ${n} C: $\\text{C}_{${n}}\\text{H}_{2 \\cdot ${n} + 2} = \\text{C}_{${n}}\\text{H}_{${2 * n + 2}}$.`, `Alkane with ${n} C: $\\text{C}_{${n}}\\text{H}_{2 \\cdot ${n} + 2} = \\text{C}_{${n}}\\text{H}_{${2 * n + 2}}$.`)]; }
);
BIQ("VGKJ2", 2, [
 ["Hva er en buffer?", ["En løsning som motstår endring i pH", "En sterk syre", "En indikator", "Et salt"], "Buffere består av en svak syre og dens korresponderende base.", "What is a buffer?", ["A solution that resists changes in pH", "A strong acid", "An indicator", "A salt"], "Buffers consist of a weak acid and its conjugate base."],
 ["Bufferlikningen gir $\\text{pH} = \\text{p}K_a$ når …", ["$[\\text{HA}] = [\\text{A}^-]$", "$[\\text{HA}] = 0$", "løsningen er nøytral", "$K_a = 1$"], "$\\text{pH} = \\text{p}K_a + \\lg\\dfrac{[\\text{A}^-]}{[\\text{HA}]}$, og $\\lg 1 = 0$.", "The buffer equation gives $\\text{pH} = \\text{p}K_a$ when …", ["$[\\text{HA}] = [\\text{A}^-]$", "$[\\text{HA}] = 0$", "the solution is neutral", "$K_a = 1$"], "$\\text{pH} = \\text{p}K_a + \\lg\\dfrac{[\\text{A}^-]}{[\\text{HA}]}$, and $\\lg 1 = 0$."],
 ["Hvorfor er pH ved ekvivalenspunktet over 7 når eddiksyre titreres med NaOH?", ["Acetat-ionet er en svak base", "Det er for mye NaOH", "Eddiksyre er sterk", "Det er ikke over 7"], "Ved ekvivalens er det bare acetat igjen, og det tar opp protoner fra vannet.", "Why is the pH at the equivalence point above 7 when acetic acid is titrated with NaOH?", ["The acetate ion is a weak base", "There is too much NaOH", "Acetic acid is strong", "It isn't above 7"], "At equivalence only acetate is left, and it takes protons from the water."],
 ["Blodet er bufret rundt pH …", { n: 7.4, tol: 0.05, u: "" }, "Karbonatbufferen holder blodets pH på omtrent 7,4.", "Blood is buffered around pH …", null, "The carbonate buffer keeps blood pH at about 7.4."]
]);
GEN("VGKJ2", 2,
 () => { const [nm, en, pKa] = R.p([["eddiksyre", "acetic acid", 4.76], ["ammonium", "ammonium", 9.25], ["dihydrogenfosfat", "dihydrogen phosphate", 7.21], ["karbonsyre", "carbonic acid", 6.35]]), a = R.p([0.05, 0.1, 0.2, 0.3]), b = R.p([0.05, 0.1, 0.2, 0.4]), pH = pKa + Math.log10(b / a);
   return [T(`En buffer inneholder ${nf(a)} M ${nm} ($\\text{p}K_a = ${mf(pKa)}$) og ${nf(b)} M av den korresponderende basen. Hva er pH?`, `A buffer contains ${nf(a)} M ${en} ($\\text{p}K_a = ${mf(pKa)}$) and ${nf(b)} M of its conjugate base. What is the pH?`), { n: pH, tol: 0.02, u: "" },
     T(`$\\text{pH} = ${mf(pKa)} + \\lg\\dfrac{${mf(b)}}{${mf(a)}} = ${mf(pH, 2)}$.`, `$\\text{pH} = ${mf(pKa)} + \\lg\\dfrac{${mf(b)}}{${mf(a)}} = ${mf(pH, 2)}$.`)]; }
);
BIQ("VGKJ2", 3, [
 ["I en galvanisk celle: hvor skjer oksidasjonen?", ["Ved anoden", "Ved katoden", "I saltbroen", "I ledningen"], "Anode = oksidasjon, katode = reduksjon (a–o, k–r).", "In a galvanic cell: where does oxidation take place?", ["At the anode", "At the cathode", "In the salt bridge", "In the wire"], "Anode = oxidation, cathode = reduction."],
 ["$E^\\circ(\\text{Cu}^{2+}/\\text{Cu}) = +0{,}34$ V og $E^\\circ(\\text{Zn}^{2+}/\\text{Zn}) = -0{,}76$ V. Hva er cellespenningen?", { n: 1.1, tol: 0.001, u: "V" }, "$E = E_{\\text{katode}} - E_{\\text{anode}} = 0{,}34 - (-0{,}76) = 1{,}10$ V.", "$E^\\circ(\\text{Cu}^{2+}/\\text{Cu}) = +0.34$ V and $E^\\circ(\\text{Zn}^{2+}/\\text{Zn}) = -0.76$ V. What is the cell voltage?", null, "$E = E_{\\text{cathode}} - E_{\\text{anode}} = 0.34 - (-0.76) = 1.10$ V."],
 ["Hva er forskjellen på en galvanisk celle og en elektrolysecelle?", ["Galvanisk gir strøm fra en spontan reaksjon, elektrolyse bruker strøm", "De er like", "Elektrolyse gir strøm", "Galvanisk krever strøm"], "Et batteri er galvanisk. Ved elektrolyse driver vi en ikke-spontan reaksjon med strøm.", "What is the difference between a galvanic cell and an electrolytic cell?", ["Galvanic produces current from a spontaneous reaction, electrolysis uses current", "They are the same", "Electrolysis produces current", "Galvanic requires current"], "A battery is galvanic. In electrolysis we drive a non-spontaneous reaction with current."],
 ["Hvorfor brukes offeranoder av sink på båter?", ["Sink oksideres i stedet for stålet", "Sink er sterkere", "Sink er billig pynt", "Sink leder ikke strøm"], "Sink er et mer uedelt metall og ruster først, så stålet beskyttes.", "Why are sacrificial zinc anodes used on boats?", ["Zinc is oxidised instead of the steel", "Zinc is stronger", "Zinc is cheap decoration", "Zinc does not conduct"], "Zinc is a less noble metal and corrodes first, so the steel is protected."]
]);
GEN("VGKJ2", 3,
 () => { const pairs = [["Ag^+/Ag", 0.80], ["Cu^{2+}/Cu", 0.34], ["Pb^{2+}/Pb", -0.13], ["Ni^{2+}/Ni", -0.25], ["Fe^{2+}/Fe", -0.44], ["Zn^{2+}/Zn", -0.76], ["Al^{3+}/Al", -1.66], ["Mg^{2+}/Mg", -2.37]];
   const [a, b] = R.distinct(2, 0, pairs.length - 1).map(i => pairs[i]), [cat, an] = a[1] > b[1] ? [a, b] : [b, a], E = cat[1] - an[1];
   return [T(`En galvanisk celle lages av $\\mathrm{${a[0]}}$ ($E^\\circ = ${mf(a[1])}$ V) og $\\mathrm{${b[0]}}$ ($E^\\circ = ${mf(b[1])}$ V). Hva er standard cellespenning?`, `A galvanic cell is made from $\\mathrm{${a[0]}}$ ($E^\\circ = ${mf(a[1])}$ V) and $\\mathrm{${b[0]}}$ ($E^\\circ = ${mf(b[1])}$ V). What is the standard cell voltage?`), { n: E, tol: 0.001, u: "V" },
     T(`Høyest $E^\\circ$ blir katode: $E = ${mf(cat[1])} - (${mf(an[1])}) = ${mf(E, 2)}$ V.`, `The highest $E^\\circ$ becomes the cathode: $E = ${mf(cat[1])} - (${mf(an[1])}) = ${mf(E, 2)}$ V.`)]; },
 () => { const I = R.p([0.5, 1, 2, 5]), tmin = R.p([10, 20, 30, 60]), q = I * tmin * 60, n = q / (2 * 96485), m = n * 63.55;
   return [T(`Kobber felles ut fra $\\text{Cu}^{2+}$ ved elektrolyse med ${nf(I)} A i ${tmin} min. Hvor mange gram kobber dannes? ($F = 96\\,485$ C/mol, $M = 63{,}55$ g/mol)`, `Copper is deposited from $\\text{Cu}^{2+}$ by electrolysis at ${nf(I)} A for ${tmin} min. How many grams of copper form? ($F = 96\\,485$ C/mol, $M = 63.55$ g/mol)`), { n: m, tol: rel(m, 0.01), u: "g" },
     T(`$Q = It = ${mf(q, 0)}$ C. $n(\\text{Cu}) = \\dfrac{Q}{2F} = ${mf(n, 5)}$ mol. $m = nM = ${mf(m, 3)}$ g.`, `$Q = It = ${mf(q, 0)}$ C. $n(\\text{Cu}) = \\dfrac{Q}{2F} = ${mf(n, 5)}$ mol. $m = nM = ${mf(m, 3)}$ g.`)]; }
);
})();
