// ============================================================
//  add_vgs_g.js – Fysikk 1 og Fysikk 2: mange flere oppgaver og generatorer i alle enhetene
// ============================================================
(() => {
const g = 9.81;
// ================= FYSIKK 1 =================
// ---- 0: Bevegelse ----
BIQ("VGFY1", 0, [
 ["En bil kjører 90 km/t. Hva er farten i m/s?", { n: 25, tol: 0.01, u: "m/s" }, "Del på 3,6: $90/3{,}6 = 25$ m/s.", "A car drives at 90 km/h. What is the speed in m/s?", null, "Divide by 3.6: $90/3.6 = 25$ m/s."],
 ["Hva forteller arealet under en fart–tid-graf?", ["Strekningen", "Akselerasjonen", "Farten", "Tiden"], "Areal = fart · tid = strekning.", "What does the area under a velocity–time graph tell you?", ["The displacement", "The acceleration", "The velocity", "The time"], "Area = velocity · time = displacement."],
 ["Hva forteller stigningstallet til en fart–tid-graf?", ["Akselerasjonen", "Strekningen", "Posisjonen", "Massen"], "$a = \\Delta v / \\Delta t$ er stigningen.", "What does the slope of a velocity–time graph tell you?", ["The acceleration", "The displacement", "The position", "The mass"], "$a = \\Delta v / \\Delta t$ is the slope."],
 ["En stein slippes fra 20 m høyde. Omtrent hvor lang tid tar det før den treffer bakken?", { n: 2.02, tol: 0.03, u: "s" }, "$s = \\tfrac12 gt^2$ gir $t = \\sqrt{2 \\cdot 20/9{,}81} = 2{,}02$ s.", "A stone is dropped from 20 m. Roughly how long does it take to hit the ground?", null, "$s = \\tfrac12 gt^2$ gives $t = \\sqrt{2 \\cdot 20/9.81} = 2.02$ s."],
 ["Et legeme har konstant fart. Hva er akselerasjonen?", { n: 0, tol: 0, u: "m/s²" }, "Konstant fart betyr ingen endring i fart: $a = 0$.", "A body has constant velocity. What is the acceleration?", null, "Constant velocity means no change in velocity: $a = 0$."],
 ["Hvilken formel gjelder IKKE når akselerasjonen er konstant?", ["$s = v \\cdot t$ med varierende fart", "$v = v_0 + at$", "$s = v_0t + \\tfrac12 at^2$", "$v^2 - v_0^2 = 2as$"], "$s = vt$ gjelder bare når farten er konstant.", "Which formula does NOT hold when the acceleration is constant?", ["$s = v \\cdot t$ with changing speed", "$v = v_0 + at$", "$s = v_0t + \\tfrac12 at^2$", "$v^2 - v_0^2 = 2as$"], "$s = vt$ only holds when the speed is constant."],
 ["En bil bremser fra 20 m/s til 0 på 4 s. Hva er akselerasjonen?", { n: -5, tol: 0, u: "m/s²" }, "$a = \\dfrac{0 - 20}{4} = -5$ m/s². Negativ fordi farten minker.", "A car brakes from 20 m/s to 0 in 4 s. What is the acceleration?", null, "$a = \\dfrac{0 - 20}{4} = -5$ m/s². Negative because the speed decreases."]
]);
GEN("VGFY1", 0,
 () => { const v0 = R.i(0, 15), a = R.p([0.5, 1, 1.5, 2, 2.5, 3]), t = R.i(2, 12), s = v0 * t + 0.5 * a * t * t;
   return [T(`Et legeme har startfart ${v0} m/s og akselerasjon ${nf(a)} m/s². Hvor langt har det kommet etter ${t} s?`, `A body has initial velocity ${v0} m/s and acceleration ${nf(a)} m/s². How far has it gone after ${t} s?`), { n: s, tol: rel(s, 0.01), u: "m" },
     T(`$s = v_0t + \\tfrac12 at^2 = ${v0} \\cdot ${t} + \\tfrac12 \\cdot ${mf(a)} \\cdot ${t}^2 = ${mf(s)}$ m.`, `$s = v_0t + \\tfrac12 at^2 = ${v0} \\cdot ${t} + \\tfrac12 \\cdot ${mf(a)} \\cdot ${t}^2 = ${mf(s)}$ m.`)]; },
 () => { const v = R.p([50, 60, 80, 90, 100, 110, 120]), mu = R.p([0.3, 0.5, 0.7, 0.8]), vs = v / 3.6, s = vs * vs / (2 * mu * g);
   return [T(`En bil i ${v} km/t bremser med akselerasjon $${mf(mu * g, 2)}$ m/s². Hvor lang er bremselengden?`, `A car at ${v} km/h brakes with a deceleration of $${mf(mu * g, 2)}$ m/s². How long is the braking distance?`), { n: s, tol: rel(s, 0.01), u: "m" },
     T(`$v_0 = ${mf(vs, 2)}$ m/s. $v^2 - v_0^2 = 2as$ med $v = 0$: $s = \\dfrac{v_0^2}{2a} = ${mf(s, 1)}$ m. Dobbel fart gir fire ganger så lang bremselengde!`, `$v_0 = ${mf(vs, 2)}$ m/s. $v^2 - v_0^2 = 2as$ with $v = 0$: $s = \\dfrac{v_0^2}{2a} = ${mf(s, 1)}$ m. Double speed gives four times the braking distance!`)]; },
 () => { const h = R.p([5, 10, 15, 20, 30, 45, 80]), v = Math.sqrt(2 * g * h);
   return [T(`En ball slippes fra ${h} m høyde. Hvor stor fart har den når den treffer bakken (uten luftmotstand)?`, `A ball is dropped from a height of ${h} m. What is its speed when it hits the ground (no air resistance)?`), { n: v, tol: rel(v, 0.01), u: "m/s" },
     T(`$v = \\sqrt{2gh} = \\sqrt{2 \\cdot 9{,}81 \\cdot ${h}} = ${mf(v, 2)}$ m/s.`, `$v = \\sqrt{2gh} = \\sqrt{2 \\cdot 9.81 \\cdot ${h}} = ${mf(v, 2)}$ m/s.`)]; },
 () => { const v1 = R.p([36, 54, 72]), v2 = v1 + R.p([18, 36]), t = R.p([4, 5, 8, 10]), a = (v2 - v1) / 3.6 / t;
   return [T(`En bil øker farten fra ${v1} km/t til ${v2} km/t på ${t} s. Hva er akselerasjonen?`, `A car speeds up from ${v1} km/h to ${v2} km/h in ${t} s. What is the acceleration?`), { n: a, tol: rel(a, 0.01), u: "m/s²" },
     T(`$\\Delta v = ${v2 - v1}$ km/t $= ${mf((v2 - v1) / 3.6, 2)}$ m/s. $a = ${mf((v2 - v1) / 3.6, 2)}/${t} = ${mf(a, 3)}$ m/s².`, `$\\Delta v = ${v2 - v1}$ km/h $= ${mf((v2 - v1) / 3.6, 2)}$ m/s. $a = ${mf((v2 - v1) / 3.6, 2)}/${t} = ${mf(a, 3)}$ m/s².`)]; }
);
// ---- 1: Krefter og Newtons lover ----
BIQ("VGFY1", 1, [
 ["Newtons 1. lov sier at …", ["et legeme uten resultantkraft holder konstant fart", "kraft er masse ganger fart", "alle krefter har en motkraft", "tunge ting faller fortere"], "Uten resultantkraft endres ikke farten (treghetsloven).", "Newton's 1st law says that …", ["a body with no net force keeps a constant velocity", "force is mass times velocity", "every force has a counterforce", "heavy things fall faster"], "Without a net force the velocity does not change (the law of inertia)."],
 ["Hva er tyngden til en person på 70 kg?", { n: 686.7, tol: 1, u: "N" }, "$G = mg = 70 \\cdot 9{,}81 = 686{,}7$ N.", "What is the weight of a 70 kg person?", null, "$G = mg = 70 \\cdot 9.81 = 686.7$ N."],
 ["Du dytter på en vegg. Hva er motkraften etter Newtons 3. lov?", ["Veggen dytter like hardt tilbake på deg", "Friksjonen fra gulvet", "Tyngden din", "Det finnes ingen"], "Kraft og motkraft virker på hvert sitt legeme, like store og motsatt rettet.", "You push on a wall. What is the counterforce by Newton's 3rd law?", ["The wall pushes back on you just as hard", "The friction from the floor", "Your weight", "There is none"], "Force and counterforce act on different bodies, equal and opposite."],
 ["En heis akselererer oppover. Hva viser badevekta du står på?", ["Mer enn vanlig", "Mindre enn vanlig", "Det samme", "Null"], "$N - mg = ma$, så $N = m(g + a) > mg$.", "A lift accelerates upwards. What does the scale you stand on show?", ["More than usual", "Less than usual", "The same", "Zero"], "$N - mg = ma$, so $N = m(g + a) > mg$."],
 ["En kloss på 2 kg dras med 10 N, og friksjonen er 4 N. Hva er akselerasjonen?", { n: 3, tol: 0, u: "m/s²" }, "$\\Sigma F = 10 - 4 = 6$ N, $a = 6/2 = 3$ m/s².", "A 2 kg block is pulled with 10 N and the friction is 4 N. What is the acceleration?", null, "$\\Sigma F = 10 - 4 = 6$ N, $a = 6/2 = 3$ m/s²."],
 ["Friksjonskraften $R = \\mu N$. Hva skjer med friksjonen hvis normalkraften dobles?", ["Den dobles", "Den halveres", "Den er uendret", "Den firedobles"], "$R$ er proporsjonal med $N$.", "The friction force $R = \\mu N$. What happens to the friction if the normal force doubles?", ["It doubles", "It halves", "It is unchanged", "It quadruples"], "$R$ is proportional to $N$."],
 ["En fallskjermhopper faller med konstant fart. Hva er luftmotstanden?", ["Like stor som tyngden", "Større enn tyngden", "Null", "Halvparten av tyngden"], "Konstant fart gir $\\Sigma F = 0$, så luftmotstanden balanserer tyngden.", "A skydiver falls at constant speed. What is the air resistance?", ["Equal to the weight", "Greater than the weight", "Zero", "Half the weight"], "Constant velocity gives $\\Sigma F = 0$, so air resistance balances the weight."]
]);
GEN("VGFY1", 1,
 () => { const m = R.p([2, 5, 10, 20, 50]), F = R.p([20, 40, 60, 100, 200]), mu = R.p([0.1, 0.2, 0.3]), R_ = mu * m * g, a = (F - R_) / m;
   if(a <= 0) return [T(`En kloss på ${m} kg ligger på et bord. Hva er tyngden?`, `A ${m} kg block lies on a table. What is its weight?`), { n: m * g, tol: 0.5, u: "N" }, T(`$G = mg = ${m} \\cdot 9{,}81 = ${mf(m * g, 1)}$ N.`, `$G = mg = ${m} \\cdot 9.81 = ${mf(m * g, 1)}$ N.`)];
   return [T(`En kloss på ${m} kg trekkes bortover med ${F} N. Friksjonstallet er ${nf(mu)}. Hva er akselerasjonen?`, `A ${m} kg block is pulled along with ${F} N. The friction coefficient is ${nf(mu)}. What is the acceleration?`), { n: a, tol: rel(a, 0.01), u: "m/s²" },
     T(`$R = \\mu mg = ${mf(mu)} \\cdot ${m} \\cdot 9{,}81 = ${mf(R_, 1)}$ N. $a = \\dfrac{${F} - ${mf(R_, 1)}}{${m}} = ${mf(a, 2)}$ m/s².`, `$R = \\mu mg = ${mf(mu)} \\cdot ${m} \\cdot 9.81 = ${mf(R_, 1)}$ N. $a = \\dfrac{${F} - ${mf(R_, 1)}}{${m}} = ${mf(a, 2)}$ m/s².`)]; },
 () => { const m = R.p([50, 60, 70, 80]), a = R.p([1, 1.5, 2, 2.5, -1, -2]), N = m * (g + a);
   return [T(`Du (${m} kg) står på en vekt i en heis som akselererer ${a > 0 ? "oppover" : "nedover"} med ${nf(Math.abs(a))} m/s². Hva er normalkraften fra vekta?`, `You (${m} kg) stand on a scale in a lift accelerating ${a > 0 ? "upwards" : "downwards"} at ${nf(Math.abs(a))} m/s². What is the normal force from the scale?`), { n: N, tol: rel(N, 0.01), u: "N" },
     T(`$N - mg = ma$ gir $N = m(g + a) = ${m}(9{,}81 ${a < 0 ? "-" : "+"} ${nf(Math.abs(a))}) = ${mf(N, 1)}$ N.`, `$N - mg = ma$ gives $N = m(g + a) = ${m}(9.81 ${a < 0 ? "-" : "+"} ${nf(Math.abs(a))}) = ${mf(N, 1)}$ N.`)]; },
 () => { const m1 = R.p([1, 2, 3]), m2 = R.p([1, 2, 4, 5]), a = m2 * g / (m1 + m2);
   return [T(`En vogn på ${m1} kg på et friksjonsfritt bord er festet med en snor over en trinse til et lodd på ${m2} kg som henger fritt. Hva er akselerasjonen?`, `A ${m1} kg cart on a frictionless table is tied with a string over a pulley to a ${m2} kg weight hanging freely. What is the acceleration?`), { n: a, tol: rel(a, 0.01), u: "m/s²" },
     T(`Hele systemet: $a = \\dfrac{m_2 g}{m_1 + m_2} = \\dfrac{${m2} \\cdot 9{,}81}{${m1 + m2}} = ${mf(a, 2)}$ m/s².`, `The whole system: $a = \\dfrac{m_2 g}{m_1 + m_2} = \\dfrac{${m2} \\cdot 9.81}{${m1 + m2}} = ${mf(a, 2)}$ m/s².`)]; }
);
// ---- 2: Energi og arbeid ----
BIQ("VGFY1", 2, [
 ["Hva er den kinetiske energien til en ball på 0,5 kg med fart 4 m/s?", { n: 4, tol: 0, u: "J" }, "$E_k = \\tfrac12 mv^2 = \\tfrac12 \\cdot 0{,}5 \\cdot 16 = 4$ J.", "What is the kinetic energy of a 0.5 kg ball at 4 m/s?", null, "$E_k = \\tfrac12 mv^2 = \\tfrac12 \\cdot 0.5 \\cdot 16 = 4$ J."],
 ["Hva skjer med den kinetiske energien når farten dobles?", ["Den firedobles", "Den dobles", "Den er uendret", "Den halveres"], "$E_k \\propto v^2$, og $2^2 = 4$.", "What happens to the kinetic energy when the speed doubles?", ["It quadruples", "It doubles", "It is unchanged", "It halves"], "$E_k \\propto v^2$, and $2^2 = 4$."],
 ["Du bærer en tung sekk bortover et flatt gulv med konstant fart. Hvor mye arbeid gjør du på sekken (fysisk sett)?", ["Null", "Mye", "$mgh$", "$\\tfrac12 mv^2$"], "Kraften din er loddrett og forflytningen vannrett: $W = Fs\\cos 90^\\circ = 0$.", "You carry a heavy bag across a flat floor at constant speed. How much work do you do on the bag (physically)?", ["Zero", "A lot", "$mgh$", "$\\tfrac12 mv^2$"], "Your force is vertical and the displacement horizontal: $W = Fs\\cos 90^\\circ = 0$."],
 ["En motor løfter 100 kg 12 m på 20 s. Hva er effekten?", { n: 588.6, tol: 1, u: "W" }, "$P = \\dfrac{mgh}{t} = \\dfrac{100 \\cdot 9{,}81 \\cdot 12}{20} = 588{,}6$ W.", "A motor lifts 100 kg by 12 m in 20 s. What is the power?", null, "$P = \\dfrac{mgh}{t} = \\dfrac{100 \\cdot 9.81 \\cdot 12}{20} = 588.6$ W."],
 ["En lyspære bruker 60 J og gir 6 J lys. Hva er virkningsgraden?", { n: 10, tol: 0, u: "%" }, "$\\eta = 6/60 = 0{,}10 = 10$ %. Resten blir varme.", "A light bulb uses 60 J and gives 6 J of light. What is the efficiency?", null, "$\\eta = 6/60 = 0.10 = 10$ %. The rest becomes heat."],
 ["Hvor blir det av mekanisk energi som «forsvinner» ved friksjon?", ["Den blir til indre energi (varme)", "Den forsvinner helt", "Den blir til masse", "Den blir til potensiell energi"], "Energi er bevart: friksjon gjør mekanisk energi om til varme.", "Where does mechanical energy that \"disappears\" due to friction go?", ["It becomes internal energy (heat)", "It disappears completely", "It becomes mass", "It becomes potential energy"], "Energy is conserved: friction turns mechanical energy into heat."],
 ["Hva er 1 kWh i joule?", { n: 3600000, tol: 0, u: "J" }, "$1000 \\text{ W} \\cdot 3600 \\text{ s} = 3\\,600\\,000$ J.", "What is 1 kWh in joules?", null, "$1000 \\text{ W} \\cdot 3600 \\text{ s} = 3\\,600\\,000$ J."]
]);
GEN("VGFY1", 2,
 () => { const h = R.p([2, 5, 10, 15, 20, 40]), v0 = R.p([0, 2, 3, 5]), v = Math.sqrt(v0 * v0 + 2 * g * h);
   return [T(`En skater starter med fart ${v0} m/s på toppen av en rampe som er ${h} m høy. Hva er farten nederst (se bort fra friksjon)?`, `A skater starts at ${v0} m/s at the top of a ${h} m high ramp. What is the speed at the bottom (ignore friction)?`), { n: v, tol: rel(v, 0.01), u: "m/s" },
     T(`Energibevaring: $\\tfrac12 v_0^2 + gh = \\tfrac12 v^2$, så $v = \\sqrt{${v0}^2 + 2 \\cdot 9{,}81 \\cdot ${h}} = ${mf(v, 2)}$ m/s. Massen spiller ingen rolle!`, `Energy conservation: $\\tfrac12 v_0^2 + gh = \\tfrac12 v^2$, so $v = \\sqrt{${v0}^2 + 2 \\cdot 9.81 \\cdot ${h}} = ${mf(v, 2)}$ m/s. The mass does not matter!`)]; },
 () => { const P = R.p([60, 100, 1000, 2000, 2400]), t = R.p([0.5, 1, 2, 3, 8]), days = R.p([1, 7, 30]), E = P * t * days / 1000, pr = R.p([1, 1.5, 2]), cost = E * pr;
   return [T(`Et apparat på ${P} W står på ${nf(t)} timer hver dag i ${days} ${days === 1 ? "dag" : "dager"}. Strømprisen er ${nf(pr)} kr/kWh. Hva koster det?`, `An appliance of ${P} W runs ${nf(t)} hours a day for ${days} ${days === 1 ? "day" : "days"}. Electricity costs ${nf(pr)} NOK/kWh. What does it cost?`), { n: cost, tol: rel(cost, 0.01, 0.01), u: "kr" },
     T(`$E = ${P} \\text{ W} \\cdot ${nf(t * days)} \\text{ h} = ${mf(E, 3)}$ kWh. Pris: $${mf(E, 3)} \\cdot ${mf(pr)} = ${mf(cost, 2)}$ kr.`, `$E = ${P} \\text{ W} \\cdot ${nf(t * days)} \\text{ h} = ${mf(E, 3)}$ kWh. Cost: $${mf(E, 3)} \\cdot ${mf(pr)} = ${mf(cost, 2)}$ NOK.`)]; },
 () => { const m = R.p([0.2, 0.5, 1, 2]), h = R.p([1, 2, 3, 5]), hb = R.p([0.4, 0.5, 0.6, 0.7, 0.8]) * h, loss = m * g * (h - hb), pct = (1 - hb / h) * 100;
   return [T(`En ball på ${nf(m)} kg slippes fra ${h} m og spretter opp til ${nf(hb)} m. Hvor mange prosent av energien gikk tapt i sprettet?`, `A ${nf(m)} kg ball is dropped from ${h} m and bounces up to ${nf(hb)} m. What percentage of the energy was lost in the bounce?`), { n: pct, tol: 0.2, u: "%" },
     T(`Potensiell energi er proporsjonal med høyden: tapet er $1 - \\dfrac{${mf(hb)}}{${h}} = ${mf(pct, 1)}$ %, altså $${mf(loss, 2)}$ J.`, `Potential energy is proportional to height: the loss is $1 - \\dfrac{${mf(hb)}}{${h}} = ${mf(pct, 1)}$ %, i.e. $${mf(loss, 2)}$ J.`)]; }
);
// ---- 3: Elektrisitet ----
BIQ("VGFY1", 3, [
 ["To motstander på 4 Ω og 6 Ω er koblet i serie. Hva er total resistans?", { n: 10, tol: 0, u: "Ω" }, "I serie legges de sammen: $4 + 6 = 10$ Ω.", "Two resistors of 4 Ω and 6 Ω are connected in series. What is the total resistance?", null, "In series they add up: $4 + 6 = 10$ Ω."],
 ["To motstander på 6 Ω er koblet i parallell. Hva er total resistans?", { n: 3, tol: 0, u: "Ω" }, "$\\dfrac{1}{R} = \\dfrac16 + \\dfrac16 = \\dfrac13$, så $R = 3$ Ω.", "Two 6 Ω resistors are connected in parallel. What is the total resistance?", null, "$\\dfrac{1}{R} = \\dfrac16 + \\dfrac16 = \\dfrac13$, so $R = 3$ Ω."],
 ["Hva skjer med total resistans når du kobler flere pærer i parallell?", ["Den blir mindre", "Den blir større", "Den er uendret", "Den blir null med én gang"], "Flere veier for strømmen gir lavere total resistans.", "What happens to the total resistance when you connect more bulbs in parallel?", ["It gets smaller", "It gets larger", "It is unchanged", "It becomes zero immediately"], "More paths for the current give lower total resistance."],
 ["En vannkoker på 2000 W er koblet til 230 V. Hvor stor strøm går det?", { n: 8.7, tol: 0.05, u: "A" }, "$I = P/U = 2000/230 = 8{,}7$ A.", "A 2000 W kettle is connected to 230 V. What current flows?", null, "$I = P/U = 2000/230 = 8.7$ A."],
 ["Hva sier Kirchhoffs strømlov?", ["Strømmen inn i et knutepunkt er lik strømmen ut", "Spenningen er lik overalt", "Resistansen er konstant", "Strøm og spenning er proporsjonale"], "Ladning hoper seg ikke opp: det som går inn, må ut.", "What does Kirchhoff's current law say?", ["The current into a junction equals the current out", "The voltage is the same everywhere", "The resistance is constant", "Current and voltage are proportional"], "Charge does not pile up: what goes in must come out."],
 ["Hva er ladningen til ett elektron?", ["$-1{,}6 \\cdot 10^{-19}$ C", "$1{,}6 \\cdot 10^{19}$ C", "$-9{,}1 \\cdot 10^{-31}$ C", "$-1$ C"], "Elementærladningen $e = 1{,}6 \\cdot 10^{-19}$ C. $9{,}1 \\cdot 10^{-31}$ kg er massen.", "What is the charge of one electron?", ["$-1.6 \\cdot 10^{-19}$ C", "$1.6 \\cdot 10^{19}$ C", "$-9.1 \\cdot 10^{-31}$ C", "$-1$ C"], "The elementary charge $e = 1.6 \\cdot 10^{-19}$ C. $9.1 \\cdot 10^{-31}$ kg is the mass."],
 ["Et batteri har emk 9 V og indre resistans 1 Ω. Det kobles til 8 Ω. Hva er strømmen?", { n: 1, tol: 0, u: "A" }, "$I = \\dfrac{\\varepsilon}{R + r} = \\dfrac{9}{8 + 1} = 1$ A.", "A battery has emf 9 V and internal resistance 1 Ω. It is connected to 8 Ω. What is the current?", null, "$I = \\dfrac{\\varepsilon}{R + r} = \\dfrac{9}{8 + 1} = 1$ A."]
]);
GEN("VGFY1", 3,
 () => { const r1 = R.p([2, 4, 6, 10, 12, 20]), r2 = R.p([3, 4, 6, 12, 15, 30]), U = R.p([6, 9, 12, 24]), Rp = r1 * r2 / (r1 + r2), I = U / Rp;
   return [T(`${r1} Ω og ${r2} Ω er koblet i parallell til ${U} V. Hva er den totale strømmen?`, `${r1} Ω and ${r2} Ω are connected in parallel to ${U} V. What is the total current?`), { n: I, tol: rel(I, 0.01), u: "A" },
     T(`$R = \\dfrac{${r1} \\cdot ${r2}}{${r1} + ${r2}} = ${mf(Rp, 3)}$ Ω. $I = U/R = ${mf(I, 3)}$ A.`, `$R = \\dfrac{${r1} \\cdot ${r2}}{${r1} + ${r2}} = ${mf(Rp, 3)}$ Ω. $I = U/R = ${mf(I, 3)}$ A.`)]; },
 () => { const r1 = R.p([10, 20, 47, 100]), r2 = R.p([10, 22, 33, 68]), U = R.p([5, 9, 12]), U2 = U * r2 / (r1 + r2);
   return [T(`En spenningsdeler har $R_1 = ${r1}$ Ω og $R_2 = ${r2}$ Ω i serie over ${U} V. Hva er spenningen over $R_2$?`, `A voltage divider has $R_1 = ${r1}$ Ω and $R_2 = ${r2}$ Ω in series across ${U} V. What is the voltage across $R_2$?`), { n: U2, tol: rel(U2, 0.01), u: "V" },
     T(`$U_2 = U\\dfrac{R_2}{R_1 + R_2} = ${U}\\cdot\\dfrac{${r2}}{${r1 + r2}} = ${mf(U2, 3)}$ V.`, `$U_2 = U\\dfrac{R_2}{R_1 + R_2} = ${U}\\cdot\\dfrac{${r2}}{${r1 + r2}} = ${mf(U2, 3)}$ V.`)]; },
 () => { const eps = R.p([1.5, 4.5, 9, 12]), r = R.p([0.2, 0.5, 1, 2]), Rl = R.p([2, 5, 10, 20]), I = eps / (Rl + r), Uk = I * Rl;
   return [T(`Et batteri har emk ${nf(eps)} V og indre resistans ${nf(r)} Ω. Det kobles til en ytre motstand på ${Rl} Ω. Hva er polspenningen?`, `A battery has emf ${nf(eps)} V and internal resistance ${nf(r)} Ω. It is connected to an external resistor of ${Rl} Ω. What is the terminal voltage?`), { n: Uk, tol: rel(Uk, 0.01), u: "V" },
     T(`$I = \\dfrac{${mf(eps)}}{${Rl} + ${mf(r)}} = ${mf(I, 3)}$ A. $U_k = RI = ${mf(Uk, 3)}$ V (litt under emk fordi noe spenning tapes inne i batteriet).`, `$I = \\dfrac{${mf(eps)}}{${Rl} + ${mf(r)}} = ${mf(I, 3)}$ A. $U_k = RI = ${mf(Uk, 3)}$ V (a little below the emf because some voltage is lost inside the battery).`)]; }
);
// ---- 4: Atomer, stråling og universet ----
BIQ("VGFY1", 4, [
 ["Hva består en alfapartikkel av?", ["2 protoner og 2 nøytroner", "Ett elektron", "Et foton", "Ett proton"], "En alfapartikkel er en heliumkjerne.", "What does an alpha particle consist of?", ["2 protons and 2 neutrons", "One electron", "A photon", "One proton"], "An alpha particle is a helium nucleus."],
 ["Hvilken stråling stoppes av et papirark?", ["Alfa", "Beta", "Gamma", "Røntgen"], "Alfa har kort rekkevidde og stoppes av papir eller huden.", "Which radiation is stopped by a sheet of paper?", ["Alpha", "Beta", "Gamma", "X-rays"], "Alpha has a short range and is stopped by paper or the skin."],
 ["Halveringstiden er 5 år. Hvor mye er igjen etter 15 år?", { n: 12.5, tol: 0.01, u: "%" }, "Tre halveringstider: $\\left(\\tfrac12\\right)^3 = \\tfrac18 = 12{,}5$ %.", "The half-life is 5 years. How much is left after 15 years?", null, "Three half-lives: $\\left(\\tfrac12\\right)^3 = \\tfrac18 = 12.5$ %."],
 ["Hva skjer med nukleontallet ved betaminus-stråling?", ["Det er uendret", "Det øker med 1", "Det minker med 4", "Det minker med 1"], "Et nøytron blir til et proton og et elektron: antall nukleoner er det samme, men protontallet øker med 1.", "What happens to the nucleon number in beta-minus decay?", ["It is unchanged", "It increases by 1", "It decreases by 4", "It decreases by 1"], "A neutron becomes a proton and an electron: the number of nucleons is the same, but the proton number increases by 1."],
 ["Hva er energikilden i sola?", ["Fusjon av hydrogen til helium", "Fisjon av uran", "Forbrenning", "Radioaktivt nedfall"], "I kjernen smelter hydrogen sammen til helium, og massen som «forsvinner», blir energi ($E = mc^2$).", "What is the energy source in the Sun?", ["Fusion of hydrogen into helium", "Fission of uranium", "Combustion", "Radioactive fallout"], "In the core hydrogen fuses into helium, and the mass that \"disappears\" becomes energy ($E = mc^2$)."],
 ["Hva forteller rødforskyvningen av lys fra fjerne galakser?", ["At universet utvider seg", "At galaksene er varme", "At lyset er gammelt", "At galaksene er røde"], "Galaksene fjerner seg fra oss, og jo lenger borte, jo raskere (Hubbles lov).", "What does the redshift of light from distant galaxies tell us?", ["That the universe is expanding", "That the galaxies are hot", "That the light is old", "That the galaxies are red"], "The galaxies move away from us, and the further away, the faster (Hubble's law)."],
 ["Et foton har bølgelengde 500 nm. Hva er energien? ($h = 6{,}63 \\cdot 10^{-34}$ Js, $c = 3{,}00 \\cdot 10^8$ m/s)", ["$3{,}98 \\cdot 10^{-19}$ J", "$3{,}98 \\cdot 10^{19}$ J", "$6{,}63 \\cdot 10^{-34}$ J", "$1{,}5 \\cdot 10^{-15}$ J"], "$E = \\dfrac{hc}{\\lambda} = \\dfrac{6{,}63 \\cdot 10^{-34} \\cdot 3{,}00 \\cdot 10^8}{500 \\cdot 10^{-9}} = 3{,}98 \\cdot 10^{-19}$ J.", "A photon has wavelength 500 nm. What is its energy? ($h = 6.63 \\cdot 10^{-34}$ Js, $c = 3.00 \\cdot 10^8$ m/s)", ["$3.98 \\cdot 10^{-19}$ J", "$3.98 \\cdot 10^{19}$ J", "$6.63 \\cdot 10^{-34}$ J", "$1.5 \\cdot 10^{-15}$ J"], "$E = \\dfrac{hc}{\\lambda} = \\dfrac{6.63 \\cdot 10^{-34} \\cdot 3.00 \\cdot 10^8}{500 \\cdot 10^{-9}} = 3.98 \\cdot 10^{-19}$ J."]
]);
GEN("VGFY1", 4,
 () => { const T12 = R.p([2, 5, 8, 12, 30, 5730]), n = R.i(1, 6), t = n * T12, left = 100 / 2 ** n;
   return [T(`Et stoff har halveringstid ${T12} år. Hvor mange prosent er igjen etter ${t} år?`, `A substance has a half-life of ${T12} years. What percentage is left after ${t} years?`), { n: left, tol: 0.01, u: "%" },
     T(`${t}/${T12} = ${n} halveringstider: $100 \\cdot \\left(\\tfrac12\\right)^{${n}} = ${mf(left, 3)}$ %.`, `${t}/${T12} = ${n} half-lives: $100 \\cdot \\left(\\tfrac12\\right)^{${n}} = ${mf(left, 3)}$ %.`)]; },
 () => { const lam = R.p([400, 450, 500, 550, 600, 650, 700]), E = 6.63e-34 * 3e8 / (lam * 1e-9), eV = E / 1.6e-19;
   return [T(`Hva er energien til et foton med bølgelengde ${lam} nm, i elektronvolt?`, `What is the energy of a photon with wavelength ${lam} nm, in electronvolts?`), { n: eV, tol: 0.02, u: "eV" },
     T(`$E = \\dfrac{hc}{\\lambda} = \\dfrac{6{,}63 \\cdot 10^{-34} \\cdot 3{,}00 \\cdot 10^8}{${lam} \\cdot 10^{-9}} = ${mf(E * 1e19, 3)} \\cdot 10^{-19}$ J $= ${mf(eV, 2)}$ eV.`, `$E = \\dfrac{hc}{\\lambda} = \\dfrac{6.63 \\cdot 10^{-34} \\cdot 3.00 \\cdot 10^8}{${lam} \\cdot 10^{-9}} = ${mf(E * 1e19, 3)} \\cdot 10^{-19}$ J $= ${mf(eV, 2)}$ eV.`)]; },
 () => { const [el, Z, A] = R.p([["U", 92, 238], ["Ra", 88, 226], ["Po", 84, 210], ["Th", 90, 232], ["Rn", 86, 222]]), alpha = R.p([true, false]);
   return [T(`${el}-${A} (protontall ${Z}) sender ut en ${alpha ? "alfapartikkel" : "betaminus-partikkel"}. Hva blir det nye nukleontallet?`, `${el}-${A} (proton number ${Z}) emits ${alpha ? "an alpha particle" : "a beta-minus particle"}. What is the new nucleon number?`), { n: alpha ? A - 4 : A, tol: 0, u: "" },
     T(alpha ? `Alfa tar med seg 2 protoner og 2 nøytroner: $${A} - 4 = ${A - 4}$, og protontallet blir ${Z - 2}.` : `Ved betaminus blir et nøytron til et proton: nukleontallet er fortsatt ${A}, og protontallet blir ${Z + 1}.`,
       alpha ? `Alpha takes away 2 protons and 2 neutrons: $${A} - 4 = ${A - 4}$, and the proton number becomes ${Z - 2}.` : `In beta-minus a neutron becomes a proton: the nucleon number is still ${A}, and the proton number becomes ${Z + 1}.`)]; }
);

// ================= FYSIKK 2 =================
// ---- 0: Kast og bevegelse i to dimensjoner ----
BIQ("VGFY2", 0, [
 ["I et skrått kast uten luftmotstand: hva er akselerasjonen i vannrett retning?", { n: 0, tol: 0, u: "m/s²" }, "Bare tyngden virker, og den er loddrett. Vannrett akselerasjon er 0, så vannrett fart er konstant.", "In a projectile without air resistance: what is the horizontal acceleration?", null, "Only gravity acts, and it is vertical. The horizontal acceleration is 0, so the horizontal velocity is constant."],
 ["Hvilken utskytingsvinkel gir lengst kast på flatt underlag (uten luftmotstand)?", { n: 45, tol: 0, u: "°" }, "$R = \\dfrac{v_0^2 \\sin 2\\theta}{g}$ er størst når $2\\theta = 90^\\circ$, altså $\\theta = 45^\\circ$.", "Which launch angle gives the longest throw on level ground (no air resistance)?", null, "$R = \\dfrac{v_0^2 \\sin 2\\theta}{g}$ is largest when $2\\theta = 90^\\circ$, i.e. $\\theta = 45^\\circ$."],
 ["En ball kastes vannrett fra et bord samtidig som en annen slippes fra samme høyde. Hvilken lander først?", ["De lander samtidig", "Den som kastes", "Den som slippes", "Det avhenger av massen"], "Den loddrette bevegelsen er lik for begge: samme høyde og samme $g$.", "A ball is thrown horizontally from a table while another is dropped from the same height. Which lands first?", ["They land at the same time", "The thrown one", "The dropped one", "It depends on the mass"], "The vertical motion is the same for both: same height and same $g$."],
 ["Hva er farten på toppen av et skrått kast?", ["Bare den vannrette komponenten", "Null", "Startfarten", "Bare den loddrette komponenten"], "På toppen er $v_y = 0$, men $v_x$ er den samme som ved start.", "What is the speed at the top of a projectile?", ["Only the horizontal component", "Zero", "The initial speed", "Only the vertical component"], "At the top $v_y = 0$, but $v_x$ is the same as at the start."],
 ["30° og 60° gir samme kastlengde. Hvorfor?", ["$\\sin 60^\\circ = \\sin 120^\\circ$", "De har samme høyde", "Luftmotstanden", "Det gir de ikke"], "$\\sin(2 \\cdot 30^\\circ) = \\sin(2 \\cdot 60^\\circ)$. Komplementære vinkler gir samme lengde.", "30° and 60° give the same range. Why?", ["$\\sin 60^\\circ = \\sin 120^\\circ$", "They have the same height", "Air resistance", "They don't"], "$\\sin(2 \\cdot 30^\\circ) = \\sin(2 \\cdot 60^\\circ)$. Complementary angles give the same range."]
]);
GEN("VGFY2", 0,
 () => { const h = R.p([1, 1.25, 2, 5, 10, 20]), v = R.p([2, 3, 5, 8, 10]), t = Math.sqrt(2 * h / g), x = v * t;
   return [T(`En ball ruller av et bord som er ${nf(h)} m høyt med fart ${v} m/s. Hvor langt fra bordkanten lander den?`, `A ball rolls off a ${nf(h)} m high table at ${v} m/s. How far from the edge does it land?`), { n: x, tol: rel(x, 0.01), u: "m" },
     T(`Falltid $t = \\sqrt{2h/g} = ${mf(t, 3)}$ s. Vannrett: $x = vt = ${v} \\cdot ${mf(t, 3)} = ${mf(x, 2)}$ m.`, `Fall time $t = \\sqrt{2h/g} = ${mf(t, 3)}$ s. Horizontally: $x = vt = ${v} \\cdot ${mf(t, 3)} = ${mf(x, 2)}$ m.`)]; },
 () => { const v0 = R.p([10, 15, 20, 25, 30]), th = R.p([20, 30, 40, 50, 60, 70]), H = (v0 * Math.sin(th * DEG)) ** 2 / (2 * g);
   return [T(`En ball skytes ut med ${v0} m/s i ${th}° vinkel. Hvor høyt kommer den (fra utskytingspunktet)?`, `A ball is launched at ${v0} m/s at ${th}°. How high does it go (from the launch point)?`), { n: H, tol: rel(H, 0.01), u: "m" },
     T(`$v_{0y} = ${v0}\\sin ${th}^\\circ = ${mf(v0 * Math.sin(th * DEG), 2)}$ m/s. $H = \\dfrac{v_{0y}^2}{2g} = ${mf(H, 2)}$ m.`, `$v_{0y} = ${v0}\\sin ${th}^\\circ = ${mf(v0 * Math.sin(th * DEG), 2)}$ m/s. $H = \\dfrac{v_{0y}^2}{2g} = ${mf(H, 2)}$ m.`)]; },
 () => { const v0 = R.p([10, 15, 20, 25]), th = R.p([15, 30, 45, 60, 75]), Rg = v0 * v0 * Math.sin(2 * th * DEG) / g;
   return [T(`Hvor langt går et kast med ${v0} m/s i ${th}° på flatt underlag (uten luftmotstand)?`, `How far does a throw at ${v0} m/s and ${th}° go on level ground (no air resistance)?`), { n: Rg, tol: rel(Rg, 0.01), u: "m" },
     T(`$R = \\dfrac{v_0^2\\sin 2\\theta}{g} = \\dfrac{${v0}^2 \\sin ${2 * th}^\\circ}{9{,}81} = ${mf(Rg, 2)}$ m.`, `$R = \\dfrac{v_0^2\\sin 2\\theta}{g} = \\dfrac{${v0}^2 \\sin ${2 * th}^\\circ}{9.81} = ${mf(Rg, 2)}$ m.`)]; }
);
// ---- 1: Sirkelbevegelse og gravitasjon ----
BIQ("VGFY2", 1, [
 ["Hvilken vei peker akselerasjonen til et legeme i jevn sirkelbevegelse?", ["Inn mot sentrum", "Langs banen", "Ut fra sentrum", "Det har ingen akselerasjon"], "Retningen på farten endres hele tiden, og akselerasjonen $v^2/r$ peker inn mot sentrum.", "In which direction does the acceleration of a body in uniform circular motion point?", ["Towards the centre", "Along the path", "Away from the centre", "It has no acceleration"], "The direction of the velocity changes all the time, and the acceleration $v^2/r$ points towards the centre."],
 ["Hva skjer med gravitasjonskraften når avstanden dobles?", ["Den blir en firedel", "Den halveres", "Den dobles", "Den er uendret"], "$F = \\gamma\\dfrac{mM}{r^2}$, og $2^2 = 4$.", "What happens to the gravitational force when the distance doubles?", ["It becomes a quarter", "It halves", "It doubles", "It is unchanged"], "$F = \\gamma\\dfrac{mM}{r^2}$, and $2^2 = 4$."],
 ["Hvorfor føler astronauter på romstasjonen seg vektløse?", ["De faller fritt rundt jorda sammen med stasjonen", "Det er ingen tyngdekraft der", "De er for langt unna jorda", "Stasjonen skjermer for tyngden"], "Tyngdekraften der er omtrent 90 % av den på bakken, men alt faller sammen.", "Why do astronauts on the space station feel weightless?", ["They fall freely around the Earth together with the station", "There is no gravity there", "They are too far from the Earth", "The station shields gravity"], "Gravity there is about 90 % of that on the ground, but everything falls together."],
 ["En berg-og-dal-bane-vogn går gjennom en loop. Hva er minste fart på toppen for å holde seg på banen (radius 10 m)?", { n: 9.9, tol: 0.05, u: "m/s" }, "På toppen må $mg \\le mv^2/r$, så $v \\ge \\sqrt{gr} = \\sqrt{98{,}1} = 9{,}9$ m/s.", "A roller coaster car goes through a loop. What is the minimum speed at the top to stay on the track (radius 10 m)?", null, "At the top $mg \\le mv^2/r$, so $v \\ge \\sqrt{gr} = \\sqrt{98.1} = 9.9$ m/s."],
 ["Hvilken satellitt har lengst omløpstid?", ["Den som er lengst unna jorda", "Den som er nærmest jorda", "Den tyngste", "Alle har samme"], "Keplers 3. lov: $T^2 \\propto r^3$. Massen til satellitten spiller ingen rolle.", "Which satellite has the longest orbital period?", ["The one furthest from the Earth", "The one closest to the Earth", "The heaviest one", "They are all the same"], "Kepler's 3rd law: $T^2 \\propto r^3$. The mass of the satellite does not matter."]
]);
GEN("VGFY2", 1,
 () => { const r = R.p([0.5, 1, 1.5, 2]), T_ = R.p([0.5, 1, 2]), m = R.p([0.1, 0.2, 0.5]), v = 2 * Math.PI * r / T_, F = m * v * v / r;
   return [T(`En ball på ${nf(m)} kg svinges rundt i en sirkel med radius ${nf(r)} m. Én runde tar ${nf(T_)} s. Hva er snordraget (se bort fra tyngden)?`, `A ${nf(m)} kg ball is swung in a circle with radius ${nf(r)} m. One lap takes ${nf(T_)} s. What is the string tension (ignore gravity)?`), { n: F, tol: rel(F, 0.01), u: "N" },
     T(`$v = \\dfrac{2\\pi r}{T} = ${mf(v, 3)}$ m/s. $F = \\dfrac{mv^2}{r} = ${mf(F, 2)}$ N.`, `$v = \\dfrac{2\\pi r}{T} = ${mf(v, 3)}$ m/s. $F = \\dfrac{mv^2}{r} = ${mf(F, 2)}$ N.`)]; },
 () => { const h = R.p([400, 800, 2000, 20000, 35786]), r = 6.371e6 + h * 1000, v = Math.sqrt(3.986e14 / r);
   return [T(`Hva er banefarten til en satellitt ${h} km over jordoverflaten? (Jordas radius 6371 km, $GM = 3{,}986 \\cdot 10^{14}$ m³/s²)`, `What is the orbital speed of a satellite ${h} km above the Earth's surface? (Earth's radius 6371 km, $GM = 3.986 \\cdot 10^{14}$ m³/s²)`), { n: v / 1000, tol: 0.02, u: "km/s" },
     T(`$v = \\sqrt{\\dfrac{GM}{r}}$ med $r = ${mf(r / 1e6, 3)} \\cdot 10^6$ m gir $v = ${mf(v / 1000, 2)}$ km/s.`, `$v = \\sqrt{\\dfrac{GM}{r}}$ with $r = ${mf(r / 1e6, 3)} \\cdot 10^6$ m gives $v = ${mf(v / 1000, 2)}$ km/s.`)]; },
 () => { const f = R.p([2, 3, 4, 0.5]), F = 1 / (f * f);
   return [T(`Avstanden mellom to legemer blir ${nf(f)} ganger så stor. Hvor mange ganger så stor blir gravitasjonskraften?`, `The distance between two bodies becomes ${nf(f)} times as large. How many times as large does the gravitational force become?`), { n: F, tol: 0.001, u: "" },
     T(`$F \\propto \\dfrac{1}{r^2}$: $\\dfrac{1}{${mf(f)}^2} = ${mf(F, 4)}$.`, `$F \\propto \\dfrac{1}{r^2}$: $\\dfrac{1}{${mf(f)}^2} = ${mf(F, 4)}$.`)]; }
);
// ---- 2: Elektromagnetisme ----
BIQ("VGFY2", 2, [
 ["Hva er kraften på en strømleder i et magnetfelt?", ["$F = IlB$", "$F = qE$", "$F = ma$", "$F = kx$"], "Når lederen står vinkelrett på feltet: $F = IlB$.", "What is the force on a current-carrying wire in a magnetic field?", ["$F = IlB$", "$F = qE$", "$F = ma$", "$F = kx$"], "When the wire is perpendicular to the field: $F = IlB$."],
 ["Når induseres det en spenning i en spole?", ["Når den magnetiske fluksen gjennom spolen endres", "Når det er et konstant magnetfelt", "Bare når spolen er av jern", "Alltid"], "Faradays lov: $\\varepsilon = -N\\dfrac{\\Delta\\Phi}{\\Delta t}$.", "When is a voltage induced in a coil?", ["When the magnetic flux through the coil changes", "When there is a constant magnetic field", "Only when the coil is made of iron", "Always"], "Faraday's law: $\\varepsilon = -N\\dfrac{\\Delta\\Phi}{\\Delta t}$."],
 ["Hva sier Lenz' regel?", ["Den induserte strømmen motvirker endringen som skapte den", "Strømmen går alltid med klokka", "Spenningen er proporsjonal med strømmen", "Magnetfeltet er alltid null"], "Derfor er det et minus i Faradays lov.", "What does Lenz's law say?", ["The induced current opposes the change that caused it", "The current always flows clockwise", "The voltage is proportional to the current", "The magnetic field is always zero"], "That is why there is a minus sign in Faraday's law."],
 ["Et elektron beveger seg vinkelrett på et magnetfelt. Hvilken bane får det?", ["En sirkel", "En rett linje", "En parabel", "Det stopper"], "Magnetkraften står alltid vinkelrett på farten og virker som sentripetalkraft.", "An electron moves perpendicular to a magnetic field. What path does it follow?", ["A circle", "A straight line", "A parabola", "It stops"], "The magnetic force is always perpendicular to the velocity and acts as a centripetal force."],
 ["En leder på 0,5 m fører 4 A vinkelrett på et felt på 0,2 T. Hva er kraften?", { n: 0.4, tol: 0.001, u: "N" }, "$F = IlB = 4 \\cdot 0{,}5 \\cdot 0{,}2 = 0{,}4$ N.", "A 0.5 m wire carries 4 A perpendicular to a 0.2 T field. What is the force?", null, "$F = IlB = 4 \\cdot 0.5 \\cdot 0.2 = 0.4$ N."]
]);
GEN("VGFY2", 2,
 () => { const N = R.p([50, 100, 200, 500]), A = R.p([0.01, 0.02, 0.05]), B1 = R.p([0, 0.1, 0.2]), B2 = B1 + R.p([0.2, 0.4, 0.5]), t = R.p([0.1, 0.2, 0.5]), eps = N * A * (B2 - B1) / t;
   return [T(`En spole med ${N} vindinger og areal ${nf(A)} m² står vinkelrett på et magnetfelt som øker fra ${nf(B1)} T til ${nf(B2)} T på ${nf(t)} s. Hva er den induserte spenningen (tallverdi)?`, `A coil with ${N} turns and area ${nf(A)} m² is perpendicular to a magnetic field that increases from ${nf(B1)} T to ${nf(B2)} T in ${nf(t)} s. What is the induced emf (magnitude)?`), { n: eps, tol: rel(eps, 0.01), u: "V" },
     T(`$\\varepsilon = N\\dfrac{\\Delta\\Phi}{\\Delta t} = ${N}\\cdot\\dfrac{${mf(A)}\\cdot ${mf(B2 - B1)}}{${mf(t)}} = ${mf(eps, 3)}$ V.`, `$\\varepsilon = N\\dfrac{\\Delta\\Phi}{\\Delta t} = ${N}\\cdot\\dfrac{${mf(A)}\\cdot ${mf(B2 - B1)}}{${mf(t)}} = ${mf(eps, 3)}$ V.`)]; },
 () => { const v = R.p([1, 2, 5]) * 1e6, B = R.p([0.001, 0.002, 0.005, 0.01]), r = 9.11e-31 * v / (1.6e-19 * B);
   return [T(`Et elektron med fart $${mf(v / 1e6)} \\cdot 10^6$ m/s kommer vinkelrett inn i et magnetfelt på ${nf(B * 1000)} mT. Hva er radien i banen, i cm? ($m_e = 9{,}11 \\cdot 10^{-31}$ kg)`, `An electron with speed $${mf(v / 1e6)} \\cdot 10^6$ m/s enters a magnetic field of ${nf(B * 1000)} mT perpendicularly. What is the radius of the path, in cm? ($m_e = 9.11 \\cdot 10^{-31}$ kg)`), { n: r * 100, tol: rel(r * 100, 0.01), u: "cm" },
     T(`$qvB = \\dfrac{mv^2}{r}$ gir $r = \\dfrac{mv}{qB} = ${mf(r * 100, 3)}$ cm.`, `$qvB = \\dfrac{mv^2}{r}$ gives $r = \\dfrac{mv}{qB} = ${mf(r * 100, 3)}$ cm.`)]; },
 () => { const l = R.p([0.1, 0.2, 0.5]), v = R.p([2, 5, 10]), B = R.p([0.1, 0.5, 1]), eps = B * l * v;
   return [T(`En metallstang på ${nf(l)} m beveger seg med ${v} m/s vinkelrett på et magnetfelt på ${nf(B)} T. Hva er den induserte spenningen?`, `A ${nf(l)} m metal rod moves at ${v} m/s perpendicular to a ${nf(B)} T magnetic field. What is the induced emf?`), { n: eps, tol: rel(eps, 0.01), u: "V" },
     T(`$\\varepsilon = Blv = ${mf(B)} \\cdot ${mf(l)} \\cdot ${v} = ${mf(eps, 3)}$ V.`, `$\\varepsilon = Blv = ${mf(B)} \\cdot ${mf(l)} \\cdot ${v} = ${mf(eps, 3)}$ V.`)]; }
);
// ---- 3: Kvantefysikk og relativitet ----
BIQ("VGFY2", 3, [
 ["Hva viste den fotoelektriske effekten?", ["At lys kommer i energipakker (fotoner)", "At lys er en bølge", "At elektroner er positive", "At lys har masse"], "Bare frekvensen, ikke intensiteten, bestemmer om elektroner slås løs: $E = hf$.", "What did the photoelectric effect show?", ["That light comes in energy packets (photons)", "That light is a wave", "That electrons are positive", "That light has mass"], "Only the frequency, not the intensity, decides whether electrons are knocked out: $E = hf$."],
 ["Hva skjer med tiden for en klokke som beveger seg svært raskt, sett fra oss?", ["Den går saktere", "Den går fortere", "Den stopper", "Ingenting"], "Tidsdilatasjon: $\\Delta t = \\gamma \\Delta t_0$ med $\\gamma > 1$.", "What happens to time for a clock moving very fast, as seen by us?", ["It runs slower", "It runs faster", "It stops", "Nothing"], "Time dilation: $\\Delta t = \\gamma \\Delta t_0$ with $\\gamma > 1$."],
 ["Hva sier Heisenbergs uskarphetsrelasjon?", ["Posisjon og bevegelsesmengde kan ikke begge bestemmes nøyaktig samtidig", "Alt er tilfeldig", "Elektroner står stille", "Lys er alltid en partikkel"], "$\\Delta x \\Delta p \\ge \\dfrac{h}{4\\pi}$.", "What does Heisenberg's uncertainty principle say?", ["Position and momentum cannot both be determined exactly at the same time", "Everything is random", "Electrons stand still", "Light is always a particle"], "$\\Delta x \\Delta p \\ge \\dfrac{h}{4\\pi}$."],
 ["Hva er de Broglie-bølgelengden?", ["$\\lambda = \\dfrac{h}{p}$", "$\\lambda = \\dfrac{c}{f}$", "$\\lambda = hf$", "$\\lambda = mc^2$"], "Partikler har bølgeegenskaper med bølgelengde $h/(mv)$.", "What is the de Broglie wavelength?", ["$\\lambda = \\dfrac{h}{p}$", "$\\lambda = \\dfrac{c}{f}$", "$\\lambda = hf$", "$\\lambda = mc^2$"], "Particles have wave properties with wavelength $h/(mv)$."],
 ["Hva er $\\gamma$ for $v = 0{,}6c$?", { n: 1.25, tol: 0.001, u: "" }, "$\\gamma = \\dfrac{1}{\\sqrt{1 - 0{,}36}} = \\dfrac{1}{0{,}8} = 1{,}25$.", "What is $\\gamma$ for $v = 0.6c$?", null, "$\\gamma = \\dfrac{1}{\\sqrt{1 - 0.36}} = \\dfrac{1}{0.8} = 1.25$."]
]);
GEN("VGFY2", 3,
 () => { const b = R.p([0.3, 0.5, 0.6, 0.8, 0.9, 0.99]), t0 = R.p([1, 2, 5, 10]), gm = 1 / Math.sqrt(1 - b * b), t = gm * t0;
   return [T(`Et romskip flyr med $${mf(b)}c$. Ombord går det ${t0} år. Hvor lang tid går det på jorda?`, `A spaceship travels at $${mf(b)}c$. On board ${t0} years pass. How much time passes on Earth?`), { n: t, tol: rel(t, 0.01), u: T("år", "years") },
     T(`$\\gamma = \\dfrac{1}{\\sqrt{1 - ${mf(b)}^2}} = ${mf(gm, 3)}$, så $\\Delta t = \\gamma\\Delta t_0 = ${mf(t, 3)}$ år.`, `$\\gamma = \\dfrac{1}{\\sqrt{1 - ${mf(b)}^2}} = ${mf(gm, 3)}$, so $\\Delta t = \\gamma\\Delta t_0 = ${mf(t, 3)}$ years.`)]; },
 () => { const W = R.p([2.1, 2.3, 4.3, 4.7]), lam = R.p([200, 250, 300, 350]), Ef = 1240 / lam, Ek = Ef - W;
   if(Ek <= 0) return [T(`Et foton har bølgelengde ${lam} nm. Hva er energien i eV? (Bruk $hc = 1240$ eV·nm)`, `A photon has wavelength ${lam} nm. What is its energy in eV? (Use $hc = 1240$ eV·nm)`), { n: Ef, tol: 0.01, u: "eV" }, T(`$E = 1240/${lam} = ${mf(Ef, 3)}$ eV.`, `$E = 1240/${lam} = ${mf(Ef, 3)}$ eV.`)];
   return [T(`Lys med bølgelengde ${lam} nm treffer et metall med løsrivningsarbeid ${nf(W)} eV. Hva er største kinetiske energi til elektronene? (Bruk $hc = 1240$ eV·nm)`, `Light with wavelength ${lam} nm hits a metal with work function ${nf(W)} eV. What is the maximum kinetic energy of the electrons? (Use $hc = 1240$ eV·nm)`), { n: Ek, tol: 0.01, u: "eV" },
     T(`$E_f = 1240/${lam} = ${mf(Ef, 3)}$ eV. $E_k = E_f - W = ${mf(Ek, 3)}$ eV.`, `$E_f = 1240/${lam} = ${mf(Ef, 3)}$ eV. $E_k = E_f - W = ${mf(Ek, 3)}$ eV.`)]; },
 () => { const m = R.p([0.001, 0.01, 1]), E = m * 9e16;
   return [T(`Hvor mye energi tilsvarer ${nf(m * 1000)} g masse ($E = mc^2$)? Svar i $10^{13}$ J.`, `How much energy corresponds to ${nf(m * 1000)} g of mass ($E = mc^2$)? Answer in $10^{13}$ J.`), { n: E / 1e13, tol: rel(E / 1e13, 0.01), u: "" },
     T(`$E = mc^2 = ${mf(m)} \\cdot (3 \\cdot 10^8)^2 = ${mf(E / 1e13, 3)} \\cdot 10^{13}$ J.`, `$E = mc^2 = ${mf(m)} \\cdot (3 \\cdot 10^8)^2 = ${mf(E / 1e13, 3)} \\cdot 10^{13}$ J.`)]; }
);
})();
