// ============================================================
//  ØKONOMI OG ADMINISTRASJON – pugge-kort. Format som i drill.js: [id, tagg, spørsmål, svar, [tre gale], forklaring].
// ============================================================
Object.assign(DR_TAGS, { obeg: ["Økonomibegreper", "Business terms"], ofor: ["Økonomiformler", "Business formulas"] });
Object.assign(DR_DECKS, {
  ob: { study: "oko", tags: new Set(["obeg"]), nb: "Pugg: begreper", en: "Flashcards: terms", sym: "📒", short: ["Begreper", "Terms"] },
  of: { study: "oko", tags: new Set(["ofor"]), nb: "Pugg: formler", en: "Flashcards: formulas", sym: "🧮", short: ["Formler", "Formulas"] }
});
DRILL.push(
  // ---------- begreper ----------
  ["ob1", "obeg", ["Hva er dekningsbidrag per enhet?", "What is the contribution margin per unit?"], ["Pris minus variabel kostnad per enhet", "Price minus variable cost per unit"], [["Pris minus faste kostnader", "Price minus fixed costs"], ["Inntekt minus skatt", "Revenue minus tax"], ["Faste kostnader delt på mengde", "Fixed costs divided by quantity"]], ["DB dekker først de faste kostnadene, deretter blir det overskudd.", "The CM first covers fixed costs, then becomes profit."]],
  ["ob2", "obeg", ["Hva er nullpunktet (break-even)?", "What is the break-even point?"], ["Mengden der resultatet er null", "The quantity where profit is zero"], [["Mengden der prisen er null", "The quantity where the price is zero"], ["Mengden der kostnadene er null", "The quantity where costs are zero"], ["Mengden der salget er størst", "The quantity where sales are highest"]], ["Totalt DB = faste kostnader.", "Total CM = fixed costs."]],
  ["ob3", "obeg", ["Hva er forskjellen på utbetaling og kostnad?", "What is the difference between a payment and a cost?"], ["Utbetaling er når pengene går ut, kostnad er verdiforbruket", "A payment is when money leaves, a cost is the use of value"], [["Ingen forskjell", "No difference"], ["Kostnad kommer alltid før utbetaling", "The cost always comes before the payment"], ["Utbetaling gjelder bare lønn", "Payments only concern wages"]], ["En maskin betales i dag, men kostnadsføres over levetiden (avskrivning).", "A machine is paid today but expensed over its lifetime (depreciation)."]],
  ["ob4", "obeg", ["Hva viser balansen?", "What does the balance sheet show?"], ["Eiendeler, egenkapital og gjeld på et tidspunkt", "Assets, equity and liabilities at a point in time"], [["Inntekter og kostnader i en periode", "Revenue and costs over a period"], ["Bare kontantstrømmen", "Only the cash flow"], ["Budsjettet for neste år", "Next year's budget"]], ["Eiendeler = egenkapital + gjeld.", "Assets = equity + liabilities."]],
  ["ob5", "obeg", ["Hva viser resultatregnskapet?", "What does the income statement show?"], ["Inntekter og kostnader i en periode", "Revenue and costs over a period"], [["Eiendeler på en dato", "Assets on a date"], ["Bare gjelden", "Only the debt"], ["Aksjekursen", "The share price"]], ["Inntekter − kostnader = årsresultat.", "Revenue − costs = net profit."]],
  ["ob6", "obeg", ["Hva er likviditet?", "What is liquidity?"], ["Evnen til å betale regninger når de forfaller", "The ability to pay bills when they fall due"], [["Hvor lønnsom bedriften er", "How profitable the firm is"], ["Hvor mye gjeld bedriften har totalt", "How much debt the firm has in total"], ["Hvor mange ansatte bedriften har", "How many employees the firm has"]], ["Et lønnsomt firma kan likevel gå konkurs uten likviditet.", "A profitable firm can still go bankrupt without liquidity."]],
  ["ob7", "obeg", ["Hva er soliditet?", "What is solvency?"], ["Evnen til å tåle tap, målt ved egenkapitalandel", "The ability to absorb losses, measured by the equity ratio"], [["Evnen til å betale regninger i dag", "The ability to pay bills today"], ["Hvor fort varelageret selges", "How fast inventory is sold"], ["Hvor stor omsetningen er", "How big the turnover is"]], ["Høy egenkapitalandel gir god soliditet.", "A high equity ratio means good solvency."]],
  ["ob8", "obeg", ["Hva betyr at etterspørselen er elastisk?", "What does elastic demand mean?"], ["Mengden endrer seg prosentvis mer enn prisen", "Quantity changes by a larger percentage than the price"], [["Prisen endrer seg aldri", "The price never changes"], ["Mengden er alltid konstant", "Quantity is always constant"], ["Etterspørselen øker når prisen øker", "Demand rises when the price rises"]], ["Elastisitet med tallverdi over 1 er elastisk.", "An elasticity with absolute value above 1 is elastic."]],
  ["ob9", "obeg", ["Hva er BNP?", "What is GDP?"], ["Verdien av alle varer og tjenester produsert i et land i et år", "The value of all goods and services produced in a country in a year"], [["Statens samlede gjeld", "Total government debt"], ["Alt landet eksporterer", "Everything the country exports"], ["Summen av alle lønninger", "The sum of all wages"]], ["Realt BNP er justert for prisstigning.", "Real GDP is adjusted for inflation."]],
  ["ob10", "obeg", ["Hva skjer vanligvis når Norges Bank setter opp renten?", "What usually happens when the central bank raises the rate?"], ["Etterspørselen og prisveksten dempes", "Demand and inflation are dampened"], [["Inflasjonen øker", "Inflation rises"], ["Kronen svekkes alltid", "The krone always weakens"], ["Lånene blir billigere", "Loans become cheaper"]], ["Dyrere lån gir mindre forbruk og investering. Kronen styrkes ofte.", "Dearer loans mean less spending and investment. The krone often strengthens."]],
  ["ob11", "obeg", ["Hva kjennetegner monopol?", "What characterises a monopoly?"], ["Én tilbyder uten nære erstatninger", "One seller with no close substitutes"], [["Mange små tilbydere", "Many small sellers"], ["Få store tilbydere", "A few large sellers"], ["Én kjøper", "One buyer"]], ["Få store tilbydere kalles oligopol.", "A few large sellers is called oligopoly."]],
  ["ob12", "obeg", ["Hva er alternativkostnad?", "What is opportunity cost?"], ["Verdien av det beste alternativet du gir opp", "The value of the best alternative you give up"], [["Kostnaden som allerede er betalt", "A cost already paid"], ["Den billigste kostnaden", "The cheapest cost"], ["Kostnaden inkludert mva", "The cost including VAT"]], ["Allerede betalte kostnader er sunk costs og skal ikke påvirke valget.", "Costs already paid are sunk costs and should not affect the choice."]],
  // ---------- formler ----------
  ["of1", "ofor", ["Nullpunktsmengde?", "Break-even quantity?"], ["Faste kostnader / DB per enhet", "Fixed costs / CM per unit"], [["DB per enhet / faste kostnader", "CM per unit / fixed costs"], ["Pris / variabel kostnad", "Price / variable cost"], ["Faste kostnader × pris", "Fixed costs × price"]], ["Eks.: 120 000 / 60 = 2 000 enheter.", "E.g. 120,000 / 60 = 2,000 units."]],
  ["of2", "ofor", ["Sikkerhetsmargin?", "Margin of safety?"], ["(Budsjettert salg − nullpunktsomsetning) / budsjettert salg", "(Budgeted sales − break-even sales) / budgeted sales"], [["Nullpunkt / salg", "Break-even / sales"], ["Salg − kostnader", "Sales − costs"], ["DB / faste kostnader", "CM / fixed costs"]], ["Viser hvor mye salget kan falle før man taper penger.", "Shows how far sales can fall before making a loss."]],
  ["of3", "ofor", ["Lineær avskrivning per år?", "Straight-line depreciation per year?"], ["(Anskaffelseskost − restverdi) / levetid", "(Cost − residual value) / useful life"], [["Anskaffelseskost / restverdi", "Cost / residual value"], ["Restverdi / levetid", "Residual value / useful life"], ["Anskaffelseskost × levetid", "Cost × useful life"]], ["Eks.: (500 000 − 50 000)/5 = 90 000 per år.", "E.g. (500,000 − 50,000)/5 = 90,000 per year."]],
  ["of4", "ofor", ["Saldoavskrivning i år n?", "Declining-balance value after n years?"], ["Saldo = K₀·(1 − p)ⁿ", "Balance = K₀·(1 − p)ⁿ"], [["K₀·(1 + p)ⁿ", "K₀·(1 + p)ⁿ"], ["K₀ − n·p", "K₀ − n·p"], ["K₀/(1 − p)ⁿ", "K₀/(1 − p)ⁿ"]], ["Samme prosent av en stadig lavere saldo.", "The same percentage of an ever-smaller balance."]],
  ["of5", "ofor", ["Totalrentabilitet?", "Return on assets?"], ["(Driftsresultat + finansinntekter) / totalkapital", "(Operating profit + financial income) / total assets"], [["Årsresultat / egenkapital", "Net profit / equity"], ["Gjeld / egenkapital", "Debt / equity"], ["Omløpsmidler / kortsiktig gjeld", "Current assets / current liabilities"]], ["Måler avkastningen på all kapital i bedriften.", "Measures the return on all capital in the firm."]],
  ["of6", "ofor", ["Likviditetsgrad 1?", "Current ratio?"], ["Omløpsmidler / kortsiktig gjeld", "Current assets / current liabilities"], [["Kortsiktig gjeld / omløpsmidler", "Current liabilities / current assets"], ["Egenkapital / totalkapital", "Equity / total assets"], ["Kontanter / lønn", "Cash / wages"]], ["Tommelfingerregel: bør være over 2.", "Rule of thumb: should be above 2."]],
  ["of7", "ofor", ["Egenkapitalandel?", "Equity ratio?"], ["Egenkapital / totalkapital", "Equity / total assets"], [["Gjeld / egenkapital", "Debt / equity"], ["Egenkapital / gjeld", "Equity / debt"], ["Resultat / egenkapital", "Profit / equity"]], ["Måler soliditet.", "Measures solvency."]],
  ["of8", "ofor", ["Nåverdi av beløp K om n år?", "Present value of an amount K in n years?"], ["K / (1 + r)ⁿ", "K / (1 + r)ⁿ"], [["K·(1 + r)ⁿ", "K·(1 + r)ⁿ"], ["K − n·r", "K − n·r"], ["K·r·n", "K·r·n"]], ["Diskontering: penger i dag er mer verdt enn penger senere.", "Discounting: money today is worth more than money later."]],
  ["of9", "ofor", ["Priselastisitet?", "Price elasticity?"], ["Prosentvis endring i mengde / prosentvis endring i pris", "Percentage change in quantity / percentage change in price"], [["Prosentvis endring i pris / prosentvis endring i mengde", "Percentage change in price / percentage change in quantity"], ["Pris / mengde", "Price / quantity"], ["Mengde − pris", "Quantity − price"]], ["Negativ for normale varer.", "Negative for normal goods."]],
  ["of10", "ofor", ["Pris inkl. 25 % mva fra pris eks. mva?", "Price incl. 25% VAT from price excl. VAT?"], ["Pris × 1,25", "Price × 1.25"], [["Pris × 0,75", "Price × 0.75"], ["Pris / 1,25", "Price / 1.25"], ["Pris + 25", "Price + 25"]], ["Motsatt vei: pris inkl. mva / 1,25.", "The other way: price incl. VAT / 1.25."]],
  ["of11", "ofor", ["Grenseinntekt ved maksimalt overskudd?", "Marginal revenue at maximum profit?"], ["Grenseinntekt = grensekostnad", "Marginal revenue = marginal cost"], [["Grenseinntekt = 0", "Marginal revenue = 0"], ["Grenseinntekt = gjennomsnittskostnad", "Marginal revenue = average cost"], ["Grenseinntekt = pris × 2", "Marginal revenue = price × 2"]], ["O'(x) = I'(x) − K'(x) = 0.", "P'(x) = R'(x) − C'(x) = 0."]],
  ["of12", "ofor", ["Realrente (omtrent)?", "Real interest rate (approximately)?"], ["Nominell rente − inflasjon", "Nominal rate − inflation"], [["Nominell rente + inflasjon", "Nominal rate + inflation"], ["Inflasjon − nominell rente", "Inflation − nominal rate"], ["Nominell rente × inflasjon", "Nominal rate × inflation"]], ["Nøyaktig: (1 + r)/(1 + i) − 1.", "Exactly: (1 + r)/(1 + i) − 1."]]
);
