// ============================================================
//  SYKEPLEIE – pugge-kort (flashcards) med repetisjon med økende mellomrom (samme system som grunnbegrepene).
//  Kan øves som flervalg eller som kort som snus. Format som i drill.js: [id, tagg, spørsmål, svar, [tre gale], forklaring].
// ============================================================
Object.assign(DR_TAGS, { sanat: ["Anatomi", "Anatomy"], snorm: ["Normalverdier", "Normal values"], slm: ["Legemidler", "Medicines"], sfork: ["Forkortelser og begreper", "Abbreviations and terms"] });
Object.assign(DR_DECKS, {
  sa: { study: "syk", tags: new Set(["sanat"]), nb: "Pugg: anatomi", en: "Flashcards: anatomy", sym: "🫀", short: ["Anatomi", "Anatomy"] },
  sn: { study: "syk", tags: new Set(["snorm"]), nb: "Pugg: normalverdier", en: "Flashcards: normal values", sym: "📏", short: ["Normalverdier", "Normal values"] },
  sl: { study: "syk", tags: new Set(["slm"]), nb: "Pugg: legemidler", en: "Flashcards: medicines", sym: "💊", short: ["Legemidler", "Medicines"] },
  sk: { study: "syk", tags: new Set(["sfork"]), nb: "Pugg: forkortelser", en: "Flashcards: abbreviations", sym: "🔤", short: ["Forkortelser", "Abbreviations"] }
});
DRILL.push(
  // ---------- anatomi ----------
  ["sa1", "sanat", ["Hvilket kammer pumper blod ut i aorta?", "Which chamber pumps blood into the aorta?"], ["Venstre ventrikkel", "The left ventricle"], [["Høyre ventrikkel", "The right ventricle"], ["Venstre forkammer", "The left atrium"], ["Høyre forkammer", "The right atrium"]], ["Venstre ventrikkel → aortaklaffen → aorta → kroppen.", "Left ventricle → aortic valve → aorta → the body."]],
  ["sa2", "sanat", ["Hvor sitter hjertets pacemaker?", "Where is the heart's pacemaker?"], ["Sinusknuten", "The sinus node"], [["AV-knuten", "The AV node"], ["Aortaklaffen", "The aortic valve"], ["Venstre ventrikkel", "The left ventricle"]], ["Sinusknuten i høyre forkammer setter i gang hvert slag.", "The sinus node in the right atrium starts every beat."]],
  ["sa3", "sanat", ["Hvor skjer gassutvekslingen?", "Where does gas exchange happen?"], ["I alveolene", "In the alveoli"], [["I bronkiene", "In the bronchi"], ["I luftrøret", "In the trachea"], ["I pleura", "In the pleura"]], ["Tynne vegger og mange kapillærer gir rask diffusjon.", "Thin walls and many capillaries give fast diffusion."]],
  ["sa4", "sanat", ["Hvilken klaff ligger mellom høyre forkammer og høyre ventrikkel?", "Which valve lies between the right atrium and right ventricle?"], ["Trikuspidalklaffen", "The tricuspid valve"], [["Mitralklaffen", "The mitral valve"], ["Aortaklaffen", "The aortic valve"], ["Pulmonalklaffen", "The pulmonary valve"]], ["Tri til høyre, mitral til venstre.", "Tri on the right, mitral on the left."]],
  ["sa5", "sanat", ["Hva er nyrens funksjonelle enhet?", "What is the kidney's functional unit?"], ["Nefronet", "The nephron"], [["Alveolen", "The alveolus"], ["Nevronet", "The neuron"], ["Villi", "The villus"]], ["Glomerulus filtrerer, tubuli tar opp igjen.", "The glomerulus filters, the tubules reabsorb."]],
  ["sa6", "sanat", ["Hvilket organ lager galle?", "Which organ makes bile?"], ["Leveren", "The liver"], [["Galleblæren", "The gallbladder"], ["Bukspyttkjertelen", "The pancreas"], ["Milten", "The spleen"]], ["Leveren lager galle, galleblæren lagrer den.", "The liver makes bile, the gallbladder stores it."]],
  ["sa7", "sanat", ["Hva styrer lillehjernen?", "What does the cerebellum control?"], ["Balanse og koordinasjon", "Balance and coordination"], [["Pust og puls", "Breathing and pulse"], ["Språk", "Language"], ["Syn", "Vision"]], ["Pust og puls styres fra hjernestammen.", "Breathing and pulse are controlled from the brainstem."]],
  ["sa8", "sanat", ["Hva er den viktigste inspirasjonsmuskelen?", "What is the main muscle of inspiration?"], ["Diafragma", "The diaphragm"], [["Brystmuskelen", "The pectoral muscle"], ["Magemusklene", "The abdominal muscles"], ["Hjertet", "The heart"]], ["Diafragma trekker seg sammen og senkes, og luft strømmer inn.", "The diaphragm contracts and moves down, and air flows in."]],
  ["sa9", "sanat", ["Hvor tas det meste av næringen opp?", "Where is most nutrition absorbed?"], ["I tynntarmen", "In the small intestine"], [["I magesekken", "In the stomach"], ["I tykktarmen", "In the large intestine"], ["I spiserøret", "In the oesophagus"]], ["Tarmtottene gir en enorm overflate.", "The villi give an enormous surface area."]],
  ["sa10", "sanat", ["Hvilket hormon fra hypofysen øker gjenopptaket av vann i nyrene?", "Which pituitary hormone increases water reabsorption in the kidneys?"], ["ADH", "ADH"], [["Aldosteron", "Aldosterone"], ["Insulin", "Insulin"], ["Kortisol", "Cortisol"]], ["ADH = antidiuretisk hormon. Aldosteron kommer fra binyrene.", "ADH = antidiuretic hormone. Aldosterone comes from the adrenal glands."]],
  ["sa11", "sanat", ["Hvilken effekt har parasympatikus på pulsen?", "What effect does the parasympathetic system have on heart rate?"], ["Senker den", "Lowers it"], [["Øker den", "Raises it"], ["Ingen effekt", "No effect"], ["Gjør den uregelmessig", "Makes it irregular"]], ["Hvile og fordøye: lavere puls, mer tarmaktivitet.", "Rest and digest: lower heart rate, more gut activity."]],
  ["sa12", "sanat", ["Hvilke vitaminer er fettløselige?", "Which vitamins are fat-soluble?"], ["A, D, E og K", "A, D, E and K"], [["B og C", "B and C"], ["Bare C", "Only C"], ["Bare D", "Only D"]], ["Huskeregel: ADEK.", "Mnemonic: ADEK."]],
  // ---------- normalverdier ----------
  ["sn1", "snorm", ["Normal respirasjonsfrekvens (voksen, hvile)?", "Normal respiratory rate (adult, at rest)?"], ["12–20 per minutt", "12–20 per minute"], [["6–10 per minutt", "6–10 per minute"], ["22–30 per minutt", "22–30 per minute"], ["30–40 per minutt", "30–40 per minute"]], ["Høy frekvens er et tidlig varseltegn.", "A high rate is an early warning sign."]],
  ["sn2", "snorm", ["Normal SpO₂ hos lungefrisk voksen?", "Normal SpO₂ in an adult with healthy lungs?"], ["96–100 %", "96–100%"], [["88–92 %", "88–92%"], ["80–85 %", "80–85%"], ["90–94 %", "90–94%"]], ["Lavere mål kan gjelde ved kronisk lungesykdom.", "Lower targets can apply in chronic lung disease."]],
  ["sn3", "snorm", ["Normal hvilepuls hos voksen?", "Normal resting pulse in an adult?"], ["60–100 slag/min", "60–100 beats/min"], [["30–50 slag/min", "30–50 beats/min"], ["110–140 slag/min", "110–140 beats/min"], ["140–180 slag/min", "140–180 beats/min"]], ["I NEWS2 gir 51–90 null poeng.", "In NEWS2, 51–90 scores zero points."]],
  ["sn4", "snorm", ["Normalområde for kalium i blodet?", "Normal range for potassium in the blood?"], ["3,5–5,0 mmol/l", "3.5–5.0 mmol/L"], [["137–145 mmol/l", "137–145 mmol/L"], ["1,0–2,0 mmol/l", "1.0–2.0 mmol/L"], ["8–12 mmol/l", "8–12 mmol/L"]], ["137–145 er natrium.", "137–145 is sodium."]],
  ["sn5", "snorm", ["Normalområde for natrium i blodet?", "Normal range for sodium in the blood?"], ["Omtrent 137–145 mmol/l", "About 137–145 mmol/L"], [["3,5–5,0 mmol/l", "3.5–5.0 mmol/L"], ["100–110 mmol/l", "100–110 mmol/L"], ["160–170 mmol/l", "160–170 mmol/L"]], ["Referanseområdene kan variere litt mellom laboratorier.", "Reference ranges can vary slightly between laboratories."]],
  ["sn6", "snorm", ["Normal kroppstemperatur (0 poeng i NEWS2)?", "Normal body temperature (0 points in NEWS2)?"], ["36,1–38,0 °C", "36.1–38.0 °C"], [["34,0–35,5 °C", "34.0–35.5 °C"], ["38,5–39,5 °C", "38.5–39.5 °C"], ["35,0–36,0 °C", "35.0–36.0 °C"]], ["35,1–36,0 og 38,1–39,0 gir 1 poeng.", "35.1–36.0 and 38.1–39.0 give 1 point."]],
  ["sn7", "snorm", ["Normal fastende blodsukker?", "Normal fasting blood glucose?"], ["Omtrent 4–6 mmol/l", "About 4–6 mmol/L"], [["Omtrent 10–12 mmol/l", "About 10–12 mmol/L"], ["Omtrent 1–2 mmol/l", "About 1–2 mmol/L"], ["Omtrent 15–20 mmol/l", "About 15–20 mmol/L"]], ["Fastende 7,0 eller høyere kan tyde på diabetes.", "Fasting 7.0 or higher may indicate diabetes."]],
  ["sn8", "snorm", ["Minste urinproduksjon før du varsler (voksen)?", "Minimum urine output before reporting (adult)?"], ["Omtrent 0,5 ml/kg/t", "About 0.5 mL/kg/h"], [["Omtrent 5 ml/kg/t", "About 5 mL/kg/h"], ["Omtrent 0,05 ml/kg/t", "About 0.05 mL/kg/h"], ["Omtrent 2 l/t", "About 2 L/h"]], ["70 kg gir omtrent 35 ml per time.", "70 kg gives about 35 mL per hour."]],
  ["sn9", "snorm", ["Normal BMI for voksne?", "Normal BMI for adults?"], ["18,5–24,9", "18.5–24.9"], [["25–29,9", "25–29.9"], ["15–18", "15–18"], ["30–35", "30–35"]], ["Over 70 år: under 22 gir risiko for underernæring.", "Over 70: below 22 means risk of undernutrition."]],
  ["sn10", "snorm", ["NEWS2-sum som krever akutt respons?", "NEWS2 total that requires an emergency response?"], ["7 eller mer", "7 or more"], [["2 eller mer", "2 or more"], ["1 eller mer", "1 or more"], ["12 eller mer", "12 or more"]], ["5–6 haster, 7 eller mer er akutt.", "5–6 is urgent, 7 or more is an emergency."]],
  // ---------- legemidler ----------
  ["sl1", "slm", ["Motgift mot opioider?", "Antidote to opioids?"], ["Nalokson", "Naloxone"], [["Vitamin K", "Vitamin K"], ["Flumazenil", "Flumazenil"], ["Glukagon", "Glucagon"]], ["Nalokson er en opioidantagonist.", "Naloxone is an opioid antagonist."]],
  ["sl2", "slm", ["Motgift mot warfarin?", "Antidote to warfarin?"], ["Vitamin K", "Vitamin K"], [["Nalokson", "Naloxone"], ["Protamin", "Protamine"], ["Adrenalin", "Adrenaline"]], ["Warfarin hemmer vitamin K-avhengige koagulasjonsfaktorer.", "Warfarin inhibits vitamin K-dependent clotting factors."]],
  ["sl3", "slm", ["Hvilken prøve følger warfarin?", "Which test monitors warfarin?"], ["INR", "INR"], [["CRP", "CRP"], ["HbA1c", "HbA1c"], ["Kreatinin", "Creatinine"]], ["INR måler hvor raskt blodet koagulerer.", "INR measures how fast the blood clots."]],
  ["sl4", "slm", ["Viktigste alvorlige bivirkning av opioider?", "Most important serious side effect of opioids?"], ["Respirasjonsdepresjon", "Respiratory depression"], [["Diaré", "Diarrhoea"], ["Hypertensjon", "Hypertension"], ["Høyt blodsukker", "High blood glucose"]], ["Følg respirasjonsfrekvens og bevissthet. Forebygg også forstoppelse.", "Monitor respiratory rate and consciousness. Also prevent constipation."]],
  ["sl5", "slm", ["Vanlig maks døgndose paracetamol (frisk voksen)?", "Usual maximum daily dose of paracetamol (healthy adult)?"], ["4 g", "4 g"], [["1 g", "1 g"], ["8 g", "8 g"], ["400 mg", "400 mg"]], ["Lavere ved lav vekt, høy alder og leversykdom.", "Lower with low weight, old age and liver disease."]],
  ["sl6", "slm", ["Furosemid kan gi lav …?", "Furosemide can cause low …?"], ["Kalium", "Potassium"], [["Glukose", "Glucose"], ["Hemoglobin", "Haemoglobin"], ["Kolesterol", "Cholesterol"]], ["Slyngediuretika øker utskillelsen av kalium.", "Loop diuretics increase potassium excretion."]],
  ["sl7", "slm", ["Viktig bivirkning av NSAIDs (f.eks. ibuprofen)?", "Important side effect of NSAIDs (e.g. ibuprofen)?"], ["Magesår og blødning", "Stomach ulcers and bleeding"], [["Lavt blodsukker", "Low blood glucose"], ["Hårvekst", "Hair growth"], ["Høy puls", "High pulse"]], ["NSAIDs kan også skade nyrene.", "NSAIDs can also damage the kidneys."]],
  ["sl8", "slm", ["Tegn på føling (hypoglykemi)?", "Signs of hypoglycaemia?"], ["Svette, skjelving og forvirring", "Sweating, trembling and confusion"], [["Tørste og mye urin", "Thirst and a lot of urine"], ["Feber og utslett", "Fever and rash"], ["Hoste og slim", "Cough and mucus"]], ["Tørste og mye urin tyder på høyt blodsukker.", "Thirst and a lot of urine suggest high blood glucose."]],
  ["sl9", "slm", ["Hva gir man ved anafylaksi?", "What is given for anaphylaxis?"], ["Adrenalin", "Adrenaline"], [["Paracetamol", "Paracetamol"], ["Nalokson", "Naloxone"], ["Furosemid", "Furosemide"]], ["Adrenalin i muskel (i.m.) er førstevalg.", "Intramuscular (i.m.) adrenaline is first choice."]],
  ["sl10", "slm", ["Betablokkere senker …?", "Beta blockers lower …?"], ["Puls og blodtrykk", "Heart rate and blood pressure"], [["Blodsukker", "Blood glucose"], ["Kalium", "Potassium"], ["Temperatur", "Temperature"]], ["Forsiktighet ved astma.", "Caution in asthma."]],
  // ---------- forkortelser og begreper ----------
  ["sk1", "sfork", ["p.o.", "p.o."], ["Gjennom munnen (per os)", "By mouth (per os)"], [["I en vene", "Into a vein"], ["Under huden", "Under the skin"], ["I en muskel", "Into a muscle"]], ["Latin: per os.", "Latin: per os."]],
  ["sk2", "sfork", ["i.v.", "i.v."], ["I en vene (intravenøst)", "Into a vein (intravenous)"], [["Under huden", "Under the skin"], ["I en muskel", "Into a muscle"], ["Gjennom munnen", "By mouth"]], ["Biotilgjengeligheten er 100 %.", "The bioavailability is 100%."]],
  ["sk3", "sfork", ["s.c.", "s.c."], ["Under huden (subkutant)", "Under the skin (subcutaneous)"], [["Under tungen", "Under the tongue"], ["I en vene", "Into a vein"], ["I en muskel", "Into a muscle"]], ["Insulin og lavmolekylært heparin gis ofte s.c.", "Insulin and low-molecular-weight heparin are often given s.c."]],
  ["sk4", "sfork", ["i.m.", "i.m."], ["I en muskel (intramuskulært)", "Into a muscle (intramuscular)"], [["I en vene", "Into a vein"], ["Under huden", "Under the skin"], ["Gjennom munnen", "By mouth"]], ["Adrenalin ved anafylaksi gis i.m.", "Adrenaline for anaphylaxis is given i.m."]],
  ["sk5", "sfork", ["Hva står ISBAR for?", "What does ISBAR stand for?"], ["Identifikasjon, Situasjon, Bakgrunn, Aktuell vurdering, Råd", "Identify, Situation, Background, Assessment, Recommendation"], [["Innleggelse, Sykdom, Behandling, Akutt, Resept", "Admission, Sickness, Bed, Acute, Recipe"], ["Infeksjon, Smitte, Bakterie, Antibiotika, Resistens", "Infection, Spread, Bacteria, Antibiotics, Resistance"], ["Intravenøs, Subkutan, Bolus, Ampulle, Rate", "Intravenous, Subcutaneous, Bolus, Ampoule, Rate"]], ["En fast rekkefølge for muntlig rapport.", "A fixed order for verbal handover."]],
  ["sk6", "sfork", ["Hva står ABCDE for?", "What does ABCDE stand for?"], ["Airway, Breathing, Circulation, Disability, Exposure", "Airway, Breathing, Circulation, Disability, Exposure"], [["Allergi, Blod, Cirkulasjon, Diagnose, Eksamen", "Allergy, Blood, Circulation, Diagnosis, Exam"], ["Anamnese, Bevissthet, CRP, Diurese, EKG", "History, Consciousness, CRP, Diuresis, ECG"], ["Alder, BMI, Calcium, Diett, Energi", "Age, BMI, Calcium, Diet, Energy"]], ["Undersøk og behandle i denne rekkefølgen.", "Assess and treat in this order."]],
  ["sk7", "sfork", ["Hva betyr hypoglykemi?", "What does hypoglycaemia mean?"], ["Lavt blodsukker", "Low blood glucose"], [["Høyt blodsukker", "High blood glucose"], ["Lavt blodtrykk", "Low blood pressure"], ["Lav temperatur", "Low temperature"]], ["Hypo = under, glyk = sukker, emi = i blodet.", "Hypo = below, glyc = sugar, aemia = in the blood."]],
  ["sk8", "sfork", ["Hva betyr takykardi?", "What does tachycardia mean?"], ["Rask puls", "Fast heart rate"], [["Langsom puls", "Slow heart rate"], ["Rask pust", "Fast breathing"], ["Høyt blodtrykk", "High blood pressure"]], ["Hos voksne: over 100 slag/min. Langsom puls heter bradykardi.", "In adults: over 100 beats/min. A slow heart rate is called bradycardia."]],
  ["sk9", "sfork", ["Hva betyr dyspné?", "What does dyspnoea mean?"], ["Tung pust (pustebesvær)", "Shortness of breath"], [["Svelgvansker", "Difficulty swallowing"], ["Smerte ved vannlating", "Pain on urination"], ["Hodepine", "Headache"]], ["Svelgvansker heter dysfagi.", "Difficulty swallowing is called dysphagia."]],
  ["sk10", "sfork", ["Hva betyr oliguri?", "What does oliguria mean?"], ["Lite urin", "Low urine output"], [["Mye urin", "A lot of urine"], ["Blod i urinen", "Blood in the urine"], ["Smerte ved vannlating", "Pain on urination"]], ["Mye urin heter polyuri. Ingen urin heter anuri.", "A lot of urine is polyuria. No urine is anuria."]],
  ["sk11", "sfork", ["Hva er de fem R-ene?", "What are the five rights?"], ["Pasient, legemiddel, dose, administrasjonsmåte, tidspunkt", "Patient, drug, dose, route, time"], [["Resept, rom, rekkefølge, rapport, risiko", "Prescription, room, order, report, risk"], ["Ro, renhold, respirasjon, reaksjon, respons", "Rest, cleaning, respiration, reaction, response"], ["Rask, rolig, riktig, ryddig, rent", "Quick, calm, correct, tidy, clean"]], ["Riktig pasient, legemiddel, dose, administrasjonsmåte og tidspunkt.", "Right patient, drug, dose, route and time."]]
);
