// ============================================================
//  VIDEREGÅENDE FELLESFAG – pugge-kort (historie, samfunnskunnskap, geografi, religion og etikk, naturfag).
//  Brukes også i Par-jakt, Sant eller usant og dueller. Format: [id, tagg, spørsmål, svar, [tre gale], forklaring].
// ============================================================
Object.assign(DR_TAGS, { vhi: ["Historie", "History"], vsa: ["Samfunnskunnskap", "Social studies"], vge: ["Geografi", "Geography"], vre: ["Religion og etikk", "Religion and ethics"], vna: ["Naturfag", "Natural science"] });
Object.assign(DR_DECKS, {
  vff: { study: "vgs", tags: new Set(["vhi", "vsa", "vge"]), nb: "Pugg: historie og samfunn", en: "Flashcards: history and society", sym: "🏛", short: ["Hist./samf.", "Hist./soc."] },
  vfr: { study: "vgs", tags: new Set(["vre", "vna"]), nb: "Pugg: religion og naturfag", en: "Flashcards: religion and science", sym: "☯", short: ["Rel./natur", "Rel./sci."] }
});
DRILL.push(
  ["vh1", "vhi", ["Når ble Grunnloven vedtatt?", "When was the Constitution adopted?"], ["17. mai 1814", "17 May 1814"], [["7. juni 1905", "7 June 1905"], ["8. mai 1945", "8 May 1945"], ["9. april 1940", "9 April 1940"]], ["På Eidsvoll.", "At Eidsvoll."]],
  ["vh2", "vhi", ["Når ble Norge selvstendig fra Sverige?", "When did Norway become independent of Sweden?"], ["1905", "1905"], [["1814", "1814"], ["1884", "1884"], ["1945", "1945"]], ["Unionen ble oppløst 7. juni 1905.", "The union was dissolved on 7 June 1905."]],
  ["vh3", "vhi", ["Når fikk kvinner stemmerett i Norge?", "When did women get the vote in Norway?"], ["1913", "1913"], [["1898", "1898"], ["1905", "1905"], ["1945", "1945"]], ["Menn fikk allmenn stemmerett i 1898.", "Men got universal suffrage in 1898."]],
  ["vh4", "vhi", ["Når ble Norge angrepet i andre verdenskrig?", "When was Norway invaded in the Second World War?"], ["9. april 1940", "9 April 1940"], [["1. september 1939", "1 September 1939"], ["8. mai 1945", "8 May 1945"], ["22. juni 1941", "22 June 1941"]], ["Okkupert til 8. mai 1945.", "Occupied until 8 May 1945."]],
  ["vh5", "vhi", ["Når falt Berlinmuren?", "When did the Berlin Wall fall?"], ["1989", "1989"], [["1961", "1961"], ["1991", "1991"], ["1945", "1945"]], ["Den ble bygd i 1961.", "It was built in 1961."]],
  ["vh6", "vhi", ["Slaget på Stiklestad?", "The Battle of Stiklestad?"], ["1030", "1030"], [["793", "793"], ["1349", "1349"], ["1397", "1397"]], ["Olav Haraldsson falt.", "Olaf Haraldsson fell."]],
  ["vh7", "vhi", ["Svartedauden kom til Norge?", "The Black Death reached Norway?"], ["1349", "1349"], [["1030", "1030"], ["1537", "1537"], ["1397", "1397"]], ["Kanskje halvparten døde.", "Perhaps half died."]],
  ["vh8", "vhi", ["Hvem startet reformasjonen?", "Who started the Reformation?"], ["Martin Luther (1517)", "Martin Luther (1517)"], [["Napoleon", "Napoleon"], ["Montesquieu", "Montesquieu"], ["Karl Marx", "Karl Marx"]], ["Danmark-Norge ble luthersk i 1537.", "Denmark-Norway became Lutheran in 1537."]],
  ["vh9", "vhi", ["Den franske revolusjonen?", "The French Revolution?"], ["1789", "1789"], [["1776", "1776"], ["1814", "1814"], ["1848", "1848"]], ["Frihet, likhet, brorskap.", "Liberty, equality, fraternity."]],
  ["vh10", "vhi", ["Hvem ledet NS-regimet under krigen?", "Who led the NS regime during the war?"], ["Vidkun Quisling", "Vidkun Quisling"], [["Einar Gerhardsen", "Einar Gerhardsen"], ["Haakon VII", "Haakon VII"], ["Johan Nygaardsvold", "Johan Nygaardsvold"]], ["Henrettet i 1945.", "Executed in 1945."]],
  ["vh11", "vhi", ["Når ble Sametinget opprettet?", "When was the Sami Parliament established?"], ["1989", "1989"], [["1905", "1905"], ["1814", "1814"], ["2012", "2012"]], ["Etter Alta-saken.", "After the Alta controversy."]],
  ["vh12", "vhi", ["Når ble Ekofisk funnet?", "When was Ekofisk discovered?"], ["1969", "1969"], [["1905", "1905"], ["1990", "1990"], ["1945", "1945"]], ["Starten på oljealderen.", "The start of the oil age."]],
  ["vs1", "vsa", ["Antall stortingsrepresentanter?", "Number of members of Parliament?"], ["169", "169"], [["150", "150"], ["120", "120"], ["200", "200"]], ["Valgt hvert fjerde år.", "Elected every four years."]],
  ["vs2", "vsa", ["Hvem har den dømmende makten?", "Who holds the judicial power?"], ["Domstolene", "The courts"], [["Stortinget", "Parliament"], ["Regjeringen", "The government"], ["Kongen", "The King"]], ["Tingrett, lagmannsrett, Høyesterett.", "District court, court of appeal, Supreme Court."]],
  ["vs3", "vsa", ["Faste medlemmer i FNs sikkerhetsråd?", "Permanent members of the UN Security Council?"], ["5", "5"], [["3", "3"], ["10", "10"], ["15", "15"]], ["USA, Russland, Kina, Storbritannia, Frankrike.", "USA, Russia, China, UK, France."]],
  ["vs4", "vsa", ["NATOs artikkel 5?", "NATO's Article 5?"], ["Et angrep på én er et angrep på alle", "An attack on one is an attack on all"], [["Felles valuta", "A common currency"], ["Fri flyt av varer", "Free movement of goods"], ["Felles grunnlov", "A common constitution"]], ["Kollektivt forsvar.", "Collective defence."]],
  ["vs5", "vsa", ["Kriminell lavalder i Norge?", "Age of criminal responsibility in Norway?"], ["15 år", "15"], [["12 år", "12"], ["18 år", "18"], ["16 år", "16"]], ["Straffeloven § 20.", "Penal Code section 20."]],
  ["vs6", "vsa", ["Hva er styringsrenten?", "What is the policy rate?"], ["Renten Norges Bank bruker for å styre prisveksten", "The rate Norges Bank uses to steer inflation"], [["Renten på studielån", "The student loan rate"], ["Skatteprosenten", "The tax rate"], ["Renten på kredittkort", "The credit card rate"]], ["Målet er om lag 2 % inflasjon.", "The target is about 2 % inflation."]],
  ["vs7", "vsa", ["Den fjerde statsmakt?", "The fourth estate?"], ["Pressen", "The press"], [["Kongen", "The King"], ["Kirken", "The church"], ["Politiet", "The police"]], ["Den kontrollerer makthaverne.", "It holds power to account."]],
  ["vg1", "vge", ["Hva måler breddegrader?", "What do latitudes measure?"], ["Avstand nord/sør for ekvator", "Distance north/south of the equator"], [["Avstand øst/vest for Greenwich", "Distance east/west of Greenwich"], ["Høyde over havet", "Height above sea level"], ["Tidssoner", "Time zones"]], ["Fra 0° til 90°.", "From 0° to 90°."]],
  ["vg2", "vge", ["Hva gjør Golfstrømmen for Norge?", "What does the Gulf Stream do for Norway?"], ["Gir mildere klima", "Gives a milder climate"], [["Gir mer snø", "Gives more snow"], ["Gir jordskjelv", "Causes earthquakes"], ["Gir tørke", "Causes drought"]], ["Varmt vann fra sør.", "Warm water from the south."]],
  ["vg3", "vge", ["Plategrensen på Island?", "The plate boundary at Iceland?"], ["Divergent", "Divergent"], [["Konvergent", "Convergent"], ["Transform", "Transform"], ["Ingen", "None"]], ["Platene glir fra hverandre.", "The plates move apart."]],
  ["vg4", "vge", ["Orografisk nedbør?", "Orographic precipitation?"], ["Luft presses opp over fjell og gir regn", "Air forced up over mountains gives rain"], [["Regn fra tordenbyger", "Rain from thunderstorms"], ["Regn ved fronter", "Rain at fronts"], ["Snø fra polene", "Snow from the poles"]], ["Typisk på Vestlandet.", "Typical of western Norway."]],
  ["vg5", "vge", ["Bred bunn i befolkningspyramiden betyr …", "A wide base in a population pyramid means …"], ["Mange barn, ung befolkning", "Many children, young population"], [["Aldrende befolkning", "Ageing population"], ["Høy dødsrate blant barn", "High child mortality only"], ["Mange innvandrere", "Many immigrants"]], ["Typisk tidlig i den demografiske overgangen.", "Typical early in the demographic transition."]],
  ["vg6", "vge", ["Hva er kvikkleire?", "What is quick clay?"], ["Leire som kan bli flytende", "Clay that can liquefy"], [["Vulkansk aske", "Volcanic ash"], ["Tørr sand", "Dry sand"], ["Is i bakken", "Ground ice"]], ["Gjerdrum 2020.", "Gjerdrum 2020."]],
  ["vr1", "vre", ["Islams fem søyler?", "The Five Pillars of Islam?"], ["Shahada, salah, zakat, sawm, hajj", "Shahada, salah, zakat, sawm, hajj"], [["Tora, Talmud, sabbat, kosher, synagoge", "Torah, Talmud, Sabbath, kosher, synagogue"], ["Dåp, nattverd, jul, påske, pinse", "Baptism, communion, Christmas, Easter, Pentecost"], ["Karma, samsara, moksha, atman, Brahman", "Karma, samsara, moksha, atman, Brahman"]], ["Tro, bønn, allmisse, faste og pilegrimsreise.", "Faith, prayer, alms, fasting and pilgrimage."]],
  ["vr2", "vre", ["Treenigheten?", "The Trinity?"], ["Far, Sønn og Hellig Ånd", "Father, Son and Holy Spirit"], [["Brahma, Vishnu og Shiva", "Brahma, Vishnu and Shiva"], ["Abraham, Isak og Jakob", "Abraham, Isaac and Jacob"], ["Tro, håp og kjærlighet", "Faith, hope and love"]], ["Én Gud i tre personer.", "One God in three persons."]],
  ["vr3", "vre", ["Jødedommens hviledag?", "Judaism's day of rest?"], ["Sabbat (fredag kveld–lørdag kveld)", "Sabbath (Friday evening–Saturday evening)"], [["Søndag", "Sunday"], ["Fredag", "Friday"], ["Mandag", "Monday"]], ["Sabbaten.", "The Sabbath."]],
  ["vr4", "vre", ["Hvem grunnla buddhismen?", "Who founded Buddhism?"], ["Siddhartha Gautama", "Siddhartha Gautama"], [["Krishna", "Krishna"], ["Konfucius", "Confucius"], ["Muhammad", "Muhammad"]], ["Buddha betyr «den oppvåknede».", "Buddha means \"the awakened one\"."]],
  ["vr5", "vre", ["Utilitarisme?", "Utilitarianism?"], ["Mest mulig lykke for flest mulig", "The greatest happiness for the greatest number"], [["Følg plikten uansett", "Follow duty regardless"], ["Bli et godt menneske", "Become a good person"], ["Intensjonen teller mest", "Intention matters most"]], ["Bentham og Mill.", "Bentham and Mill."]],
  ["vr6", "vre", ["Det kategoriske imperativ?", "The categorical imperative?"], ["Kant", "Kant"], [["Aristoteles", "Aristotle"], ["Mill", "Mill"], ["Platon", "Plato"]], ["Pliktetikk.", "Duty ethics."]],
  ["vr7", "vre", ["Den gylne middelvei?", "The golden mean?"], ["Aristoteles", "Aristotle"], [["Kant", "Kant"], ["Sokrates", "Socrates"], ["Descartes", "Descartes"]], ["Dydsetikk.", "Virtue ethics."]],
  ["vr8", "vre", ["«Jeg tenker, altså er jeg»?", "\"I think, therefore I am\"?"], ["Descartes", "Descartes"], [["Sokrates", "Socrates"], ["Platon", "Plato"], ["Sartre", "Sartre"]], ["Det eneste han ikke kunne tvile på.", "The one thing he could not doubt."]],
  ["vn1", "vna", ["Alfastråling stoppes av …", "Alpha radiation is stopped by …"], ["Papir", "Paper"], [["Tykt bly", "Thick lead"], ["Ingenting", "Nothing"], ["Betong", "Concrete"]], ["Beta stoppes av aluminium, gamma dempes av bly.", "Beta is stopped by aluminium, gamma weakened by lead."]],
  ["vn2", "vna", ["Største strålekilde i norske hjem?", "Largest radiation source in Norwegian homes?"], ["Radon", "Radon"], [["Mobiltelefoner", "Mobile phones"], ["Wi-Fi", "Wi-Fi"], ["Mikrobølgeovner", "Microwave ovens"]], ["Radioaktiv gass fra berggrunnen.", "Radioactive gas from the bedrock."]],
  ["vn3", "vna", ["Energi i 1 g fett?", "Energy in 1 g of fat?"], ["Om lag 37 kJ", "About 37 kJ"], [["Om lag 17 kJ", "About 17 kJ"], ["Om lag 4 kJ", "About 4 kJ"], ["Om lag 100 kJ", "About 100 kJ"]], ["Karbohydrat og protein: om lag 17 kJ/g.", "Carbohydrate and protein: about 17 kJ/g."]],
  ["vn4", "vna", ["Virker antibiotika mot virus?", "Do antibiotics work against viruses?"], ["Nei", "No"], [["Ja", "Yes"], ["Bare mot influensa", "Only against flu"], ["Bare hos barn", "Only in children"]], ["Bare mot bakterier.", "Only against bacteria."]],
  ["vn5", "vna", ["Norges viktigste strømkilde?", "Norway's main electricity source?"], ["Vannkraft", "Hydropower"], [["Kjernekraft", "Nuclear power"], ["Kullkraft", "Coal power"], ["Solkraft", "Solar power"]], ["Rundt 90 % av strømmen.", "Around 90 % of electricity."]],
  ["vn6", "vna", ["Parisavtalen: mål for oppvarming?", "The Paris Agreement: warming target?"], ["Godt under 2 °C, helst 1,5 °C", "Well below 2 °C, preferably 1.5 °C"], [["Under 5 °C", "Below 5 °C"], ["Ingen oppvarming", "No warming"], ["Under 0,5 °C", "Below 0.5 °C"]], ["Fra 2015.", "From 2015."]]
);
