// ============================================================
//  VIDEREGÅENDE – pugge-kort. Matte- og fysikkortene fra grunnbegrepene brukes også her,
//  og i tillegg kommer egne kort i kjemi og biologi.
// ============================================================
Object.assign(DR_TAGS, { vkj: ["Kjemi", "Chemistry"], vbi: ["Biologi", "Biology"], vma: ["Matte VGS", "Maths (upper secondary)"] });
Object.assign(DR_DECKS, {
  vm: { study: "vgs", tags: new Set([...DR_MATH, "vma"]), nb: "Pugg: matteformler", en: "Flashcards: maths formulas", sym: "∑", short: ["Matte", "Maths"] },
  vf: { study: "vgs", tags: DR_DECKS.f.tags, nb: "Pugg: fysikk", en: "Flashcards: physics", sym: "⚛", short: ["Fysikk", "Physics"] },
  vk: { study: "vgs", tags: new Set(["vkj"]), nb: "Pugg: kjemi", en: "Flashcards: chemistry", sym: "🧪", short: ["Kjemi", "Chemistry"] },
  vb: { study: "vgs", tags: new Set(["vbi"]), nb: "Pugg: biologi", en: "Flashcards: biology", sym: "🧬", short: ["Biologi", "Biology"] }
});
DRILL.push(
  ["vk1", "vkj", ["Hva er kjemisk symbol for natrium?", "What is the chemical symbol for sodium?"], "Na", ["N", "So", "Nt"], ["Fra latin natrium.", "From Latin natrium."]],
  ["vk2", "vkj", ["Hva er kjemisk symbol for kalium?", "What is the chemical symbol for potassium?"], "K", ["P", "Ka", "Po"], ["Fra latin kalium. P er fosfor.", "From Latin kalium. P is phosphorus."]],
  ["vk3", "vkj", ["Hva er kjemisk symbol for jern?", "What is the chemical symbol for iron?"], "Fe", ["I", "Ir", "Jn"], ["Fra latin ferrum.", "From Latin ferrum."]],
  ["vk4", "vkj", ["Hva er Avogadros tall?", "What is Avogadro's number?"], DS`$6{,}02 \cdot 10^{23}$`, [DS`$3{,}00 \cdot 10^{8}$`, DS`$6{,}63 \cdot 10^{-34}$`, DS`$1{,}6 \cdot 10^{-19}$`], ["Antall partikler i 1 mol.", "The number of particles in 1 mole."]],
  ["vk5", "vkj", ["Formel for stoffmengde?", "Formula for amount of substance?"], DS`$n = \dfrac{m}{M}$`, [DS`$n = m \cdot M$`, DS`$n = \dfrac{M}{m}$`, DS`$n = c \cdot m$`], ["Masse delt på molar masse.", "Mass divided by molar mass."]],
  ["vk6", "vkj", ["Definisjonen av pH?", "The definition of pH?"], DS`$-\lg[\text{H}_3\text{O}^+]$`, [DS`$\lg[\text{H}_3\text{O}^+]$`, DS`$-\ln[\text{OH}^-]$`, DS`$[\text{H}_3\text{O}^+]^{-1}$`], ["pH 7 er nøytralt ved 25 °C.", "pH 7 is neutral at 25 °C."]],
  ["vk7", "vkj", ["Hva er oksidasjon?", "What is oxidation?"], ["Tap av elektroner", "Loss of electrons"], [["Opptak av elektroner", "Gain of electrons"], ["Tap av protoner", "Loss of protons"], ["Opptak av nøytroner", "Gain of neutrons"]], ["OIL RIG: oxidation is loss, reduction is gain.", "OIL RIG: oxidation is loss, reduction is gain."]],
  ["vk8", "vkj", ["Bindingstype mellom metall og ikke-metall?", "Bond type between a metal and a non-metal?"], ["Ionebinding", "Ionic bond"], [["Kovalent binding", "Covalent bond"], ["Metallbinding", "Metallic bond"], ["Hydrogenbinding", "Hydrogen bond"]], ["Metallet gir fra seg elektroner til ikke-metallet.", "The metal gives electrons to the non-metal."]],
  ["vk9", "vkj", ["Hva kjennetegner gruppe 18 (edelgassene)?", "What characterises group 18 (the noble gases)?"], ["Fullt ytterskall og lite reaktive", "Full outer shell and not very reactive"], [["Ett valenselektron", "One valence electron"], ["Svært reaktive metaller", "Very reactive metals"], ["Radioaktive", "Radioactive"]], ["Helium, neon, argon …", "Helium, neon, argon …"]],
  ["vk10", "vkj", ["Hva er molar masse for O₂?", "What is the molar mass of O₂?"], ["32,00 g/mol", "32.00 g/mol"], [["16,00 g/mol", "16.00 g/mol"], ["8,00 g/mol", "8.00 g/mol"], ["18,02 g/mol", "18.02 g/mol"]], ["2 · 16,00 = 32,00.", "2 · 16.00 = 32.00."]],
  ["vb1", "vbi", ["Hvor lages ATP i cellen?", "Where is ATP made in the cell?"], ["Mitokondriene", "The mitochondria"], [["Kloroplastene", "The chloroplasts"], ["Ribosomene", "The ribosomes"], ["Cellekjernen", "The nucleus"]], ["Ved celleånding.", "By cellular respiration."]],
  ["vb2", "vbi", ["Likningen for fotosyntese?", "The equation for photosynthesis?"], ["CO₂ + H₂O + lys → glukose + O₂", "CO₂ + H₂O + light → glucose + O₂"], [["Glukose + O₂ → CO₂ + H₂O", "Glucose + O₂ → CO₂ + H₂O"], ["O₂ + lys → CO₂", "O₂ + light → CO₂"], ["N₂ + H₂O → protein", "N₂ + H₂O → protein"]], ["Motsatt av celleånding.", "The opposite of cellular respiration."]],
  ["vb3", "vbi", ["Hvilken base parer med G i DNA?", "Which base pairs with G in DNA?"], "C", ["A", "T", "U"], ["A–T og C–G.", "A–T and C–G."]],
  ["vb4", "vbi", ["Hva gir mitose?", "What does mitosis produce?"], ["To like celler", "Two identical cells"], [["Fire kjønnsceller", "Four sex cells"], ["Én celle med dobbelt DNA", "One cell with double DNA"], ["Celler med halvt kromosomtall", "Cells with half the chromosome number"]], ["Meiose gir kjønnsceller med halvt kromosomtall.", "Meiosis gives sex cells with half the chromosome number."]],
  ["vb5", "vbi", ["Hva er et allel?", "What is an allele?"], ["En variant av et gen", "A variant of a gene"], [["Et kromosom", "A chromosome"], ["Et protein", "A protein"], ["En celletype", "A cell type"]], ["Dominante alleler skjuler recessive.", "Dominant alleles mask recessive ones."]],
  ["vb6", "vbi", ["Transkripsjon er …", "Transcription is …"], ["DNA → mRNA", "DNA → mRNA"], [["mRNA → protein", "mRNA → protein"], ["DNA → DNA", "DNA → DNA"], ["Protein → DNA", "Protein → DNA"]], ["Translasjon er mRNA → protein.", "Translation is mRNA → protein."]],
  ["vb7", "vbi", ["Energioverføring mellom trofiske nivåer?", "Energy transfer between trophic levels?"], ["Omtrent 10 %", "About 10%"], [["Omtrent 50 %", "About 50%"], ["Omtrent 90 %", "About 90%"], ["100 %", "100%"]], ["Resten tapes som varme.", "The rest is lost as heat."]],
  ["vb8", "vbi", ["Hva mangler dyreceller som planteceller har?", "What do animal cells lack that plant cells have?"], ["Cellevegg og kloroplaster", "A cell wall and chloroplasts"], [["Cellekjerne", "A nucleus"], ["Mitokondrier", "Mitochondria"], ["Cellemembran", "A cell membrane"]], ["Plantecellen har også en stor vakuole.", "The plant cell also has a large vacuole."]],
  ["vb9", "vbi", ["Kilden til ny genetisk variasjon?", "The source of new genetic variation?"], ["Mutasjoner", "Mutations"], [["Seleksjon", "Selection"], ["Konkurranse", "Competition"], ["Tilpasning", "Adaptation"]], ["Seleksjonen avgjør hvilke varianter som blir vanlige.", "Selection decides which variants become common."]],
  ["vb10", "vbi", ["Hva er osmose?", "What is osmosis?"], ["Vann som diffunderer gjennom en halvgjennomtrengelig membran", "Water diffusing through a semi-permeable membrane"], [["Aktiv transport av ioner", "Active transport of ions"], ["Celledeling", "Cell division"], ["Nedbrytning av glukose", "Breakdown of glucose"]], ["Vannet går mot høyest konsentrasjon av oppløst stoff.", "Water moves towards the highest concentration of dissolved substance."]]
);

DRILL.push(
  ["vm1", "vma", ["$\\lg(ab) = $ ?", "$\\lg(ab) = $ ?"], DS`$\lg a + \lg b$`, [DS`$\lg a \cdot \lg b$`, DS`$\lg(a + b)$`, DS`$b\lg a$`], ["Logaritmen gjør produkt til sum.", "The logarithm turns a product into a sum."]],
  ["vm2", "vma", ["$\\lg a^n = $ ?", "$\\lg a^n = $ ?"], DS`$n\lg a$`, [DS`$(\lg a)^n$`, DS`$\lg n \cdot a$`, DS`$\lg a + n$`], ["Eksponenten kommer ned foran.", "The exponent comes down in front."]],
  ["vm3", "vma", ["$a^{\\frac{m}{n}} = $ ?", "$a^{\\frac{m}{n}} = $ ?"], DS`$\left(\sqrt[n]{a}\right)^m$`, [DS`$\left(\sqrt[m]{a}\right)^n$`, DS`$\dfrac{a^m}{n}$`, DS`$a^m \cdot a^n$`], ["Nevneren er roten, telleren er potensen.", "The denominator is the root, the numerator the power."]],
  ["vm4", "vma", ["Vekstfaktor ved $p$ % nedgang?", "Growth factor for a $p$ % decrease?"], DS`$1 - \dfrac{p}{100}$`, [DS`$1 + \dfrac{p}{100}$`, DS`$\dfrac{p}{100}$`, DS`$-\dfrac{p}{100}$`], ["7 % nedgang gir 0,93.", "A 7 % decrease gives 0.93."]],
  ["vm5", "vma", ["Restteoremet: resten ved $P(x) : (x - a)$?", "The remainder theorem: the remainder of $P(x) : (x - a)$?"], DS`$P(a)$`, [DS`$P(-a)$`, DS`$P(0)$`, DS`$a$`], ["$P(a) = 0$ betyr at $(x - a)$ er en faktor.", "$P(a) = 0$ means $(x - a)$ is a factor."]],
  ["vm6", "vma", ["Når snur du ulikhetstegnet?", "When do you flip the inequality sign?"], ["Når du ganger eller deler med et negativt tall", "When you multiply or divide by a negative number"], [["Når du legger til et negativt tall", "When you add a negative number"], ["Aldri", "Never"], ["Når du kvadrerer", "When you square"]], ["$-2x > 6 \\Rightarrow x < -3$.", "$-2x > 6 \\Rightarrow x < -3$."]],
  ["vm7", "vma", ["$(\\ln u)' = $ ?", "$(\\ln u)' = $ ?"], DS`$\dfrac{u'}{u}$`, [DS`$\dfrac{1}{u}$`, DS`$u' \ln u$`, DS`$\dfrac{u}{u'}$`], ["Kjerneregelen med $(\\ln x)' = 1/x$.", "The chain rule with $(\\ln x)' = 1/x$."]],
  ["vm8", "vma", ["$(e^{kx})' = $ ?", "$(e^{kx})' = $ ?"], DS`$ke^{kx}$`, [DS`$e^{kx}$`, DS`$kxe^{kx - 1}$`, DS`$\dfrac{e^{kx}}{k}$`], ["Den indre deriverte er $k$.", "The inner derivative is $k$."]],
  ["vm9", "vma", ["Produktregelen?", "The product rule?"], DS`$(uv)' = u'v + uv'$`, [DS`$(uv)' = u'v'$`, DS`$(uv)' = u'v - uv'$`, DS`$(uv)' = \dfrac{u'}{v'}$`], ["Deriver én faktor om gangen.", "Differentiate one factor at a time."]],
  ["vm10", "vma", ["Brøkregelen?", "The quotient rule?"], DS`$\left(\dfrac{u}{v}\right)' = \dfrac{u'v - uv'}{v^2}$`, [DS`$\dfrac{u'v + uv'}{v^2}$`, DS`$\dfrac{u'}{v'}$`, DS`$\dfrac{uv' - u'v}{v^2}$`], ["Minus i telleren, $v^2$ i nevneren.", "Minus in the numerator, $v^2$ in the denominator."]],
  ["vm11", "vma", ["Definisjonen av den deriverte?", "The definition of the derivative?"], DS`$\lim\limits_{h \to 0}\dfrac{f(x + h) - f(x)}{h}$`, [DS`$\lim\limits_{h \to 0}\dfrac{f(h)}{h}$`, DS`$\dfrac{f(b) - f(a)}{b - a}$`, DS`$\lim\limits_{x \to 0} f(x)$`], ["Stigningen til sekanten når $h \\to 0$.", "The slope of the secant as $h \\to 0$."]],
  ["vm12", "vma", ["Farten til $\\vec r(t) = [x(t), y(t)]$?", "The speed of $\\vec r(t) = [x(t), y(t)]$?"], DS`$\sqrt{x'(t)^2 + y'(t)^2}$`, [DS`$x'(t) + y'(t)$`, DS`$\sqrt{x(t)^2 + y(t)^2}$`, DS`$x''(t)$`], ["Lengden av fartsvektoren.", "The length of the velocity vector."]],
  ["vm13", "vma", ["Delvis integrasjon?", "Integration by parts?"], DS`$\int u'v\,dx = uv - \int uv'\,dx$`, [DS`$\int u'v\,dx = u'v' - \int uv\,dx$`, DS`$\int uv\,dx = \int u\,dx \int v\,dx$`, DS`$\int u'v\,dx = uv + \int uv'\,dx$`], ["Baklengs produktregel.", "The product rule backwards."]],
  ["vm14", "vma", ["Omdreiningsvolum om $x$-aksen?", "Volume of revolution about the $x$-axis?"], DS`$\pi\int_a^b f(x)^2\,dx$`, [DS`$2\pi\int_a^b f(x)\,dx$`, DS`$\int_a^b \pi f(x)\,dx$`, DS`$\pi\int_a^b f'(x)^2\,dx$`], ["Summen av sirkelskiver med areal $\\pi f(x)^2$.", "The sum of discs with area $\\pi f(x)^2$."]],
  ["vm15", "vma", ["$1 + 2 + \\dots + n = $ ?", "$1 + 2 + \\dots + n = $ ?"], DS`$\dfrac{n(n + 1)}{2}$`, [DS`$n^2$`, DS`$\dfrac{n(n - 1)}{2}$`, DS`$2^n - 1$`], ["Gauss: 1 til 100 er 5050.", "Gauss: 1 to 100 is 5050."]],
  ["vm16", "vma", ["Sum av en uendelig geometrisk rekke ($|k| < 1$)?", "Sum of an infinite geometric series ($|k| < 1$)?"], DS`$\dfrac{a_1}{1 - k}$`, [DS`$\dfrac{a_1}{k - 1}$`, DS`$a_1 k^n$`, DS`$\dfrac{a_1(k^n - 1)}{k - 1}$`], ["Konvergerer bare når $|k| < 1$.", "Converges only when $|k| < 1$."]],
  ["vm17", "vma", ["Avstand fra punkt til plan $ax + by + cz + d = 0$?", "Distance from a point to the plane $ax + by + cz + d = 0$?"], DS`$\dfrac{|ax_1 + by_1 + cz_1 + d|}{\sqrt{a^2 + b^2 + c^2}}$`, [DS`$|ax_1 + by_1 + cz_1 + d|$`, DS`$\sqrt{a^2 + b^2 + c^2}$`, DS`$\dfrac{ax_1 + by_1 + cz_1}{d}$`], ["Del på lengden av normalvektoren.", "Divide by the length of the normal vector."]],
  ["vm18", "vma", ["Terminbeløp på annuitetslån?", "Instalment on an annuity loan?"], DS`$\dfrac{L \cdot r}{1 - (1 + r)^{-n}}$`, [DS`$\dfrac{L}{n}$`, DS`$L(1 + r)^n$`, DS`$\dfrac{L}{n} + L \cdot r$`], ["Lånet er nåverdien av terminbeløpene.", "The loan is the present value of the instalments."]],
  ["vm19", "vma", ["Binomisk: $P(X = k)$?", "Binomial: $P(X = k)$?"], DS`$\binom{n}{k}p^k(1 - p)^{n - k}$`, [DS`$\binom{n}{k}p^k$`, DS`$p^k(1 - p)^n$`, DS`$n \cdot p^k$`], ["Antall måter ganger sannsynligheten for hver.", "Number of ways times the probability of each."]],
  ["vm20", "vma", ["Standardavvik i binomisk fordeling?", "Standard deviation in the binomial distribution?"], DS`$\sqrt{np(1 - p)}$`, [DS`$np$`, DS`$np(1 - p)$`, DS`$\sqrt{np}$`], ["Forventning $np$, varians $np(1 - p)$.", "Mean $np$, variance $np(1 - p)$."]],
  ["vm21", "vma", ["Andel innenfor $\\mu \\pm 2\\sigma$ i normalfordelingen?", "Share within $\\mu \\pm 2\\sigma$ in the normal distribution?"], ["Omtrent 95 %", "About 95 %"], [["Omtrent 68 %", "About 68 %"], ["Omtrent 99,7 %", "About 99.7 %"], ["Omtrent 50 %", "About 50 %"]], ["68–95–99,7-regelen.", "The 68–95–99.7 rule."]],
  ["vm22", "vma", ["Når forkaster du $H_0$?", "When do you reject $H_0$?"], ["Når p-verdien er mindre enn $\\alpha$", "When the p-value is less than $\\alpha$"], [["Når p-verdien er større enn $\\alpha$", "When the p-value is greater than $\\alpha$"], ["Når $Z = 0$", "When $Z = 0$"], ["Aldri", "Never"]], ["Et usannsynlig resultat under $H_0$ er bevis mot $H_0$.", "An unlikely result under $H_0$ is evidence against $H_0$."]],
  ["vm23", "vma", ["Overskuddet er størst når …", "The profit is largest when …"], DS`$I'(x) = K'(x)$`, [DS`$I(x) = K(x)$`, DS`$K'(x) = 0$`, DS`$I(x) = 0$`], ["Grenseinntekt = grensekostnad.", "Marginal revenue = marginal cost."]],
  ["vm24", "vma", ["Induksjon: de to stegene?", "Induction: the two steps?"], ["Grunnlag og induksjonstrinn", "Base case and induction step"], [["Hypotese og moteksempel", "Hypothesis and counterexample"], ["Derivasjon og integrasjon", "Differentiation and integration"], ["Antakelse og motsigelse", "Assumption and contradiction"]], ["Vis $P(1)$ og $P(k) \\Rightarrow P(k + 1)$.", "Show $P(1)$ and $P(k) \\Rightarrow P(k + 1)$."]]
);
