// ============================================================
//  VIDEREGÅENDE – pugge-kort. Matte- og fysikkortene fra grunnbegrepene brukes også her,
//  og i tillegg kommer egne kort i kjemi og biologi.
// ============================================================
Object.assign(DR_TAGS, { vkj: ["Kjemi", "Chemistry"], vbi: ["Biologi", "Biology"] });
Object.assign(DR_DECKS, {
  vm: { study: "vgs", tags: DR_MATH, nb: "Pugg: matteformler", en: "Flashcards: maths formulas", sym: "∑", short: ["Matte", "Maths"] },
  vf: { study: "vgs", tags: DR_DECKS.f.tags, nb: "Pugg: fysikk", en: "Flashcards: physics", sym: "⚛", short: ["Fysikk", "Physics"] },
  vk: { study: "vgs", tags: new Set(["vkj"]), nb: "Pugg: kjemi", en: "Flashcards: chemistry", sym: "🧪", short: ["Kjemi", "Chemistry"] },
  vb: { study: "vgs", tags: new Set(["vbi"]), nb: "Pugg: biologi", en: "Flashcards: biology", sym: "🧬", short: ["Biologi", "Biology"] }
});
DRILL.push(
  ["vk1", "vkj", ["Hva er kjemisk symbol for natrium?", "What is the chemical symbol for sodium?"], "Na", ["N", "So", "Nt"], ["Fra latin natrium.", "From Latin natrium."]],
  ["vk2", "vkj", ["Hva er kjemisk symbol for kalium?", "What is the chemical symbol for potassium?"], "K", ["P", "Ka", "Po"], ["Fra latin kalium. P er fosfor.", "From Latin kalium. P is phosphorus."]],
  ["vk3", "vkj", ["Hva er kjemisk symbol for jern?", "What is the chemical symbol for iron?"], "Fe", ["I", "Ir", "Jn"], ["Fra latin ferrum.", "From Latin ferrum."]],
  ["vk4", "vkj", ["Hva er Avogadros tall?", "What is Avogadro's number?"], DS`$6{,}02 \cdot 10^{23}$`, [DS`$3{,}00 \cdot 10^{8}$`, DS`$6{,}63 \cdot 10^{-34}$`, DS`$1{,}6 \cdot 10^{-19}$`], ["Antall partikler i 1 mol.", "The number of particles in 1 mole."]],
  ["vk5", "vkj", ["Formel for stoffmengde?", "Formula for amount of substance?"], DS`$n = \dfrac{m}{M}$`, [DS`$n = m \cdot M$`, DS`$n = \dfrac{M}{m}$`, DS`$n = c \cdot m$`], ["Masse delt på molar masse.", "Mass divided by molar mass."]],
  ["vk6", "vkj", ["Definisjonen av pH?", "The definition of pH?"], DS`$-\lg[\text{H}_3\text{O}^+]$`, [DS`$\lg[\text{H}_3\text{O}^+]$`, DS`$-\ln[\text{OH}^-]$`, DS`$[\text{H}_3\text{O}^+]^{-1}$`], ["pH 7 er nøytralt ved 25 °C.", "pH 7 is neutral at 25 °C."]],
  ["vk7", "vkj", ["Hva er oksidasjon?", "What is oxidation?"], ["Tap av elektroner", "Loss of electrons"], [["Opptak av elektroner", "Gain of electrons"], ["Tap av protoner", "Loss of protons"], ["Opptak av nøytroner", "Gain of neutrons"]], ["OIL RIG: oxidation is loss, reduction is gain.", "OIL RIG: oxidation is loss, reduction is gain."]],
  ["vk8", "vkj", ["Bindingstype mellom metall og ikke-metall?", "Bond type between a metal and a non-metal?"], ["Ionebinding", "Ionic bond"], [["Kovalent binding", "Covalent bond"], ["Metallbinding", "Metallic bond"], ["Hydrogenbinding", "Hydrogen bond"]], ["Metallet gir fra seg elektroner til ikke-metallet.", "The metal gives electrons to the non-metal."]],
  ["vk9", "vkj", ["Hva kjennetegner gruppe 18 (edelgassene)?", "What characterises group 18 (the noble gases)?"], ["Fullt ytterskall og lite reaktive", "Full outer shell and not very reactive"], [["Ett valenselektron", "One valence electron"], ["Svært reaktive metaller", "Very reactive metals"], ["Radioaktive", "Radioactive"]], ["Helium, neon, argon …", "Helium, neon, argon …"]],
  ["vk10", "vkj", ["Hva er molar masse for O₂?", "What is the molar mass of O₂?"], ["32,00 g/mol", "32.00 g/mol"], [["16,00 g/mol", "16.00 g/mol"], ["8,00 g/mol", "8.00 g/mol"], ["18,02 g/mol", "18.02 g/mol"]], ["2 · 16,00 = 32,00.", "2 · 16.00 = 32.00."]],
  ["vb1", "vbi", ["Hvor lages ATP i cellen?", "Where is ATP made in the cell?"], ["Mitokondriene", "The mitochondria"], [["Kloroplastene", "The chloroplasts"], ["Ribosomene", "The ribosomes"], ["Cellekjernen", "The nucleus"]], ["Ved celleånding.", "By cellular respiration."]],
  ["vb2", "vbi", ["Likningen for fotosyntese?", "The equation for photosynthesis?"], ["CO₂ + H₂O + lys → glukose + O₂", "CO₂ + H₂O + light → glucose + O₂"], [["Glukose + O₂ → CO₂ + H₂O", "Glucose + O₂ → CO₂ + H₂O"], ["O₂ + lys → CO₂", "O₂ + light → CO₂"], ["N₂ + H₂O → protein", "N₂ + H₂O → protein"]], ["Motsatt av celleånding.", "The opposite of cellular respiration."]],
  ["vb3", "vbi", ["Hvilken base parer med G i DNA?", "Which base pairs with G in DNA?"], "C", ["A", "T", "U"], ["A–T og C–G.", "A–T and C–G."]],
  ["vb4", "vbi", ["Hva gir mitose?", "What does mitosis produce?"], ["To like celler", "Two identical cells"], [["Fire kjønnsceller", "Four sex cells"], ["Én celle med dobbelt DNA", "One cell with double DNA"], ["Celler med halvt kromosomtall", "Cells with half the chromosome number"]], ["Meiose gir kjønnsceller med halvt kromosomtall.", "Meiosis gives sex cells with half the chromosome number."]],
  ["vb5", "vbi", ["Hva er et allel?", "What is an allele?"], ["En variant av et gen", "A variant of a gene"], [["Et kromosom", "A chromosome"], ["Et protein", "A protein"], ["En celletype", "A cell type"]], ["Dominante alleler skjuler recessive.", "Dominant alleles mask recessive ones."]],
  ["vb6", "vbi", ["Transkripsjon er …", "Transcription is …"], ["DNA → mRNA", "DNA → mRNA"], [["mRNA → protein", "mRNA → protein"], ["DNA → DNA", "DNA → DNA"], ["Protein → DNA", "Protein → DNA"]], ["Translasjon er mRNA → protein.", "Translation is mRNA → protein."]],
  ["vb7", "vbi", ["Energioverføring mellom trofiske nivåer?", "Energy transfer between trophic levels?"], ["Omtrent 10 %", "About 10%"], [["Omtrent 50 %", "About 50%"], ["Omtrent 90 %", "About 90%"], ["100 %", "100%"]], ["Resten tapes som varme.", "The rest is lost as heat."]],
  ["vb8", "vbi", ["Hva mangler dyreceller som planteceller har?", "What do animal cells lack that plant cells have?"], ["Cellevegg og kloroplaster", "A cell wall and chloroplasts"], [["Cellekjerne", "A nucleus"], ["Mitokondrier", "Mitochondria"], ["Cellemembran", "A cell membrane"]], ["Plantecellen har også en stor vakuole.", "The plant cell also has a large vacuole."]],
  ["vb9", "vbi", ["Kilden til ny genetisk variasjon?", "The source of new genetic variation?"], ["Mutasjoner", "Mutations"], [["Seleksjon", "Selection"], ["Konkurranse", "Competition"], ["Tilpasning", "Adaptation"]], ["Seleksjonen avgjør hvilke varianter som blir vanlige.", "Selection decides which variants become common."]],
  ["vb10", "vbi", ["Hva er osmose?", "What is osmosis?"], ["Vann som diffunderer gjennom en halvgjennomtrengelig membran", "Water diffusing through a semi-permeable membrane"], [["Aktiv transport av ioner", "Active transport of ions"], ["Celledeling", "Cell division"], ["Nedbrytning av glukose", "Breakdown of glucose"]], ["Vannet går mot høyest konsentrasjon av oppløst stoff.", "Water moves towards the highest concentration of dissolved substance."]]
);
