// ============================================================
//  RETTSVITENSKAP – pugge-kort. Format som i drill.js: [id, tagg, spørsmål, svar, [tre gale], forklaring].
// ============================================================
Object.assign(DR_TAGS, { jpar: ["Paragrafer og frister", "Sections and deadlines"], jbeg: ["Juridiske begreper", "Legal terms"] });
Object.assign(DR_DECKS, {
  jp: { study: "jus", tags: new Set(["jpar"]), nb: "Pugg: paragrafer og frister", en: "Flashcards: sections and deadlines", sym: "§", short: ["Paragrafer", "Sections"] },
  jb: { study: "jus", tags: new Set(["jbeg"]), nb: "Pugg: begreper", en: "Flashcards: terms", sym: "⚖️", short: ["Begreper", "Terms"] }
});
DRILL.push(
  // ---------- paragrafer og frister ----------
  ["jp1", "jpar", ["Klagefrist for enkeltvedtak?", "Appeal deadline for individual decisions?"], ["3 uker (fvl. § 29)", "3 weeks (section 29)"], [["2 uker", "2 weeks"], ["1 måned", "1 month"], ["6 uker", "6 weeks"]], ["Regnes fra vedtaket kom frem.", "Counted from when the decision reached the party."]],
  ["jp2", "jpar", ["Alminnelig foreldelsesfrist?", "General limitation period?"], ["3 år", "3 years"], [["1 år", "1 year"], ["5 år", "5 years"], ["10 år", "10 years"]], ["Foreldelsesloven § 2.", "Limitation Act section 2."]],
  ["jp3", "jpar", ["Ytterste frist for erstatningskrav?", "Longest-stop period for damages?"], ["20 år", "20 years"], [["3 år", "3 years"], ["10 år", "10 years"], ["50 år", "50 years"]], ["Foreldelsesloven § 9.", "Limitation Act section 9."]],
  ["jp4", "jpar", ["Absolutt reklamasjonsfrist for vanlige varer?", "Absolute notice deadline for ordinary goods?"], ["2 år", "2 years"], [["1 år", "1 year"], ["5 år", "5 years"], ["6 måneder", "6 months"]], ["5 år for ting som skal vare vesentlig lenger.", "5 years for things meant to last considerably longer."]],
  ["jp5", "jpar", ["Strafferettslig lavalder?", "Age of criminal responsibility?"], ["15 år", "15"], [["12 år", "12"], ["16 år", "16"], ["18 år", "18"]], ["Straffeloven § 20.", "Penal Code section 20."]],
  ["jp6", "jpar", ["Generalklausulen i avtaleloven?", "The general clause of the Contracts Act?"], ["§ 36", "Section 36"], [["§ 33", "Section 33"], ["§ 1", "Section 1"], ["§ 28", "Section 28"]], ["Urimelige avtaler kan settes til side eller endres.", "Unreasonable contracts can be set aside or modified."]],
  ["jp7", "jpar", ["Nødverge i straffeloven?", "Self-defence in the Penal Code?"], ["§ 18", "Section 18"], [["§ 17", "Section 17"], ["§ 20", "Section 20"], ["§ 15", "Section 15"]], ["§ 17 er nødrett.", "Section 17 is necessity."]],
  ["jp8", "jpar", ["Arbeidsgiveransvaret?", "Employer liability?"], ["Skadeserstatningsloven § 2-1", "Damages Act section 2-1"], [["Straffeloven § 15", "Penal Code section 15"], ["Avtaleloven § 36", "Contracts Act section 36"], ["Forvaltningsloven § 2", "Public Administration Act section 2"]], ["Arbeidsgiveren svarer for ansattes feil i tjenesten.", "The employer answers for employees' faults at work."]],
  ["jp9", "jpar", ["Forbud mot tilbakevirkende lover?", "Ban on retroactive laws?"], ["Grunnloven § 97", "Constitution Article 97"], [["Grunnloven § 100", "Constitution Article 100"], ["Grunnloven § 89", "Constitution Article 89"], ["Grunnloven § 113", "Constitution Article 113"]], ["§ 100 er ytringsfrihet.", "Article 100 is freedom of expression."]],
  ["jp10", "jpar", ["Antall stortingsrepresentanter?", "Number of members of Parliament?"], ["169", "169"], [["150", "150"], ["165", "165"], ["199", "199"]], ["Grunnloven § 57.", "Constitution Article 57."]],
  ["jp11", "jpar", ["Taushetsplikt i forvaltningsloven?", "Confidentiality in the Public Administration Act?"], ["§ 13", "Section 13"], [["§ 18", "Section 18"], ["§ 6", "Section 6"], ["§ 29", "Section 29"]], ["§ 18 er partsinnsyn.", "Section 18 is access for parties."]],
  ["jp12", "jpar", ["Lovhjemmel for straff?", "Legal basis for punishment?"], ["Grunnloven § 96", "Constitution Article 96"], [["Grunnloven § 57", "Constitution Article 57"], ["Straffeloven § 36", "Penal Code section 36"], ["Grunnloven § 121", "Constitution Article 121"]], ["Ingen straff uten lov.", "No punishment without law."]],
  // ---------- begreper ----------
  ["jb1", "jbeg", ["Lex superior?", "Lex superior?"], ["Høyere rettsregel går foran lavere", "A higher-ranking rule prevails over a lower one"], [["Nyere regel går foran eldre", "The newer rule prevails"], ["Spesiell regel går foran generell", "The specific rule prevails"], ["Den milde regelen går foran", "The mildest rule prevails"]], ["Grunnlov > lov > forskrift.", "Constitution > statute > regulation."]],
  ["jb2", "jbeg", ["Lex posterior?", "Lex posterior?"], ["Nyere regel går foran eldre", "The newer rule prevails over the older"], [["Høyere regel går foran", "The higher rule prevails"], ["Spesiell regel går foran", "The specific rule prevails"], ["Eldre regel går foran", "The older rule prevails"]], ["Gjelder regler på samme trinn.", "Applies to rules at the same level."]],
  ["jb3", "jbeg", ["Prejudikat?", "Precedent?"], ["Høyesterettsavgjørelse som følges i like saker", "A Supreme Court decision followed in similar cases"], [["Et lovforslag", "A bill"], ["En forskrift", "A regulation"], ["En tingrettsdom", "A district court judgment"]], ["Plenum og storkammer veier tyngst.", "Plenary and grand chamber decisions weigh most."]],
  ["jb4", "jbeg", ["Enkeltvedtak?", "Individual decision?"], ["Vedtak om rettigheter eller plikter for bestemte personer", "A decision on rights or duties of specific persons"], [["Regler for alle", "Rules for everyone"], ["En dom", "A judgment"], ["En avtale", "An agreement"]], ["Forvaltningsloven § 2 b.", "Public Administration Act section 2 b."]],
  ["jb5", "jbeg", ["Culpa?", "Culpa?"], ["Skyld: forsett eller uaktsomhet", "Fault: intent or negligence"], [["Objektivt ansvar", "Strict liability"], ["Et kontraktsbrudd", "A breach of contract"], ["En straff", "A penalty"]], ["Det vanligste ansvarsgrunnlaget.", "The most common basis of liability."]],
  ["jb6", "jbeg", ["Adekvans?", "Adequacy?"], ["Skaden er en påregnelig følge", "The harm is a foreseeable consequence"], [["Skaden var tilsiktet", "The harm was intended"], ["Skaden er forsikret", "The harm is insured"], ["Skaden er liten", "The harm is small"]], ["Avgrenser ansvaret mot fjerne følger.", "Limits liability for remote consequences."]],
  ["jb7", "jbeg", ["Forelegg?", "Penalty notice?"], ["Tilbud om bot uten rettssak", "An offer of a fine without a trial"], [["En fengselsdom", "A prison sentence"], ["En anke", "An appeal"], ["En klage", "A complaint"]], ["Vedtatt forelegg virker som en dom.", "An accepted notice works like a judgment."]],
  ["jb8", "jbeg", ["Rettskraft?", "Res judicata?"], ["En endelig dom kan ikke prøves på nytt", "A final judgment cannot be tried again"], [["En dom kan alltid ankes", "A judgment can always be appealed"], ["Dommen er skrevet av Høyesterett", "The judgment is by the Supreme Court"], ["Dommen gjelder i ett år", "The judgment lasts a year"]], ["Hindrer ny sak om det samme.", "Prevents a new case on the same matter."]],
  ["jb9", "jbeg", ["Dualisme?", "Dualism?"], ["Traktater må gjennomføres i norsk rett", "Treaties must be implemented in Norwegian law"], [["Traktater gjelder automatisk", "Treaties apply automatically"], ["To parlamenter", "Two parliaments"], ["To domstoler", "Two courts"]], ["Ved inkorporering eller transformasjon.", "By incorporation or transformation."]],
  ["jb10", "jbeg", ["Antitetisk tolkning?", "A contrario reasoning?"], ["Det som ikke er nevnt, faller utenfor", "What is not mentioned falls outside"], [["Regelen brukes på lignende tilfeller", "The rule is applied to similar cases"], ["Ordlyden utvides", "The wording is extended"], ["Den nyeste regelen gjelder", "The newest rule applies"]], ["Motsatsen er analogi.", "The opposite is analogy."]],
  ["jb11", "jbeg", ["Legalitetsprinsippet?", "The principle of legality?"], ["Inngrep overfor borgerne krever hjemmel i lov", "Interference with citizens requires a legal basis"], [["Alle er like for loven", "Everyone is equal before the law"], ["Avtaler skal holdes", "Contracts must be kept"], ["Tvil kommer tiltalte til gode", "Doubt benefits the accused"]], ["Grunnloven § 113.", "Constitution Article 113."]],
  ["jb12", "jbeg", ["Inhabilitet?", "Disqualification?"], ["Saksbehandleren har for nær tilknytning til saken", "The official is too closely connected to the case"], [["Saksbehandleren er syk", "The official is ill"], ["Saken er for gammel", "The case is too old"], ["Parten mangler advokat", "The party has no lawyer"]], ["Forvaltningsloven § 6.", "Public Administration Act section 6."]]
);
