// Teoribok – referanseeksempel: Statikk og dynamikk, enhet 0 (Statikk og likevekt)
TOPICS("MAPE1300", 0, [
{ id: "kraftkomponenter",
  fig: `<svg viewBox="0 0 240 140"><path d="M40 115H210M40 115V15" class="dim"/><path d="M40 115L165 40" class="a"/><path d="M165 40l-14 2 7 11z" class="af"/><path d="M40 115H165" class="d"/><path d="M165 115V40" class="d"/><path d="M78 115a38 38 0 0 0-5-19" class="t"/><text x="96" y="65">F</text><text x="95" y="132">F<tspan dy="4" font-size="10">x</tspan></text><text x="172" y="82">F<tspan dy="4" font-size="10">y</tspan></text><text x="84" y="108">θ</text></svg>`,
  nb: { t: "Kraftkomponenter",
    intro: "En kraft har både størrelse og retning. For å regne med den deler vi den opp i en horisontal og en vertikal del, kalt komponenter. Da kan vi summere krefter i hver retning for seg.",
    f: [["F_x = F\\cos\\theta", "horisontal komponent (θ målt fra x-aksen)"], ["F_y = F\\sin\\theta", "vertikal komponent"], ["F = \\sqrt{F_x^2 + F_y^2}", "størrelsen tilbake fra komponentene"]],
    legend: [["F", "kraftens størrelse", "N"], ["\\theta", "vinkel fra x-aksen", "°"], ["F_x,\\ F_y", "komponenter", "N"]],
    ex: "$F = 200$ N med $\\theta = 30^\\circ$:\n$F_x = 200\\cos 30^\\circ \\approx 173$ N og $F_y = 200\\sin 30^\\circ = 100$ N.",
    tip: "Cosinus hører til siden som ligger inntil vinkelen, sinus til siden rett overfor." },
  en: { t: "Force components",
    intro: "A force has both a magnitude and a direction. To calculate with it we split it into a horizontal and a vertical part, called components. Then we can add up forces in each direction separately.",
    f: [["F_x = F\\cos\\theta", "horizontal component (θ measured from the x-axis)"], ["F_y = F\\sin\\theta", "vertical component"], ["F = \\sqrt{F_x^2 + F_y^2}", "magnitude back from the components"]],
    legend: [["F", "magnitude of the force", "N"], ["\\theta", "angle from the x-axis", "°"], ["F_x,\\ F_y", "components", "N"]],
    ex: "$F = 200$ N at $\\theta = 30^\\circ$:\n$F_x = 200\\cos 30^\\circ \\approx 173$ N and $F_y = 200\\sin 30^\\circ = 100$ N.",
    tip: "Cosine belongs to the side next to the angle, sine to the side opposite it." } },
{ id: "moment",
  fig: `<svg viewBox="0 0 240 140"><circle cx="50" cy="95" r="5" class="af"/><path d="M50 95H190" class="b"/><path d="M190 95V25" class="a"/><path d="M190 95l-6-13h12z" class="af"/><path d="M50 118H190M50 112v12M190 112v12" class="d"/><path d="M78 70a30 30 0 0 1 20 -20" class="t"/><path d="M98 50l-11 1 6 8z" class="tf"/><text x="40" y="83">O</text><text x="200" y="50">F</text><text x="115" y="134">d</text><text x="70" y="43">M</text></svg>`,
  nb: { t: "Moment",
    intro: "Et moment er kraftens evne til å dreie noe rundt et punkt. Jo større kraft og jo lengre arm, desto større dreieeffekt. Armen er den vinkelrette avstanden fra punktet til kraftens virkelinje.",
    f: [["M = F \\cdot d", "moment om et punkt"], ["M = F\\,d\\sin\\alpha", "når kraften ikke står vinkelrett på armen"]],
    legend: [["M", "moment", "Nm"], ["F", "kraft", "N"], ["d", "arm, vinkelrett avstand", "m"], ["\\alpha", "vinkel mellom arm og kraft", "°"]],
    ex: "En skiftenøkkel på 0,25 m med 80 N vinkelrett på enden:\n$M = 80 \\cdot 0{,}25 = 20$ Nm.",
    tip: "Velg fortegn én gang (f.eks. mot klokka = positiv) og hold deg til det gjennom hele oppgaven." },
  en: { t: "Moment",
    intro: "A moment is a force's ability to turn something about a point. The larger the force and the longer the arm, the larger the turning effect. The arm is the perpendicular distance from the point to the force's line of action.",
    f: [["M = F \\cdot d", "moment about a point"], ["M = F\\,d\\sin\\alpha", "when the force is not perpendicular to the arm"]],
    legend: [["M", "moment", "Nm"], ["F", "force", "N"], ["d", "arm, perpendicular distance", "m"], ["\\alpha", "angle between arm and force", "°"]],
    ex: "A 0.25 m wrench with 80 N perpendicular at the end:\n$M = 80 \\cdot 0.25 = 20$ Nm.",
    tip: "Choose a sign convention once (e.g. counterclockwise = positive) and stick to it for the whole problem." } },
{ id: "likevekt",
  fig: `<svg viewBox="0 0 240 140"><path d="M30 70H210" class="b"/><path d="M30 70l-10 18h20z M150 70l-10 18h20z" class="d"/><path d="M110 20V62" class="a"/><path d="M110 70l-6-13h12z" class="af"/><path d="M30 118V78 M150 118V78" class="g"/><path d="M30 78l-6 13h12z M150 78l-6 13h12z" class="gf"/><text x="116" y="30">P</text><text x="10" y="112">A</text><text x="130" y="112">B</text></svg>`,
  nb: { t: "Likevekt",
    intro: "Et legeme som står i ro (eller beveger seg med konstant fart) er i likevekt. Da er summen av alle krefter null i hver retning, og summen av alle momenter om et hvilket som helst punkt er null. I planet gir det tre ligninger.",
    f: [["\\sum F_x = 0", "horisontal likevekt"], ["\\sum F_y = 0", "vertikal likevekt"], ["\\sum M_O = 0", "momentlikevekt om et valgfritt punkt O"]],
    legend: [["\\sum", "summen av", ""], ["O", "valgfritt momentpunkt", ""]],
    ex: "Bjelke på 4 m, last $P = 10$ kN 1 m fra A.\nMoment om A: $B\\cdot 4 = 10\\cdot 1 \\Rightarrow B = 2{,}5$ kN.\nVertikalt: $A = 10 - 2{,}5 = 7{,}5$ kN.",
    tip: "Ta moment om et punkt der en ukjent kraft angriper – da forsvinner den fra ligningen." },
  en: { t: "Equilibrium",
    intro: "A body at rest (or moving at constant velocity) is in equilibrium. Then the sum of all forces is zero in each direction, and the sum of all moments about any point is zero. In the plane this gives three equations.",
    f: [["\\sum F_x = 0", "horizontal equilibrium"], ["\\sum F_y = 0", "vertical equilibrium"], ["\\sum M_O = 0", "moment equilibrium about any point O"]],
    legend: [["\\sum", "the sum of", ""], ["O", "any moment point", ""]],
    ex: "4 m beam, load $P = 10$ kN 1 m from A.\nMoments about A: $B\\cdot 4 = 10\\cdot 1 \\Rightarrow B = 2.5$ kN.\nVertical: $A = 10 - 2.5 = 7.5$ kN.",
    tip: "Take moments about a point where an unknown force acts – it then drops out of the equation." } },
{ id: "opplagre",
  fig: `<svg viewBox="0 0 240 140"><path d="M20 50h50" class="b"/><path d="M45 50l-12 20h24z" class="d"/><path d="M28 76h34" class="d"/><path d="M100 50h50" class="b"/><path d="M125 50l-12 18h24z" class="d"/><circle cx="117" cy="73" r="4" class="d"/><circle cx="133" cy="73" r="4" class="d"/><path d="M185 30v50" class="d"/><path d="M185 30l-8 8M185 42l-8 8M185 54l-8 8M185 66l-8 8M185 78l-8 8" class="d"/><path d="M185 55h40" class="b"/><text x="30" y="110">2</text><text x="120" y="110">1</text><text x="200" y="110">3</text></svg>`,
  nb: { t: "Opplagre og reaksjoner",
    intro: "Et opplager holder konstruksjonen på plass og gir reaksjonskrefter. Hvor mange ukjente det gir, avhenger av hvilke bevegelser det hindrer. Tallene i figuren viser antall ukjente i 2D.",
    f: [["\\text{Rulle: } 1", "én kraft vinkelrett på underlaget"], ["\\text{Fastlager: } 2", "to krefter, $A_x$ og $A_y$"], ["\\text{Innspenning: } 3", "to krefter og ett moment"]],
    legend: [["A_x,\\ A_y", "reaksjonskrefter i opplager A", "N"], ["M_A", "innspenningsmoment", "Nm"]],
    ex: "Fritt opplagt bjelke = fastlager + rulle: $2 + 1 = 3$ ukjente.\nTre likevektsligninger holder akkurat – bjelken er statisk bestemt.",
    tip: "Tegn alltid et frilegemediagram: fjern opplagrene og sett inn reaksjonskreftene i stedet." },
  en: { t: "Supports and reactions",
    intro: "A support holds the structure in place and provides reaction forces. How many unknowns it gives depends on which motions it prevents. The numbers in the figure show the number of unknowns in 2D.",
    f: [["\\text{Roller: } 1", "one force perpendicular to the surface"], ["\\text{Pin: } 2", "two forces, $A_x$ and $A_y$"], ["\\text{Fixed: } 3", "two forces and one moment"]],
    legend: [["A_x,\\ A_y", "reaction forces at support A", "N"], ["M_A", "fixed-end moment", "Nm"]],
    ex: "Simply supported beam = pin + roller: $2 + 1 = 3$ unknowns.\nThree equilibrium equations are exactly enough – the beam is statically determinate.",
    tip: "Always draw a free-body diagram: remove the supports and put the reaction forces in their place." } }
]);
