// ============================================================
//  Emnesider for elementmetoden (FEM): sterk form og energi, Gateaux-deriverte, svak form og masterelementet.
//  Samme notasjon som teorien i add_zdeep_fem.js.
// ============================================================
TOPICS("FEM", 0, [
{ id: "stav-sterk-form",
  fig: `<svg viewBox="0 0 240 140"><path d="M28 40V100" class="dim"/><path d="M20 46l8-6M20 58l8-6M20 70l8-6M20 82l8-6M20 94l8-6" class="dim"/><rect x="28" y="62" width="170" height="16" rx="3" class="d"/><path d="M48 54v8M78 54v8M108 54v8M138 54v8M168 54v8" class="a"/><path d="M60 50H190" class="a"/><path d="M190 50l-8-4v8z" class="af"/><path d="M198 70H228" class="t"/><path d="M228 70l-9-5v10z" class="tf"/><text x="110" y="42">F_x</text><text x="214" y="92">P</text></svg>`,
  nb: { t: "Stavproblemet: sterk form",
    intro: "En stav som er fast i den ene enden og dras i av en fordelt last $F_x$ og en punktlast $P$. Tre sammenhenger gir alt: tøyning $\\varepsilon = u'$, Hookes lov $\\sigma = E\\varepsilon$ og likevekt $N' + F_x = 0$. Sammen gir de differensialligningen med én forskyvningsbetingelse (essensiell) og én kraftbetingelse (naturlig).",
    f: [["-(EA\\,u')' = F_x", "sterk form for $0 < x < L$"], ["u(0) = 0,\\quad EA\\,u'(L) = P", "essensiell og naturlig randbetingelse"], ["N = EA\\,u'", "normalkraft"]],
    legend: [["u", "forskyvning", "m"], ["EA", "aksialstivhet", "N"], ["F_x", "fordelt last", "N/m"], ["P", "punktlast i enden", "N"]],
    ex: "Konstant $EA$, jevn last $q$, punktlast $P$:\n$u(x) = \\frac{1}{EA}\\big((P + qL)x - \\tfrac12 qx^2\\big)$ og $N(x) = P + q(L - x)$.",
    tip: "Forskyvningsbetingelser er essensielle (settes inn i funksjonsrommet). Kraftbetingelser er naturlige (kommer inn via randleddet i svak form)." },
  en: { t: "The bar problem: strong form",
    intro: "A bar fixed at one end and pulled by a distributed load $F_x$ and a point load $P$. Three relations give everything: strain $\\varepsilon = u'$, Hooke's law $\\sigma = E\\varepsilon$ and equilibrium $N' + F_x = 0$. Together they give the differential equation with one displacement condition (essential) and one force condition (natural).",
    f: [["-(EA\\,u')' = F_x", "strong form for $0 < x < L$"], ["u(0) = 0,\\quad EA\\,u'(L) = P", "essential and natural boundary condition"], ["N = EA\\,u'", "normal force"]],
    legend: [["u", "displacement", "m"], ["EA", "axial stiffness", "N"], ["F_x", "distributed load", "N/m"], ["P", "point load at the end", "N"]],
    ex: "Constant $EA$, uniform load $q$, point load $P$:\n$u(x) = \\frac{1}{EA}\\big((P + qL)x - \\tfrac12 qx^2\\big)$ and $N(x) = P + q(L - x)$.",
    tip: "Displacement conditions are essential (built into the function space). Force conditions are natural (enter through the boundary term in the weak form)." } },
{ id: "potensiell-energi",
  fig: `<svg viewBox="0 0 240 140"><path d="M30 118H214" class="dim"/><path d="M34 30Q120 190 206 30" class="a"/><circle cx="120" cy="110" r="5" class="af"/><text x="128" y="104">min Π</text><text x="40" y="26">Π</text></svg>`,
  nb: { t: "Total potensiell energi",
    intro: "Staven velger forskyvningen som gjør den totale potensielle energien minst. Energien er tøyningsenergien minus arbeidet lastene kan gjøre. Med $L^2$-indreproduktet $(f, g) = \\int_0^L fg\\,dx$ blir uttrykket kort.",
    f: [["\\Pi(u) = \\tfrac12\\int_0^L EA(u')^2dx - \\int_0^L F_x\\,u\\,dx - P\\,u(L)", "total potensiell energi"], ["\\Pi(u) = \\tfrac12 B(u, u) - F(u)", "kort form"]],
    legend: [["\\Pi", "total potensiell energi", "J"], ["B(u, u)", "to ganger tøyningsenergien", "J"], ["F(u)", "lastenes arbeid", "J"]],
    ex: "En fjær med stivhet $k$ og kraft $F$: $\\Pi(u) = \\tfrac12 ku^2 - Fu$. Minimum der $\\Pi'(u) = ku - F = 0$, altså $u = F/k$. Staven er den samme ideen med integraler.",
    tip: "Minimum av $\\Pi$ finner du med Gateaux-deriverte: $\\delta\\Pi(u, v) = 0$ for alle tillatte $v$." },
  en: { t: "Total potential energy",
    intro: "The bar chooses the displacement that makes the total potential energy smallest. The energy is the strain energy minus the work the loads can do. With the $L^2$ inner product $(f, g) = \\int_0^L fg\\,dx$ the expression is short.",
    f: [["\\Pi(u) = \\tfrac12\\int_0^L EA(u')^2dx - \\int_0^L F_x\\,u\\,dx - P\\,u(L)", "total potential energy"], ["\\Pi(u) = \\tfrac12 B(u, u) - F(u)", "short form"]],
    legend: [["\\Pi", "total potential energy", "J"], ["B(u, u)", "twice the strain energy", "J"], ["F(u)", "work of the loads", "J"]],
    ex: "A spring with stiffness $k$ and force $F$: $\\Pi(u) = \\tfrac12 ku^2 - Fu$. Minimum where $\\Pi'(u) = ku - F = 0$, so $u = F/k$. The bar is the same idea with integrals.",
    tip: "You find the minimum of $\\Pi$ with the Gateaux derivative: $\\delta\\Pi(u, v) = 0$ for all admissible $v$." } },
{ id: "lastvektor",
  fig: `<svg viewBox="0 0 240 140"><path d="M30 100H210" class="d"/><circle cx="30" cy="100" r="5" class="af"/><circle cx="210" cy="100" r="5" class="af"/><path d="M30 40L210 70" class="dim"/><path d="M60 45v45M100 52v38M140 58v32M180 65v25" class="dim"/><path d="M30 60v30M210 74v16" class="a"/><path d="M30 94l-4-8h8zM210 94l-4-8h8z" class="af"/><text x="18" y="34">q₁</text><text x="200" y="62">q₂</text></svg>`,
  nb: { t: "Konsistent lastvektor",
    intro: "En fordelt last må gjøres om til krefter i nodene. Den riktige (konsistente) måten er å vekte lasten med formfunksjonene: $F^e_i = \\int F_x\\,\\varphi_i\\,dx$. Da gjør nodekreftene det samme arbeidet som den fordelte lasten for alle forskyvninger elementet kan ha.",
    f: [["F^e = \\frac{qh}{2}\\begin{pmatrix}1\\\\ 1\\end{pmatrix}", "jevn last, lineært element"], ["F^e = \\frac{h}{6}\\begin{pmatrix}2q_1 + q_2\\\\ q_1 + 2q_2\\end{pmatrix}", "lineært varierende last"], ["F^e = qh\\begin{pmatrix}1/6\\\\ 2/3\\\\ 1/6\\end{pmatrix}", "jevn last, kvadratisk element"]],
    legend: [["q", "fordelt last", "N/m"], ["h", "elementlengde", "m"], ["F^e_i", "nodekraft", "N"]],
    ex: "Last fra $q_1 = 0$ til $q_2 = 6$ kN/m over $h = 3$ m:\n$F^e = \\frac36(0 + 6,\\ 0 + 12) = (3,\\ 6)$ kN. Summen $9$ kN er hele lasten $\\tfrac12\\cdot 6\\cdot 3$.",
    tip: "Kontroll: summen av nodekreftene skal alltid være lik hele lasten på elementet." },
  en: { t: "Consistent load vector",
    intro: "A distributed load must be turned into forces at the nodes. The correct (consistent) way is to weight the load with the shape functions: $F^e_i = \\int F_x\\,\\varphi_i\\,dx$. Then the nodal forces do the same work as the distributed load for every displacement the element can have.",
    f: [["F^e = \\frac{qh}{2}\\begin{pmatrix}1\\\\ 1\\end{pmatrix}", "uniform load, linear element"], ["F^e = \\frac{h}{6}\\begin{pmatrix}2q_1 + q_2\\\\ q_1 + 2q_2\\end{pmatrix}", "linearly varying load"], ["F^e = qh\\begin{pmatrix}1/6\\\\ 2/3\\\\ 1/6\\end{pmatrix}", "uniform load, quadratic element"]],
    legend: [["q", "distributed load", "N/m"], ["h", "element length", "m"], ["F^e_i", "nodal force", "N"]],
    ex: "Load from $q_1 = 0$ to $q_2 = 6$ kN/m over $h = 3$ m:\n$F^e = \\frac36(0 + 6,\\ 0 + 12) = (3,\\ 6)$ kN. The sum $9$ kN is the whole load $\\tfrac12\\cdot 6\\cdot 3$.",
    tip: "Check: the sum of the nodal forces must always equal the whole load on the element." } }
]);
TOPICS("FEM", 1, [
{ id: "gateaux",
  fig: `<svg viewBox="0 0 240 140"><path d="M24 116H220" class="dim"/><path d="M30 104C80 40 150 40 210 60" class="a"/><path d="M30 104C80 70 150 70 210 90" class="t"/><path d="M120 52V78" class="d"/><path d="M120 78l-4-8h8z" class="af"/><text x="126" y="70">θv</text><text x="200" y="54">u</text><text x="196" y="104">u+θv</text></svg>`,
  nb: { t: "Gateaux-deriverte",
    intro: "Den deriverte for funksjonaler: hvor mye endrer energien $\\Pi$ seg når vi dytter hele forskyvningsfunksjonen $u$ et lite stykke $\\theta$ i retningen $v$? Gang ut $\\Pi(u + \\theta v)$, ta leddet som er proporsjonalt med $\\theta$ – det er $\\delta\\Pi(u, v)$.",
    f: [["\\delta\\Pi(u, v) = \\lim_{\\theta\\to0}\\frac{\\Pi(u + \\theta v) - \\Pi(u)}{\\theta}", "definisjon"], ["\\delta\\Pi(u, v) = \\int_0^L EA\\,u'v'\\,dx - \\int_0^L F_x\\,v\\,dx - P\\,v(L)", "for staven"]],
    legend: [["u", "punktet (forskyvningen) vi deriverer i", ""], ["v", "retningen (variasjon, testfunksjon), $v(0) = 0$", ""], ["\\theta", "lite tall", ""]],
    ex: "$\\Pi(u) = \\int_0^1(\\tfrac12(u')^2 - u)\\,dx$.\nLeddet med $\\theta$ i $\\Pi(u + \\theta v)$ er $\\theta\\int_0^1(u'v' - v)\\,dx$.\nAltså er $\\delta\\Pi(u, v) = \\int_0^1(u'v' - v)\\,dx$.",
    tip: "Snarvei: $\\delta\\Pi(u, v) = \\frac{d}{d\\theta}\\Pi(u + \\theta v)$ i $\\theta = 0$. Deriver under integraltegnet." },
  en: { t: "The Gateaux derivative",
    intro: "The derivative for functionals: how much does the energy $\\Pi$ change when we nudge the whole displacement function $u$ a small step $\\theta$ in the direction $v$? Expand $\\Pi(u + \\theta v)$ and take the term proportional to $\\theta$ – that is $\\delta\\Pi(u, v)$.",
    f: [["\\delta\\Pi(u, v) = \\lim_{\\theta\\to0}\\frac{\\Pi(u + \\theta v) - \\Pi(u)}{\\theta}", "definition"], ["\\delta\\Pi(u, v) = \\int_0^L EA\\,u'v'\\,dx - \\int_0^L F_x\\,v\\,dx - P\\,v(L)", "for the bar"]],
    legend: [["u", "the point (displacement) we differentiate at", ""], ["v", "the direction (variation, test function), $v(0) = 0$", ""], ["\\theta", "small number", ""]],
    ex: "$\\Pi(u) = \\int_0^1(\\tfrac12(u')^2 - u)\\,dx$.\nThe term with $\\theta$ in $\\Pi(u + \\theta v)$ is $\\theta\\int_0^1(u'v' - v)\\,dx$.\nSo $\\delta\\Pi(u, v) = \\int_0^1(u'v' - v)\\,dx$.",
    tip: "Shortcut: $\\delta\\Pi(u, v) = \\frac{d}{d\\theta}\\Pi(u + \\theta v)$ at $\\theta = 0$. Differentiate under the integral sign." } },
{ id: "svak-form-stav",
  fig: `<svg viewBox="0 0 240 140"><rect x="20" y="30" width="80" height="44" rx="8" class="d"/><rect x="140" y="30" width="80" height="44" rx="8" class="a"/><path d="M104 52H132" class="a"/><path d="M136 52l-9-5v10z" class="af"/><text x="50" y="58">u″</text><text x="168" y="58">u′v′</text><text x="108" y="100">∫v</text></svg>`,
  nb: { t: "Svak form for staven",
    intro: "Den svake formen sier at energien ikke endrer seg i noen tillatt retning. Den får du enten fra $\\delta\\Pi(u, v) = 0$, eller ved å gange den sterke formen med en testfunksjon $v$ og delvis integrere. Kraftbetingelsen i enden kommer da inn av seg selv.",
    f: [["B(u, v) = F(v)\\quad \\text{for alle } v,\\ v(0) = 0", "svak form"], ["B(u, v) = \\int_0^L EA\\,u'v'\\,dx", "bilineær form"], ["F(v) = \\int_0^L F_x\\,v\\,dx + P\\,v(L)", "lineær form"]],
    legend: [["B", "symmetrisk, bilineær", ""], ["F", "lineær (lastene)", ""], ["v", "testfunksjon", ""]],
    ex: "Delvis integrasjon: $\\int_0^L -(EAu')'v\\,dx = \\int_0^L EAu'v'\\,dx - [EAu'v]_0^L$. Med $v(0) = 0$ og $EAu'(L) = P$ blir randleddet $P\\,v(L)$.",
    tip: "Svak form krever bare førstederiverte – derfor holder stykkevis lineære funksjoner." },
  en: { t: "The weak form for the bar",
    intro: "The weak form says the energy does not change in any admissible direction. You get it either from $\\delta\\Pi(u, v) = 0$, or by multiplying the strong form by a test function $v$ and integrating by parts. The force condition at the end then appears by itself.",
    f: [["B(u, v) = F(v)\\quad \\text{for all } v,\\ v(0) = 0", "weak form"], ["B(u, v) = \\int_0^L EA\\,u'v'\\,dx", "bilinear form"], ["F(v) = \\int_0^L F_x\\,v\\,dx + P\\,v(L)", "linear form"]],
    legend: [["B", "symmetric, bilinear", ""], ["F", "linear (the loads)", ""], ["v", "test function", ""]],
    ex: "Integration by parts: $\\int_0^L -(EAu')'v\\,dx = \\int_0^L EAu'v'\\,dx - [EAu'v]_0^L$. With $v(0) = 0$ and $EAu'(L) = P$ the boundary term becomes $P\\,v(L)$.",
    tip: "The weak form only needs first derivatives – that is why piecewise linear functions are enough." } },
{ id: "masterelement",
  fig: `<svg viewBox="0 0 240 140"><path d="M30 40H110" class="a"/><circle cx="30" cy="40" r="4" class="af"/><circle cx="110" cy="40" r="4" class="af"/><text x="22" y="28">−1</text><text x="104" y="28">1</text><text x="62" y="58">ξ</text><path d="M120 54L150 84" class="d"/><path d="M150 84l-9-2 6-6z" class="af"/><path d="M110 100H220" class="t"/><circle cx="110" cy="100" r="4" class="tf"/><circle cx="220" cy="100" r="4" class="tf"/><text x="104" y="122">x₁</text><text x="212" y="122">x₂</text></svg>`,
  nb: { t: "Masterelement og Jacobian",
    intro: "Alle elementer regnes på samme masterelement $\\xi\\in[-1, 1]$ og avbildes til det fysiske elementet. Jacobianen $J$ er hvor mye elementet strekkes. Integraler får faktoren $J$, deriverte deles på $J$.",
    f: [["\\varphi_1 = \\frac{1 - \\xi}{2},\\quad \\varphi_2 = \\frac{1 + \\xi}{2}", "lineære formfunksjoner"], ["x(\\xi) = x_1\\varphi_1 + x_2\\varphi_2,\\quad J = \\frac{h}{2}", "avbildning og Jacobian"], ["B^e_{ij} = \\int_{-1}^{1} EA\\,\\frac{d\\varphi_i}{d\\xi}\\frac{d\\varphi_j}{d\\xi}\\frac{1}{J}\\,d\\xi", "elementmatrise"], ["F^e_i = \\int_{-1}^{1} F_x\\,\\varphi_i\\,J\\,d\\xi", "elementvektor"]],
    legend: [["\\xi", "koordinat på masterelementet", ""], ["J", "Jacobian $dx/d\\xi$", "m"], ["h", "elementlengde", "m"]],
    ex: "$h = 2$ m, $EA = 600$ kN: $J = 1$, $\\frac{d\\varphi_1}{d\\xi} = -\\tfrac12$, så $B^e_{11} = \\int_{-1}^{1} 600\\cdot\\tfrac14\\,d\\xi = 300$ kN/m $= EA/h$.",
    tip: "Kjerneregelen: $\\frac{d\\varphi}{dx} = \\frac1J\\frac{d\\varphi}{d\\xi}$. Glemmer du $J$, blir stivheten feil med en faktor $h/2$." },
  en: { t: "Master element and Jacobian",
    intro: "All elements are computed on the same master element $\\xi\\in[-1, 1]$ and mapped to the physical element. The Jacobian $J$ is how much the element is stretched. Integrals get the factor $J$, derivatives are divided by $J$.",
    f: [["\\varphi_1 = \\frac{1 - \\xi}{2},\\quad \\varphi_2 = \\frac{1 + \\xi}{2}", "linear shape functions"], ["x(\\xi) = x_1\\varphi_1 + x_2\\varphi_2,\\quad J = \\frac{h}{2}", "mapping and Jacobian"], ["B^e_{ij} = \\int_{-1}^{1} EA\\,\\frac{d\\varphi_i}{d\\xi}\\frac{d\\varphi_j}{d\\xi}\\frac{1}{J}\\,d\\xi", "element matrix"], ["F^e_i = \\int_{-1}^{1} F_x\\,\\varphi_i\\,J\\,d\\xi", "element vector"]],
    legend: [["\\xi", "coordinate on the master element", ""], ["J", "Jacobian $dx/d\\xi$", "m"], ["h", "element length", "m"]],
    ex: "$h = 2$ m, $EA = 600$ kN: $J = 1$, $\\frac{d\\varphi_1}{d\\xi} = -\\tfrac12$, so $B^e_{11} = \\int_{-1}^{1} 600\\cdot\\tfrac14\\,d\\xi = 300$ kN/m $= EA/h$.",
    tip: "Chain rule: $\\frac{d\\varphi}{dx} = \\frac1J\\frac{d\\varphi}{d\\xi}$. Forget $J$ and the stiffness is off by a factor $h/2$." } }
]);
