// ============================================================
//  Teoribok – Førerkort bil (FKB). Korte oppslagssider til teoriprøven, også som åpne nettsider (tools/seo.js).
//  MC deler disse enhetene (SHAREUNIT i add_forer.js).
// ============================================================

// ================= FKB – enhet 0: Vikeplikt og forkjørsrett =================
TOPICS("FKB", 0, [
{ id: "hoyreregelen", pic: "hoyreregelen",
  nb: { t: "Høyreregelen",
    intro: "I kryss uten skilt, oppmerking eller lys har du vikeplikt for kjørende som kommer fra høyre. Regelen gjelder uansett hvor bred vegen er eller hvilket vegdekke den har, og den gjelder også syklister i kjørebanen. Unntaket er den som kjører ut fra en avkjørsel, for eksempel en parkeringsplass eller gårdsplass. Den har alltid vikeplikt for all trafikk.",
    ex: "Tre biler kommer samtidig til et kryss uten skilt: én fra høyre for deg, én fra venstre.\nDen fra høyre har ingen på sin høyre side og kjører først. Så kjører du. Den fra venstre har deg på sin høyre side og kjører sist.",
    tip: "Se alltid til høyre først i kryss uten skilt, og husk at T-kryss også er kryss." },
  en: { t: "The right-hand rule",
    intro: "At junctions without signs, markings or lights you must give way to traffic coming from the right. The rule applies whatever the width or surface of the road, and it also applies to cyclists in the carriageway. The exception is anyone leaving a private exit such as a car park or driveway: they must always give way to all traffic.",
    ex: "Three cars arrive together at a junction without signs: one from your right, one from your left.\nThe one from the right has nobody on its right and goes first. Then you go. The one from the left has you on its right and goes last.",
    tip: "Always look right first at junctions without signs, and remember that T-junctions are junctions too." } },
{ id: "hvem-bestemmer", pic: "hvem-bestemmer",
  nb: { t: "Hva gjelder foran hva?",
    intro: "Når flere signaler gir ulik beskjed, følger du en fast rekkefølge. Tegn fra politiet går foran alt. Deretter kommer trafikklys, så skilt, så oppmerking og til slutt de generelle trafikkreglene som høyreregelen. Er trafikklyset slått av eller blinker gult, gjelder skiltene igjen.",
    ex: "Lyset viser grønt, men det står et vikepliktskilt ved krysset. Lyset går foran skiltet, så du kan kjøre.\nBlinker lyset gult, gjelder vikepliktskiltet.",
    tip: "Grønt lys betyr at du kan kjøre, ikke at du har forkjørsrett. Venstresvingende viker fortsatt for møtende." },
  en: { t: "What overrides what?",
    intro: "When signals disagree, follow a fixed order. Police signals override everything. Then come traffic lights, then signs, then road markings, and finally the general rules such as the right-hand rule. If the traffic light is off or flashing amber, the signs apply again.",
    ex: "The light is green, but there is a give-way sign at the junction. The light overrides the sign, so you may go.\nIf the light flashes amber, the give-way sign applies.",
    tip: "Green means you may go, not that you have priority. Turning left, you still give way to oncoming traffic." } },
{ id: "venstresving-gaaende", pic: "venstresving-gaaende",
  nb: { t: "Når du svinger",
    intro: "Den som svinger til venstre, har vikeplikt for møtende trafikk, også møtende som svinger til høyre inn i samme veg. Når du svinger, har du dessuten vikeplikt for gående som krysser vegen du svinger inn på, selv om det ikke er gangfelt der. Se etter syklister i blindsonen før du svinger til høyre.",
    ex: "Du skal til høyre, og en fotgjenger går over vegen du svinger inn på.\nDu venter til fotgjengeren er over, selv om det ikke er gangfelt.",
    tip: "Vent midt i krysset med hjulene rett fram når du skal til venstre. Blir du påkjørt bakfra, skyves du da ikke ut foran møtende." },
  en: { t: "When you turn",
    intro: "Whoever turns left must give way to oncoming traffic, including oncoming traffic turning right into the same road. When you turn, you must also give way to pedestrians crossing the road you turn into, even without a crossing. Check for cyclists in the blind spot before turning right.",
    ex: "You are turning right, and a pedestrian is crossing the road you turn into.\nYou wait until the pedestrian is across, even without a crossing.",
    tip: "Wait in the junction with your wheels straight when turning left. If hit from behind, you are not pushed into oncoming traffic." } },
]);

// ================= FKB – enhet 1: Skilt og vegoppmerking =================
TOPICS("FKB", 1, [
{ id: "skiltgrupper", pic: "skiltgrupper",
  nb: { t: "Skiltgruppene",
    intro: "Skiltene er delt i grupper du kjenner igjen på formen og fargen. Fareskilt er trekanter med rød kant og spissen opp. Forbudsskilt er runde med rød kant. Påbudsskilt er runde og blå. Opplysningsskilt er blå firkanter. Vikeplikt (trekant med spissen ned) og stopp (åttekant) har egne former, så du kjenner dem igjen bakfra og i snø.",
    ex: "Et rundt skilt med rød kant og tallet 60 er et forbudsskilt: det er forbudt å kjøre fortere enn 60 km/t.\nEt rundt blått skilt med en pil er et påbud om å kjøre i pilens retning.",
    tip: "Midlertidige skilt ved vegarbeid har gul bunn og går foran de faste skiltene." },
  en: { t: "Groups of road signs",
    intro: "Signs fall into groups you recognise by shape and colour. Warning signs are triangles with a red border pointing up. Prohibitory signs are round with a red border. Mandatory signs are round and blue. Information signs are blue rectangles. Give way (triangle pointing down) and stop (octagon) have unique shapes so you recognise them from behind and in snow.",
    ex: "A round sign with a red border and the number 60 is prohibitory: you may not drive faster than 60 km/h.\nA round blue sign with an arrow orders you to drive in the arrow's direction.",
    tip: "Temporary signs at roadworks have a yellow background and override the permanent signs." } },
{ id: "linjer", pic: "linjer",
  nb: { t: "Linjene i vegen",
    intro: "Gul oppmerking skiller trafikk i motsatt retning, hvit skiller felt i samme retning og markerer kanten. En heltrukket linje (sperrelinje) skal ikke krysses. En stiplet varsellinje med lange streker varsler om sperrelinje eller fare. Ved dobbel linje gjelder linjen nærmest deg: er den stiplet, kan du krysse.",
    ex: "Midt i vegen ligger en heltrukket og en stiplet gul linje. Den stiplede ligger nærmest deg.\nDu kan krysse for å kjøre forbi når det er trygt, men den møtende kan ikke.",
    tip: "Haitenner (trekanter tvers over feltet) er vikepliktlinjen. Der stanser du om det trengs." },
  en: { t: "Lines on the road",
    intro: "Yellow markings separate opposite directions, white markings separate lanes in the same direction and mark the edge. A solid line must not be crossed. A broken warning line with long dashes warns of a solid line or danger ahead. With a double line, the line nearest you applies: if it is broken, you may cross.",
    ex: "In the middle of the road there is a solid and a broken yellow line. The broken one is nearest you.\nYou may cross to overtake when safe, but the oncoming traffic may not.",
    tip: "Shark teeth (triangles across the lane) are the give-way line. Stop there if needed." } },
{ id: "trafikklys", pic: "trafikklys",
  nb: { t: "Trafikklysene",
    intro: "Rødt betyr stans ved stopplinjen. Rødt og gult samtidig betyr at lyset straks blir grønt, men du skal fortsatt vente. Grønt betyr at du kan kjøre hvis det er trygt. Gult betyr stans, med mindre du er så nær at du ikke kan stanse trygt. Blinkende gult betyr at du skal være ekstra aktsom og følge skilt og vikepliktsregler.",
    ex: "Lyset skifter fra grønt til gult like før stopplinjen, og bilen bak ligger tett.\nKan du ikke stanse uten fare, kjører du rolig gjennom. Ellers stanser du.",
    tip: "En grønn pil ved siden av rødt lys betyr at du kan kjøre i pilens retning, men vik for gående." },
  en: { t: "Traffic lights",
    intro: "Red means stop at the stop line. Red and amber together means the light is about to turn green, but you must still wait. Green means you may go if it is safe. Amber means stop, unless you are so close that you cannot stop safely. Flashing amber means take extra care and follow signs and right-of-way rules.",
    ex: "The light turns from green to amber just before the stop line, and the car behind is close.\nIf you cannot stop without danger, you drive calmly through. Otherwise you stop.",
    tip: "A green arrow beside a red light means you may go in the arrow's direction, but give way to pedestrians." } },
]);

// ================= FKB – enhet 2: Fart, avstand og stopplengde =================
TOPICS("FKB", 2, [
{ id: "stopplengde", pic: "stopplengde", sim: "dvstopp",
  nb: { t: "Stopplengde",
    intro: "Stopplengden er strekningen fra du oppdager en fare til bilen står stille. Den er summen av reaksjonslengden (mens du reagerer) og bremselengden (mens bilen bremser). Reaksjonslengden øker i takt med farten, mens bremselengden øker med kvadratet av farten. Derfor blir stopplengden mye lengre når farten øker litt.",
    f: [["s_{\\text{stopp}} = s_{\\text{reaksjon}} + s_{\\text{brems}}", "stopplengde"], ["s_{\\text{reaksjon}} = v \\cdot t_r", "reaksjonslengde med farten i m/s"], ["s_{\\text{brems}} = \\dfrac{v^2}{2a}", "bremselengde med retardasjonen a"]],
    legend: [["v", "fart", "m/s"], ["t_r", "reaksjonstid, ofte rundt 1 s", "s"], ["a", "retardasjon, omtrent 7 på tørr asfalt", "m/s²"]],
    ex: "I 50 km/t er $v \\approx 13{,}9$ m/s.\nReaksjonslengde med 1 s: $13{,}9$ m. Bremselengde: $13{,}9^2/(2\\cdot 7) \\approx 13{,}8$ m.\nStopplengden blir omtrent 28 m.",
    tip: "Dobbel fart gir fire ganger så lang bremselengde. Del km/t på 3,6 for å få m/s." },
  en: { t: "Stopping distance",
    intro: "Stopping distance is the distance from spotting a hazard until the car stands still. It is the sum of the reaction distance (while you react) and the braking distance (while the car brakes). Reaction distance grows in step with speed, while braking distance grows with the square of speed. So a little more speed gives a much longer stopping distance.",
    f: [["s_{\\text{stop}} = s_{\\text{reaction}} + s_{\\text{brake}}", "stopping distance"], ["s_{\\text{reaction}} = v \\cdot t_r", "reaction distance with speed in m/s"], ["s_{\\text{brake}} = \\dfrac{v^2}{2a}", "braking distance with deceleration a"]],
    legend: [["v", "speed", "m/s"], ["t_r", "reaction time, often about 1 s", "s"], ["a", "deceleration, about 7 on dry tarmac", "m/s²"]],
    ex: "At 50 km/h, $v \\approx 13.9$ m/s.\nReaction distance with 1 s: $13.9$ m. Braking distance: $13.9^2/(2\\cdot 7) \\approx 13.8$ m.\nThe stopping distance is about 28 m.",
    tip: "Double the speed gives four times the braking distance. Divide km/h by 3.6 to get m/s." } },
{ id: "avstand-tresekunder", pic: "avstand-tresekunder", sim: "dvavstand",
  nb: { t: "Tresekundersregelen",
    intro: "Avstanden til bilen foran bør være minst tre sekunder under gode forhold. Velg et fast punkt, for eksempel et skilt. Når bilen foran passerer det, teller du sakte til tre. Kommer du fram til punktet før du er ferdig, ligger du for tett. På glatt føre, i mørke og i regn bør avstanden være mye større.",
    f: [["d = v \\cdot 3\\ \\text{s}", "tresekundersavstand i meter med farten i m/s"]],
    legend: [["d", "avstand til bilen foran", "m"], ["v", "fart", "m/s"]],
    ex: "I 80 km/t er $v \\approx 22{,}2$ m/s.\nTre sekunder gir $d \\approx 22{,}2 \\cdot 3 \\approx 67$ m.",
    tip: "Avstanden i sekunder passer i alle farter. Avstanden i meter må øke når farten øker." },
  en: { t: "The three-second rule",
    intro: "Keep at least three seconds to the car in front in good conditions. Pick a fixed point such as a sign. When the car in front passes it, count slowly to three. If you reach the point before you finish, you are too close. On slippery roads, in the dark and in rain the gap should be much larger.",
    f: [["d = v \\cdot 3\\ \\text{s}", "three-second gap in metres with speed in m/s"]],
    legend: [["d", "distance to the car in front", "m"], ["v", "speed", "m/s"]],
    ex: "At 80 km/h, $v \\approx 22.2$ m/s.\nThree seconds gives $d \\approx 22.2 \\cdot 3 \\approx 67$ m.",
    tip: "A gap in seconds works at every speed. A gap in metres must grow with speed." } },
{ id: "krasjkrefter", pic: "krasjvekt", sim: "dvkrasj",
  nb: { t: "Krefter i et krasj",
    intro: "Når bilen stanser brått, fortsetter kroppen din med samme fart til noe stopper den. Med belte tar beltet og knusesonen imot over noen titalls centimeter. Uten belte stopper kroppen mot rattet, dashbordet eller frontruta på bare noen få centimeter, og kreftene blir mange ganger større. Fordi bevegelsesenergien vokser med kvadratet av farten, gir dobbel fart fire ganger så store krefter.",
    f: [["W = \\dfrac{m \\cdot v^2}{2 \\cdot d \\cdot g}", "omtrentlig «vekt» kroppen presses med, i kg"]],
    legend: [["m", "kroppsvekt", "kg"], ["v", "fart før krasjet", "m/s"], ["d", "strekningen kroppen bremses på, omtrent 0,4 med belte og 0,1 uten", "m"], ["g", "tyngdeakselerasjonen, 9,81", "m/s²"]],
    ex: "Du veier 75 kg og kjører i 50 km/t, altså $v \\approx 13{,}9$ m/s.\nMed belte: $W = 75 \\cdot 13{,}9^2 / (2 \\cdot 0{,}4 \\cdot 9{,}81) \\approx 1800$ kg, omtrent som en bil.\nUten belte ($d = 0{,}1$ m) blir det omtrent 7400 kg, mer enn en elefant.",
    tip: "Et barn på 20 kg på fanget i 50 km/t tilsvarer nesten 2 tonn. Ingen klarer å holde igjen det, derfor skal barn alltid sikres i eget sete." },
  en: { t: "Forces in a crash",
    intro: "When the car stops suddenly, your body keeps going at the same speed until something stops it. With a belt, the belt and the crumple zone take the load over a few tens of centimetres. Without a belt the body stops against the wheel, dashboard or windscreen within just a few centimetres, and the forces become many times larger. Because kinetic energy grows with the square of speed, double the speed gives four times the force.",
    f: [["W = \\dfrac{m \\cdot v^2}{2 \\cdot d \\cdot g}", "rough \"weight\" pressing on the body, in kg"]],
    legend: [["m", "body weight", "kg"], ["v", "speed before the crash", "m/s"], ["d", "distance over which the body stops, about 0.4 with a belt and 0.1 without", "m"], ["g", "gravitational acceleration, 9.81", "m/s²"]],
    ex: "You weigh 75 kg and drive at 50 km/h, so $v \\approx 13.9$ m/s.\nWith a belt: $W = 75 \\cdot 13.9^2 / (2 \\cdot 0.4 \\cdot 9.81) \\approx 1800$ kg, about a car.\nWithout a belt ($d = 0.1$ m) it is about 7400 kg, more than an elephant.",
    tip: "A 20 kg child on a lap at 50 km/h equals almost 2 tonnes. Nobody can hold that back, which is why children must always be restrained in their own seat." } },
{ id: "fartsgrenser", pic: "fartsgrenser", sim: "dvsving",
  nb: { t: "Fartsgrensene",
    intro: "Den generelle fartsgrensen er 50 km/t i tettbygd strøk og 80 km/t utenfor. Skilt kan sette andre grenser, fra 30 km/t ved skoler til 110 km/t på enkelte motorveger. Med tilhenger uten bremser er grensen 60 km/t, med bremser 80 km/t. Du skal alltid tilpasse farten til forholdene, også under fartsgrensen.",
    f: [["v_{\\text{tettbygd}} = 50\\ \\tfrac{\\text{km}}{\\text{t}}, \\quad v_{\\text{ellers}} = 80\\ \\tfrac{\\text{km}}{\\text{t}}", "generelle fartsgrenser"], ["1\\ \\tfrac{\\text{m}}{\\text{s}} = 3{,}6\\ \\tfrac{\\text{km}}{\\text{t}}", "omregning"]],
    ex: "Fartsgrensen er 80 km/t, men det er tåke og glatt.\nDu må kjøre så sakte at du kan stanse på den strekningen du ser, kanskje langt under 80.",
    tip: "En fotgjenger som blir påkjørt i 30 km/t, overlever oftest. I 50 km/t er risikoen for å dø mange ganger høyere." },
  en: { t: "Speed limits",
    intro: "The general limit is 50 km/h in built-up areas and 80 km/h elsewhere. Signs can set other limits, from 30 km/h near schools to 110 km/h on some motorways. With an unbraked trailer the limit is 60 km/h, with a braked trailer 80 km/h. You must always adapt your speed to the conditions, even below the limit.",
    f: [["v_{\\text{built-up}} = 50\\ \\tfrac{\\text{km}}{\\text{h}}, \\quad v_{\\text{elsewhere}} = 80\\ \\tfrac{\\text{km}}{\\text{h}}", "general speed limits"], ["1\\ \\tfrac{\\text{m}}{\\text{s}} = 3.6\\ \\tfrac{\\text{km}}{\\text{h}}", "conversion"]],
    ex: "The limit is 80 km/h, but there is fog and ice.\nYou must drive slowly enough to stop within the distance you can see, perhaps far below 80.",
    tip: "A pedestrian hit at 30 km/h usually survives. At 50 km/h the risk of death is many times higher." } },
]);

// ================= FKB – enhet 6: Rus, trøtthet og oppmerksomhet =================
TOPICS("FKB", 6, [
{ id: "promille", pic: "promille", sim: "dvpromille",
  nb: { t: "Promille og forbrenning",
    intro: "Promillegrensen for å kjøre bil i Norge er 0,2. Kroppen forbrenner omtrent 0,15 promille i timen, og ingenting får det til å gå fortere: verken kaffe, mat, søvn eller kald dusj. Har du drukket mye kvelden før, kan du fortsatt ha promille neste morgen.",
    f: [["t \\approx \\dfrac{\\text{promille}}{0{,}15}\\ \\text{timer}", "tid før alkoholen er ute av kroppen"], ["\\text{grense: } 0{,}2\\ \\text{‰}", "promillegrensen for bil"]],
    ex: "Du har 1,2 promille ved midnatt.\n$t \\approx 1{,}2/0{,}15 = 8$ timer. Du er ikke edru før rundt klokka åtte.",
    tip: "Er du i tvil, kjører du ikke. Mange tar seg selv i promillekontroll morgenen etter." },
  en: { t: "Blood alcohol and burn-off",
    intro: "The drink-driving limit in Norway is 0.2 per mille. The body burns about 0.15 per mille per hour, and nothing speeds it up: not coffee, food, sleep or a cold shower. If you drank a lot the evening before, you may still be over the limit next morning.",
    f: [["t \\approx \\dfrac{\\text{per mille}}{0.15}\\ \\text{hours}", "time until the alcohol is gone"], ["\\text{limit: } 0.2\\ \\text{‰}", "the limit for cars"]],
    ex: "You have 1.2 per mille at midnight.\n$t \\approx 1.2/0.15 = 8$ hours. You are not sober until about eight o'clock.",
    tip: "If in doubt, do not drive. Many are caught in checks the morning after." } },
{ id: "trotthet", pic: "trotthet",
  nb: { t: "Trøtthet og mikrosøvn",
    intro: "Trøtthet gjør reaksjonstiden lengre og kan gi mikrosøvn: du sovner i noen sekunder uten å merke det. Tegn på trøtthet er gjesping, tunge øyelokk, at du ikke husker de siste kilometerne og at du vingler i feltet. Kaffe og åpent vindu hjelper bare kort. Det eneste som virker, er å stoppe og sove.",
    f: [["s = v \\cdot t", "strekningen du kjører i blinde under mikrosøvn"]],
    legend: [["v", "fart", "m/s"], ["t", "tiden du sover", "s"]],
    ex: "Du sovner i 3 sekunder i 90 km/t ($v = 25$ m/s).\n$s = 25 \\cdot 3 = 75$ m uten kontroll over bilen.",
    tip: "Ta pause minst hver annen time på lange turer, og stopp med en gang du kjenner de første tegnene." },
  en: { t: "Tiredness and microsleep",
    intro: "Tiredness lengthens your reaction time and can cause microsleep: you fall asleep for a few seconds without noticing. Signs are yawning, heavy eyelids, not remembering the last few kilometres and drifting in the lane. Coffee and an open window help only briefly. The only real cure is to stop and sleep.",
    f: [["s = v \\cdot t", "the distance you travel blind during microsleep"]],
    legend: [["v", "speed", "m/s"], ["t", "time asleep", "s"]],
    ex: "You fall asleep for 3 seconds at 90 km/h ($v = 25$ m/s).\n$s = 25 \\cdot 3 = 75$ m without control of the car.",
    tip: "Take a break at least every two hours on long trips, and stop as soon as you notice the first signs." } },
{ id: "mobil-blind", pic: "mobil-blind", sim: "dvblind",
  nb: { t: "Blikket bort fra vegen",
    intro: "Håndholdt mobil er forbudt mens du kjører, og selv et kort blikk på en skjerm gjør at du kjører langt i blinde. Håndfri samtale er lov, men tar også oppmerksomhet. Still inn navigasjon og musikk før du kjører, og la meldinger vente til du står stille.",
    f: [["s = \\dfrac{v_{\\text{km/t}}}{3{,}6} \\cdot t", "strekning i blinde med farten i km/t"]],
    legend: [["v_{\\text{km/t}}", "fart", "km/t"], ["t", "tiden du ser bort", "s"]],
    ex: "Du ser på mobilen i 2 sekunder i 80 km/t.\n$s = 80/3{,}6 \\cdot 2 \\approx 44$ m i blinde.",
    tip: "Legg mobilen utenfor rekkevidde eller bruk «ikke forstyrr» når du kjører." },
  en: { t: "Eyes off the road",
    intro: "Holding a phone while driving is forbidden, and even a quick glance at a screen means driving a long way blind. Hands-free calls are legal but also take attention. Set up navigation and music before you go, and let messages wait until you have stopped.",
    f: [["s = \\dfrac{v_{\\text{km/h}}}{3.6} \\cdot t", "distance driven blind with speed in km/h"]],
    legend: [["v_{\\text{km/h}}", "speed", "km/h"], ["t", "time looking away", "s"]],
    ex: "You look at your phone for 2 seconds at 80 km/h.\n$s = 80/3.6 \\cdot 2 \\approx 44$ m blind.",
    tip: "Put the phone out of reach or use do-not-disturb while driving." } },
]);

// ================= FKB – enhet 9: Ulykker og førstehjelp =================
TOPICS("FKB", 9, [
{ id: "sikre-ulykke", pic: "sikre-ulykke",
  nb: { t: "Sikre ulykkesstedet",
    intro: "Kommer du til en ulykke, skal du stanse og hjelpe. Sikre først stedet så ingen flere blir skadet: parker trygt med nødblinklys, ta på refleksvest og sett ut varseltrekanten godt bak. Skaff deg oversikt, ring nødnummeret og start førstehjelp. Flytt bare skadde som er i fare der de ligger.",
    ex: "Du kommer til en utforkjøring i 80-sone.\nNødblinklys og refleksvest på, varseltrekanten 150–250 m bak, ring 113 og sjekk om de skadde puster.",
    tip: "Har du ikke oversikt, ring 113. De hjelper deg gjennom resten." },
  en: { t: "Securing an accident scene",
    intro: "If you come to an accident, you must stop and help. First secure the scene so nobody else is hurt: park safely with hazard lights, put on a reflective vest and place the warning triangle well behind. Get an overview, call the emergency number and start first aid. Only move injured people who are in danger where they lie.",
    ex: "You come to a car off the road in an 80 zone.\nHazard lights and vest on, warning triangle 150–250 m behind, call 113 and check whether the injured are breathing.",
    tip: "If you lack an overview, call 113. They will guide you through the rest." } },
{ id: "hlr", pic: "hlr",
  nb: { t: "HLR: hjerte-lunge-redning",
    intro: "Puster personen ikke normalt, skal du ringe 113 og starte HLR med en gang. Gi 30 brystkompresjoner midt på brystet, omtrent 5–6 cm dype og i takt 100–120 i minuttet, og så 2 innblåsninger. Fortsett til hjelpen kommer eller personen begynner å puste. Bruk hjertestarter så fort du får tak i en.",
    ex: "En person er livløs og puster ikke normalt.\nRing 113 på høyttaler, start 30 kompresjoner og 2 innblåsninger, og be noen hente hjertestarter.",
    tip: "Klarer du ikke innblåsninger, gi bare kompresjoner. Det er mye bedre enn ingenting." },
  en: { t: "CPR",
    intro: "If the person is not breathing normally, call 113 and start CPR at once. Give 30 chest compressions in the middle of the chest, about 5–6 cm deep at a rate of 100–120 per minute, then 2 rescue breaths. Continue until help arrives or the person starts breathing. Use a defibrillator as soon as you get one.",
    ex: "A person is unresponsive and not breathing normally.\nCall 113 on speaker, start 30 compressions and 2 breaths, and ask someone to fetch a defibrillator.",
    tip: "If you cannot give breaths, give compressions only. That is far better than nothing." } },
{ id: "bevisstlos-blodning", pic: "bevisstlos-blodning",
  nb: { t: "Bevisstløs og blødninger",
    intro: "En bevisstløs person som puster normalt, legger du i stabilt sideleie så luftveiene holdes åpne, og du holder personen varm. Store blødninger stanser du med direkte trykk på såret. Ved sjokk skal personen ligge, holdes varm og ha ro. Brannskader kjøler du med lunkent vann i omtrent 20 minutter.",
    ex: "En motorsyklist ligger bevisstløs, men puster normalt.\nLegg personen i stabilt sideleie, ta ikke av hjelmen uten grunn, hold personen varm og følg med på pusten.",
    tip: "Sjekk pusten jevnlig. Slutter personen å puste normalt, starter du HLR." },
  en: { t: "Unconscious and bleeding",
    intro: "Place an unconscious person who is breathing normally in the recovery position to keep the airway open, and keep them warm. Stop heavy bleeding with direct pressure on the wound. In shock the person should lie down, be kept warm and calm. Cool burns with lukewarm water for about 20 minutes.",
    ex: "A motorcyclist lies unconscious but breathing normally.\nPlace them in the recovery position, do not remove the helmet without reason, keep them warm and monitor breathing.",
    tip: "Check breathing regularly. If they stop breathing normally, start CPR." } },
]);
