// Teoribok: GMAT, MEK1000, MEK2000, DAVE3700, DAVE3705

// =====================================================================
// GMAT: Grunnleggende matematikk
// =====================================================================

// Enhet 0: Tall, brøk og prosent
TOPICS("GMAT", 0, [
{ id: "regnerekkefolge",
  nb: { t: "Regnerekkefølge",
    intro: "Når et regnestykke har flere regneoperasjoner, må vi vite hvilken som skal gjøres først for å få samme svar hver gang. Rekkefølgen er: parenteser, så potenser, så ganging og deling, og til slutt pluss og minus.",
    f: [["()\\ \\to\\ a^n\\ \\to\\ \\times,\\div\\ \\to\\ +,-", "rekkefølgen regnestykket skal utføres i"], ["-a^2 = -(a^2),\\quad (-a)^2 = a^2", "potensen gjelder bare tallet uten parentes"]],
    legend: [["()", "regnes først", ""], ["a^n", "potens, regnes før $\\times$ og $\\div$", ""]],
    ex: "$10 - 2\\cdot(3 - 5) = 10 - 2\\cdot(-2) = 10 + 4 = 14$.",
    tip: "Å trekke fra et negativt tall er det samme som å legge til." },
  en: { t: "Order of operations",
    intro: "When a calculation has several operations, we need to know which one to do first to get the same answer every time. The order is: parentheses, then powers, then multiplication and division, and finally addition and subtraction.",
    f: [["()\\ \\to\\ a^n\\ \\to\\ \\times,\\div\\ \\to\\ +,-", "the order the calculation is carried out in"], ["-a^2 = -(a^2),\\quad (-a)^2 = a^2", "the power applies only to the number without parentheses"]],
    legend: [["()", "computed first", ""], ["a^n", "power, computed before $\\times$ and $\\div$", ""]],
    ex: "$10 - 2\\cdot(3 - 5) = 10 - 2\\cdot(-2) = 10 + 4 = 14$.",
    tip: "Subtracting a negative number is the same as adding it." } },
{ id: "brok",
  nb: { t: "Brøkregning",
    intro: "En brøk $\\frac{a}{b}$ betyr $a$ delt på $b$. Ved pluss og minus må brøkene ha felles nevner, ved ganging ganger vi teller med teller og nevner med nevner, og ved deling ganger vi med den omvendte brøken.",
    f: [["\\frac{a}{b} + \\frac{c}{d} = \\frac{ad+bc}{bd}", "addisjon (felles nevner)"], ["\\frac{a}{b}\\cdot\\frac{c}{d} = \\frac{ac}{bd}", "multiplikasjon"], ["\\frac{a}{b} : \\frac{c}{d} = \\frac{a}{b}\\cdot\\frac{d}{c}", "divisjon: gang med den omvendte brøken"]],
    legend: [["a,\\ c", "tellere", ""], ["b,\\ d", "nevnere", ""]],
    ex: "$\\frac{1}{2} + \\frac{1}{3} = \\frac{3}{6} + \\frac{2}{6} = \\frac{5}{6}$.\n$\\frac{2}{3}\\cdot\\frac{3}{4} = \\frac{6}{12} = \\frac{1}{2}$.",
    tip: "Nevnerne skal aldri legges sammen direkte, som i $\\frac12+\\frac13 \\neq \\frac25$." },
  en: { t: "Fractions",
    intro: "A fraction $\\frac{a}{b}$ means $a$ divided by $b$. For addition and subtraction the fractions need a common denominator, for multiplication we multiply numerator by numerator and denominator by denominator, and for division we multiply by the reciprocal.",
    f: [["\\frac{a}{b} + \\frac{c}{d} = \\frac{ad+bc}{bd}", "addition (common denominator)"], ["\\frac{a}{b}\\cdot\\frac{c}{d} = \\frac{ac}{bd}", "multiplication"], ["\\frac{a}{b} \\div \\frac{c}{d} = \\frac{a}{b}\\cdot\\frac{d}{c}", "division: multiply by the reciprocal"]],
    legend: [["a,\\ c", "numerators", ""], ["b,\\ d", "denominators", ""]],
    ex: "$\\frac{1}{2} + \\frac{1}{3} = \\frac{3}{6} + \\frac{2}{6} = \\frac{5}{6}$.\n$\\frac{2}{3}\\cdot\\frac{3}{4} = \\frac{6}{12} = \\frac{1}{2}$.",
    tip: "Never add the denominators directly, as in $\\frac12+\\frac13 \\neq \\frac25$." } },
{ id: "prosent",
  nb: { t: "Prosent og vekstfaktor",
    intro: "Prosent betyr hundredeler: $p\\,\\% = \\frac{p}{100}$. En økning på $p\\,\\%$ svarer til å gange med vekstfaktoren $1+\\frac{p}{100}$, og en nedgang svarer til å gange med $1-\\frac{p}{100}$. Flere endringer etter hverandre ganges sammen.",
    f: [["p\\,\\% = \\frac{p}{100}", "prosent som desimaltall"], ["\\text{ny} = \\text{gammel}\\cdot\\left(1 \\pm \\frac{p}{100}\\right)", "vekstfaktor ved økning (+) eller nedgang (−)"], ["\\text{endring} = \\frac{\\text{ny} - \\text{gammel}}{\\text{gammel}}\\cdot 100\\,\\%", "prosentvis endring"]],
    legend: [["p", "prosentsats", "%"]],
    ex: "En motor koster 8000 kr, prisen økes med 25 % og settes så ned med 20 %:\n$8000\\cdot 1{,}25\\cdot 0{,}80 = 8000$ kr - prisen er tilbake der den startet.",
    tip: "$+20\\,\\%$ etterfulgt av $-20\\,\\%$ gir ikke samme pris: $1{,}2\\cdot 0{,}8 = 0{,}96$, altså 4 % lavere." },
  en: { t: "Percent and growth factor",
    intro: "Percent means hundredths: $p\\% = \\frac{p}{100}$. An increase of $p\\%$ corresponds to multiplying by the growth factor $1+\\frac{p}{100}$, and a decrease corresponds to multiplying by $1-\\frac{p}{100}$. Several changes in a row are multiplied together.",
    f: [["p\\% = \\frac{p}{100}", "percent as a decimal"], ["\\text{new} = \\text{old}\\cdot\\left(1 \\pm \\frac{p}{100}\\right)", "growth factor for an increase (+) or decrease (−)"], ["\\text{change} = \\frac{\\text{new} - \\text{old}}{\\text{old}}\\cdot 100\\%", "percentage change"]],
    legend: [["p", "percentage rate", "%"]],
    ex: "A motor costs NOK 8000, the price is raised by 25% and then reduced by 20%:\n$8000\\cdot 1.25\\cdot 0.80 = 8000$ NOK - the price is back where it started.",
    tip: "$+20\\%$ followed by $-20\\%$ does not give the original price: $1.2\\cdot 0.8 = 0.96$, i.e. 4% lower." } }
]);

// Enhet 1: Potenser, røtter og tierpotenser
TOPICS("GMAT", 1, [
{ id: "potensregler",
  nb: { t: "Potensregler",
    intro: "En potens $a^n$ er en snarvei for gjentatt multiplikasjon av $a$ med seg selv $n$ ganger. Ved ganging av like grunntall legges eksponentene sammen, ved deling trekkes de fra, og ved potens i potens ganges de.",
    f: [["a^m\\cdot a^n = a^{m+n}", "ganging: legg sammen eksponentene"], ["\\frac{a^m}{a^n} = a^{m-n}", "deling: trekk fra eksponentene"], ["(a^m)^n = a^{mn}", "potens i potens: gang eksponentene"]],
    legend: [["a", "grunntall", ""], ["m,\\ n", "eksponenter", ""]],
    ex: "$2^3\\cdot 2^4 = 2^7 = 128$.",
    tip: "$a^m\\cdot a^n \\neq a^{mn}$ - eksponentene legges sammen, ikke ganges." },
  en: { t: "Rules of powers",
    intro: "A power $a^n$ is a shorthand for multiplying $a$ by itself $n$ times. When multiplying the same base the exponents are added, when dividing they are subtracted, and for a power of a power they are multiplied.",
    f: [["a^m\\cdot a^n = a^{m+n}", "multiplication: add the exponents"], ["\\frac{a^m}{a^n} = a^{m-n}", "division: subtract the exponents"], ["(a^m)^n = a^{mn}", "power of a power: multiply the exponents"]],
    legend: [["a", "base", ""], ["m,\\ n", "exponents", ""]],
    ex: "$2^3\\cdot 2^4 = 2^7 = 128$.",
    tip: "$a^m\\cdot a^n \\neq a^{mn}$ - the exponents are added, not multiplied." } },
{ id: "rotter",
  nb: { t: "Røtter",
    intro: "Roten $\\sqrt[n]{a}$ er tallet som gir $a$ når det opphøyes i $n$-te. En rot kan alltid skrives som en brøkeksponent, og negativ eksponent betyr at brøken snus.",
    f: [["\\sqrt[n]{a} = a^{1/n}", "rot som brøkeksponent"], ["\\sqrt{ab} = \\sqrt{a}\\cdot\\sqrt{b}", "produktregel for røtter"], ["a^{-n} = \\frac{1}{a^n}", "negativ eksponent"]],
    legend: [["n", "rotens grad", ""], ["a", "radikand, tallet under rottegnet", ""]],
    ex: "$\\sqrt[3]{64}\\cdot 4^{-1} = 4\\cdot\\frac{1}{4} = 1$, siden $4^3 = 64$.",
    tip: "$\\sqrt{a+b} \\neq \\sqrt{a}+\\sqrt{b}$ - røtter kan bare deles opp ved ganging og deling." },
  en: { t: "Roots",
    intro: "The root $\\sqrt[n]{a}$ is the number that gives $a$ when raised to the power $n$. A root can always be written as a fractional exponent, and a negative exponent means the fraction is flipped.",
    f: [["\\sqrt[n]{a} = a^{1/n}", "root as a fractional exponent"], ["\\sqrt{ab} = \\sqrt{a}\\cdot\\sqrt{b}", "product rule for roots"], ["a^{-n} = \\frac{1}{a^n}", "negative exponent"]],
    legend: [["n", "degree of the root", ""], ["a", "radicand, the number under the root sign", ""]],
    ex: "$\\sqrt[3]{64}\\cdot 4^{-1} = 4\\cdot\\frac{1}{4} = 1$, since $4^3 = 64$.",
    tip: "$\\sqrt{a+b} \\neq \\sqrt{a}+\\sqrt{b}$ - roots only split over multiplication and division." } },
{ id: "normalform",
  nb: { t: "Normalform",
    intro: "Normalform (vitenskapelig notasjon) er en kompakt måte å skrive svært store eller svært små tall på. Tallet skrives som en mantisse mellom 1 og 10 ganget med en tierpotens, og enhetsprefikser som kilo og milli bygger på det samme.",
    f: [["t = a\\cdot 10^n,\\quad 1 \\le |a| < 10", "normalform"], ["\\text{k} = 10^3,\\ \\text{m} = 10^{-3},\\ \\mu = 10^{-6}", "vanlige enhetsprefikser"]],
    legend: [["a", "mantisse", ""], ["n", "heltalls eksponent", ""]],
    ex: "$\\dfrac{(2{,}0\\cdot 10^5)\\cdot(3{,}0\\cdot 10^{-2})}{4{,}0\\cdot 10^3} = 1{,}5\\cdot 10^0 = 1{,}5$.",
    tip: "Pass på at mantissen alltid blir mellom 1 og 10, ellers er det ikke normalform." },
  en: { t: "Scientific notation",
    intro: "Scientific notation is a compact way to write very large or very small numbers. The number is written as a mantissa between 1 and 10 multiplied by a power of ten, and unit prefixes such as kilo and milli are built on the same idea.",
    f: [["t = a\\cdot 10^n,\\quad 1 \\le |a| < 10", "scientific notation"], ["\\text{k} = 10^3,\\ \\text{m} = 10^{-3},\\ \\mu = 10^{-6}", "common unit prefixes"]],
    legend: [["a", "mantissa", ""], ["n", "integer exponent", ""]],
    ex: "$\\dfrac{(2.0\\cdot 10^5)\\cdot(3.0\\cdot 10^{-2})}{4.0\\cdot 10^3} = 1.5\\cdot 10^0 = 1.5$.",
    tip: "Make sure the mantissa always ends up between 1 and 10, otherwise it is not scientific notation." } }
]);

// Enhet 2: Algebra og ligninger
TOPICS("GMAT", 2, [
{ id: "kvadratsetninger",
  nb: { t: "Kvadratsetningene",
    intro: "Kvadratsetningene er snarveier for å multiplisere ut vanlige parentesuttrykk, og brukes motsatt vei ved faktorisering. De dukker opp overalt når vi forenkler algebraiske uttrykk.",
    f: [["(a+b)^2 = a^2 + 2ab + b^2", "første kvadratsetning"], ["(a-b)^2 = a^2 - 2ab + b^2", "andre kvadratsetning"], ["(a+b)(a-b) = a^2 - b^2", "konjugatsetningen"]],
    legend: [["a,\\ b", "ledd i parentesen", ""]],
    ex: "$(x+3)^2 = x^2 + 6x + 9$.\n$(x+3)(x-3) = x^2 - 9$.",
    tip: "$(a+b)^2 \\neq a^2 + b^2$ - det midterste leddet $2ab$ blir ofte glemt." },
  en: { t: "The square rules",
    intro: "The square rules are shortcuts for expanding common parenthesised expressions, and are used in reverse when factoring. They show up everywhere when simplifying algebraic expressions.",
    f: [["(a+b)^2 = a^2 + 2ab + b^2", "first square rule"], ["(a-b)^2 = a^2 - 2ab + b^2", "second square rule"], ["(a+b)(a-b) = a^2 - b^2", "difference of squares"]],
    legend: [["a,\\ b", "terms in the parentheses", ""]],
    ex: "$(x+3)^2 = x^2 + 6x + 9$.\n$(x+3)(x-3) = x^2 - 9$.",
    tip: "$(a+b)^2 \\neq a^2 + b^2$ - the middle term $2ab$ is often forgotten." } },
{ id: "linearligning",
  nb: { t: "Lineær ligning",
    intro: "En lineær ligning har den ukjente $x$ bare i første grad. Vi løser den ved å gjøre samme operasjon på begge sider av likhetstegnet, til $x$ står alene på én side.",
    f: [["ax + b = c\\ \\Rightarrow\\ x = \\frac{c-b}{a}", "løs en lineær ligning for x"]],
    legend: [["a,\\ b,\\ c", "kjente tall", ""], ["x", "den ukjente", ""]],
    ex: "$3(x-2) = 2x+4 \\Rightarrow 3x - 6 = 2x + 4 \\Rightarrow x = 10$.",
    tip: "Det du gjør på den ene siden av likhetstegnet, må du også gjøre på den andre." },
  en: { t: "Linear equation",
    intro: "A linear equation has the unknown $x$ only to the first power. We solve it by performing the same operation on both sides of the equals sign, until $x$ stands alone on one side.",
    f: [["ax + b = c\\ \\Rightarrow\\ x = \\frac{c-b}{a}", "solve a linear equation for x"]],
    legend: [["a,\\ b,\\ c", "known numbers", ""], ["x", "the unknown", ""]],
    ex: "$3(x-2) = 2x+4 \\Rightarrow 3x - 6 = 2x + 4 \\Rightarrow x = 10$.",
    tip: "Whatever you do to one side of the equals sign, you must do to the other." } },
{ id: "andregradsligning",
  nb: { t: "Andregradsligning",
    intro: "En andregradsligning $ax^2+bx+c=0$ løses med abc-formelen, i motsetning til en lineær ligning som løses ved å flytte og dele. Uttrykket under rottegnet, diskriminanten $D$, forteller hvor mange løsninger vi får før vi i det hele tatt regner ut roten.",
    f: [["x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}", "abc-formelen"], ["D = b^2 - 4ac", "diskriminanten"]],
    legend: [["a,\\ b,\\ c", "koeffisienter i $ax^2+bx+c=0$", ""], ["D", "diskriminant", ""]],
    ex: "$x^2 - 2x - 8 = 0$: $D = 4+32 = 36$, så $x = \\frac{2\\pm 6}{2} = 4$ eller $-2$.",
    tip: "$D>0$ gir to løsninger, $D=0$ gir én, og $D<0$ gir ingen reelle løsninger." },
  en: { t: "Quadratic equation",
    intro: "A quadratic equation $ax^2+bx+c=0$ is solved with the quadratic formula. The expression under the root sign, the discriminant $D$, tells us how many solutions we get.",
    f: [["x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}", "the quadratic formula"], ["D = b^2 - 4ac", "the discriminant"]],
    legend: [["a,\\ b,\\ c", "coefficients in $ax^2+bx+c=0$", ""], ["D", "discriminant", ""]],
    ex: "$x^2 - 2x - 8 = 0$: $D = 4+32 = 36$, so $x = \\frac{2\\pm 6}{2} = 4$ or $-2$.",
    tip: "$D>0$ gives two solutions, $D=0$ gives one, and $D<0$ gives no real solutions." } }
]);

// Enhet 3: Funksjoner og grafer
TOPICS("GMAT", 3, [
{ id: "linearfunksjon",
  fig: `<svg viewBox="0 0 240 140"><path d="M30 120H225" class="dim"/><path d="M30 130V15" class="dim"/><path d="M30 100L205 18" class="a"/><path d="M205 18l-15 3 5 12z" class="af"/><path d="M100 67H160V39" class="dim"/><text x="120" y="82">Δx</text><text x="163" y="55">Δy</text><text x="15" y="103">b</text><text x="208" y="15">f</text></svg>`,
  nb: { t: "Lineær funksjon",
    intro: "En lineær funksjon $f(x)=ax+b$ har en graf som er en rett linje. Stigningstallet $a$ er endring i $y$ per endring i $x$, og $b$ er skjæringspunktet med y-aksen.",
    f: [["f(x) = ax + b", "lineær funksjon"], ["a = \\frac{y_2 - y_1}{x_2 - x_1} = \\frac{\\Delta y}{\\Delta x}", "stigningstall mellom to punkter"]],
    legend: [["a", "stigningstall", ""], ["b", "skjæring med y-aksen (der $x=0$)", ""]],
    ex: "Linjen gjennom $(1,3)$ og $(4,12)$: $a = \\frac{12-3}{4-1}=3$, og $3 = 3\\cdot 1+b \\Rightarrow b=0$, så $f(x)=3x$.",
    tip: "Det er $a$, ikke $b$, som er stigningstallet - lett å blande." },
  en: { t: "Linear function",
    intro: "A linear function $f(x)=ax+b$ has a graph that is a straight line. The slope $a$ is the change in $y$ per change in $x$, and $b$ is the y-intercept.",
    f: [["f(x) = ax + b", "linear function"], ["a = \\frac{y_2 - y_1}{x_2 - x_1} = \\frac{\\Delta y}{\\Delta x}", "slope between two points"]],
    legend: [["a", "slope", ""], ["b", "y-intercept (where $x=0$)", ""]],
    ex: "The line through $(1,3)$ and $(4,12)$: $a = \\frac{12-3}{4-1}=3$, and $3 = 3\\cdot 1+b \\Rightarrow b=0$, so $f(x)=3x$.",
    tip: "It is $a$, not $b$, that is the slope - easy to mix up." } },
{ id: "andregradsfunksjon",
  fig: `<svg viewBox="0 0 240 140"><path d="M20 125H225" class="dim"/><path d="M30 125V15" class="dim"/><path d="M35 35Q120 135 205 35" class="d"/><circle cx="120" cy="85" r="3" class="af"/><path d="M120 125V85" class="dash"/><text x="107" y="138">x<tspan dy="4" font-size="10">t</tspan></text><text x="130" y="80">V</text></svg>`,
  nb: { t: "Andregradsfunksjon",
    intro: "En andregradsfunksjon $f(x)=ax^2+bx+c$ har en parabel som graf. Er $a>0$ vender parabelen oppover med et bunnpunkt (minimum), er $a<0$ vender den nedover med et toppunkt (maksimum).",
    f: [["f(x) = ax^2 + bx + c", "andregradsfunksjon"], ["x_t = -\\frac{b}{2a}", "x-koordinaten til topp-/bunnpunktet V"]],
    legend: [["a", "avgjør retning (opp/ned) og bredde", ""], ["x_t", "x-koordinat til ekstremalpunktet", ""]],
    ex: "$f(x)=-2x^2+8x+3$: $x_t = -\\frac{8}{2\\cdot(-2)}=2$, og $f(2)=-8+16+3=11$. Siden $a<0$ er $(2,11)$ et maksimum.",
    tip: "Sett $x_t$ inn i funksjonen igjen for å finne y-koordinaten til ekstremalpunktet." },
  en: { t: "Quadratic function",
    intro: "A quadratic function $f(x)=ax^2+bx+c$ has a parabola as its graph. If $a>0$ the parabola opens upward with a minimum, and if $a<0$ it opens downward with a maximum.",
    f: [["f(x) = ax^2 + bx + c", "quadratic function"], ["x_t = -\\frac{b}{2a}", "x-coordinate of the vertex V"]],
    legend: [["a", "sets direction (up/down) and width", ""], ["x_t", "x-coordinate of the vertex", ""]],
    ex: "$f(x)=-2x^2+8x+3$: $x_t = -\\frac{8}{2\\cdot(-2)}=2$, and $f(2)=-8+16+3=11$. Since $a<0$, $(2,11)$ is a maximum.",
    tip: "Plug $x_t$ back into the function to find the y-coordinate of the vertex." } },
{ id: "nullpunkter",
  nb: { t: "Nullpunkter og diskriminant",
    intro: "Nullpunktene til en funksjon er der grafen krysser x-aksen, altså løsningene av $f(x)=0$. For en andregradsfunksjon forteller fortegnet til diskriminanten $D$ hvor mange nullpunkter grafen har.",
    f: [["D>0:\\ \\text{to nullpunkter}", "parabelen krysser x-aksen to steder"], ["D=0:\\ \\text{ett nullpunkt}", "parabelen tangerer x-aksen"], ["D<0:\\ \\text{ingen nullpunkter}", "parabelen når ikke x-aksen"]],
    legend: [["D", "diskriminant, $D=b^2-4ac$", ""]],
    ex: "$f(x)=x^2-4x+4$: $D=16-16=0$, ett nullpunkt $x=2$.\n$f(x)=x^2+2x+5$: $D=4-20=-16<0$, ingen nullpunkter.",
    tip: "Toppunktet over x-aksen (parabel som vender nedover) gir ingen nullpunkter - sjekk alltid fortegnet til $a$ og $D$ sammen." },
  en: { t: "Zeros and discriminant",
    intro: "The zeros of a function are where the graph crosses the x-axis, i.e. the solutions of $f(x)=0$. For a quadratic function the sign of the discriminant $D$ tells us how many zeros the graph has.",
    f: [["D>0:\\ \\text{two zeros}", "the parabola crosses the x-axis twice"], ["D=0:\\ \\text{one zero}", "the parabola touches the x-axis"], ["D<0:\\ \\text{no zeros}", "the parabola never reaches the x-axis"]],
    legend: [["D", "discriminant, $D=b^2-4ac$", ""]],
    ex: "$f(x)=x^2-4x+4$: $D=16-16=0$, one zero $x=2$.\n$f(x)=x^2+2x+5$: $D=4-20=-16<0$, no zeros.",
    tip: "A vertex above the x-axis for a downward parabola gives no zeros - always check the sign of $a$ together with $D$." } }
]);

// Enhet 4: Eksponential- og logaritmefunksjoner
TOPICS("GMAT", 4, [
{ id: "eksponentialfunksjon",
  nb: { t: "Eksponentialfunksjon",
    intro: "En eksponentialfunksjon $f(x)=a\\cdot b^x$ ganger med samme faktor $b$ for hver økning av $x$ med 1, i motsetning til en lineær funksjon som legger til det samme. I fysikk og kalkulus brukes ofte grunntallet $e$.",
    f: [["f(x) = a\\cdot b^x", "eksponentialfunksjon, $a=f(0)$"], ["N(t) = N_0 e^{kt}", "med naturlig grunntall e"]],
    legend: [["a,\\ N_0", "startverdi", ""], ["b", "vekstfaktor per steg", ""], ["k", "vekstrate ($k>0$ vekst, $k<0$ nedgang)", "1/tid"]],
    ex: "$N_0=200$, 5 % vekst per år: $N(3)=200\\cdot 1{,}05^3 \\approx 231{,}5$.",
    tip: "10 % vekst to år på rad gir $1{,}1^2=1{,}21$, altså 21 %, ikke 20 %." },
  en: { t: "Exponential function",
    intro: "An exponential function $f(x)=a\\cdot b^x$ multiplies by the same factor $b$ for every increase of $x$ by 1, unlike a linear function which adds the same amount. In physics and calculus the base $e$ is often used.",
    f: [["f(x) = a\\cdot b^x", "exponential function, $a=f(0)$"], ["N(t) = N_0 e^{kt}", "with the natural base e"]],
    legend: [["a,\\ N_0", "initial value", ""], ["b", "growth factor per step", ""], ["k", "growth rate ($k>0$ growth, $k<0$ decay)", "1/time"]],
    ex: "$N_0=200$, 5% growth per year: $N(3)=200\\cdot 1.05^3 \\approx 231.5$.",
    tip: "10% growth two years in a row gives $1.1^2=1.21$, i.e. 21%, not 20%." } },
{ id: "logaritmer",
  nb: { t: "Logaritmer",
    intro: "Logaritmen er den omvendte operasjonen av potens: $\\log_b x=y$ betyr $b^y=x$. Vi bruker logaritmer til å løse ligninger der den ukjente står i eksponenten.",
    f: [["\\log_b x = y \\iff b^y = x", "definisjon av logaritme"], ["\\ln(ab) = \\ln a + \\ln b,\\quad \\ln(a^n) = n\\ln a", "regneregler for logaritmer"]],
    legend: [["b", "grunntall", ""], ["x", "argument, $x>0$", ""]],
    ex: "Løs $1{,}05^t = 1{,}5$: $t = \\dfrac{\\ln 1{,}5}{\\ln 1{,}05} \\approx 8{,}31$.",
    tip: "$\\ln(a+b)$ er ikke $\\ln a + \\ln b$ - logaritmen av en sum kan ikke forenkles slik." },
  en: { t: "Logarithms",
    intro: "The logarithm is the inverse operation of a power: $\\log_b x=y$ means $b^y=x$. We use logarithms to solve equations where the unknown is in the exponent.",
    f: [["\\log_b x = y \\iff b^y = x", "definition of a logarithm"], ["\\ln(ab) = \\ln a + \\ln b,\\quad \\ln(a^n) = n\\ln a", "logarithm rules"]],
    legend: [["b", "base", ""], ["x", "argument, $x>0$", ""]],
    ex: "Solve $1.05^t = 1.5$: $t = \\dfrac{\\ln 1.5}{\\ln 1.05} \\approx 8.31$.",
    tip: "$\\ln(a+b)$ is not $\\ln a + \\ln b$ - the logarithm of a sum cannot be simplified that way." } },
{ id: "halveringstid",
  nb: { t: "Halverings- og doblingstid",
    intro: "Halveringstiden er tiden det tar før en avtagende størrelse er halvert, og doblingstiden er den tilsvarende tiden for en voksende størrelse. Begge finnes direkte fra vekstraten $k$.",
    f: [["T = \\frac{\\ln 2}{|k|}", "halverings- eller doblingstid"]],
    legend: [["T", "halverings- eller doblingstid", "tid"], ["k", "vekstrate", "1/tid"]],
    ex: "En radioaktiv kilde avtar med 12 % per år: $k=\\ln 0{,}88 \\approx -0{,}128$, så $T=\\dfrac{\\ln 2}{0{,}128}\\approx 5{,}42$ år.",
    tip: "Formelen gjelder uansett hvor du starter på kurven - halveringstiden er alltid den samme for eksponentiell nedgang." },
  en: { t: "Half-life and doubling time",
    intro: "The half-life is the time it takes for a decreasing quantity to be halved, and the doubling time is the corresponding time for a growing quantity. Both follow directly from the growth rate $k$.",
    f: [["T = \\frac{\\ln 2}{|k|}", "half-life or doubling time"]],
    legend: [["T", "half-life or doubling time", "time"], ["k", "growth rate", "1/time"]],
    ex: "A radioactive source decays by 12% per year: $k=\\ln 0.88 \\approx -0.128$, so $T=\\dfrac{\\ln 2}{0.128}\\approx 5.42$ years.",
    tip: "The formula holds no matter where you start on the curve - the half-life is always the same for exponential decay." } }
]);

// Enhet 5: Trigonometri og geometri
TOPICS("GMAT", 5, [
{ id: "trigonometri",
  fig: `<svg viewBox="0 0 240 140"><path d="M40 120H200V30L40 120Z" class="d"/><path d="M180 120V100H200V120" class="dim"/><path d="M60 120a20 20 0 0 1 18-9" class="t"/><text x="65" y="112">v</text><text x="115" y="132">b</text><text x="207" y="78">a</text><text x="105" y="70">c</text></svg>`,
  nb: { t: "Trigonometri i rettvinklet trekant",
    intro: "I en rettvinklet trekant knytter sinus, cosinus og tangens vinkelen $v$ til forholdet mellom sidene. Pythagoras' setning knytter sidene sammen uten vinkler.",
    f: [["\\sin v = \\frac{\\text{motstående}}{\\text{hypotenus}},\\ \\cos v = \\frac{\\text{hosliggende}}{\\text{hypotenus}}", "sinus og cosinus"], ["a^2 + b^2 = c^2", "Pythagoras' setning, $c$ er hypotenusen"]],
    legend: [["v", "spiss vinkel", "°"], ["c", "hypotenus (lengste side)", ""]],
    ex: "En rampe er 4,0 m lang og hever seg 0,80 m: $\\sin v = \\frac{0{,}80}{4{,}0}=0{,}20 \\Rightarrow v\\approx 11{,}5^\\circ$, og bakkelengden er $\\sqrt{4{,}0^2-0{,}80^2}\\approx 3{,}92$ m.",
    tip: "Sjekk at kalkulatoren står i DEG når vinkelen er i grader, ellers blir svaret helt feil." },
  en: { t: "Trigonometry in a right triangle",
    intro: "In a right triangle, sine, cosine and tangent relate the angle $v$ to the ratio between the sides. The Pythagorean theorem relates the sides without any angles.",
    f: [["\\sin v = \\frac{\\text{opposite}}{\\text{hypotenuse}},\\ \\cos v = \\frac{\\text{adjacent}}{\\text{hypotenuse}}", "sine and cosine"], ["a^2 + b^2 = c^2", "the Pythagorean theorem, $c$ is the hypotenuse"]],
    legend: [["v", "acute angle", "°"], ["c", "hypotenuse (longest side)", ""]],
    ex: "A ramp is 4.0 m long and rises 0.80 m: $\\sin v = \\frac{0.80}{4.0}=0.20 \\Rightarrow v\\approx 11.5^\\circ$, and the ground length is $\\sqrt{4.0^2-0.80^2}\\approx 3.92$ m.",
    tip: "Check that the calculator is in DEG mode when the angle is in degrees, otherwise the answer is completely wrong." } },
{ id: "enhetssirkel",
  fig: `<svg viewBox="0 0 240 140"><path d="M60 75H180M120 15V135" class="dim"/><circle cx="120" cy="75" r="50" class="d"/><path d="M120 75L156 40" class="a"/><path d="M156 40l-16 3 3 15z" class="af"/><path d="M140 75a20 20 0 0 1-6-17" class="t"/><text x="145" y="70">v</text><text x="160" y="35">P</text></svg>`,
  nb: { t: "Enhetssirkelen og radianer",
    intro: "Enhetssirkelen definerer sinus og cosinus for alle vinkler, ikke bare de spisse: punktet med vinkel $v$ fra positiv x-akse har koordinatene $(\\cos v,\\sin v)$. Radianer er en alternativ måte å måle vinkler på, der en hel omdreining er $2\\pi$.",
    f: [["\\text{rad} = \\text{grader}\\cdot\\frac{\\pi}{180}", "omregning mellom grader og radianer"], ["\\sin^2 v + \\cos^2 v = 1", "enhetssirkel-identiteten"]],
    legend: [["v", "vinkel", "rad eller °"], ["P", "punktet $(\\cos v,\\sin v)$ på sirkelen", ""]],
    ex: "$210^\\circ = 210\\cdot\\frac{\\pi}{180} = \\frac{7\\pi}{6}\\approx 3{,}67$ rad, og $\\sin 210^\\circ=-0{,}5$.",
    tip: "Fortegnet til $\\sin$ og $\\cos$ avhenger av hvilken kvadrant punktet $P$ ligger i." },
  en: { t: "The unit circle and radians",
    intro: "The unit circle defines sine and cosine for all angles, not just acute ones: the point at angle $v$ from the positive x-axis has coordinates $(\\cos v,\\sin v)$. Radians are an alternative way to measure angles, where a full turn is $2\\pi$.",
    f: [["\\text{rad} = \\text{degrees}\\cdot\\frac{\\pi}{180}", "converting between degrees and radians"], ["\\sin^2 v + \\cos^2 v = 1", "the unit circle identity"]],
    legend: [["v", "angle", "rad or °"], ["P", "the point $(\\cos v,\\sin v)$ on the circle", ""]],
    ex: "$210^\\circ = 210\\cdot\\frac{\\pi}{180} = \\frac{7\\pi}{6}\\approx 3.67$ rad, and $\\sin 210^\\circ=-0.5$.",
    tip: "The sign of $\\sin$ and $\\cos$ depends on which quadrant the point $P$ is in." } },
{ id: "sinus-cosinussetning",
  fig: `<svg viewBox="0 0 240 140"><path d="M40 120L190 120L140 30Z" class="d"/><text x="105" y="132">c</text><text x="170" y="80">a</text><text x="85" y="80">b</text><text x="30" y="128">A</text><text x="195" y="128">B</text><text x="140" y="22">C</text></svg>`,
  nb: { t: "Sinus- og cosinussetningen",
    intro: "I en vilkårlig trekant, uten rett vinkel, brukes sinussetningen når vi kjenner en side og vinkelen rett overfor den, og cosinussetningen når vi kjenner to sider og vinkelen mellom dem.",
    f: [["\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C}", "sinussetningen"], ["c^2 = a^2 + b^2 - 2ab\\cos C", "cosinussetningen"]],
    legend: [["a,\\ b,\\ c", "sider i trekanten", ""], ["A,\\ B,\\ C", "vinklene motsatt sidene $a,b,c$", "°"]],
    ex: "To stenger på 3,0 m og 5,0 m er festet med $60^\\circ$ mellom seg: $c=\\sqrt{3^2+5^2-2\\cdot3\\cdot5\\cos60^\\circ}=\\sqrt{19}\\approx 4{,}36$ m.",
    tip: "Sinussetningen kan gi to mulige vinkler ($v$ og $180^\\circ-v$) - sjekk hvilken som passer med figuren." },
  en: { t: "The law of sines and cosines",
    intro: "In an arbitrary triangle, without a right angle, the law of sines is used when we know a side and the angle opposite it, and the law of cosines when we know two sides and the angle between them.",
    f: [["\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C}", "the law of sines"], ["c^2 = a^2 + b^2 - 2ab\\cos C", "the law of cosines"]],
    legend: [["a,\\ b,\\ c", "sides of the triangle", ""], ["A,\\ B,\\ C", "angles opposite the sides $a,b,c$", "°"]],
    ex: "Two rods, 3.0 m and 5.0 m, are joined with $60^\\circ$ between them: $c=\\sqrt{3^2+5^2-2\\cdot3\\cdot5\\cos60^\\circ}=\\sqrt{19}\\approx 4.36$ m.",
    tip: "The law of sines can give two possible angles ($v$ and $180^\\circ-v$) - check which one fits the figure." } }
]);

// Enhet 6: Vektorer
TOPICS("GMAT", 6, [
{ id: "vektorkomponenter",
  fig: `<svg viewBox="0 0 240 140"><path d="M40 115H210M40 115V15" class="dim"/><path d="M40 115L150 45" class="a"/><path d="M150 45l-14 1 6 12z" class="af"/><path d="M40 115H150" class="d"/><path d="M150 115V45" class="d"/><path d="M75 115a35 35 0 0 0-4-17" class="t"/><text x="90" y="72">a</text><text x="85" y="132">a<tspan dy="4" font-size="10">x</tspan></text><text x="157" y="82">a<tspan dy="4" font-size="10">y</tspan></text><text x="82" y="107">θ</text></svg>`,
  nb: { t: "Vektorkomponenter",
    intro: "En vektor $\\vec a$ har både størrelse og retning, og kan deles opp i en x- og en y-komponent. Det gjør det enkelt å legge sammen flere vektorer: legg sammen komponentene hver for seg.",
    f: [["\\vec a = (a_x, a_y)", "komponentform"], ["|\\vec a| = \\sqrt{a_x^2+a_y^2}", "lengden av vektoren"], ["a_x = |\\vec a|\\cos\\theta,\\ a_y = |\\vec a|\\sin\\theta", "komponenter fra lengde og vinkel"]],
    legend: [["a_x,\\ a_y", "komponenter", ""], ["\\theta", "vinkel fra x-aksen", "°"]],
    ex: "En vektor med lengde 10 og vinkel $37^\\circ$: $a_x=10\\cos37^\\circ\\approx 7{,}99$ og $a_y=10\\sin37^\\circ\\approx 6{,}02$.",
    tip: "Vektorer legges sammen ved å legge sammen komponentene, aldri ved å legge sammen lengdene direkte." },
  en: { t: "Vector components",
    intro: "A vector $\\vec a$ has both magnitude and direction, and can be split into an x- and a y-component. This makes it easy to add several vectors: add the components separately.",
    f: [["\\vec a = (a_x, a_y)", "component form"], ["|\\vec a| = \\sqrt{a_x^2+a_y^2}", "magnitude of the vector"], ["a_x = |\\vec a|\\cos\\theta,\\ a_y = |\\vec a|\\sin\\theta", "components from magnitude and angle"]],
    legend: [["a_x,\\ a_y", "components", ""], ["\\theta", "angle from the x-axis", "°"]],
    ex: "A vector of length 10 at angle $37^\\circ$: $a_x=10\\cos37^\\circ\\approx 7.99$ and $a_y=10\\sin37^\\circ\\approx 6.02$.",
    tip: "Vectors are added by adding the components, never by adding the magnitudes directly." } },
{ id: "skalarprodukt",
  nb: { t: "Skalarproduktet",
    intro: "Skalarproduktet (prikkproduktet) av to vektorer gir et tall, ikke en vektor. Det brukes til å finne vinkelen mellom vektorer, og til å regne ut arbeid: $W=\\vec F\\cdot\\vec s$.",
    f: [["\\vec a\\cdot\\vec b = a_xb_x + a_yb_y", "skalarprodukt, komponentform"], ["\\vec a\\cdot\\vec b = |\\vec a||\\vec b|\\cos\\theta", "skalarprodukt, geometrisk form"]],
    legend: [["\\theta", "vinkel mellom vektorene", "°"]],
    ex: "$\\vec a=(3,4)$ og $\\vec b=(4,-3)$: $\\vec a\\cdot\\vec b=12-12=0$, så vektorene står vinkelrett på hverandre.",
    tip: "Skalarproduktet er null nøyaktig når vektorene står vinkelrett på hverandre." },
  en: { t: "The dot product",
    intro: "The dot product (scalar product) of two vectors gives a number, not a vector. It is used to find the angle between vectors, and to calculate work: $W=\\vec F\\cdot\\vec s$.",
    f: [["\\vec a\\cdot\\vec b = a_xb_x + a_yb_y", "dot product, component form"], ["\\vec a\\cdot\\vec b = |\\vec a||\\vec b|\\cos\\theta", "dot product, geometric form"]],
    legend: [["\\theta", "angle between the vectors", "°"]],
    ex: "$\\vec a=(3,4)$ and $\\vec b=(4,-3)$: $\\vec a\\cdot\\vec b=12-12=0$, so the vectors are perpendicular.",
    tip: "The dot product is zero exactly when the vectors are perpendicular." } },
{ id: "moment-kryssprodukt",
  fig: `<svg viewBox="0 0 240 140"><circle cx="50" cy="105" r="4" class="af"/><path d="M50 105L170 60" class="d"/><path d="M170 60L170 20" class="a"/><path d="M170 20l-7 12h14z" class="af"/><path d="M75 95a30 25 0 0 1 15-22" class="t"/><text x="35" y="100">O</text><text x="178" y="40">F</text><text x="100" y="90">r</text><text x="68" y="80">M</text></svg>`,
  nb: { t: "Moment som kryssprodukt",
    intro: "Momentet av en kraft om et punkt kan regnes ut med vektorer i planet, uten å måle vinkler direkte. Det er $z$-komponenten av kryssproduktet mellom armvektoren og kraften.",
    f: [["M = r_xF_y - r_yF_x", "moment om O, $\\vec r$ er vektoren fra O til angrepspunktet"]],
    legend: [["\\vec r", "vektor fra punktet til angrepspunktet", ""], ["\\vec F", "kraft", "N"]],
    ex: "$\\vec r=(0{,}3,0)$ m og $\\vec F=(0,50)$ N: $M = 0{,}3\\cdot50 - 0\\cdot0 = 15$ Nm.",
    tip: "Positivt fortegn betyr moment mot klokka, negativt betyr med klokka." },
  en: { t: "Moment as a cross product",
    intro: "The moment of a force about a point can be found using vectors in the plane, without measuring angles directly. It is the $z$-component of the cross product between the arm vector and the force.",
    f: [["M = r_xF_y - r_yF_x", "moment about O, $\\vec r$ is the vector from O to the point of application"]],
    legend: [["\\vec r", "vector from the point to the point of application", ""], ["\\vec F", "force", "N"]],
    ex: "$\\vec r=(0.3,0)$ m and $\\vec F=(0,50)$ N: $M = 0.3\\cdot50 - 0\\cdot0 = 15$ Nm.",
    tip: "A positive sign means the moment is counterclockwise, a negative sign clockwise." } }
]);

// =====================================================================
// MEK1000: Kalkulus
// =====================================================================

// Enhet 0: Derivasjon
TOPICS("MEK1000", 0, [
{ id: "derivasjonsregler",
  nb: { t: "Produkt- og kjerneregel",
    intro: "Når en funksjon er satt sammen av flere funksjoner, må vi bruke egne regler for å derivere den. Produktregelen gjelder for et produkt av to funksjoner, og kjerneregelen for en funksjon inni en annen funksjon.",
    f: [["(fg)' = f'g + fg'", "produktregelen"], ["\\left(\\frac{f}{g}\\right)' = \\frac{f'g - fg'}{g^2}", "brøkregelen"], ["\\big(f(g(x))\\big)' = f'(g(x))\\cdot g'(x)", "kjerneregelen"]],
    legend: [["f,\\ g", "funksjoner av x", ""]],
    ex: "$f(x)=x^2e^x$: $f'(x) = 2xe^x + x^2e^x$ (produktregelen), så $f'(0)=0$.",
    tip: "I brøkregelen kommer minus foran andre ledd og $g^2$ i nevneren - ikke bytt om på leddene." },
  en: { t: "Product and chain rule",
    intro: "When a function is built up from several functions, we need special rules to differentiate it. The product rule applies to a product of two functions, and the chain rule to a function inside another function.",
    f: [["(fg)' = f'g + fg'", "the product rule"], ["\\left(\\frac{f}{g}\\right)' = \\frac{f'g - fg'}{g^2}", "the quotient rule"], ["\\big(f(g(x))\\big)' = f'(g(x))\\cdot g'(x)", "the chain rule"]],
    legend: [["f,\\ g", "functions of x", ""]],
    ex: "$f(x)=x^2e^x$: $f'(x) = 2xe^x + x^2e^x$ (product rule), so $f'(0)=0$.",
    tip: "In the quotient rule the minus sign and $g^2$ in the denominator matter - don't swap the terms." } },
{ id: "standardderiverte",
  nb: { t: "Standardderiverte",
    intro: "Noen funksjoner går igjen så ofte at det lønner seg å kunne de deriverte utenat: eksponentialfunksjonen, den naturlige logaritmen og de trigonometriske funksjonene.",
    f: [["\\frac{d}{dx}e^x = e^x", "eksponentialfunksjonen"], ["\\frac{d}{dx}\\ln x = \\frac{1}{x}", "naturlig logaritme"], ["\\frac{d}{dx}\\sin x = \\cos x,\\quad \\frac{d}{dx}\\cos x = -\\sin x", "sinus og cosinus"]],
    legend: [["e", "Eulers tall, $\\approx 2{,}718$", ""]],
    ex: "Med kjerneregelen: $\\dfrac{d}{dx}\\sin(2x) = 2\\cos(2x)$ og $\\dfrac{d}{dx}e^{x^2} = 2x\\,e^{x^2}$.",
    tip: "Glem ikke å gange med den indre deriverte når argumentet ikke bare er $x$." },
  en: { t: "Standard derivatives",
    intro: "Some functions appear so often that it pays to know their derivatives by heart: the exponential function, the natural logarithm and the trigonometric functions.",
    f: [["\\frac{d}{dx}e^x = e^x", "the exponential function"], ["\\frac{d}{dx}\\ln x = \\frac{1}{x}", "the natural logarithm"], ["\\frac{d}{dx}\\sin x = \\cos x,\\quad \\frac{d}{dx}\\cos x = -\\sin x", "sine and cosine"]],
    legend: [["e", "Euler's number, $\\approx 2.718$", ""]],
    ex: "With the chain rule: $\\dfrac{d}{dx}\\sin(2x) = 2\\cos(2x)$ and $\\dfrac{d}{dx}e^{x^2} = 2x\\,e^{x^2}$.",
    tip: "Don't forget to multiply by the inner derivative when the argument is not just $x$." } },
{ id: "kritiske-punkter",
  nb: { t: "Ekstremalpunkter",
    intro: "I et ekstremalpunkt (topp- eller bunnpunkt) er stigningstallet til tangenten null. Fortegnet til den andrederiverte forteller om det er et maksimum eller et minimum.",
    f: [["f'(x) = 0", "kritisk punkt"], ["f''(x) > 0 \\Rightarrow \\text{minimum},\\quad f''(x) < 0 \\Rightarrow \\text{maksimum}", "andrederiverttesten"]],
    legend: [["f'(x)", "stigningstallet til tangenten", ""], ["f''(x)", "krumningen (konkav opp/ned)", ""]],
    ex: "$f(x)=x^2-4x$: $f'(x)=2x-4=0 \\Rightarrow x=2$, og $f''(x)=2>0$, så $x=2$ er et minimum, $f(2)=-4$.",
    tip: "$f'(x)=0$ alene garanterer ikke et ekstremalpunkt - sjekk også $f''(x)$, eller om fortegnet til $f'$ skifter." },
  en: { t: "Extreme points",
    intro: "At an extreme point (a maximum or minimum) the slope of the tangent is zero. The sign of the second derivative tells us whether it is a maximum or a minimum.",
    f: [["f'(x) = 0", "critical point"], ["f''(x) > 0 \\Rightarrow \\text{minimum},\\quad f''(x) < 0 \\Rightarrow \\text{maximum}", "the second derivative test"]],
    legend: [["f'(x)", "slope of the tangent", ""], ["f''(x)", "curvature (concave up/down)", ""]],
    ex: "$f(x)=x^2-4x$: $f'(x)=2x-4=0 \\Rightarrow x=2$, and $f''(x)=2>0$, so $x=2$ is a minimum, $f(2)=-4$.",
    tip: "$f'(x)=0$ alone does not guarantee an extreme point - also check $f''(x)$, or whether the sign of $f'$ changes." } }
]);

// Enhet 1: Integrasjon
TOPICS("MEK1000", 1, [
{ id: "bestemt-integral",
  nb: { t: "Bestemt integral",
    intro: "Analysens fundamentalteorem knytter derivasjon og integrasjon sammen: for å regne ut et bestemt integral finner vi en antiderivert $F$ og setter inn grensene.",
    f: [["\\int_a^b f(x)\\,dx = F(b) - F(a)", "analysens fundamentalteorem, der $F'=f$"]],
    legend: [["F", "en antiderivert til f", ""], ["a,\\ b", "integrasjonsgrenser", ""]],
    ex: "$\\displaystyle\\int_0^{\\pi}\\sin x\\,dx = [-\\cos x]_0^{\\pi} = 1-(-1) = 2$.",
    tip: "Husk å sette inn øvre grense minus nedre grense, i den rekkefølgen." },
  en: { t: "Definite integral",
    intro: "The fundamental theorem of calculus links differentiation and integration: to compute a definite integral we find an antiderivative $F$ and plug in the limits.",
    f: [["\\int_a^b f(x)\\,dx = F(b) - F(a)", "the fundamental theorem of calculus, where $F'=f$"]],
    legend: [["F", "an antiderivative of f", ""], ["a,\\ b", "limits of integration", ""]],
    ex: "$\\displaystyle\\int_0^{\\pi}\\sin x\\,dx = [-\\cos x]_0^{\\pi} = 1-(-1) = 2$.",
    tip: "Remember to substitute the upper limit minus the lower limit, in that order." } },
{ id: "delvis-integrasjon",
  nb: { t: "Delvis integrasjon",
    intro: "Delvis integrasjon brukes når integranden er et produkt av to funksjoner, og kommer direkte fra produktregelen for derivasjon. Man velger $u$ og $v'$ slik at det gjenstående integralet blir enklere.",
    f: [["\\int u\\,v'\\,dx = uv - \\int u'\\,v\\,dx", "delvis integrasjon"]],
    legend: [["u", "deriveres", ""], ["v'", "integreres til v", ""]],
    ex: "$\\displaystyle\\int xe^x\\,dx$ med $u=x,\\ v'=e^x$: $= xe^x - \\int e^x\\,dx = (x-1)e^x + C$.",
    tip: "Velg $u$ som blir enklere når den deriveres (som $x$), og $v'$ som er enkel å integrere (som $e^x$)." },
  en: { t: "Integration by parts",
    intro: "Integration by parts is used when the integrand is a product of two functions, and follows directly from the product rule for differentiation. We choose $u$ and $v'$ so the remaining integral becomes simpler.",
    f: [["\\int u\\,v'\\,dx = uv - \\int u'\\,v\\,dx", "integration by parts"]],
    legend: [["u", "differentiated", ""], ["v'", "integrated to give v", ""]],
    ex: "$\\displaystyle\\int xe^x\\,dx$ with $u=x,\\ v'=e^x$: $= xe^x - \\int e^x\\,dx = (x-1)e^x + C$.",
    tip: "Choose $u$ so it gets simpler when differentiated (like $x$), and $v'$ easy to integrate (like $e^x$)." } },
{ id: "substitusjon",
  nb: { t: "Substitusjon",
    intro: "Substitusjon er integrasjonens motstykke til kjerneregelen. Ved å bytte ut en del av integranden med en ny variabel $u$, kan et vanskelig integral bli et enkelt et.",
    f: [["\\int f(g(x))\\,g'(x)\\,dx = \\int f(u)\\,du,\\quad u=g(x)", "substitusjonsregelen"]],
    legend: [["u", "ny variabel, $u=g(x)$", ""]],
    ex: "$\\displaystyle\\int 2x\\cos(x^2)\\,dx$ med $u=x^2$, $du=2x\\,dx$: $= \\int\\cos u\\,du = \\sin(x^2)+C$.",
    tip: "Se etter en faktor i integranden som er den deriverte av resten - det er ofte tegnet på riktig substitusjon." },
  en: { t: "Substitution",
    intro: "Substitution is the integration counterpart of the chain rule. By replacing part of the integrand with a new variable $u$, a difficult integral can become a simple one.",
    f: [["\\int f(g(x))\\,g'(x)\\,dx = \\int f(u)\\,du,\\quad u=g(x)", "the substitution rule"]],
    legend: [["u", "new variable, $u=g(x)$", ""]],
    ex: "$\\displaystyle\\int 2x\\cos(x^2)\\,dx$ with $u=x^2$, $du=2x\\,dx$: $= \\int\\cos u\\,du = \\sin(x^2)+C$.",
    tip: "Look for a factor in the integrand that is the derivative of the rest - that is often the sign of the right substitution." } }
]);

// Enhet 2: Grenser, rekker og komplekse tall
TOPICS("MEK1000", 2, [
{ id: "grenser-lhopital",
  nb: { t: "Grenser og L'Hôpital",
    intro: "En grenseverdi beskriver hva en funksjon nærmer seg når $x$ nærmer seg et bestemt punkt, selv om funksjonen kanskje ikke er definert akkurat der. L'Hôpitals regel gir en snarvei når vi ellers ville fått $0/0$ eller $\\infty/\\infty$.",
    f: [["\\lim_{x\\to a}\\frac{f(x)}{g(x)} = \\lim_{x\\to a}\\frac{f'(x)}{g'(x)}", "L'Hôpitals regel (ved $0/0$ eller $\\infty/\\infty$)"]],
    legend: [["a", "punktet grensen tas mot", ""]],
    ex: "$\\displaystyle\\lim_{x\\to0}\\frac{\\sin x}{x} = 1$ (typen $0/0$).",
    tip: "L'Hôpital gjelder bare for $0/0$ eller $\\infty/\\infty$ - andre former må skrives om først." },
  en: { t: "Limits and L'Hôpital",
    intro: "A limit describes what a function approaches as $x$ approaches a certain point, even if the function may not be defined exactly there. L'Hôpital's rule gives a shortcut whenever we would otherwise get $0/0$ or $\\infty/\\infty$.",
    f: [["\\lim_{x\\to a}\\frac{f(x)}{g(x)} = \\lim_{x\\to a}\\frac{f'(x)}{g'(x)}", "L'Hôpital's rule (for $0/0$ or $\\infty/\\infty$)"]],
    legend: [["a", "the point the limit is taken towards", ""]],
    ex: "$\\displaystyle\\lim_{x\\to0}\\frac{\\sin x}{x} = 1$ (the type $0/0$).",
    tip: "L'Hôpital only applies to $0/0$ or $\\infty/\\infty$ - other forms must be rewritten first." } },
{ id: "taylorrekke",
  nb: { t: "Taylorrekke",
    intro: "En Taylorrekke tilnærmer en funksjon med et polynom bygd av funksjonens deriverte i ett punkt. Jo flere ledd vi tar med, desto bedre blir tilnærmingen nær punktet.",
    f: [["e^x = 1 + x + \\frac{x^2}{2!} + \\frac{x^3}{3!} + \\dots", "Taylorrekken til $e^x$ om $x=0$"]],
    legend: [["n!", "$n$-fakultet", ""]],
    ex: "Tilnærm $e^{0{,}1}$ med grad 2: $1+0{,}1+\\frac{0{,}1^2}{2}=1{,}105$ (eksakt verdi $\\approx 1{,}1052$).",
    tip: "Nærmere utviklingspunktet gir en bedre tilnærming for et gitt antall ledd." },
  en: { t: "Taylor series",
    intro: "A Taylor series approximates a function with a polynomial built from the function's derivatives at one point. The more terms we include, the better the approximation near that point.",
    f: [["e^x = 1 + x + \\frac{x^2}{2!} + \\frac{x^3}{3!} + \\dots", "the Taylor series of $e^x$ about $x=0$"]],
    legend: [["n!", "$n$ factorial", ""]],
    ex: "Approximate $e^{0.1}$ to degree 2: $1+0.1+\\frac{0.1^2}{2}=1.105$ (exact value $\\approx 1.1052$).",
    tip: "Closer to the expansion point gives a better approximation for a given number of terms." } },
{ id: "komplekse-tall",
  nb: { t: "Komplekse tall",
    intro: "Et komplekst tall $z=a+bi$ har en reell og en imaginær del, der $i^2=-1$. Eulers formel knytter komplekse eksponentialfunksjoner til sinus og cosinus.",
    f: [["z = a+bi,\\quad i^2=-1", "kartesisk form"], ["|z| = \\sqrt{a^2+b^2}", "modulus (lengde)"], ["e^{i\\theta} = \\cos\\theta + i\\sin\\theta", "Eulers formel"]],
    legend: [["a,\\ b", "realdel, imaginærdel", ""], ["\\bar z", "konjugert: $a-bi$", ""]],
    ex: "$|3+4i| = \\sqrt{9+16}=5$, og $e^{i\\pi}=\\cos\\pi+i\\sin\\pi=-1$.",
    tip: "$i^2=-1$ er alt man trenger å huske - alle andre regler følger av vanlig algebra." },
  en: { t: "Complex numbers",
    intro: "A complex number $z=a+bi$ has a real and an imaginary part, where $i^2=-1$. Euler's formula connects complex exponentials to sine and cosine.",
    f: [["z = a+bi,\\quad i^2=-1", "Cartesian form"], ["|z| = \\sqrt{a^2+b^2}", "modulus (magnitude)"], ["e^{i\\theta} = \\cos\\theta + i\\sin\\theta", "Euler's formula"]],
    legend: [["a,\\ b", "real part, imaginary part", ""], ["\\bar z", "conjugate: $a-bi$", ""]],
    ex: "$|3+4i| = \\sqrt{9+16}=5$, and $e^{i\\pi}=\\cos\\pi+i\\sin\\pi=-1$.",
    tip: "$i^2=-1$ is all you need to remember - every other rule follows from ordinary algebra." } }
]);

// =====================================================================
// MEK2000: Lineær algebra og differensialligninger
// =====================================================================

// Enhet 0: Matriser
TOPICS("MEK2000", 0, [
{ id: "determinant",
  nb: { t: "Determinant (2×2)",
    intro: "Determinanten til en kvadratisk matrise er et enkelt tall som forteller mye om matrisen, blant annet om den har en invers. For en 2×2-matrise regnes den ut direkte fra elementene.",
    f: [["\\det\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix} = ad-bc", "2×2-determinant"]],
    legend: [["\\det A", "determinanten til A", ""]],
    ex: "$\\det\\begin{pmatrix}2&1\\\\3&4\\end{pmatrix} = 2\\cdot4-1\\cdot3 = 5$.",
    tip: "$\\det A=0$ betyr at $A$ ikke er inverterbar, og at kolonnene er lineært avhengige." },
  en: { t: "Determinant (2×2)",
    intro: "The determinant of a square matrix is a single number that tells us a lot about the matrix, including whether it has an inverse. For a 2×2 matrix it is computed directly from the entries.",
    f: [["\\det\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix} = ad-bc", "2×2 determinant"]],
    legend: [["\\det A", "the determinant of A", ""]],
    ex: "$\\det\\begin{pmatrix}2&1\\\\3&4\\end{pmatrix} = 2\\cdot4-1\\cdot3 = 5$.",
    tip: "$\\det A=0$ means $A$ is not invertible, and that the columns are linearly dependent." } },
{ id: "matrisemultiplikasjon",
  nb: { t: "Matrisemultiplikasjon",
    intro: "Å multiplisere matriser gjøres rad ganger kolonne, og er ikke det samme som å gange elementvis. Rekkefølgen betyr noe: generelt er $AB\\neq BA$.",
    f: [["(AB)_{ij} = \\sum_k A_{ik}B_{kj}", "element $ij$ i produktet, rad i A ganger kolonne j i B"], ["(AB)^T = B^TA^T", "transponert av et produkt (rekkefølgen snus)"]],
    legend: [["A^T", "transponert av A (rader og kolonner byttet)", ""]],
    ex: "$A=\\begin{pmatrix}-3&-2\\\\3&-3\\end{pmatrix}$, $B=\\begin{pmatrix}-2&-2\\\\-1&0\\end{pmatrix}$: $(AB)_{11}=(-3)(-2)+(-2)(-1)=8$.",
    tip: "$AB\\neq BA$ generelt - rekkefølgen på matrisene betyr like mye som rekkefølgen på rotasjoner." },
  en: { t: "Matrix multiplication",
    intro: "Multiplying matrices is done row times column, and is not the same as multiplying entrywise. The order matters: in general $AB\\neq BA$.",
    f: [["(AB)_{ij} = \\sum_k A_{ik}B_{kj}", "entry $ij$ of the product, row i of A times column j of B"], ["(AB)^T = B^TA^T", "transpose of a product (order is reversed)"]],
    legend: [["A^T", "transpose of A (rows and columns swapped)", ""]],
    ex: "$A=\\begin{pmatrix}-3&-2\\\\3&-3\\end{pmatrix}$, $B=\\begin{pmatrix}-2&-2\\\\-1&0\\end{pmatrix}$: $(AB)_{11}=(-3)(-2)+(-2)(-1)=8$.",
    tip: "$AB\\neq BA$ in general - the order of the matrices matters, just like the order of rotations." } },
{ id: "invers-matrise",
  nb: { t: "Invers matrise",
    intro: "Den inverse matrisen $A^{-1}$ oppfyller $AA^{-1}=I$, og finnes bare når $\\det A\\neq0$. Den fungerer omtrent som «å dele på en matrise»: den brukes til å løse $A\\vec x=\\vec b$ direkte som $\\vec x=A^{-1}\\vec b$. For en 2×2-matrise finnes det en enkel formel.",
    f: [["A^{-1} = \\frac{1}{\\det A}\\begin{pmatrix}d&-b\\\\-c&a\\end{pmatrix}", "invers av $A=\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}$"]],
    legend: [["I", "identitetsmatrisen (1 på diagonalen, 0 ellers)", ""]],
    ex: "$A=\\begin{pmatrix}2&1\\\\3&4\\end{pmatrix}$, $\\det A=5$: $A^{-1}=\\frac15\\begin{pmatrix}4&-1\\\\-3&2\\end{pmatrix}$.",
    tip: "Bytt diagonalen, skift fortegn på de to andre elementene, og del alt på determinanten." },
  en: { t: "Inverse matrix",
    intro: "The inverse matrix $A^{-1}$ satisfies $AA^{-1}=I$, and exists only when $\\det A\\neq0$. It works much like \"dividing by a matrix\": it is used to solve $A\\vec x=\\vec b$ directly as $\\vec x=A^{-1}\\vec b$. For a 2×2 matrix there is a simple formula.",
    f: [["A^{-1} = \\frac{1}{\\det A}\\begin{pmatrix}d&-b\\\\-c&a\\end{pmatrix}", "inverse of $A=\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}$"]],
    legend: [["I", "the identity matrix (1 on the diagonal, 0 elsewhere)", ""]],
    ex: "$A=\\begin{pmatrix}2&1\\\\3&4\\end{pmatrix}$, $\\det A=5$: $A^{-1}=\\frac15\\begin{pmatrix}4&-1\\\\-3&2\\end{pmatrix}$.",
    tip: "Swap the diagonal, flip the sign of the other two entries, and divide everything by the determinant." } }
]);

// Enhet 1: Lineære systemer og egenverdier
TOPICS("MEK2000", 1, [
{ id: "egenverdier",
  nb: { t: "Egenverdier og egenvektorer",
    intro: "En egenvektor $\\vec v$ til matrisen $A$ er en vektor som bare skaleres, ikke dreies, når vi multipliserer med $A$. Skaleringsfaktoren $\\lambda$ kalles egenverdien.",
    f: [["A\\vec v = \\lambda\\vec v,\\quad \\vec v\\neq\\vec 0", "egenverdiligningen"], ["\\det(A-\\lambda I) = 0", "karakteristisk ligning, gir egenverdiene"]],
    legend: [["\\lambda", "egenverdi", ""], ["\\vec v", "egenvektor", ""]],
    ex: "$A=\\begin{pmatrix}4&1\\\\2&3\\end{pmatrix}$: $\\lambda^2-7\\lambda+10=0$ gir $\\lambda=5$ og $\\lambda=2$.",
    tip: "Summen av egenverdiene er sporet til $A$, og produktet er $\\det A$ - en rask kontroll." },
  en: { t: "Eigenvalues and eigenvectors",
    intro: "An eigenvector $\\vec v$ of the matrix $A$ is a vector that is only scaled, not rotated, when multiplied by $A$. The scaling factor $\\lambda$ is called the eigenvalue.",
    f: [["A\\vec v = \\lambda\\vec v,\\quad \\vec v\\neq\\vec 0", "the eigenvalue equation"], ["\\det(A-\\lambda I) = 0", "characteristic equation, gives the eigenvalues"]],
    legend: [["\\lambda", "eigenvalue", ""], ["\\vec v", "eigenvector", ""]],
    ex: "$A=\\begin{pmatrix}4&1\\\\2&3\\end{pmatrix}$: $\\lambda^2-7\\lambda+10=0$ gives $\\lambda=5$ and $\\lambda=2$.",
    tip: "The sum of the eigenvalues is the trace of $A$, and the product is $\\det A$ - a quick check." } },
{ id: "linere-systemer",
  nb: { t: "Lineære systemer og rang",
    intro: "Rangen til en matrise er antall pivotelementer i trappeformen, og forteller hvor mange av likningene som faktisk er uavhengige. Har systemet flere ukjente enn rangen, blir noen variabler frie.",
    f: [["\\text{rang}(A) = \\text{antall pivotelementer}", "rangen til A"], ["\\text{antall frie variabler} = n - \\text{rang}(A)", "$n$ er antall ukjente"]],
    legend: [["n", "antall ukjente", ""]],
    ex: "Et system med 3 ligninger og 5 ukjente har rang høyst 3, så minst $5-3=2$ variabler blir frie.",
    tip: "Hvis $\\det A=0$ for et kvadratisk system, har $A\\vec x=\\vec 0$ også ikke-trivielle løsninger." },
  en: { t: "Linear systems and rank",
    intro: "The rank of a matrix is the number of pivot entries in its row echelon form, and tells us how many equations are actually independent. If a system has more unknowns than its rank, some variables become free.",
    f: [["\\text{rank}(A) = \\text{number of pivots}", "the rank of A"], ["\\text{free variables} = n - \\text{rank}(A)", "$n$ is the number of unknowns"]],
    legend: [["n", "number of unknowns", ""]],
    ex: "A system with 3 equations and 5 unknowns has rank at most 3, so at least $5-3=2$ variables are free.",
    tip: "If $\\det A=0$ for a square system, $A\\vec x=\\vec 0$ also has non-trivial solutions." } },
{ id: "basis-vektorrom",
  nb: { t: "Basis for et vektorrom",
    intro: "En basis for et vektorrom er en mengde lineært uavhengige vektorer som utspenner hele rommet - enhver vektor i rommet kan skrives entydig som en kombinasjon av basisvektorene.",
    f: [["\\text{basis: lineært uavhengige vektorer som utspenner rommet}", "definisjon av basis"]],
    legend: [["\\dim V", "dimensjonen til rommet V, antall basisvektorer", ""]],
    ex: "I $\\mathbb R^3$ er $\\vec e_1=(1,0,0),\\ \\vec e_2=(0,1,0),\\ \\vec e_3=(0,0,1)$ standardbasisen, og $\\dim\\mathbb R^3=3$.",
    tip: "Alle baser for samme vektorrom har like mange vektorer, lik romdimensjonen." },
  en: { t: "Basis of a vector space",
    intro: "A basis of a vector space is a set of linearly independent vectors that spans the whole space - every vector in the space can be written uniquely as a combination of the basis vectors.",
    f: [["\\text{basis: linearly independent vectors that span the space}", "definition of a basis"]],
    legend: [["\\dim V", "the dimension of the space V, number of basis vectors", ""]],
    ex: "In $\\mathbb R^3$, $\\vec e_1=(1,0,0),\\ \\vec e_2=(0,1,0),\\ \\vec e_3=(0,0,1)$ is the standard basis, and $\\dim\\mathbb R^3=3$.",
    tip: "Every basis of the same vector space has the same number of vectors, equal to the dimension." } }
]);

// Enhet 2: Differensialligninger
TOPICS("MEK2000", 2, [
{ id: "forste-ordens-de",
  nb: { t: "Første ordens differensialligning",
    intro: "En separabel differensialligning $y'=ky$ har løsning $y=Ce^{kx}$, der $C$ bestemmes av en initialbetingelse. For en mer generell lineær ligning $y'+p(x)y=q(x)$ bruker vi en integrerende faktor.",
    f: [["y' = ky\\ \\Rightarrow\\ y = Ce^{kx}", "separabel ligning, eksponentiell vekst/nedgang"], ["\\mu(x) = e^{\\int p(x)\\,dx}", "integrerende faktor for $y'+p(x)y=q(x)$"]],
    legend: [["k", "vekstrate (konstant)", ""], ["C", "konstant, bestemmes av $y(0)$", ""]],
    ex: "$y'=-2y$, $y(0)=5$: $y=5e^{-2x}$, så $y(\\ln 2)=5\\cdot2^{-2}=1{,}25$.",
    tip: "Ganger man ligningen med den integrerende faktoren $\\mu$, blir venstresiden $(\\mu y)'$." },
  en: { t: "First-order differential equation",
    intro: "A separable differential equation $y'=ky$ has solution $y=Ce^{kx}$, where $C$ is determined by an initial condition. For a more general linear equation $y'+p(x)y=q(x)$ we use an integrating factor.",
    f: [["y' = ky\\ \\Rightarrow\\ y = Ce^{kx}", "separable equation, exponential growth/decay"], ["\\mu(x) = e^{\\int p(x)\\,dx}", "integrating factor for $y'+p(x)y=q(x)$"]],
    legend: [["k", "growth rate (constant)", ""], ["C", "constant, determined by $y(0)$", ""]],
    ex: "$y'=-2y$, $y(0)=5$: $y=5e^{-2x}$, so $y(\\ln 2)=5\\cdot2^{-2}=1.25$.",
    tip: "Multiplying the equation by the integrating factor $\\mu$ turns the left side into $(\\mu y)'$." } },
{ id: "andre-ordens-homogen",
  nb: { t: "Andre ordens, reelle røtter",
    intro: "For en homogen andreordens ligning $y''+ay'+by=0$ med konstante koeffisienter setter vi opp den karakteristiske ligningen. Har den to forskjellige reelle røtter, blir den generelle løsningen en sum av to eksponentialfunksjoner.",
    f: [["r^2 + ar + b = 0", "karakteristisk ligning for $y''+ay'+by=0$"], ["y = C_1e^{r_1x} + C_2e^{r_2x}", "generell løsning, to forskjellige reelle røtter"]],
    legend: [["r_1,\\ r_2", "røtter av den karakteristiske ligningen", ""]],
    ex: "$y''-3y'+2y=0$: $r^2-3r+2=(r-1)(r-2)=0$ gir $r=1,2$, så $y=C_1e^x+C_2e^{2x}$.",
    tip: "Sett opp den karakteristiske ligningen ved å bytte $y''\\to r^2$, $y'\\to r$, $y\\to1$." },
  en: { t: "Second order, real roots",
    intro: "For a homogeneous second-order equation $y''+ay'+by=0$ with constant coefficients we set up the characteristic equation. If it has two distinct real roots, the general solution is a sum of two exponentials.",
    f: [["r^2 + ar + b = 0", "characteristic equation for $y''+ay'+by=0$"], ["y = C_1e^{r_1x} + C_2e^{r_2x}", "general solution, two distinct real roots"]],
    legend: [["r_1,\\ r_2", "roots of the characteristic equation", ""]],
    ex: "$y''-3y'+2y=0$: $r^2-3r+2=(r-1)(r-2)=0$ gives $r=1,2$, so $y=C_1e^x+C_2e^{2x}$.",
    tip: "Set up the characteristic equation by replacing $y''\\to r^2$, $y'\\to r$, $y\\to1$." } },
{ id: "dobbel-kompleks-rot",
  nb: { t: "Dobbel og kompleks rot",
    intro: "Når den karakteristiske ligningen har en dobbel rot, må den andre løsningen ha en ekstra faktor $x$ for å være uavhengig av den første. Når røttene er komplekse, $\\pm i\\beta$, blir løsningen sinus og cosinus i stedet for eksponentialfunksjoner.",
    f: [["(C_1 + C_2x)e^{rx}", "dobbel rot $r$"], ["C_1\\cos\\beta x + C_2\\sin\\beta x", "rent imaginære røtter $\\pm i\\beta$"]],
    legend: [["r", "den doble roten", ""], ["\\beta", "imaginærdel (svingefrekvens)", ""]],
    ex: "$y''+y=0$ har røtter $r=\\pm i$: $y=C_1\\cos x+C_2\\sin x$.\nDobbel rot $r=2$: $y=(C_1+C_2x)e^{2x}$.",
    tip: "En vanlig feil er å skrive $C_1e^{rx}+C_2e^{rx}$ ved dobbel rot - det er bare én løsning, ikke to." },
  en: { t: "Double and complex root",
    intro: "When the characteristic equation has a double root, the second solution needs an extra factor of $x$ to be independent of the first. When the roots are complex, $\\pm i\\beta$, the solution becomes sine and cosine instead of exponentials.",
    f: [["(C_1 + C_2x)e^{rx}", "double root $r$"], ["C_1\\cos\\beta x + C_2\\sin\\beta x", "purely imaginary roots $\\pm i\\beta$"]],
    legend: [["r", "the double root", ""], ["\\beta", "imaginary part (oscillation frequency)", ""]],
    ex: "$y''+y=0$ has roots $r=\\pm i$: $y=C_1\\cos x+C_2\\sin x$.\nDouble root $r=2$: $y=(C_1+C_2x)e^{2x}$.",
    tip: "A common mistake is writing $C_1e^{rx}+C_2e^{rx}$ for a double root - that is only one solution, not two." } }
]);

// =====================================================================
// DAVE3700: Flervariabel analyse
// =====================================================================

// Enhet 0: Partielle deriverte
TOPICS("DAVE3700", 0, [
{ id: "partiellderivert-gradient",
  nb: { t: "Partiellderivert og gradient",
    intro: "En partiellderivert deriverer med hensyn på én variabel om gangen, mens de andre holdes konstante. Gradienten $\\nabla f$ samler alle partiellderiverte i en vektor som peker i retningen der $f$ vokser raskest.",
    f: [["f_x = \\frac{\\partial f}{\\partial x}", "partiellderivert mhp x (y holdes konstant)"], ["\\nabla f = (f_x, f_y)", "gradienten"]],
    legend: [["\\nabla f", "gradientvektor, peker mot sterkest vekst", ""]],
    ex: "$f=x^2+y^2$ i $(3,4)$: $\\nabla f=(6,8)$, og $|\\nabla f|=\\sqrt{36+64}=10$.",
    tip: "Gradienten står alltid vinkelrett på nivåkurvene til $f$." },
  en: { t: "Partial derivative and gradient",
    intro: "A partial derivative differentiates with respect to one variable at a time, holding the others constant. The gradient $\\nabla f$ collects all partial derivatives into a vector pointing in the direction where $f$ increases fastest.",
    f: [["f_x = \\frac{\\partial f}{\\partial x}", "partial derivative w.r.t. x (y held constant)"], ["\\nabla f = (f_x, f_y)", "the gradient"]],
    legend: [["\\nabla f", "gradient vector, points towards steepest increase", ""]],
    ex: "$f=x^2+y^2$ at $(3,4)$: $\\nabla f=(6,8)$, and $|\\nabla f|=\\sqrt{36+64}=10$.",
    tip: "The gradient is always perpendicular to the level curves of $f$." } },
{ id: "andrederiverttest",
  nb: { t: "Andrederiverttesten",
    intro: "I et kritisk punkt der $\\nabla f=\\vec 0$ avgjør andrederiverttesten om det er et lokalt minimum, maksimum eller et sadelpunkt, ved hjelp av en diskriminant $D$ bygd av de andre partiellderiverte.",
    f: [["D = f_{xx}f_{yy} - f_{xy}^2", "testverdien"], ["D>0,\\ f_{xx}>0:\\ \\text{minimum}", "lokalt minimum"], ["D<0:\\ \\text{sadelpunkt}", "sadelpunkt"]],
    legend: [["D", "diskriminant for andrederiverttesten", ""], ["f_{xx},\\,f_{yy},\\,f_{xy}", "andre partielle deriverte", ""]],
    ex: "$f=3x^2+2y^2$ i origo: $f_{xx}=6,\\,f_{yy}=4,\\,f_{xy}=0$, $D=24>0$ og $f_{xx}>0$ - lokalt minimum.",
    tip: "$D<0$ gir alltid et sadelpunkt, uansett fortegn på $f_{xx}$." },
  en: { t: "The second derivative test",
    intro: "At a critical point where $\\nabla f=\\vec 0$, the second derivative test decides whether it is a local minimum, maximum or a saddle point, using a discriminant $D$ built from the second partial derivatives.",
    f: [["D = f_{xx}f_{yy} - f_{xy}^2", "the test value"], ["D>0,\\ f_{xx}>0:\\ \\text{minimum}", "local minimum"], ["D<0:\\ \\text{saddle point}", "saddle point"]],
    legend: [["D", "discriminant for the second derivative test", ""], ["f_{xx},\\,f_{yy},\\,f_{xy}", "second partial derivatives", ""]],
    ex: "$f=3x^2+2y^2$ at the origin: $f_{xx}=6,\\,f_{yy}=4,\\,f_{xy}=0$, $D=24>0$ and $f_{xx}>0$ - local minimum.",
    tip: "$D<0$ always gives a saddle point, whatever the sign of $f_{xx}$." } },
{ id: "lagrange-multiplikator",
  nb: { t: "Lagranges metode",
    intro: "Lagranges metode finner ekstremalpunkter for $f$ når $(x,y)$ er bundet til en kurve $g(x,y)=0$. I ekstremalpunktet er nivåkurven til $f$ tangent til bibetingelsen, så gradientene er parallelle.",
    f: [["\\nabla f = \\lambda\\nabla g", "Lagrange-betingelsen, sammen med $g=0$"]],
    legend: [["\\lambda", "Lagrange-multiplikator", ""], ["g(x,y)=0", "bibetingelsen", ""]],
    ex: "Maksimer $f=xy$ når $x+y=10$: $\\nabla f=(y,x)=\\lambda(1,1) \\Rightarrow x=y$, som med $x+y=10$ gir $x=y=5$ og $f=25$.",
    tip: "Lagranges metode gir kandidater til ekstremalpunkter - sjekk om de er maks eller min ved å sammenligne funksjonsverdier." },
  en: { t: "Lagrange multipliers",
    intro: "Lagrange's method finds extreme points of $f$ when $(x,y)$ is constrained to a curve $g(x,y)=0$. At the extreme point the level curve of $f$ is tangent to the constraint, so the gradients are parallel.",
    f: [["\\nabla f = \\lambda\\nabla g", "the Lagrange condition, together with $g=0$"]],
    legend: [["\\lambda", "Lagrange multiplier", ""], ["g(x,y)=0", "the constraint", ""]],
    ex: "Maximize $f=xy$ subject to $x+y=10$: $\\nabla f=(y,x)=\\lambda(1,1) \\Rightarrow x=y$, which with $x+y=10$ gives $x=y=5$ and $f=25$.",
    tip: "Lagrange's method gives candidates for extreme points - check whether they are a max or min by comparing function values." } }
]);

// Enhet 1: Multiple integraler
TOPICS("DAVE3700", 1, [
{ id: "dobbeltintegral",
  nb: { t: "Dobbeltintegral",
    intro: "Et dobbeltintegral summerer en funksjon over et areal, og regnes vanligvis ut som to vanlige integraler etter hverandre. Fubinis teorem sier at rekkefølgen på integrasjonen ikke spiller noen rolle for kontinuerlige funksjoner på et rektangel.",
    f: [["\\iint_R f(x,y)\\,dA = \\int\\!\\!\\int f(x,y)\\,dx\\,dy", "dobbeltintegral, Fubinis teorem"]],
    legend: [["dA", "arealelement", "m²"]],
    ex: "$\\displaystyle\\iint_{[0,1]\\times[0,1]} xy\\,dA = \\int_0^1 x\\,dx\\cdot\\int_0^1 y\\,dy = \\tfrac12\\cdot\\tfrac12 = 0{,}25$.",
    tip: "Når integranden er et produkt $f(x)g(y)$ på et rektangel, kan integralet splittes i to enkle integraler." },
  en: { t: "Double integral",
    intro: "A double integral sums a function over an area, and is usually computed as two ordinary integrals in a row. Fubini's theorem says the order of integration does not matter for continuous functions on a rectangle.",
    f: [["\\iint_R f(x,y)\\,dA = \\int\\!\\!\\int f(x,y)\\,dx\\,dy", "double integral, Fubini's theorem"]],
    legend: [["dA", "area element", "m²"]],
    ex: "$\\displaystyle\\iint_{[0,1]\\times[0,1]} xy\\,dA = \\int_0^1 x\\,dx\\cdot\\int_0^1 y\\,dy = \\tfrac12\\cdot\\tfrac12 = 0.25$.",
    tip: "When the integrand is a product $f(x)g(y)$ on a rectangle, the integral splits into two simple integrals." } },
{ id: "polarkoordinater",
  fig: `<svg viewBox="0 0 240 140"><path d="M50 115H210M50 115V25" class="dim"/><path d="M50 115L160 45" class="a"/><path d="M160 45l-15 2 7 12z" class="af"/><path d="M85 115a45 45 0 0 1 20-38" class="t"/><text x="95" y="98">r</text><text x="90" y="108">θ</text></svg>`,
  nb: { t: "Polarkoordinater",
    intro: "I polarkoordinater beskrives et punkt med avstand $r$ fra origo og vinkel $\\theta$. Arealelementet får en ekstra faktor $r$, som kommer fra Jacobi-determinanten ved variabelbyttet.",
    f: [["dA = r\\,dr\\,d\\theta", "arealelement i polarkoordinater"], ["x = r\\cos\\theta,\\ y = r\\sin\\theta", "sammenheng med kartesiske koordinater"]],
    legend: [["r", "avstand fra origo", ""], ["\\theta", "vinkel", "rad"]],
    ex: "Arealet av en enhetssirkel: $\\displaystyle\\int_0^{2\\pi}\\!\\int_0^1 r\\,dr\\,d\\theta = 2\\pi\\cdot\\tfrac12 = \\pi$.",
    tip: "Ikke glem faktoren $r$ i arealelementet - det er den vanligste feilen ved bytte til polarkoordinater." },
  en: { t: "Polar coordinates",
    intro: "In polar coordinates a point is described by its distance $r$ from the origin and angle $\\theta$. The area element gets an extra factor of $r$, coming from the Jacobian of the change of variables.",
    f: [["dA = r\\,dr\\,d\\theta", "area element in polar coordinates"], ["x = r\\cos\\theta,\\ y = r\\sin\\theta", "relation to Cartesian coordinates"]],
    legend: [["r", "distance from the origin", ""], ["\\theta", "angle", "rad"]],
    ex: "Area of a unit disk: $\\displaystyle\\int_0^{2\\pi}\\!\\int_0^1 r\\,dr\\,d\\theta = 2\\pi\\cdot\\tfrac12 = \\pi$.",
    tip: "Don't forget the factor $r$ in the area element - that is the most common mistake when switching to polar coordinates." } },
{ id: "kulekoordinater",
  nb: { t: "Kulekoordinater",
    intro: "Kulekoordinater beskriver et punkt med avstand $\\rho$ fra origo, en polvinkel $\\varphi$ fra z-aksen og en asimutvinkel $\\theta$ i xy-planet. De er nyttige for integraler over kuler og kuleskall.",
    f: [["dV = \\rho^2\\sin\\varphi\\,d\\rho\\,d\\varphi\\,d\\theta", "volumelement i kulekoordinater"]],
    legend: [["\\rho", "avstand fra origo", ""], ["\\varphi", "polvinkel fra z-aksen", "rad"], ["\\theta", "asimutvinkel", "rad"]],
    ex: "Volumet av en kule med radius 2: $\\displaystyle\\int_0^{2\\pi}\\!\\!\\int_0^{\\pi}\\!\\!\\int_0^2 \\rho^2\\sin\\varphi\\,d\\rho\\,d\\varphi\\,d\\theta = \\tfrac43\\pi\\cdot 2^3 \\approx 33{,}51$.",
    tip: "$\\varphi$ måles fra z-aksen, ikke fra xy-planet - lett å blande med breddegrad." },
  en: { t: "Spherical coordinates",
    intro: "Spherical coordinates describe a point by its distance $\\rho$ from the origin, a polar angle $\\varphi$ from the z-axis, and an azimuthal angle $\\theta$ in the xy-plane. They are useful for integrals over spheres and shells.",
    f: [["dV = \\rho^2\\sin\\varphi\\,d\\rho\\,d\\varphi\\,d\\theta", "volume element in spherical coordinates"]],
    legend: [["\\rho", "distance from the origin", ""], ["\\varphi", "polar angle from the z-axis", "rad"], ["\\theta", "azimuthal angle", "rad"]],
    ex: "Volume of a sphere with radius 2: $\\displaystyle\\int_0^{2\\pi}\\!\\!\\int_0^{\\pi}\\!\\!\\int_0^2 \\rho^2\\sin\\varphi\\,d\\rho\\,d\\varphi\\,d\\theta = \\tfrac43\\pi\\cdot 2^3 \\approx 33.51$.",
    tip: "$\\varphi$ is measured from the z-axis, not from the xy-plane - easy to confuse with latitude." } }
]);

// Enhet 2: Vektoranalyse
TOPICS("DAVE3700", 2, [
{ id: "divergens-curl",
  nb: { t: "Divergens og curl",
    intro: "Divergensen til et vektorfelt måler hvor mye feltet «strømmer ut» fra et punkt, mens curl måler hvor mye det virvler rundt et punkt. Begge er bygd av partiellderiverte av komponentene.",
    f: [["\\nabla\\cdot\\vec F = \\frac{\\partial F_x}{\\partial x}+\\frac{\\partial F_y}{\\partial y}+\\frac{\\partial F_z}{\\partial z}", "divergens"], ["\\nabla\\times(\\nabla f) = \\vec 0", "curl av et gradientfelt er alltid null"]],
    legend: [["\\vec F", "vektorfelt", ""]],
    ex: "$\\nabla\\cdot(x,y,z) = 1+1+1 = 3$.",
    tip: "Et gradientfelt er alltid virvelfritt: $\\nabla\\times(\\nabla f)=\\vec 0$." },
  en: { t: "Divergence and curl",
    intro: "The divergence of a vector field measures how much the field \"flows out\" from a point, while the curl measures how much it swirls around a point. Both are built from partial derivatives of the components.",
    f: [["\\nabla\\cdot\\vec F = \\frac{\\partial F_x}{\\partial x}+\\frac{\\partial F_y}{\\partial y}+\\frac{\\partial F_z}{\\partial z}", "divergence"], ["\\nabla\\times(\\nabla f) = \\vec 0", "the curl of a gradient field is always zero"]],
    legend: [["\\vec F", "vector field", ""]],
    ex: "$\\nabla\\cdot(x,y,z) = 1+1+1 = 3$.",
    tip: "A gradient field is always irrotational: $\\nabla\\times(\\nabla f)=\\vec 0$." } },
{ id: "greens-teorem",
  fig: `<svg viewBox="0 0 240 140"><path d="M60 75a60 40 0 1 0 120 0a60 40 0 1 0-120 0Z" class="fill"/><path d="M60 75a60 40 0 1 0 120 0a60 40 0 1 0-120 0Z" class="d"/><path d="M170 75l10-4-2 11z" class="af"/><text x="115" y="80">D</text><text x="175" y="60">C</text></svg>`,
  nb: { t: "Greens teorem",
    intro: "Greens teorem knytter et linjeintegral rundt en lukket kurve $C$ til et dobbeltintegral over området $D$ innenfor. Det er en snarvei når linjeintegralet er vanskelig, men dobbeltintegralet er enkelt.",
    f: [["\\oint_C P\\,dx+Q\\,dy = \\iint_D (Q_x - P_y)\\,dA", "Greens teorem"]],
    legend: [["C", "lukket kurve mot klokka rundt D", ""], ["D", "området innenfor C", ""]],
    ex: "$\\vec F=(0,x)$ rundt enhetskvadratet: $\\oint = \\iint_D (1-0)\\,dA = 1$.",
    tip: "Kurven $C$ må gå mot klokka rundt $D$, ellers snur fortegnet på resultatet." },
  en: { t: "Green's theorem",
    intro: "Green's theorem relates a line integral around a closed curve $C$ to a double integral over the region $D$ inside. It is a shortcut when the line integral is hard but the double integral is simple.",
    f: [["\\oint_C P\\,dx+Q\\,dy = \\iint_D (Q_x - P_y)\\,dA", "Green's theorem"]],
    legend: [["C", "closed curve, counterclockwise around D", ""], ["D", "the region inside C", ""]],
    ex: "$\\vec F=(0,x)$ around the unit square: $\\oint = \\iint_D (1-0)\\,dA = 1$.",
    tip: "The curve $C$ must go counterclockwise around $D$, otherwise the sign of the result flips." } },
{ id: "divergensteorem-stokes",
  nb: { t: "Divergensteoremet og Stokes",
    intro: "Divergensteoremet (Gauss) knytter fluksen ut av en lukket flate til volumintegralet av divergensen innenfor. Stokes' teorem er analogen for en åpen flate: sirkulasjonen langs randkurven er lik fluksen av curl gjennom flaten.",
    f: [["\\oiint_S \\vec F\\cdot d\\vec S = \\iiint_V \\nabla\\cdot\\vec F\\,dV", "divergensteoremet (Gauss)"], ["\\oint_C \\vec F\\cdot d\\vec r = \\iint_S(\\nabla\\times\\vec F)\\cdot d\\vec S", "Stokes' teorem"]],
    legend: [["S", "flate (lukket for Gauss, med rand C for Stokes)", ""], ["V", "volumet innenfor S", ""]],
    ex: "$\\nabla\\cdot\\vec F=2$ overalt: fluksen ut av en kube med sidekant 2 er $2\\cdot2^3=16$.",
    tip: "Greens teorem i planet er spesialtilfellet av Stokes' teorem." },
  en: { t: "Divergence theorem and Stokes",
    intro: "The divergence theorem (Gauss) relates the flux out of a closed surface to the volume integral of the divergence inside. Stokes' theorem is the analogue for an open surface: the circulation along the boundary curve equals the flux of the curl through the surface.",
    f: [["\\oiint_S \\vec F\\cdot d\\vec S = \\iiint_V \\nabla\\cdot\\vec F\\,dV", "the divergence theorem (Gauss)"], ["\\oint_C \\vec F\\cdot d\\vec r = \\iint_S(\\nabla\\times\\vec F)\\cdot d\\vec S", "Stokes' theorem"]],
    legend: [["S", "surface (closed for Gauss, with boundary C for Stokes)", ""], ["V", "the volume inside S", ""]],
    ex: "$\\nabla\\cdot\\vec F=2$ everywhere: the flux out of a cube with side 2 is $2\\cdot2^3=16$.",
    tip: "Green's theorem in the plane is the special case of Stokes' theorem." } }
]);

// =====================================================================
// DAVE3705: Laplace, Fourier og PDE
// =====================================================================

// Enhet 0: Laplacetransformasjonen
TOPICS("DAVE3705", 0, [
{ id: "laplace-definisjon",
  nb: { t: "Laplacetransformasjonen",
    intro: "Laplacetransformasjonen omformer en funksjon av tiden $t$ til en funksjon av frekvensvariabelen $s$, og gjøres ved et integral. Standardtransformer for vanlige funksjoner finnes i tabeller.",
    f: [["\\mathcal L\\{f(t)\\} = \\int_0^\\infty e^{-st}f(t)\\,dt", "definisjon"], ["\\mathcal L\\{t^n\\} = \\frac{n!}{s^{n+1}}", "potenser av t"], ["\\mathcal L\\{\\sin\\omega t\\} = \\frac{\\omega}{s^2+\\omega^2}", "sinus"]],
    legend: [["s", "kompleks frekvensvariabel", ""], ["\\omega", "vinkelfrekvens", "rad/s"]],
    ex: "$\\mathcal L\\{t\\} = \\dfrac{1}{s^2}$, og $\\mathcal L\\{\\sin(2t)\\} = \\dfrac{2}{s^2+4}$.",
    tip: "Laplacetransformen finnes bare når $s$ er stor nok til at integralet konvergerer." },
  en: { t: "The Laplace transform",
    intro: "The Laplace transform converts a function of time $t$ into a function of the frequency variable $s$, defined by an integral. Standard transforms of common functions are found in tables.",
    f: [["\\mathcal L\\{f(t)\\} = \\int_0^\\infty e^{-st}f(t)\\,dt", "definition"], ["\\mathcal L\\{t^n\\} = \\frac{n!}{s^{n+1}}", "powers of t"], ["\\mathcal L\\{\\sin\\omega t\\} = \\frac{\\omega}{s^2+\\omega^2}", "sine"]],
    legend: [["s", "complex frequency variable", ""], ["\\omega", "angular frequency", "rad/s"]],
    ex: "$\\mathcal L\\{t\\} = \\dfrac{1}{s^2}$, and $\\mathcal L\\{\\sin(2t)\\} = \\dfrac{2}{s^2+4}$.",
    tip: "The Laplace transform exists only when $s$ is large enough for the integral to converge." } },
{ id: "laplace-derivert",
  nb: { t: "Laplace av deriverte",
    intro: "Laplacetransformen gjør en derivert om til en algebraisk faktor $s$ pluss et startbetingelses-ledd. Det er derfor Laplace gjør differensialligninger om til algebraiske ligninger som er lett å løse.",
    f: [["\\mathcal L\\{f'(t)\\} = sF(s) - f(0)", "transform av førstederivert"], ["\\mathcal L\\{f''(t)\\} = s^2F(s) - sf(0) - f'(0)", "transform av andrederivert"]],
    legend: [["F(s)", "Laplacetransformen til f(t)", ""]],
    ex: "Løs $y'+3y=0$, $y(0)=4$: $sY-4+3Y=0 \\Rightarrow Y(s)=\\dfrac{4}{s+3}$, altså $y=4e^{-3t}$.",
    tip: "Transformer hele ligningen, løs for $Y(s)$, og bruk deretter en tabell baklengs (invers transform)." },
  en: { t: "Laplace of derivatives",
    intro: "The Laplace transform turns a derivative into an algebraic factor $s$ plus an initial-condition term. This is why Laplace transforms differential equations into algebraic equations that are easy to solve.",
    f: [["\\mathcal L\\{f'(t)\\} = sF(s) - f(0)", "transform of the first derivative"], ["\\mathcal L\\{f''(t)\\} = s^2F(s) - sf(0) - f'(0)", "transform of the second derivative"]],
    legend: [["F(s)", "the Laplace transform of f(t)", ""]],
    ex: "Solve $y'+3y=0$, $y(0)=4$: $sY-4+3Y=0 \\Rightarrow Y(s)=\\dfrac{4}{s+3}$, so $y=4e^{-3t}$.",
    tip: "Transform the whole equation, solve for $Y(s)$, then use a table backwards (inverse transform)." } },
{ id: "forskyvning-delbrok",
  nb: { t: "Forskyvningsregelen og delbrøk",
    intro: "Forskyvningsregelen (s-skift) forteller hva som skjer med transformen når $f(t)$ ganges med $e^{at}$. Delbrøkoppspalting brukes til å skrive en komplisert brøk i $s$ om til enklere ledd som finnes i tabellen.",
    f: [["\\mathcal L\\{e^{at}f(t)\\} = F(s-a)", "s-forskyvningsregelen"], ["\\frac{1}{s(s+1)} = \\frac1s - \\frac{1}{s+1}", "delbrøkoppspalting, eksempel"]],
    legend: [["a", "forskyvning i s, fra eksponentialfaktoren $e^{at}$", ""]],
    ex: "$\\mathcal L\\{te^{-4t}\\} = \\dfrac{1}{(s+4)^2}$, og den inverse av $\\dfrac{1}{s(s+1)}$ er $1-e^{-t}$.",
    tip: "En tidsforskyvning $f(t-a)$ gir i stedet en faktor $e^{-as}$ - ikke bland de to reglene." },
  en: { t: "Shift rule and partial fractions",
    intro: "The shift rule (s-shift) tells us what happens to the transform when $f(t)$ is multiplied by $e^{at}$. Partial fraction decomposition is used to write a complicated fraction in $s$ as simpler terms found in the table.",
    f: [["\\mathcal L\\{e^{at}f(t)\\} = F(s-a)", "the s-shift rule"], ["\\frac{1}{s(s+1)} = \\frac1s - \\frac{1}{s+1}", "partial fractions, example"]],
    legend: [["a", "shift in s, from the exponential factor $e^{at}$", ""]],
    ex: "$\\mathcal L\\{te^{-4t}\\} = \\dfrac{1}{(s+4)^2}$, and the inverse of $\\dfrac{1}{s(s+1)}$ is $1-e^{-t}$.",
    tip: "A time shift $f(t-a)$ instead gives a factor $e^{-as}$ - don't mix up the two rules." } }
]);

// Enhet 1: Fourierrekker
TOPICS("DAVE3705", 1, [
{ id: "fourierkoeffisienter",
  nb: { t: "Fourierkoeffisienter",
    intro: "En periodisk funksjon kan skrives som en sum av sinus- og cosinusledd, en Fourierrekke. Koeffisientene $a_n$ og $b_n$ finnes ved å integrere funksjonen mot henholdsvis cosinus og sinus.",
    f: [["a_n = \\frac1L\\int_{-L}^{L}f(x)\\cos\\frac{n\\pi x}{L}\\,dx", "cosinuskoeffisienter"], ["b_n = \\frac1L\\int_{-L}^{L}f(x)\\sin\\frac{n\\pi x}{L}\\,dx", "sinuskoeffisienter"]],
    legend: [["2L", "periode", ""], ["a_0/2", "middelverdien av f", ""]],
    ex: "$f(x)=5+4\\cos x$ på $[-\\pi,\\pi]$: middelverdien er $a_0/2=5$, fordi cosinusleddet har middelverdi 0.",
    tip: "Integranden med sinus gir $b_n$, og den med cosinus gir $a_n$ - lett å blande sammen." },
  en: { t: "Fourier coefficients",
    intro: "A periodic function can be written as a sum of sine and cosine terms, a Fourier series. The coefficients $a_n$ and $b_n$ are found by integrating the function against cosine and sine respectively.",
    f: [["a_n = \\frac1L\\int_{-L}^{L}f(x)\\cos\\frac{n\\pi x}{L}\\,dx", "cosine coefficients"], ["b_n = \\frac1L\\int_{-L}^{L}f(x)\\sin\\frac{n\\pi x}{L}\\,dx", "sine coefficients"]],
    legend: [["2L", "period", ""], ["a_0/2", "mean value of f", ""]],
    ex: "$f(x)=5+4\\cos x$ on $[-\\pi,\\pi]$: the mean value is $a_0/2=5$, because the cosine term has mean value 0.",
    tip: "The integrand with sine gives $b_n$, and the one with cosine gives $a_n$ - easy to mix up." } },
{ id: "odde-like-funksjoner",
  nb: { t: "Odde og like funksjoner",
    intro: "Symmetrien til en funksjon forenkler Fourierrekken kraftig: en odde funksjon har bare sinusledd, og en like funksjon har bare cosinusledd (og et konstantledd).",
    f: [["\\text{odde } f:\\ a_n=0\\ (\\text{bare sinusledd})", "odde funksjon"], ["\\text{like } f:\\ b_n=0\\ (\\text{bare cosinusledd})", "like funksjon"]],
    legend: [["a_n", "cosinuskoeffisienter", ""], ["b_n", "sinuskoeffisienter", ""]],
    ex: "$f(x)=x$ på $(-\\pi,\\pi)$ er odde: $b_n=\\dfrac{2(-1)^{n+1}}{n}$, så $b_5=\\dfrac{2}{5}=0{,}4$.",
    tip: "$\\sin$ er odde og $\\cos$ er like - det er derfor symmetrien til $f$ avgjør hvilke ledd som blir null." },
  en: { t: "Odd and even functions",
    intro: "The symmetry of a function greatly simplifies its Fourier series: an odd function has only sine terms, and an even function has only cosine terms (and a constant term).",
    f: [["\\text{odd } f:\\ a_n=0\\ (\\text{sine terms only})", "odd function"], ["\\text{even } f:\\ b_n=0\\ (\\text{cosine terms only})", "even function"]],
    legend: [["a_n", "cosine coefficients", ""], ["b_n", "sine coefficients", ""]],
    ex: "$f(x)=x$ on $(-\\pi,\\pi)$ is odd: $b_n=\\dfrac{2(-1)^{n+1}}{n}$, so $b_5=\\dfrac{2}{5}=0.4$.",
    tip: "$\\sin$ is odd and $\\cos$ is even - that is why the symmetry of $f$ decides which terms vanish." } },
{ id: "gibbs-fenomen",
  nb: { t: "Gibbs-fenomenet",
    intro: "Nær et sprang i en funksjon vil en Fourierrekke alltid overskyte litt, uansett hvor mange ledd vi tar med. Dette kalles Gibbs-fenomenet, og oversvinget flytter seg nærmere spranget, men blir ikke mindre.",
    f: [["\\text{oversving} \\approx 9\\%\\ \\text{av spranget}", "Gibbs-fenomenet"]],
    legend: [["\\text{sprang}", "diskontinuiteten i f(x)", ""]],
    ex: "En firkantbølge har alltid et oversving på ca. 9 % like ved sprangene, selv med svært mange ledd med i rekken.",
    tip: "I selve sprangpunktet konvergerer rekken mot gjennomsnittet av venstre og høyre grenseverdi." },
  en: { t: "The Gibbs phenomenon",
    intro: "Near a jump in a function, a Fourier series will always overshoot a little, no matter how many terms we include. This is called the Gibbs phenomenon, and the overshoot moves closer to the jump but does not shrink.",
    f: [["\\text{overshoot} \\approx 9\\%\\ \\text{of the jump}", "the Gibbs phenomenon"]],
    legend: [["\\text{jump}", "the discontinuity in f(x)", ""]],
    ex: "A square wave always has an overshoot of about 9% right at the jumps, even with very many terms in the series.",
    tip: "At the jump point itself, the series converges to the average of the left and right limits." } }
]);

// Enhet 2: Partielle differensialligninger
TOPICS("DAVE3705", 2, [
{ id: "varmeligningen",
  fig: `<svg viewBox="0 0 240 140"><path d="M30 90H210" class="b"/><path d="M30 70Q120 30 210 70" class="d"/><path d="M30 90V110M210 90V110" class="dim"/><text x="20" y="125">0</text><text x="200" y="125">L</text><text x="115" y="40">u</text></svg>`,
  nb: { t: "Varmeligningen",
    intro: "Varmeligningen beskriver hvordan temperaturen $u(x,t)$ i en stav utvikler seg over tid, og løses ofte ved separasjon av variable. Løsningen blir en sum av moder som hver dør ut med sin egen fart - høye moder raskest.",
    f: [["u_t = c^2u_{xx}", "varmeligningen (1D)"], ["u_n(x,t) = \\sin\\frac{n\\pi x}{L}\\,e^{-c^2(n\\pi/L)^2t}", "mode n, med $u=0$ i begge ender"]],
    legend: [["c^2", "diffusjonskoeffisient", ""], ["L", "stavens lengde", "m"]],
    ex: "$c^2=4$, $L=\\pi$, $n=3$: avtagningsraten er $\\lambda=c^2(n\\pi/L)^2=4\\cdot9=36$.",
    tip: "Fordi høye moder dør raskest ut, glattes temperaturprofilen fortere jo lenger tiden går." },
  en: { t: "The heat equation",
    intro: "The heat equation describes how the temperature $u(x,t)$ in a rod evolves over time, and is often solved by separation of variables. The solution becomes a sum of modes that each decay at their own rate - higher modes fastest.",
    f: [["u_t = c^2u_{xx}", "the heat equation (1D)"], ["u_n(x,t) = \\sin\\frac{n\\pi x}{L}\\,e^{-c^2(n\\pi/L)^2t}", "mode n, with $u=0$ at both ends"]],
    legend: [["c^2", "diffusion coefficient", ""], ["L", "length of the rod", "m"]],
    ex: "$c^2=4$, $L=\\pi$, $n=3$: the decay rate is $\\lambda=c^2(n\\pi/L)^2=4\\cdot9=36$.",
    tip: "Because higher modes decay fastest, the temperature profile smooths out faster as time passes." } },
{ id: "bolgeligningen",
  fig: `<svg viewBox="0 0 240 140"><path d="M20 90H220" class="dim"/><path d="M20 90Q60 40 100 90T180 90" class="d"/><path d="M140 60L170 60" class="a"/><path d="M170 60l-10-5v10z" class="af"/><text x="150" y="53">c</text></svg>`,
  nb: { t: "Bølgeligningen",
    intro: "Bølgeligningen beskriver forstyrrelser som forplanter seg med en fast fart $c$, som på en streng. d'Alemberts løsning viser at enhver løsning er en sum av to bølger som går hver sin vei uten å endre form.",
    f: [["u_{tt} = c^2u_{xx}", "bølgeligningen"], ["u = F(x-ct) + G(x+ct)", "d'Alemberts løsning: to bølger som går hver sin vei"]],
    legend: [["c", "bølgefart", "m/s"]],
    ex: "$u_{tt}=25u_{xx}$: $c=\\sqrt{25}=5$ m/s. En streng med $L=2$ m og $c=2$ m/s har mode 2 med vinkelfrekvens $\\omega_2=\\dfrac{c\\cdot2\\pi}{L}=2\\pi\\approx6{,}28$ rad/s.",
    tip: "I motsetning til varmeligningen dempes ikke bølgeløsningene - de svinger uten å dø ut." },
  en: { t: "The wave equation",
    intro: "The wave equation describes disturbances that propagate at a fixed speed $c$, as on a string. d'Alembert's solution shows that every solution is a sum of two waves travelling in opposite directions without changing shape.",
    f: [["u_{tt} = c^2u_{xx}", "the wave equation"], ["u = F(x-ct) + G(x+ct)", "d'Alembert's solution: two waves travelling in opposite directions"]],
    legend: [["c", "wave speed", "m/s"]],
    ex: "$u_{tt}=25u_{xx}$: $c=\\sqrt{25}=5$ m/s. A string with $L=2$ m and $c=2$ m/s has mode 2 with angular frequency $\\omega_2=\\dfrac{c\\cdot2\\pi}{L}=2\\pi\\approx6.28$ rad/s.",
    tip: "Unlike the heat equation, wave solutions are not damped - they oscillate without dying out." } },
{ id: "separasjon-laplace",
  nb: { t: "Separasjon og Laplaces ligning",
    intro: "Separasjon av variable antar at løsningen kan skrives som et produkt $u(x,t)=X(x)T(t)$, som gjør en PDE om til to enklere ordinære differensialligninger. Laplaces ligning beskriver en stasjonær (tidsuavhengig) tilstand, som stasjonær varmefordeling.",
    f: [["u(x,t) = X(x)\\,T(t)", "separasjonsansatsen"], ["\\nabla^2u = 0", "Laplaces ligning (stasjonær tilstand)"]],
    legend: [["X(x),\\ T(t)", "faktorer som hver løser en ordinær ligning", ""]],
    ex: "Stasjonær varmeledning i en stav med $u(0)=25$ og $u(10)=93$: løsningen er lineær, $u(x)=25+6{,}8x$, så $u(0)=25$.",
    tip: "Stasjonær betyr $u_t=0$, så varmeligningen blir $u_{xx}=0$, som gir en lineær løsning i 1D." },
  en: { t: "Separation and Laplace's equation",
    intro: "Separation of variables assumes the solution can be written as a product $u(x,t)=X(x)T(t)$, turning a PDE into two simpler ordinary differential equations. Laplace's equation describes a stationary (time-independent) state, such as a stationary heat distribution.",
    f: [["u(x,t) = X(x)\\,T(t)", "the separation ansatz"], ["\\nabla^2u = 0", "Laplace's equation (stationary state)"]],
    legend: [["X(x),\\ T(t)", "factors that each solve an ordinary equation", ""]],
    ex: "Stationary heat conduction in a rod with $u(0)=25$ and $u(10)=93$: the solution is linear, $u(x)=25+6.8x$, so $u(0)=25$.",
    tip: "Stationary means $u_t=0$, so the heat equation becomes $u_{xx}=0$, giving a linear solution in 1D." } }
]);
