// ============================================================
//  Teoribok – ELPE1300, ELEK, ELFT2500, ELFT2400, ELVE3610
// ============================================================

// ================= ELPE1300 – enhet 0: Likestrøm =================
TOPICS("ELPE1300", 0, [
{ id: "ohms-lov",
  fig: `<svg viewBox="0 0 240 140"><path d="M40 30H200M200 30V55M200 85V110M200 110H40M40 88V110M40 30V52" class="d"/><circle cx="40" cy="70" r="18" class="d"/><rect x="185" y="55" width="30" height="30" class="d"/><text x="15" y="74">U</text><text x="221" y="75">R</text><text x="34" y="60">+</text><text x="37" y="86">-</text></svg>`,
  nb: { t: "Ohms lov og effekt",
    intro: "Ohms lov knytter sammen spenningen over en motstand, strømmen gjennom den og motstandsverdien. Kjenner du to av de tre størrelsene, finner du alltid den tredje. Effekten som varmes opp i motstanden kan regnes ut på tre likeverdige måter, avhengig av hvilke størrelser du kjenner.",
    f: [["U = RI", "Ohms lov: spenning er motstand ganger strøm"], ["P = UI = RI^2 = \\dfrac{U^2}{R}", "effekt i en motstand, tre likeverdige former"]],
    legend: [["U", "spenning over motstanden", "V"], ["R", "motstand", "\\Omega"], ["I", "strøm gjennom motstanden", "A"], ["P", "effekt (varmetap)", "W"]],
    ex: "$U = 12$ V over $R = 4$ Ω:\n$I = U/R = 12/4 = 3$ A.\n$P = UI = 12\\cdot3 = 36$ W.",
    tip: "Har du to av U, R og I, finner Ohms lov alltid den tredje – tegn kretsen og merk det du vet." },
  en: { t: "Ohm's Law and Power",
    intro: "Ohm's law links the voltage across a resistor, the current through it and its resistance. Knowing any two of the three quantities, you can always find the third. The power dissipated as heat in the resistor can be computed in three equivalent ways, depending on which quantities you know.",
    f: [["U = RI", "Ohm's law: voltage is resistance times current"], ["P = UI = RI^2 = \\dfrac{U^2}{R}", "power in a resistor, three equivalent forms"]],
    legend: [["U", "voltage across the resistor", "V"], ["R", "resistance", "\\Omega"], ["I", "current through the resistor", "A"], ["P", "power (heat dissipated)", "W"]],
    ex: "$U = 12$ V across $R = 4$ Ω:\n$I = U/R = 12/4 = 3$ A.\n$P = UI = 12\\cdot3 = 36$ W.",
    tip: "Given any two of U, R and I, Ohm's law always gives the third – sketch the circuit and mark what you know." } },
{ id: "serie-parallell",
  fig: `<svg viewBox="0 0 240 140"><path d="M30 30H210M30 110H210M30 30V52M30 88V110M90 30V55M90 85V110M170 30V55M170 85V110" class="d"/><circle cx="30" cy="70" r="18" class="d"/><rect x="75" y="55" width="30" height="30" class="d"/><rect x="155" y="55" width="30" height="30" class="d"/><text x="8" y="74">U</text><text x="110" y="74">R<tspan dy="4" font-size="10">1</tspan></text><text x="190" y="74">R<tspan dy="4" font-size="10">2</tspan></text></svg>`,
  nb: { t: "Serie- og parallellkobling",
    intro: "I en seriekobling er strømmen lik i alle komponentene, og spenningene summeres. I en parallellkobling er spenningen lik over alle grenene, og strømmene deler seg. Disse to grunnreglene brukes til å forenkle nesten enhver motstandskrets steg for steg.",
    f: [["R_{tot}=R_1+R_2+\\dots", "serie: motstandene legges sammen"], ["\\dfrac{1}{R_{tot}}=\\dfrac{1}{R_1}+\\dfrac{1}{R_2}+\\dots", "parallell: inverse motstander legges sammen"], ["U_2=U\\dfrac{R_2}{R_1+R_2}", "spenningsdeler for to motstander i serie"]],
    legend: [["R_{tot}", "total motstand", "\\Omega"], ["R_1,\\ R_2", "enkeltmotstander", "\\Omega"], ["U", "spenning over hele kombinasjonen", "V"]],
    ex: "$R_1=12$ Ω og $R_2=6$ Ω i parallell:\n$1/R_{tot}=1/12+1/6=1/4$, så $R_{tot}=4$ Ω.",
    tip: "I serie er strømmen felles, i parallell er spenningen felles – husk hvilken størrelse som er lik før du kombinerer." },
  en: { t: "Series and Parallel",
    intro: "In a series connection the current is the same through every component, and the voltages add up. In a parallel connection the voltage is the same across every branch, and the currents split. These two basic rules are used to simplify almost any resistive circuit step by step.",
    f: [["R_{tot}=R_1+R_2+\\dots", "series: resistances add"], ["\\dfrac{1}{R_{tot}}=\\dfrac{1}{R_1}+\\dfrac{1}{R_2}+\\dots", "parallel: inverse resistances add"], ["U_2=U\\dfrac{R_2}{R_1+R_2}", "voltage divider for two resistors in series"]],
    legend: [["R_{tot}", "total resistance", "\\Omega"], ["R_1,\\ R_2", "individual resistors", "\\Omega"], ["U", "voltage across the whole combination", "V"]],
    ex: "$R_1=12$ Ω and $R_2=6$ Ω in parallel:\n$1/R_{tot}=1/12+1/6=1/4$, so $R_{tot}=4$ Ω.",
    tip: "In series the current is shared, in parallel the voltage is shared – identify which quantity is common before combining." } },
{ id: "kirchhoff",
  fig: `<svg viewBox="0 0 240 140"><circle cx="120" cy="70" r="3" class="d"/><path d="M30 40L118 68" class="a"/><path d="M118 68l-16-2 6 14z" class="af"/><path d="M30 100L118 72" class="a"/><path d="M118 72l-16 2 6-14z" class="af"/><path d="M122 70H210" class="a"/><path d="M210 70l-14-6v12z" class="af"/><text x="20" y="35">I<tspan dy="4" font-size="10">1</tspan></text><text x="19" y="111">I<tspan dy="4" font-size="10">2</tspan></text><text x="195" y="55">I<tspan dy="4" font-size="10">3</tspan></text></svg>`,
  nb: { t: "Kirchhoffs lover",
    intro: "Kirchhoffs strømlov sier at summen av strømmer inn i et knutepunkt er lik summen ut, fordi ladning er bevart. Kirchhoffs spenningslov sier at summen av spenninger rundt en hvilken som helst lukket sløyfe er null. Sammen med Ohms lov er disse to lovene nok til å løse enhver likestrømskrets.",
    f: [["\\sum I_{inn} = \\sum I_{ut}", "strømloven (KCL) i et knutepunkt"], ["\\sum U = 0", "spenningsloven (KVL) rundt en sløyfe"]],
    legend: [["I", "strøm inn/ut av knutepunktet", "A"], ["U", "spenningsfall rundt sløyfen", "V"]],
    ex: "I et knutepunkt går $5$ A og $3$ A inn, og $I$ A ut:\n$5+3=I \\Rightarrow I=8$ A.",
    tip: "Velg fortegn for strømretning og spenningsfall én gang, og hold deg til det gjennom hele kretsen." },
  en: { t: "Kirchhoff's Laws",
    intro: "Kirchhoff's current law says the sum of currents into a node equals the sum out, because charge is conserved. Kirchhoff's voltage law says the sum of voltages around any closed loop is zero. Together with Ohm's law, these two laws are enough to solve any DC circuit.",
    f: [["\\sum I_{in} = \\sum I_{out}", "current law (KCL) at a node"], ["\\sum U = 0", "voltage law (KVL) around a loop"]],
    legend: [["I", "current into/out of the node", "A"], ["U", "voltage drop around the loop", "V"]],
    ex: "At a node, $5$ A and $3$ A flow in, and $I$ A flows out:\n$5+3=I \\Rightarrow I=8$ A.",
    tip: "Pick a sign convention for current direction and voltage drop once, and stick to it throughout the circuit." } }
]);

// ================= ELPE1300 – enhet 1: Kondensator og spole =================
TOPICS("ELPE1300", 1, [
{ id: "kondensator",
  fig: `<svg viewBox="0 0 240 140"><path d="M40 30H200M200 30V62M200 78V110M200 110H40M40 88V110M40 30V52" class="d"/><circle cx="40" cy="70" r="18" class="d"/><path d="M185 62H215M185 78H215" class="d"/><text x="15" y="74">U</text><text x="222" y="74">C</text></svg>`,
  nb: { t: "Kondensator",
    intro: "En kondensator lagrer energi i et elektrisk felt mellom to plater. Ladningen den lagrer er proporsjonal med spenningen over den, og den «liker» konstant spenning – strømmen gjennom den avhenger av hvor fort spenningen endrer seg. I en likestrømskrets i stasjonær tilstand oppfører den seg som et brudd.",
    f: [["Q = CU", "ladning lagret på en kondensator"], ["i = C\\dfrac{du}{dt}", "strøm som funksjon av spenningens endringstakt"], ["E = \\tfrac12CU^2", "energi lagret i det elektriske feltet"]],
    legend: [["Q", "ladning", "C"], ["C", "kapasitans", "F"], ["U", "spenning over kondensatoren", "V"], ["E", "lagret energi", "J"]],
    ex: "$C=220$ µF lades til $U=15$ V:\n$Q=CU=220\\cdot10^{-6}\\cdot15\\approx3{,}3$ mC.",
    tip: "Spenningen over en kondensator kan ikke hoppe momentant – bare strømmen kan gjøre det." },
  en: { t: "Capacitor",
    intro: "A capacitor stores energy in an electric field between two plates. The charge it stores is proportional to the voltage across it, and it prefers constant voltage – the current through it depends on how fast the voltage changes. In a DC circuit at steady state it behaves as an open circuit.",
    f: [["Q = CU", "charge stored on a capacitor"], ["i = C\\dfrac{du}{dt}", "current as a function of the rate of change of voltage"], ["E = \\tfrac12CU^2", "energy stored in the electric field"]],
    legend: [["Q", "charge", "C"], ["C", "capacitance", "F"], ["U", "voltage across the capacitor", "V"], ["E", "stored energy", "J"]],
    ex: "$C=220$ µF charged to $U=15$ V:\n$Q=CU=220\\cdot10^{-6}\\cdot15\\approx3.3$ mC.",
    tip: "The voltage across a capacitor cannot jump instantaneously – only the current can." } },
{ id: "spole",
  fig: `<svg viewBox="0 0 240 140"><path d="M40 30H200M200 30V50M200 90V110M200 110H40M40 88V110M40 30V52" class="d"/><circle cx="40" cy="70" r="18" class="d"/><path d="M200 50a8 8 0 0 1 0 16a8 8 0 0 1 0 16a8 8 0 0 1 0 8" class="d"/><text x="15" y="74">U</text><text x="215" y="74">L</text></svg>`,
  nb: { t: "Spole",
    intro: "En spole lagrer energi i et magnetisk felt når strøm flyter gjennom den. Den «liker» konstant strøm og reagerer med en spenning som er proporsjonal med hvor fort strømmen endrer seg. I en likestrømskrets i stasjonær tilstand oppfører den seg som en kortslutning.",
    f: [["u = L\\dfrac{di}{dt}", "spenning som funksjon av strømmens endringstakt"], ["E=\\tfrac12LI^2", "energi lagret i det magnetiske feltet"]],
    legend: [["L", "induktans", "H"], ["I", "strøm gjennom spolen", "A"], ["u", "spenning over spolen", "V"], ["E", "lagret energi", "J"]],
    ex: "$L=10$ mH fører $I=2$ A:\n$E=\\tfrac12LI^2=\\tfrac12\\cdot0{,}01\\cdot4=0{,}02$ J.",
    tip: "Strømmen gjennom en spole kan ikke hoppe momentant – bare spenningen kan gjøre det." },
  en: { t: "Inductor",
    intro: "An inductor stores energy in a magnetic field when current flows through it. It prefers constant current and responds with a voltage proportional to how fast the current changes. In a DC circuit at steady state it behaves as a short circuit.",
    f: [["u = L\\dfrac{di}{dt}", "voltage as a function of the rate of change of current"], ["E=\\tfrac12LI^2", "energy stored in the magnetic field"]],
    legend: [["L", "inductance", "H"], ["I", "current through the inductor", "A"], ["u", "voltage across the inductor", "V"], ["E", "stored energy", "J"]],
    ex: "$L=10$ mH carries $I=2$ A:\n$E=\\tfrac12LI^2=\\tfrac12\\cdot0.01\\cdot4=0.02$ J.",
    tip: "The current through an inductor cannot jump instantaneously – only the voltage can." } },
{ id: "rc-tidskonstant",
  fig: `<svg viewBox="0 0 240 140"><path d="M30 120H220M30 120V20" class="dim"/><path d="M30 110C70 40 120 20 210 20" class="d"/><path d="M30 20H210" class="dash"/><path d="M95 120V70M95 70H30" class="dash"/><text x="212" y="16">U</text><text x="215" y="132">t</text><text x="10" y="70">u</text><text x="90" y="132">τ</text></svg>`,
  nb: { t: "RC-tidskonstant",
    intro: "Når en kondensator lades eller utlades gjennom en motstand, følger spenningen en eksponentiell kurve mot sluttverdien. Hvor fort dette skjer bestemmes av tidskonstanten τ = RC. Etter én tidskonstant har spenningen nådd 63 % av veien til sluttverdien, og etter fem tidskonstanter regnes den som praktisk talt ferdig.",
    f: [["\\tau=RC", "tidskonstant for en RC-krets"], ["u(t)=U(1-e^{-t/\\tau})", "oppladning mot U"], ["u(t)=U_0e^{-t/\\tau}", "utladning fra U_0"]],
    legend: [["\\tau", "tidskonstant", "s"], ["R", "motstand", "\\Omega"], ["C", "kapasitans", "F"], ["U", "sluttverdi (opplading)", "V"]],
    ex: "$R=2$ kΩ, $C=100$ µF, opplading mot $10$ V:\n$\\tau=RC=0{,}2$ s. Etter $\\tau$: $u\\approx0{,}632\\cdot10\\approx6{,}3$ V.",
    tip: "Sett $t=0$ og la $t\\to\\infty$ i formelen din og sjekk at du får start- og sluttverdien." },
  en: { t: "RC Time Constant",
    intro: "When a capacitor charges or discharges through a resistor, the voltage follows an exponential curve toward its final value. How fast this happens is set by the time constant τ = RC. After one time constant the voltage has reached 63% of the way to the final value, and after five time constants it is considered practically finished.",
    f: [["\\tau=RC", "time constant for an RC circuit"], ["u(t)=U(1-e^{-t/\\tau})", "charging toward U"], ["u(t)=U_0e^{-t/\\tau}", "discharging from U_0"]],
    legend: [["\\tau", "time constant", "s"], ["R", "resistance", "\\Omega"], ["C", "capacitance", "F"], ["U", "final value (charging)", "V"]],
    ex: "$R=2$ kΩ, $C=100$ µF, charging toward $10$ V:\n$\\tau=RC=0.2$ s. After $\\tau$: $u\\approx0.632\\cdot10\\approx6.3$ V.",
    tip: "Set $t=0$ and let $t\\to\\infty$ in your formula and check that you get the start and final values." } }
]);

// ================= ELPE1300 – enhet 2: Vekselstrøm =================
TOPICS("ELPE1300", 2, [
{ id: "sinus-rms",
  fig: `<svg viewBox="0 0 240 140"><path d="M20 70H220M20 120V20" class="dim"/><path d="M20 70C45 20 65 20 90 70S135 120 160 70S205 20 220 45" class="d"/><text x="222" y="45">t</text><text x="8" y="20">u</text><text x="30" y="34">U<tspan dy="4" font-size="10">p</tspan></text></svg>`,
  nb: { t: "Sinus og effektivverdi",
    intro: "En vekselspenning svinger sinusformet i tid, med en toppverdi og en vinkelfrekvens som avhenger av frekvensen. Fordi den skifter fortegn, bruker vi effektivverdien (RMS) til å angi en «jevn» spenning som gir samme effekt som en tilsvarende likespenning. Nettspenningen på 230 V er alltid en RMS-verdi, ikke toppverdien.",
    f: [["u(t)=U_p\\sin(\\omega t)", "sinusformet spenning med vinkelfrekvens \\omega"], ["\\omega=2\\pi f", "sammenheng mellom vinkelfrekvens og frekvens"], ["U=\\dfrac{U_p}{\\sqrt2}", "effektivverdi (RMS) for en ren sinus"]],
    legend: [["U_p", "toppverdi", "V"], ["\\omega", "vinkelfrekvens", "rad/s"], ["f", "frekvens", "Hz"], ["U", "effektivverdi (RMS)", "V"]],
    ex: "Toppverdi $U_p=325$ V:\n$U=325/\\sqrt2\\approx230$ V, altså vanlig nettspenning.",
    tip: "230 V er en RMS-verdi – toppverdien til nettspenningen er faktisk om lag 325 V." },
  en: { t: "Sine Waves and RMS",
    intro: "An AC voltage oscillates sinusoidally in time, with a peak value and an angular frequency that depends on the frequency. Because it changes sign, we use the RMS value to state a steady equivalent voltage that delivers the same power as an equivalent DC voltage. The 230 V mains voltage is always an RMS value, not the peak value.",
    f: [["u(t)=U_p\\sin(\\omega t)", "sinusoidal voltage with angular frequency \\omega"], ["\\omega=2\\pi f", "relation between angular frequency and frequency"], ["U=\\dfrac{U_p}{\\sqrt2}", "RMS value for a pure sine wave"]],
    legend: [["U_p", "peak value", "V"], ["\\omega", "angular frequency", "rad/s"], ["f", "frequency", "Hz"], ["U", "RMS value", "V"]],
    ex: "Peak value $U_p=325$ V:\n$U=325/\\sqrt2\\approx230$ V, i.e. the usual mains voltage.",
    tip: "230 V is an RMS value – the peak of the mains voltage is actually about 325 V." } },
{ id: "reaktans-impedans",
  fig: `<svg viewBox="0 0 240 140"><path d="M40 110H180M40 110V40" class="d"/><path d="M40 40L180 110" class="a"/><path d="M40 110h14v-14h-14z" class="dim"/><text x="100" y="128">R</text><text x="20" y="78">X</text><text x="106" y="64">Z</text></svg>`,
  nb: { t: "Reaktans og impedans",
    intro: "I vekselstrøm får kondensatorer og spoler en frekvensavhengig «motstand» kalt reaktans. Reaktansen til en spole øker med frekvensen, mens reaktansen til en kondensator avtar. Sammen med den vanlige motstanden danner reaktansen impedansen, som bestemmer både strømmens størrelse og faseforskyvning.",
    f: [["X_L=\\omega L", "induktiv reaktans"], ["X_C=\\dfrac{1}{\\omega C}", "kapasitiv reaktans"], ["Z=\\sqrt{R^2+X^2},\\ \\varphi=\\arctan\\dfrac{X}{R}", "impedansens størrelse og fasevinkel"]],
    legend: [["X_L,\\ X_C", "reaktans (spole, kondensator)", "\\Omega"], ["Z", "impedans", "\\Omega"], ["\\varphi", "fasevinkel", "°"]],
    ex: "$R=30$ Ω, $X_L=31{,}4$ Ω:\n$Z=\\sqrt{30^2+31{,}4^2}\\approx43{,}4$ Ω.",
    tip: "$X_C$ avtar når frekvensen øker, mens $X_L$ øker – de virker motsatt av hverandre." },
  en: { t: "Reactance and Impedance",
    intro: "In AC circuits, capacitors and inductors get a frequency-dependent opposition to current called reactance. The reactance of an inductor increases with frequency, while the reactance of a capacitor decreases. Together with the ordinary resistance, the reactance forms the impedance, which sets both the current's magnitude and its phase shift.",
    f: [["X_L=\\omega L", "inductive reactance"], ["X_C=\\dfrac{1}{\\omega C}", "capacitive reactance"], ["Z=\\sqrt{R^2+X^2},\\ \\varphi=\\arctan\\dfrac{X}{R}", "impedance magnitude and phase angle"]],
    legend: [["X_L,\\ X_C", "reactance (inductor, capacitor)", "\\Omega"], ["Z", "impedance", "\\Omega"], ["\\varphi", "phase angle", "°"]],
    ex: "$R=30$ Ω, $X_L=31.4$ Ω:\n$Z=\\sqrt{30^2+31.4^2}\\approx43.4$ Ω.",
    tip: "$X_C$ decreases as frequency rises, while $X_L$ increases – they behave oppositely." } },
{ id: "effekttrekant",
  fig: `<svg viewBox="0 0 240 140"><path d="M40 110H180M40 110V40" class="d"/><path d="M40 40L180 110" class="a"/><path d="M40 110h14v-14h-14z" class="dim"/><text x="100" y="128">P</text><text x="20" y="78">Q</text><text x="106" y="64">S</text></svg>`,
  nb: { t: "Aktiv, reaktiv og tilsynelatende effekt",
    intro: "I en vekselstrømskrets skiller vi mellom tre typer effekt: den aktive effekten som gjør nyttig arbeid, den reaktive effekten som pendler fram og tilbake i reaktive komponenter, og den tilsynelatende effekten kilden faktisk må levere. Effektfaktoren forteller hvor stor andel av den tilsynelatende effekten som er nyttig.",
    f: [["P=UI\\cos\\varphi", "aktiv effekt"], ["Q=UI\\sin\\varphi", "reaktiv effekt"], ["S=UI,\\ S^2=P^2+Q^2", "tilsynelatende effekt og effekttrekanten"]],
    legend: [["P", "aktiv effekt", "W"], ["Q", "reaktiv effekt", "VAr"], ["S", "tilsynelatende effekt", "VA"], ["\\cos\\varphi", "effektfaktor", ""]],
    ex: "$U=230$ V, $I=5{,}29$ A, $\\cos\\varphi\\approx0{,}69$:\n$P=UI\\cos\\varphi\\approx230\\cdot5{,}29\\cdot0{,}69\\approx840$ W.",
    tip: "Bare den aktive effekten $P$ gjør nyttig arbeid – $S$ er det kilden må dimensjoneres for." },
  en: { t: "Active, Reactive and Apparent Power",
    intro: "In an AC circuit we distinguish three kinds of power: the active power that does useful work, the reactive power that sloshes back and forth in reactive components, and the apparent power the source must actually supply. The power factor states what fraction of the apparent power is useful.",
    f: [["P=UI\\cos\\varphi", "active power"], ["Q=UI\\sin\\varphi", "reactive power"], ["S=UI,\\ S^2=P^2+Q^2", "apparent power and the power triangle"]],
    legend: [["P", "active power", "W"], ["Q", "reactive power", "VAr"], ["S", "apparent power", "VA"], ["\\cos\\varphi", "power factor", ""]],
    ex: "$U=230$ V, $I=5.29$ A, $\\cos\\varphi\\approx0.69$:\n$P=UI\\cos\\varphi\\approx230\\cdot5.29\\cdot0.69\\approx840$ W.",
    tip: "Only the active power $P$ does useful work – $S$ is what the source must be rated for." } }
]);

// ================= ELPE1300 – enhet 3: Nettverksanalyse =================
TOPICS("ELPE1300", 3, [
{ id: "superposisjon",
  fig: `<svg viewBox="0 0 240 140"><path d="M30 30H210M30 110H210M30 30V52M30 88V110M120 30V55M120 85V110M210 30V52M210 88V110" class="d"/><circle cx="30" cy="70" r="16" class="d"/><rect x="105" y="55" width="30" height="30" class="d"/><circle cx="210" cy="70" r="16" class="d"/><path d="M210 60V80" class="a"/><path d="M210 80l-5-9h10z" class="af"/><text x="5" y="74">U</text><text x="140" y="75">R</text><text x="224" y="82">I</text></svg>`,
  nb: { t: "Superposisjon",
    intro: "I en lineær krets med flere uavhengige kilder kan du finne strømmen eller spenningen i en gren ved å legge sammen bidraget fra hver kilde alene. Da slår du av alle de andre kildene: en spenningskilde kortsluttes til 0 V, og en strømkilde brytes til 0 A. Metoden gjelder aldri direkte for effekt, siden effekt er kvadratisk i strøm og spenning.",
    f: [["I=I'+I''+\\dots", "total strøm er summen av bidrag fra hver kilde alene"]],
    legend: [["I'", "bidrag fra kilde 1 (andre kilder slått av)", "A"], ["I''", "bidrag fra kilde 2 (andre kilder slått av)", "A"]],
    ex: "$U_1=12$ V gir $I'=1{,}2$ A, $I_2=2$ A gir $I''=0{,}8$ A:\n$I=I'+I''=1{,}2+0{,}8=2$ A.",
    tip: "Slå av kilder ved å kortslutte spenningskilder og bryte strømkilder – aldri omvendt." },
  en: { t: "Superposition",
    intro: "In a linear circuit with several independent sources you can find the current or voltage in a branch by adding the contribution from each source acting alone. To do this you turn off all the other sources: a voltage source is shorted to 0 V, and a current source is opened to 0 A. The method never applies directly to power, since power is quadratic in current and voltage.",
    f: [["I=I'+I''+\\dots", "total current is the sum of contributions from each source alone"]],
    legend: [["I'", "contribution from source 1 (other sources off)", "A"], ["I''", "contribution from source 2 (other sources off)", "A"]],
    ex: "$U_1=12$ V gives $I'=1.2$ A, $I_2=2$ A gives $I''=0.8$ A:\n$I=I'+I''=1.2+0.8=2$ A.",
    tip: "Turn off sources by shorting voltage sources and opening current sources – never the other way around." } },
{ id: "thevenin",
  fig: `<svg viewBox="0 0 240 140"><rect x="20" y="30" width="70" height="60" class="d"/><path d="M55 90V110M40 110h30" class="d"/><circle cx="40" cy="110" r="3" class="d"/><circle cx="70" cy="110" r="3" class="d"/><path d="M100 65H140" class="a"/><path d="M140 65l-10-5v10z" class="af"/><circle cx="170" cy="60" r="14" class="d"/><rect x="185" y="52" width="26" height="16" class="d"/><path d="M170 74V110M211 60H225V110M170 110H225" class="d"/><circle cx="170" cy="110" r="3" class="d"/><circle cx="225" cy="110" r="3" class="d"/><text x="35" y="60">?</text><text x="132" y="95">U<tspan dy="4" font-size="10">th</tspan></text><text x="189" y="42">R<tspan dy="4" font-size="10">th</tspan></text></svg>`,
  nb: { t: "Thévenin-ekvivalent",
    intro: "Enhver lineær krets sett fra to klemmer kan erstattes med én spenningskilde $U_{th}$ i serie med én motstand $R_{th}$. Dette forenkler kraftig når du skal analysere hvordan kretsen oppfører seg med forskjellige laster, siden du bare trenger å regne ut ekvivalenten én gang.",
    f: [["U_{th}=U_{\\text{åpen}}", "tomgangsspenningen over klemmene"], ["R_{th}=U_{\\text{åpen}}/I_{\\text{kort}}", "motstand fra åpen- og kortslutningsverdiene"]],
    legend: [["U_{th}", "Thévenin-spenning", "V"], ["R_{th}", "Thévenin-motstand", "\\Omega"], ["U_{\\text{åpen}}", "tomgangsspenning", "V"], ["I_{\\text{kort}}", "kortslutningsstrøm", "A"]],
    ex: "Tomgang $U_{\\text{åpen}}=10$ V, kortslutning $I_{\\text{kort}}=2$ A:\n$R_{th}=10/2=5$ Ω.",
    tip: "Finn $R_{th}$ med kildene slått av, eller fra forholdet mellom tomgangsspenning og kortslutningsstrøm." },
  en: { t: "Thévenin Equivalent",
    intro: "Any linear circuit seen from two terminals can be replaced by a single voltage source $U_{th}$ in series with a single resistor $R_{th}$. This is a huge simplification when analyzing how the circuit behaves with different loads, since you only need to compute the equivalent once.",
    f: [["U_{th}=U_{\\text{open}}", "the open-circuit voltage across the terminals"], ["R_{th}=U_{\\text{open}}/I_{\\text{short}}", "resistance from the open- and short-circuit values"]],
    legend: [["U_{th}", "Thévenin voltage", "V"], ["R_{th}", "Thévenin resistance", "\\Omega"], ["U_{\\text{open}}", "open-circuit voltage", "V"], ["I_{\\text{short}}", "short-circuit current", "A"]],
    ex: "Open circuit $U_{\\text{open}}=10$ V, short circuit $I_{\\text{short}}=2$ A:\n$R_{th}=10/2=5$ Ω.",
    tip: "Find $R_{th}$ with the sources turned off, or from the ratio of the open-circuit voltage to the short-circuit current." } },
{ id: "maks-effekt",
  fig: `<svg viewBox="0 0 240 140"><path d="M30 120H220M30 120V20" class="dim"/><path d="M30 115C70 40 110 25 130 25S190 60 215 115" class="d"/><path d="M130 25V120M30 120H130" class="dash"/><text x="222" y="45">P</text><text x="215" y="132">R<tspan dy="4" font-size="10">L</tspan></text><text x="122" y="132">R<tspan dy="4" font-size="10">th</tspan></text></svg>`,
  nb: { t: "Maksimal effektoverføring",
    intro: "Når en last kobles til en krets med indre (Thévenin-)motstand, blir effekten som overføres til lasten størst når lastmotstanden er lik kildens indre motstand. Ved denne betingelsen er virkningsgraden bare 50 %, siden like mye effekt går tapt i kilden selv – maksimal effekt og god virkningsgrad er altså ikke det samme.",
    f: [["P_{maks}=\\dfrac{U_{th}^2}{4R_{th}}\\ \\text{ved}\\ R_L=R_{th}", "maksimal effekt til lasten"]],
    legend: [["R_L", "lastmotstand", "\\Omega"], ["R_{th}", "kildens (Thévenin-)motstand", "\\Omega"], ["U_{th}", "Thévenin-spenning", "V"]],
    ex: "$U_{th}=10$ V, $R_{th}=5$ Ω:\n$P_{maks}=10^2/(4\\cdot5)=5$ W ved $R_L=5$ Ω.",
    tip: "$R_L=R_{th}$ gir maksimal effekt til lasten, ikke best virkningsgrad – den er da bare 50 %." },
  en: { t: "Maximum Power Transfer",
    intro: "When a load is connected to a circuit with an internal (Thévenin) resistance, the power delivered to the load is greatest when the load resistance equals the source's internal resistance. Under this condition the efficiency is only 50%, since just as much power is lost in the source itself – maximum power and good efficiency are therefore not the same thing.",
    f: [["P_{max}=\\dfrac{U_{th}^2}{4R_{th}}\\ \\text{at}\\ R_L=R_{th}", "maximum power delivered to the load"]],
    legend: [["R_L", "load resistance", "\\Omega"], ["R_{th}", "source's (Thévenin) resistance", "\\Omega"], ["U_{th}", "Thévenin voltage", "V"]],
    ex: "$U_{th}=10$ V, $R_{th}=5$ Ω:\n$P_{max}=10^2/(4\\cdot5)=5$ W at $R_L=5$ Ω.",
    tip: "$R_L=R_{th}$ gives maximum power to the load, not the best efficiency – that is then only 50%." } }
]);

// ================= ELEK – enhet 0: Dioder og transistorer =================
TOPICS("ELEK", 0, [
{ id: "diode-likeretter",
  fig: `<svg viewBox="0 0 240 140"><path d="M40 30H200M200 30V55M200 85V110M200 110H40M40 88V110M40 30V52" class="d"/><circle cx="40" cy="70" r="18" class="d"/><rect x="185" y="55" width="30" height="30" class="d"/><text x="15" y="74">U</text><text x="221" y="75">D</text></svg>`,
  nb: { t: "Diode og likeretter",
    intro: "En diode slipper strøm gjennom i én retning, med et nesten konstant spenningsfall når den leder. En silisiumdiode har typisk et spenningsfall på omtrent 0,7 V uavhengig av strømmen. En brolikeretter bruker fire dioder til å gjøre begge halvperiodene av en vekselspenning om til samme polaritet.",
    f: [["V_D\\approx0{,}7\\ \\text{V}", "spenningsfall over en silisiumdiode i lederetning"], ["I=\\dfrac{V_S-V_D}{R}", "strøm gjennom en diode i serie med en motstand"]],
    legend: [["V_D", "spenningsfall over dioden", "V"], ["V_S", "kildespenning", "V"], ["R", "seriemotstand", "\\Omega"]],
    ex: "$V_S=5$ V, $R=330$ Ω:\n$I=(5-0{,}7)/330\\approx13$ mA.",
    tip: "Sperreretning betyr (nesten) ingen strøm – ikke bytt om lederetning og sperreretning." },
  en: { t: "Diode and Rectifier",
    intro: "A diode lets current through in only one direction, with an almost constant voltage drop while conducting. A silicon diode typically has a voltage drop of about 0.7 V, nearly independent of the current. A bridge rectifier uses four diodes to turn both half-cycles of an AC voltage into the same polarity.",
    f: [["V_D\\approx0.7\\ \\text{V}", "voltage drop across a silicon diode in forward bias"], ["I=\\dfrac{V_S-V_D}{R}", "current through a diode in series with a resistor"]],
    legend: [["V_D", "voltage drop across the diode", "V"], ["V_S", "source voltage", "V"], ["R", "series resistor", "\\Omega"]],
    ex: "$V_S=5$ V, $R=330$ Ω:\n$I=(5-0.7)/330\\approx13$ mA.",
    tip: "Reverse bias means (almost) no current – do not mix up forward and reverse bias." } },
{ id: "zenerdiode",
  fig: `<svg viewBox="0 0 240 140"><path d="M40 30H200M200 30V55M200 85V110M200 110H40M40 88V110M40 30V52" class="d"/><circle cx="40" cy="70" r="18" class="d"/><rect x="185" y="55" width="30" height="30" class="d"/><text x="15" y="74">U</text><text x="221" y="75">Z</text></svg>`,
  nb: { t: "Zenerdiode",
    intro: "En zenerdiode kobles bakvendt, i sperreretning, og holder en fast spenning $V_Z$ over seg selv når den leder i denne retningen. Den brukes ofte som en enkel spenningsregulator: en seriemotstand tar opp resten av spenningen fra kilden, og strømmen gjennom motstanden setter zenerstrømmen.",
    f: [["R_S=\\dfrac{V_{inn}-V_Z}{I_Z}", "seriemotstand for en enkel zenerregulator"]],
    legend: [["V_Z", "zenerspenning", "V"], ["V_{inn}", "inngangsspenning", "V"], ["I_Z", "ønsket zenerstrøm", "A"], ["R_S", "seriemotstand", "\\Omega"]],
    ex: "$V_{inn}=12$ V, $V_Z=5{,}6$ V, $I_Z=20$ mA:\n$R_S=(12-5{,}6)/0{,}02=320$ Ω.",
    tip: "Zenerdioden kobles i sperreretning for å regulere spenning – motsatt av en vanlig diode." },
  en: { t: "Zener Diode",
    intro: "A zener diode is connected backward, in reverse bias, and holds a fixed voltage $V_Z$ across itself while conducting in this direction. It is often used as a simple voltage regulator: a series resistor absorbs the rest of the voltage from the source, and the current through it sets the zener current.",
    f: [["R_S=\\dfrac{V_{in}-V_Z}{I_Z}", "series resistor for a simple zener regulator"]],
    legend: [["V_Z", "zener voltage", "V"], ["V_{in}", "input voltage", "V"], ["I_Z", "desired zener current", "A"], ["R_S", "series resistor", "\\Omega"]],
    ex: "$V_{in}=12$ V, $V_Z=5.6$ V, $I_Z=20$ mA:\n$R_S=(12-5.6)/0.02=320$ Ω.",
    tip: "A zener diode is connected in reverse bias to regulate voltage – the opposite of an ordinary diode." } },
{ id: "bjt-transistor",
  fig: `<svg viewBox="0 0 240 140"><rect x="90" y="40" width="50" height="60" class="d"/><path d="M90 50H50M90 90H50M140 70H190" class="d"/><text x="30" y="54">B</text><text x="30" y="94">E</text><text x="195" y="74">C</text></svg>`,
  nb: { t: "BJT-transistor",
    intro: "En BJT er en strømstyrt transistor: en liten basestrøm styrer en mye større kollektorstrøm. I aktivt område er kollektorstrømmen proporsjonal med basestrømmen gjennom forsterkningen β. I metning (brukt som svitsj) er $V_{CE}$ svært lav, og kollektorstrømmen bestemmes da av resten av kretsen, ikke lenger av β.",
    f: [["I_C=\\beta I_B", "gjelder i aktivt område"], ["V_{CE}\\ \\text{lav}\\ (\\approx0{,}1\\text{–}0{,}3\\ \\text{V})", "kjennetegn på metning (transistor som lukket bryter)"]],
    legend: [["I_B", "basestrøm", "A"], ["I_C", "kollektorstrøm", "A"], ["\\beta", "strømforsterkning", ""], ["V_{CE}", "spenning kollektor–emitter", "V"]],
    ex: "$\\beta=100$, $I_B=20$ µA (aktivt område):\n$I_C=\\beta I_B=100\\cdot20=2000$ µA $=2$ mA.",
    tip: "$I_C=\\beta I_B$ gjelder bare i aktivt område – i metning bestemmes $I_C$ av lastkretsen." },
  en: { t: "BJT Transistor",
    intro: "A BJT is a current-controlled transistor: a small base current controls a much larger collector current. In the active region the collector current is proportional to the base current through the gain β. In saturation (used as a switch) $V_{CE}$ is very low, and the collector current is then set by the rest of the circuit, not by β anymore.",
    f: [["I_C=\\beta I_B", "holds in the active region"], ["V_{CE}\\ \\text{low}\\ (\\approx0.1\\text{-}0.3\\ \\text{V})", "characteristic of saturation (transistor as a closed switch)"]],
    legend: [["I_B", "base current", "A"], ["I_C", "collector current", "A"], ["\\beta", "current gain", ""], ["V_{CE}", "collector-emitter voltage", "V"]],
    ex: "$\\beta=100$, $I_B=20$ µA (active region):\n$I_C=\\beta I_B=100\\cdot20=2000$ µA $=2$ mA.",
    tip: "$I_C=\\beta I_B$ only holds in the active region – in saturation $I_C$ is set by the load circuit." } }
]);

// ================= ELEK – enhet 1: Operasjonsforsterkere =================
TOPICS("ELEK", 1, [
{ id: "opamp-grunnregler",
  fig: `<svg viewBox="0 0 240 140"><path d="M70 35L70 105L170 70Z" class="d"/><path d="M30 50H70M30 90H70M170 70H210" class="d"/><text x="77" y="56">-</text><text x="76" y="90">+</text><text x="185" y="65">V<tspan dy="4" font-size="10">o</tspan></text></svg>`,
  nb: { t: "Op-amp: grunnregler",
    intro: "En ideell operasjonsforsterker med negativ tilbakekobling følger to enkle regler: det går ingen strøm inn i inngangene, og spenningen på de to inngangene er lik (virtuell kortslutning). Disse to reglene er nok til å utlede forsterkningen til nesten alle op-amp-kretser uten å regne med den indre forsterkningen direkte.",
    f: [["I_+=I_-=0", "ingen strøm inn i inngangene"], ["V_+=V_-", "virtuell kortslutning mellom inngangene"]],
    legend: [["V_+,\\ V_-", "spenning på henholdsvis + og − inngang", "V"], ["I_+,\\ I_-", "strøm inn i inngangene", "A"]],
    ex: "Ikke-inverterende forsterker med $V_+=2$ V:\nVirtuell kortslutning gir $V_-=2$ V også.",
    tip: "De to reglene gjelder bare ved negativ tilbakekobling – uten den er utgangen i metning." },
  en: { t: "Op-Amp Golden Rules",
    intro: "An ideal operational amplifier with negative feedback follows two simple rules: no current flows into the inputs, and the voltage on the two inputs is equal (a virtual short). These two rules are enough to derive the gain of almost any op-amp circuit without dealing with the internal gain directly.",
    f: [["I_+=I_-=0", "no current flows into the inputs"], ["V_+=V_-", "virtual short between the inputs"]],
    legend: [["V_+,\\ V_-", "voltage on the + and - input respectively", "V"], ["I_+,\\ I_-", "current into the inputs", "A"]],
    ex: "Non-inverting amplifier with $V_+=2$ V:\nThe virtual short gives $V_-=2$ V as well.",
    tip: "The two rules only hold with negative feedback – without it the output saturates." } },
{ id: "inverterende-forsterker",
  fig: `<svg viewBox="0 0 240 140"><path d="M90 35L90 105L190 70Z" class="d"/><path d="M20 50H90M190 70H220" class="d"/><rect x="35" y="42" width="35" height="16" class="d"/><path d="M90 30H160V50H190" class="d"/><rect x="115" y="22" width="35" height="16" class="d"/><path d="M90 90H60V110H110" class="d"/><text x="48" y="40">R<tspan dy="4" font-size="10">i</tspan></text><text x="127" y="20">R<tspan dy="4" font-size="10">f</tspan></text></svg>`,
  nb: { t: "Inverterende forsterker",
    intro: "I en inverterende forsterker kobles signalet inn via en motstand $R_{inn}$ til den negative inngangen, mens tilbakekoblingsmotstanden $R_f$ går fra utgangen til samme inngang. Forsterkningen er negativ, altså inverterer den signalet (180° faseskift), og bestemmes bare av forholdet mellom de to motstandene.",
    f: [["A=-\\dfrac{R_f}{R_{inn}}", "spenningsforsterkning, inverterende forsterker"]],
    legend: [["R_{inn}", "inngangsmotstand", "\\Omega"], ["R_f", "tilbakekoblingsmotstand", "\\Omega"], ["A", "spenningsforsterkning", ""]],
    ex: "$R_{inn}=1$ kΩ, $R_f=10$ kΩ, $V_{inn}=0{,}2$ V:\n$V_o=-10\\cdot0{,}2=-2$ V.",
    tip: "Minustegnet betyr 180° faseskift – ikke glem det når du regner ut utgangen." },
  en: { t: "Inverting Amplifier",
    intro: "In an inverting amplifier the signal enters through a resistor $R_{in}$ to the negative input, while the feedback resistor $R_f$ runs from the output back to the same input. The gain is negative, so it inverts the signal (180° phase shift), and is set only by the ratio of the two resistors.",
    f: [["A=-\\dfrac{R_f}{R_{in}}", "voltage gain, inverting amplifier"]],
    legend: [["R_{in}", "input resistor", "\\Omega"], ["R_f", "feedback resistor", "\\Omega"], ["A", "voltage gain", ""]],
    ex: "$R_{in}=1$ kΩ, $R_f=10$ kΩ, $V_{in}=0.2$ V:\n$V_o=-10\\cdot0.2=-2$ V.",
    tip: "The minus sign means a 180° phase shift – do not forget it when computing the output." } },
{ id: "ikke-inverterende-forsterker",
  fig: `<svg viewBox="0 0 240 140"><path d="M90 35L90 105L190 70Z" class="d"/><path d="M20 90H90M190 70H220" class="d"/><path d="M90 30H160V50H190" class="d"/><rect x="115" y="22" width="35" height="16" class="d"/><path d="M90 50H60V110H90" class="d"/><rect x="45" y="102" width="30" height="16" class="d"/><text x="127" y="20">R<tspan dy="4" font-size="10">f</tspan></text><text x="50" y="117">R<tspan dy="4" font-size="10">g</tspan></text></svg>`,
  nb: { t: "Ikke-inverterende forsterker",
    intro: "I en ikke-inverterende forsterker kommer signalet rett inn på den positive inngangen, mens $R_g$ og $R_f$ danner en tilbakekoblingsdeler til den negative inngangen. Forsterkningen er alltid positiv og minst 1, og blir stor bare hvis $R_g$ er liten sammenlignet med $R_f$.",
    f: [["A=1+\\dfrac{R_f}{R_g}", "spenningsforsterkning, ikke-inverterende forsterker"]],
    legend: [["R_g", "motstand til jord fra − inngangen", "\\Omega"], ["R_f", "tilbakekoblingsmotstand", "\\Omega"], ["A", "spenningsforsterkning", ""]],
    ex: "$R_g=2{,}2$ kΩ, $R_f=22$ kΩ:\n$A=1+22/2{,}2=11$.",
    tip: "En spenningsfølger er et spesialtilfelle: $R_f=0$ og $R_g\\to\\infty$ gir $A=1$." },
  en: { t: "Non-Inverting Amplifier",
    intro: "In a non-inverting amplifier the signal enters directly at the positive input, while $R_g$ and $R_f$ form a feedback divider to the negative input. The gain is always positive and at least 1, and becomes large only if $R_g$ is small compared with $R_f$.",
    f: [["A=1+\\dfrac{R_f}{R_g}", "voltage gain, non-inverting amplifier"]],
    legend: [["R_g", "resistor to ground from the - input", "\\Omega"], ["R_f", "feedback resistor", "\\Omega"], ["A", "voltage gain", ""]],
    ex: "$R_g=2.2$ kΩ, $R_f=22$ kΩ:\n$A=1+22/2.2=11$.",
    tip: "A voltage follower is a special case: $R_f=0$ and $R_g\\to\\infty$ gives $A=1$." } }
]);

// ================= ELEK – enhet 2: Filtre og signaler =================
TOPICS("ELEK", 2, [
{ id: "rc-lavpass",
  fig: `<svg viewBox="0 0 240 140"><path d="M20 50H70" class="d"/><rect x="70" y="42" width="40" height="16" class="d"/><path d="M110 50H190" class="d"/><path d="M150 50V80" class="d"/><path d="M135 80H165M135 95H165" class="d"/><path d="M150 95V110M20 110H190M20 50V110M190 50V110" class="d"/><text x="80" y="38">R</text><text x="172" y="70">C</text><text x="192" y="54">U<tspan dy="4" font-size="10">o</tspan></text></svg>`,
  nb: { t: "RC-lavpassfilter",
    intro: "Et RC-lavpassfilter slipper gjennom lave frekvenser og demper høye. Ved knekkfrekvensen $f_c$ har amplituden falt til $1/\\sqrt2$ av lavfrekvensverdien, altså $-3$ dB, og over $f_c$ faller den videre med 20 dB per dekade.",
    f: [["f_c=\\dfrac{1}{2\\pi RC}", "knekkfrekvens for et RC-lavpass"]],
    legend: [["R", "motstand", "\\Omega"], ["C", "kapasitans", "F"], ["f_c", "knekkfrekvens", "Hz"]],
    ex: "$R=10$ kΩ, $C=100$ nF:\n$f_c=1/(2\\pi\\cdot10^4\\cdot10^{-7})\\approx159$ Hz.",
    tip: "Ved $f_c$ er forsterkningen $1/\\sqrt2\\approx0{,}707$, altså $-3$ dB, uansett verdiene på R og C." },
  en: { t: "RC Low-Pass Filter",
    intro: "An RC low-pass filter passes low frequencies and attenuates high ones. At the corner frequency $f_c$ the amplitude has dropped to $1/\\sqrt2$ of its low-frequency value, i.e. $-3$ dB, and above $f_c$ it keeps falling at 20 dB per decade.",
    f: [["f_c=\\dfrac{1}{2\\pi RC}", "corner frequency of an RC low-pass"]],
    legend: [["R", "resistance", "\\Omega"], ["C", "capacitance", "F"], ["f_c", "corner frequency", "Hz"]],
    ex: "$R=10$ kΩ, $C=100$ nF:\n$f_c=1/(2\\pi\\cdot10^4\\cdot10^{-7})\\approx159$ Hz.",
    tip: "At $f_c$ the gain is $1/\\sqrt2\\approx0.707$, i.e. $-3$ dB, regardless of the values of R and C." } },
{ id: "rc-hoypass",
  fig: `<svg viewBox="0 0 240 140"><path d="M20 50H62M78 50H190" class="d"/><path d="M65 35V65M75 35V65" class="d"/><path d="M150 50V80" class="d"/><rect x="135" y="80" width="30" height="20" class="d"/><path d="M150 100V110M20 110H190M20 50V110M190 50V110" class="d"/><text x="63" y="28">C</text><text x="170" y="93">R</text><text x="192" y="54">U<tspan dy="4" font-size="10">o</tspan></text></svg>`,
  nb: { t: "RC-høypassfilter",
    intro: "Et RC-høypassfilter slipper gjennom høye frekvenser og demper lave, motsatt av lavpassfilteret, og brukes ofte til å fjerne et likespenningsnivå (AC-kobling). Kondensator og motstand bytter rett og slett plass i forhold til lavpassfilteret, men knekkfrekvensformelen er den samme.",
    f: [["f_c=\\dfrac{1}{2\\pi RC}", "knekkfrekvens for et RC-høypass"]],
    legend: [["R", "motstand", "\\Omega"], ["C", "kapasitans", "F"], ["f_c", "knekkfrekvens", "Hz"]],
    ex: "$R=1$ kΩ, $C=1$ µF:\n$f_c=1/(2\\pi\\cdot10^3\\cdot10^{-6})\\approx159$ Hz.",
    tip: "Høypass og lavpass har samme knekkfrekvensformel – det er plasseringen av R og C som avgjør hvilken type det er." },
  en: { t: "RC High-Pass Filter",
    intro: "An RC high-pass filter passes high frequencies and attenuates low ones, the opposite of the low-pass filter, and is often used to remove a DC level (AC coupling). The capacitor and resistor simply swap places compared with the low-pass filter, but the corner-frequency formula is the same.",
    f: [["f_c=\\dfrac{1}{2\\pi RC}", "corner frequency of an RC high-pass"]],
    legend: [["R", "resistance", "\\Omega"], ["C", "capacitance", "F"], ["f_c", "corner frequency", "Hz"]],
    ex: "$R=1$ kΩ, $C=1$ µF:\n$f_c=1/(2\\pi\\cdot10^3\\cdot10^{-6})\\approx159$ Hz.",
    tip: "High-pass and low-pass share the same corner-frequency formula – it is the placement of R and C that decides the type." } },
{ id: "db-skala",
  nb: { t: "Desibel (dB)",
    intro: "Desibel er en logaritmisk måte å angi forholdet mellom to spenninger (eller andre størrelser) på, og brukes fordi forsterkning og demping i kaskadekoblede systemer da bare kan legges sammen i stedet for å multipliseres. En halvering av amplituden tilsvarer omtrent $-6$ dB.",
    f: [["|H|_{dB}=20\\log_{10}|H|", "desibel fra et spenningsforhold"]],
    legend: [["|H|", "spenningsforhold (forsterkning)", ""], ["|H|_{dB}", "forholdet i desibel", "dB"]],
    ex: "$|H|=0{,}5$:\n$|H|_{dB}=20\\log_{10}(0{,}5)\\approx-6$ dB.",
    tip: "$-3$ dB tilsvarer omtrent $1/\\sqrt2\\approx0{,}707$ i amplitude, ikke halvparten av amplituden." },
  en: { t: "Decibels (dB)",
    intro: "The decibel is a logarithmic way of stating the ratio between two voltages (or other quantities), used because gain and attenuation in cascaded systems can then simply be added instead of multiplied. Halving the amplitude corresponds to about $-6$ dB.",
    f: [["|H|_{dB}=20\\log_{10}|H|", "decibels from a voltage ratio"]],
    legend: [["|H|", "voltage ratio (gain)", ""], ["|H|_{dB}", "the ratio in decibels", "dB"]],
    ex: "$|H|=0.5$:\n$|H|_{dB}=20\\log_{10}(0.5)\\approx-6$ dB.",
    tip: "$-3$ dB corresponds to about $1/\\sqrt2\\approx0.707$ in amplitude, not half the amplitude." } }
]);

// ================= ELFT2500 – enhet 0: Tallsystemer og digital logikk =================
TOPICS("ELFT2500", 0, [
{ id: "tallsystemer",
  nb: { t: "Tallsystemer",
    intro: "Datamaskiner regner internt med binære tall (grunntall 2), men heksadesimale tall (grunntall 16) brukes ofte som en kompakt stenografi for binærtall, siden to heksadesimale siffer alltid utgjør nøyaktig én byte. Et siffer på plass $k$ har vekt $b^k$, der $b$ er grunntallet.",
    f: [["\\text{verdi}=\\sum_k d_k\\cdot b^k", "posisjonssystem: hvert siffer d_k vektes med b^k"]],
    legend: [["b", "grunntall (2, 16 eller 10)", ""], ["d_k", "siffer på plass k", ""]],
    ex: "$\\texttt{0x1F}$ i heksadesimalt:\n$1\\cdot16+15\\cdot1=31$.",
    tip: "To heksadesimale siffer er alltid nøyaktig én byte – nyttig for å lese minneadresser og fargekoder." },
  en: { t: "Number Systems",
    intro: "Computers compute internally with binary numbers (base 2), but hexadecimal numbers (base 16) are often used as a compact shorthand for binary, since two hex digits always make exactly one byte. A digit at position $k$ has weight $b^k$, where $b$ is the base.",
    f: [["\\text{value}=\\sum_k d_k\\cdot b^k", "positional system: each digit d_k is weighted by b^k"]],
    legend: [["b", "base (2, 16 or 10)", ""], ["d_k", "digit at position k", ""]],
    ex: "$\\texttt{0x1F}$ in decimal:\n$1\\cdot16+15\\cdot1=31$.",
    tip: "Two hex digits are always exactly one byte – handy for reading memory addresses and color codes." } },
{ id: "toerkomplement",
  nb: { t: "Toerkomplement",
    intro: "Toerkomplement er standardmåten datamaskiner representerer negative heltall på i et fast antall bit. Det øverste bitet forteller fortegnet, og et negativt tall $-x$ representeres som det usignerte bitmønsteret til $2^n-x$. Dette gjør at addisjon fungerer likt for positive og negative tall, uten spesialtilfeller.",
    f: [["-x \\to 2^n-x", "bitmønster for et negativt tall i n-bits toerkomplement"], ["[-2^{n-1},\\ 2^{n-1}-1]", "verdiområde for et n-bits signert heltall"]],
    legend: [["n", "antall bit", ""], ["x", "tallets absoluttverdi", ""]],
    ex: "$-5$ som 8-bits toerkomplement:\n$2^8-5=251=\\texttt{0xFB}$.",
    tip: "Husk å trekke fra $2^n$, ikke bare snu fortegnsbiten – det gir feil svar." },
  en: { t: "Two's Complement",
    intro: "Two's complement is the standard way computers represent negative integers in a fixed number of bits. The top bit signals the sign, and a negative number $-x$ is represented as the unsigned bit pattern of $2^n-x$. This makes addition work the same way for positive and negative numbers, with no special cases.",
    f: [["-x \\to 2^n-x", "bit pattern for a negative number in n-bit two's complement"], ["[-2^{n-1},\\ 2^{n-1}-1]", "range of an n-bit signed integer"]],
    legend: [["n", "number of bits", ""], ["x", "the number's absolute value", ""]],
    ex: "$-5$ as 8-bit two's complement:\n$2^8-5=251=\\texttt{0xFB}$.",
    tip: "Remember to subtract from $2^n$, not just flip the sign bit – that gives the wrong answer." } },
{ id: "logiske-porter",
  nb: { t: "Logiske porter",
    intro: "Logiske porter er byggesteinene i digital elektronikk og programvare: AND gir 1 bare når begge innganger er 1, OR gir 1 når minst én inngang er 1, XOR gir 1 når inngangene er ulike, og NOT snur en enkelt inngang. NAND og NOR er rett og slett AND og OR etterfulgt av en NOT.",
    f: [["Y=A\\cdot B", "AND: 1 bare når A=1 og B=1"], ["Y=A\\oplus B", "XOR: 1 bare når A og B er ulike"]],
    legend: [["A,\\ B", "innganger (0 eller 1)", ""], ["Y", "utgang (0 eller 1)", ""]],
    ex: "AND-port med $A=1$, $B=0$:\n$Y=1\\cdot0=0$.",
    tip: "Sett opp en sannhetstabell hvis du er usikker på hvordan en port oppfører seg." },
  en: { t: "Logic Gates",
    intro: "Logic gates are the building blocks of digital electronics and software: AND gives 1 only when both inputs are 1, OR gives 1 when at least one input is 1, XOR gives 1 when the inputs differ, and NOT inverts a single input. NAND and NOR are simply AND and OR followed by a NOT.",
    f: [["Y=A\\cdot B", "AND: 1 only when A=1 and B=1"], ["Y=A\\oplus B", "XOR: 1 only when A and B differ"]],
    legend: [["A,\\ B", "inputs (0 or 1)", ""], ["Y", "output (0 or 1)", ""]],
    ex: "AND gate with $A=1$, $B=0$:\n$Y=1\\cdot0=0$.",
    tip: "Build a truth table if you are unsure how a gate behaves." } }
]);

// ================= ELFT2500 – enhet 1: Mikrokontrollere =================
TOPICS("ELFT2500", 1, [
{ id: "gpio-pullup",
  fig: `<svg viewBox="0 0 240 140"><path d="M120 20V45" class="d"/><rect x="105" y="45" width="30" height="30" class="d"/><path d="M120 75V90" class="d"/><circle cx="120" cy="90" r="4" class="d"/><path d="M120 94V115M100 130L120 108L140 130" class="d"/><path d="M20 90H116" class="d"/><text x="112" y="15">V<tspan dy="4" font-size="10">cc</tspan></text><text x="121" y="60">R</text></svg>`,
  nb: { t: "Pull-up-motstand",
    intro: "En digital inngang som ikke er koblet til noe bestemt kan «flyte» og lese tilfeldige verdier. En pull-up-motstand trekker inngangen til et definert høyt nivå når ingenting annet driver den, for eksempel når en knapp er åpen. Når knappen trykkes inn, trekkes inngangen lav i stedet.",
    f: [["I = \\dfrac{V_{cc}}{R_{pu}}", "strøm gjennom pull-up-motstanden når inngangen trekkes lav (bryter lukket)"]],
    legend: [["V_{cc}", "forsyningsspenning", "V"], ["R_{pu}", "pull-up-motstand", "\\Omega"], ["I", "strøm gjennom motstanden", "A"]],
    ex: "$V_{cc}=3{,}3$ V, $R_{pu}=10$ kΩ, bryter lukket:\n$I=3{,}3/10000=0{,}33$ mA.",
    tip: "Uten pull-up flyter en åpen inngang og kan lese tilfeldige verdier – definer alltid nivået." },
  en: { t: "Pull-Up Resistor",
    intro: "A digital input that is not connected to anything definite can float and read random values. A pull-up resistor pulls the input to a defined high level when nothing else is driving it, for example when a button is open. When the button is pressed, the input is pulled low instead.",
    f: [["I = \\dfrac{V_{cc}}{R_{pu}}", "current through the pull-up resistor when the input is pulled low (switch closed)"]],
    legend: [["V_{cc}", "supply voltage", "V"], ["R_{pu}", "pull-up resistor", "\\Omega"], ["I", "current through the resistor", "A"]],
    ex: "$V_{cc}=3.3$ V, $R_{pu}=10$ kΩ, switch closed:\n$I=3.3/10000=0.33$ mA.",
    tip: "Without a pull-up an open input floats and can read random values – always define the level." } },
{ id: "pwm",
  fig: `<svg viewBox="0 0 240 140"><path d="M20 105H220M20 105V25" class="dim"/><path d="M20 105H40V35H90V105H110V35H160V105H180V35H220" class="d"/><text x="7" y="30">V</text><text x="222" y="110">t</text></svg>`,
  nb: { t: "PWM",
    intro: "Et PWM-signal svitsjer raskt mellom høy og lav spenning med en bestemt duty cycle, altså andelen av perioden signalet er høyt. Belastningen eller filteret etter signalet ser i praksis bare gjennomsnittsspenningen, som er proporsjonal med duty cyclen – dette brukes til å styre alt fra LED-lysstyrke til motorhastighet.",
    f: [["V_{gj} = D\\cdot V_{høy}", "gjennomsnittsspenning fra duty cycle D"]],
    legend: [["D", "duty cycle (andel av perioden signalet er høyt)", ""], ["V_{høy}", "spenningsnivå når signalet er høyt", "V"], ["V_{gj}", "gjennomsnittsspenning", "V"]],
    ex: "5 V PWM med 25 % duty cycle:\n$V_{gj}=0{,}25\\cdot5=1{,}25$ V.",
    tip: "Duty cycle regnes som pulslengden delt på hele periodetiden, ikke delt på tiden signalet er lavt." },
  en: { t: "PWM",
    intro: "A PWM signal switches rapidly between a high and a low voltage with a given duty cycle, the fraction of the period the signal is high. The load or filter after the signal effectively only sees the average voltage, which is proportional to the duty cycle – this is used to control everything from LED brightness to motor speed.",
    f: [["V_{avg} = D\\cdot V_{high}", "average voltage from duty cycle D"]],
    legend: [["D", "duty cycle (fraction of the period the signal is high)", ""], ["V_{high}", "voltage level when the signal is high", "V"], ["V_{avg}", "average voltage", "V"]],
    ex: "5 V PWM with 25% duty cycle:\n$V_{avg}=0.25\\cdot5=1.25$ V.",
    tip: "Duty cycle is the pulse length divided by the whole period, not by the time the signal is low." } },
{ id: "seriell-kommunikasjon",
  nb: { t: "Seriell kommunikasjon",
    intro: "UART, SPI og I²C er de vanligste seriellprotokollene mellom en mikrokontroller og eksterne enheter. UART er asynkron uten felles klokke og bruker start- og stoppbit; SPI er synkron med felles klokke og ingen start-/stoppbit; I²C bruker bare to linjer med åpne utganger og krever pull-up-motstander.",
    f: [["\\text{SPI byte/s}=\\dfrac{f_{SCK}}{8}", "gjennomstrømning for SPI (ingen start-/stoppbit)"]],
    legend: [["f_{SCK}", "klokkefrekvens på SPI-bussen", "Hz"]],
    ex: "SPI-klokke $1$ MHz:\nGjennomstrømning $=10^6/8=125\\,000$ byte/s.",
    tip: "UART har start- og stoppbit, SPI og I²C har det normalt ikke – tell riktig antall bit per overføring." },
  en: { t: "Serial Communication",
    intro: "UART, SPI and I2C are the most common serial protocols between a microcontroller and external devices. UART is asynchronous with no shared clock and uses start and stop bits; SPI is synchronous with a shared clock and no start/stop bits; I2C uses just two lines with open-drain outputs and requires pull-up resistors.",
    f: [["\\text{SPI bytes/s}=\\dfrac{f_{SCK}}{8}", "throughput for SPI (no start/stop bits)"]],
    legend: [["f_{SCK}", "clock frequency of the SPI bus", "Hz"]],
    ex: "SPI clock $1$ MHz:\nThroughput $=10^6/8=125\\,000$ bytes/s.",
    tip: "UART has start and stop bits, SPI and I2C normally do not – count the right number of bits per transfer." } }
]);

// ================= ELFT2500 – enhet 2: Måleteknikk =================
TOPICS("ELFT2500", 2, [
{ id: "noyaktighet-presisjon",
  fig: `<svg viewBox="0 0 240 140"><circle cx="70" cy="70" r="45" class="dim"/><circle cx="70" cy="70" r="28" class="dim"/><circle cx="70" cy="70" r="12" class="dim"/><circle cx="65" cy="68" r="2" class="rf"/><circle cx="74" cy="72" r="2" class="rf"/><circle cx="68" cy="75" r="2" class="rf"/><circle cx="72" cy="65" r="2" class="rf"/><circle cx="170" cy="70" r="45" class="dim"/><circle cx="170" cy="70" r="28" class="dim"/><circle cx="170" cy="70" r="12" class="dim"/><circle cx="130" cy="40" r="2" class="rf"/><circle cx="135" cy="45" r="2" class="rf"/><circle cx="132" cy="50" r="2" class="rf"/><circle cx="128" cy="46" r="2" class="rf"/></svg>`,
  nb: { t: "Nøyaktighet og presisjon",
    intro: "Nøyaktighet forteller hvor nær målingene i gjennomsnitt er den sanne verdien, altså hvor liten den systematiske feilen er. Presisjon forteller hvor tett målingene er samlet rundt hverandre, altså hvor liten spredningen (støyen) er. En sensor kan være presis uten å være nøyaktig, og omvendt – de to egenskapene er uavhengige av hverandre.",
    f: [["\\bar{x}=\\dfrac{1}{n}\\sum x_i", "gjennomsnitt av n målinger"], ["s=\\sqrt{\\dfrac{1}{n-1}\\sum(x_i-\\bar x)^2}", "standardavvik (angir presisjon, spredning)"]],
    legend: [["\\bar x", "gjennomsnitt av målingene", ""], ["s", "standardavvik (spredning)", ""], ["x_i", "enkeltmåling", ""]],
    ex: "Fem målinger tett samlet rundt 10,0 (sann verdi 10,0):\nGjennomsnitt $\\approx10{,}0$ (nøyaktig) og lite spredd (presist).",
    tip: "Presis er ikke det samme som nøyaktig – en vekt kan gi samme (feil) resultat hver gang." },
  en: { t: "Accuracy and Precision",
    intro: "Accuracy states how close the measurements are, on average, to the true value, i.e. how small the systematic error is. Precision states how tightly the measurements are clustered together, i.e. how small the spread (noise) is. A sensor can be precise without being accurate, and vice versa – the two properties are independent of each other.",
    f: [["\\bar{x}=\\dfrac{1}{n}\\sum x_i", "average of n measurements"], ["s=\\sqrt{\\dfrac{1}{n-1}\\sum(x_i-\\bar x)^2}", "standard deviation (states precision, spread)"]],
    legend: [["\\bar x", "average of the measurements", ""], ["s", "standard deviation (spread)", ""], ["x_i", "individual measurement", ""]],
    ex: "Five measurements clustered tightly around 10.0 (true value 10.0):\nAverage $\\approx10.0$ (accurate) and little spread (precise).",
    tip: "Precise is not the same as accurate – a scale can give the same (wrong) result every time." } },
{ id: "sampling-nyquist",
  fig: `<svg viewBox="0 0 240 140"><path d="M20 70H220" class="dim"/><path d="M20 70C40 30 60 30 80 70S120 110 140 70S180 30 200 70S220 90 220 70" class="d"/><circle cx="30" cy="55" r="3" class="rf"/><circle cx="80" cy="70" r="3" class="rf"/><circle cx="130" cy="82" r="3" class="rf"/><circle cx="180" cy="55" r="3" class="rf"/></svg>`,
  nb: { t: "Sampling og Nyquist",
    intro: "For å digitalisere et signal riktig må vi ta nok prøver per sekund. Nyquist-kriteriet sier at samplingsfrekvensen må være mer enn dobbelt så høy som den høyeste frekvenskomponenten i signalet. Samples vi for sjelden, oppstår aliasing: signalet ser ut som en helt annen (lavere) frekvens etter sampling, og denne feilen kan ikke rettes opp i etterkant.",
    f: [["f_s>2f_{maks}", "Nyquist-kriteriet for korrekt sampling"]],
    legend: [["f_s", "samplingsfrekvens", "Hz"], ["f_{maks}", "høyeste frekvenskomponent i signalet", "Hz"]],
    ex: "Signal opp til $1$ kHz:\nMinste teoretiske samplingsfrekvens: $f_s>2\\cdot1=2$ kHz.",
    tip: "Filtrer bort alt over $f_s/2$ *før* sampling – aliasing kan ikke fjernes etterpå." },
  en: { t: "Sampling and Nyquist",
    intro: "To digitize a signal correctly we must take enough samples per second. The Nyquist criterion says the sampling frequency must be more than twice the highest frequency component in the signal. If we sample too slowly, aliasing occurs: the signal appears as a completely different (lower) frequency after sampling, and this error cannot be corrected afterward.",
    f: [["f_s>2f_{max}", "Nyquist criterion for correct sampling"]],
    legend: [["f_s", "sampling frequency", "Hz"], ["f_{max}", "highest frequency component in the signal", "Hz"]],
    ex: "Signal up to $1$ kHz:\nMinimum theoretical sampling frequency: $f_s>2\\cdot1=2$ kHz.",
    tip: "Filter out everything above $f_s/2$ *before* sampling – aliasing cannot be removed afterward." } },
{ id: "wheatstone-bro",
  fig: `<svg viewBox="0 0 240 140"><path d="M120 20L200 70L120 120L40 70Z" class="d"/><rect x="65" y="35" width="30" height="14" class="d"/><rect x="145" y="35" width="30" height="14" class="d"/><rect x="65" y="91" width="30" height="14" class="d"/><rect x="145" y="91" width="30" height="14" class="d"/><path d="M120 20V10M120 130V120" class="d"/><path d="M40 70H20M200 70H220" class="d"/><text x="108" y="17">+</text><text x="108" y="135">-</text></svg>`,
  nb: { t: "Wheatstone-bro",
    intro: "En Wheatstone-bro består av fire motstander koblet i en diamantform, og brukes til å måle svært små motstandsendringer, for eksempel fra en strekklapp. Når broen er i balanse, er utgangsspenningen null; en liten endring $\\Delta R$ i én arm gir en liten, målbar differansespenning som kan forsterkes.",
    f: [["\\Delta R = GF\\cdot\\varepsilon\\cdot R", "motstandsendring fra tøyning i en strekklapp"]],
    legend: [["GF", "gauge factor (strekklappens følsomhet)", ""], ["\\varepsilon", "tøyning", ""], ["R", "motstandens nominelle verdi", "\\Omega"], ["\\Delta R", "motstandsendring", "\\Omega"]],
    ex: "$GF=2$, $\\varepsilon=0{,}001$, $R=120$ Ω:\n$\\Delta R=2\\cdot0{,}001\\cdot120=0{,}24$ Ω.",
    tip: "I balanse er utgangsspenningen null – selv en liten $\\Delta R$ gir da et tydelig utslag." },
  en: { t: "Wheatstone Bridge",
    intro: "A Wheatstone bridge consists of four resistors connected in a diamond shape, and is used to measure very small resistance changes, for example from a strain gauge. When the bridge is balanced, the output voltage is zero; a small change $\\Delta R$ in one arm gives a small, measurable differential voltage that can be amplified.",
    f: [["\\Delta R = GF\\cdot\\varepsilon\\cdot R", "resistance change from strain in a strain gauge"]],
    legend: [["GF", "gauge factor (the strain gauge's sensitivity)", ""], ["\\varepsilon", "strain", ""], ["R", "the resistor's nominal value", "\\Omega"], ["\\Delta R", "resistance change", "\\Omega"]],
    ex: "$GF=2$, $\\varepsilon=0.001$, $R=120$ Ω:\n$\\Delta R=2\\cdot0.001\\cdot120=0.24$ Ω.",
    tip: "When balanced the output voltage is zero – even a small $\\Delta R$ then gives a clear reading." } }
]);

// ================= ELFT2400 – enhet 0: Laplace og overføringsfunksjoner =================
TOPICS("ELFT2400", 0, [
{ id: "overforingsfunksjon-poler",
  fig: `<svg viewBox="0 0 240 140"><path d="M120 20V120M20 70H220" class="dim"/><path d="M70 65L80 75M80 65L70 75" class="d"/><text x="205" y="65">Re</text><text x="125" y="25">Im</text></svg>`,
  nb: { t: "Overføringsfunksjon og poler",
    intro: "En overføringsfunksjon $G(s)$ beskriver forholdet mellom et systems utgang og inngang i Laplace-planet. Polene er verdiene av $s$ som gjør nevneren null, og de bestemmer om systemet er stabilt: er realdelen til alle polene negativ, ligger de i venstre halvplan og systemet er stabilt. Nullpunktene former responsen, men avgjør ikke stabiliteten.",
    f: [["G(s)=\\dfrac{Y(s)}{U(s)}", "overføringsfunksjon, utgang delt på inngang"], ["D(s)=0", "karakteristisk ligning; røttene er polene"]],
    legend: [["G(s)", "overføringsfunksjon", ""], ["Y(s),\\ U(s)", "Laplace-transformert utgang/inngang", ""], ["D(s)", "nevneren (karakteristisk polynom)", ""]],
    ex: "$G(s)=\\dfrac{5}{s+2}$:\nPol i $s=-2$, som ligger i venstre halvplan $\\Rightarrow$ stabilt system.",
    tip: "Det er polene, ikke nullpunktene, som avgjør om et system er stabilt." },
  en: { t: "Transfer Function and Poles",
    intro: "A transfer function $G(s)$ describes the ratio between a system's output and input in the Laplace domain. The poles are the values of $s$ that make the denominator zero, and they determine whether the system is stable: if the real part of every pole is negative, they lie in the left half-plane and the system is stable. The zeros shape the response, but do not determine stability.",
    f: [["G(s)=\\dfrac{Y(s)}{U(s)}", "transfer function, output over input"], ["D(s)=0", "characteristic equation; its roots are the poles"]],
    legend: [["G(s)", "transfer function", ""], ["Y(s),\\ U(s)", "Laplace-transformed output/input", ""], ["D(s)", "the denominator (characteristic polynomial)", ""]],
    ex: "$G(s)=\\dfrac{5}{s+2}$:\nPole at $s=-2$, which lies in the left half-plane $\\Rightarrow$ stable system.",
    tip: "It is the poles, not the zeros, that determine whether a system is stable." } },
{ id: "forsteordens-system",
  fig: `<svg viewBox="0 0 240 140"><path d="M30 120H220M30 120V20" class="dim"/><path d="M30 110C70 40 120 20 210 20" class="d"/><path d="M30 20H210" class="dash"/><text x="212" y="16">K</text><text x="215" y="132">t</text></svg>`,
  nb: { t: "Førsteordens system",
    intro: "Et førsteordens system har overføringsfunksjonen $K/(\\tau s+1)$, med én pol i $s=-1/\\tau$. Responsen på et enhetssprang går eksponentielt mot sluttverdien $K$, og etter én tidskonstant $\\tau$ er den kommet 63 % av veien. Denne enkle formen dukker opp overalt: temperaturprosesser, RC-kretser og enkle motorer.",
    f: [["G(s)=\\dfrac{K}{\\tau s+1}", "førsteordens overføringsfunksjon"], ["G(0)=K", "sluttverdi ved et enhetssprang"]],
    legend: [["K", "statisk forsterkning (sluttverdi)", ""], ["\\tau", "tidskonstant", "s"]],
    ex: "$G(s)=\\dfrac{4}{2s+1}$:\nSluttverdi $G(0)=4$. Tidskonstant $\\tau=2$ s.",
    tip: "Polen ligger i $s=-1/\\tau$ – finn $\\tau$ direkte fra nevnerens form $\\tau s+1$." },
  en: { t: "First-Order System",
    intro: "A first-order system has the transfer function $K/(\\tau s+1)$, with a single pole at $s=-1/\\tau$. The response to a unit step goes exponentially toward the final value $K$, and after one time constant $\\tau$ it has covered 63% of the way. This simple form shows up everywhere: temperature processes, RC circuits and simple motors.",
    f: [["G(s)=\\dfrac{K}{\\tau s+1}", "first-order transfer function"], ["G(0)=K", "final value for a unit step"]],
    legend: [["K", "static gain (final value)", ""], ["\\tau", "time constant", "s"]],
    ex: "$G(s)=\\dfrac{4}{2s+1}$:\nFinal value $G(0)=4$. Time constant $\\tau=2$ s.",
    tip: "The pole is at $s=-1/\\tau$ – read $\\tau$ directly from the denominator's form $\\tau s+1$." } },
{ id: "andreordens-system",
  fig: `<svg viewBox="0 0 240 140"><path d="M30 120H220M30 120V20" class="dim"/><path d="M30 110C60 50 80 25 100 30S130 55 140 55S155 45 165 48S180 42 190 44S205 40 215 40" class="d"/><path d="M30 45H215" class="dash"/><text x="217" y="41">K</text><text x="215" y="132">t</text></svg>`,
  nb: { t: "Andreordens system og oversving",
    intro: "Et andreordens system med naturlig frekvens $\\omega_n$ og dempingsforhold $\\zeta$ kan svinge før det stabiliserer seg, avhengig av hvor lite dempet det er. For $0<\\zeta<1$ svinger systemet med et oversving som blir mindre jo større $\\zeta$ er, mens $\\zeta\\ge1$ gir ingen svingning i det hele tatt.",
    f: [["G(s)=\\dfrac{\\omega_n^2}{s^2+2\\zeta\\omega_ns+\\omega_n^2}", "andreordens standardform"], ["M_p=e^{-\\pi\\zeta/\\sqrt{1-\\zeta^2}}", "oversving for 0<\\zeta<1"]],
    legend: [["\\omega_n", "udempet naturlig frekvens", "rad/s"], ["\\zeta", "dempingsforhold", ""], ["M_p", "relativt oversving", ""]],
    ex: "$\\omega_n=6$, $\\zeta=0{,}3$:\n$M_p=e^{-\\pi\\cdot0{,}3/\\sqrt{1-0{,}09}}\\approx0{,}37$, altså ca. 37 %.",
    tip: "Lav $\\zeta$ gir stort oversving og mye svingning; $\\zeta\\ge1$ gir ingen svingning i det hele tatt." },
  en: { t: "Second-Order System and Overshoot",
    intro: "A second-order system with natural frequency $\\omega_n$ and damping ratio $\\zeta$ may oscillate before settling, depending on how lightly damped it is. For $0<\\zeta<1$ the system oscillates with an overshoot that shrinks as $\\zeta$ grows, while $\\zeta\\ge1$ gives no oscillation at all.",
    f: [["G(s)=\\dfrac{\\omega_n^2}{s^2+2\\zeta\\omega_ns+\\omega_n^2}", "second-order standard form"], ["M_p=e^{-\\pi\\zeta/\\sqrt{1-\\zeta^2}}", "overshoot for 0<\\zeta<1"]],
    legend: [["\\omega_n", "undamped natural frequency", "rad/s"], ["\\zeta", "damping ratio", ""], ["M_p", "relative overshoot", ""]],
    ex: "$\\omega_n=6$, $\\zeta=0.3$:\n$M_p=e^{-\\pi\\cdot0.3/\\sqrt{1-0.09}}\\approx0.37$, i.e. about 37%.",
    tip: "Low $\\zeta$ gives large overshoot and heavy oscillation; $\\zeta\\ge1$ gives no oscillation at all." } }
]);

// ================= ELFT2400 – enhet 1: PID-regulering =================
TOPICS("ELFT2400", 1, [
{ id: "p-i-d-ledd",
  nb: { t: "P-, I- og D-leddet",
    intro: "En PID-regulator kombinerer tre virkninger som hver løser et problem: P-leddet gir en rask respons proporsjonal med avviket, I-leddet integrerer avviket over tid og fjerner stasjonært avvik, og D-leddet reagerer på hvor fort avviket endrer seg og demper oversving. God regulering handler om å balansere de tre mot hverandre.",
    f: [["C(s)=K_p+\\dfrac{K_i}{s}+K_ds", "ideell PID-regulator"]],
    legend: [["K_p", "proporsjonalforsterkning", ""], ["K_i", "integralforsterkning", ""], ["K_d", "derivatforsterkning", ""]],
    ex: "$K_p=3$, $T_i=0{,}5$ s:\n$K_i=K_p/T_i=3/0{,}5=6$.",
    tip: "Mer $K_p$ gir raskere respons, men mer oversving – legg heller til et I-ledd for å fjerne stasjonært avvik." },
  en: { t: "The P, I and D Terms",
    intro: "A PID controller combines three effects that each solve a problem: the P term gives a fast response proportional to the error, the I term integrates the error over time and removes steady-state error, and the D term reacts to how fast the error is changing and damps overshoot. Good control is about balancing the three against each other.",
    f: [["C(s)=K_p+\\dfrac{K_i}{s}+K_ds", "ideal PID controller"]],
    legend: [["K_p", "proportional gain", ""], ["K_i", "integral gain", ""], ["K_d", "derivative gain", ""]],
    ex: "$K_p=3$, $T_i=0.5$ s:\n$K_i=K_p/T_i=3/0.5=6$.",
    tip: "More $K_p$ gives a faster response but more overshoot – add an I term instead to remove steady-state error." } },
{ id: "lukket-sloyfe",
  fig: `<svg viewBox="0 0 240 140"><path d="M20 70H55" class="a"/><path d="M55 70l-10-5v10z" class="af"/><circle cx="65" cy="70" r="10" class="d"/><path d="M75 70H105" class="a"/><path d="M105 70l-10-5v10z" class="af"/><rect x="105" y="55" width="40" height="30" class="d"/><path d="M145 70H190" class="a"/><path d="M190 70l-10-5v10z" class="af"/><path d="M170 70V110H65V80" class="d"/><rect x="90" y="102" width="40" height="16" class="d"/><path d="M65 80l-5-8h10z" class="af"/><text x="60" y="62">+</text><text x="51" y="90">-</text><text x="120" y="75">G</text><text x="105" y="113">H</text></svg>`,
  nb: { t: "Lukket sløyfe",
    intro: "I et tilbakekoblet reguleringssystem sammenlignes en målt verdi med en referanse, og avviket driver en regulator som påvirker prosessen. Sammenhengen mellom referansen og utgangen for en negativ tilbakekoblet sløyfe med forover-forsterkning $G$ og tilbakekobling $H$ er et enkelt, mye brukt uttrykk.",
    f: [["\\dfrac{Y}{R}=\\dfrac{G}{1+GH}", "lukket-sløyfe-overføringsfunksjon, negativ tilbakekobling"]],
    legend: [["G", "forover-forsterkning (regulator og prosess)", ""], ["H", "tilbakekoblingens overføringsfunksjon", ""], ["Y", "utgang", ""], ["R", "referanse", ""]],
    ex: "$G=10$, $H=1$:\n$Y/R=10/(1+10)\\approx0{,}909$.",
    tip: "Sett opp $G/(1+GH)$ og forenkle før du finner poler eller sluttverdi." },
  en: { t: "Closed Loop",
    intro: "In a feedback control system a measured value is compared with a reference, and the error drives a controller that affects the process. The relationship between the reference and the output for a negative-feedback loop with forward gain $G$ and feedback $H$ is a simple, widely used expression.",
    f: [["\\dfrac{Y}{R}=\\dfrac{G}{1+GH}", "closed-loop transfer function, negative feedback"]],
    legend: [["G", "forward gain (controller and process)", ""], ["H", "the feedback's transfer function", ""], ["Y", "output", ""], ["R", "reference", ""]],
    ex: "$G=10$, $H=1$:\n$Y/R=10/(1+10)\\approx0.909$.",
    tip: "Set up $G/(1+GH)$ and simplify before finding poles or the final value." } },
{ id: "ziegler-nichols",
  fig: `<svg viewBox="0 0 240 140"><path d="M20 70H220" class="dim"/><path d="M20 70C35 40 50 40 65 70S95 100 110 70S140 40 155 70S185 100 200 70S220 55 220 70" class="d"/><text x="60" y="35">T<tspan dy="4" font-size="10">u</tspan></text></svg>`,
  nb: { t: "Ziegler–Nichols",
    intro: "Ziegler–Nichols-metoden gir raske startverdier for en PID-regulator uten å måtte modellere prosessen nøyaktig. Du regulerer først med ren P-regulering og øker forsterkningen til systemet akkurat begynner å svinge vedvarende, ved kritisk forsterkning $K_u$ med periode $T_u$. Disse to tallene settes deretter rett inn i en standardtabell for å finne $K_p$, $T_i$ og $T_d$.",
    f: [["K_p=0{,}6K_u,\\ T_i=\\dfrac{T_u}{2},\\ T_d=\\dfrac{T_u}{8}", "Ziegler–Nichols svingemetode, PID-tabellen"]],
    legend: [["K_u", "kritisk (ultimat) forsterkning", ""], ["T_u", "periode ved vedvarende svingning", "s"]],
    ex: "$K_u=8$, $T_u=1{,}2$ s:\n$K_p=0{,}6\\cdot8=4{,}8$, $T_i=0{,}6$ s, $T_d=0{,}15$ s.",
    tip: "Formlene gjelder bare rett etter at du har funnet $K_u$ og $T_u$ – ikke bland dem med andre innstillingsmetoder." },
  en: { t: "Ziegler-Nichols",
    intro: "The Ziegler-Nichols method gives quick starting values for a PID controller without having to model the process accurately. You first control with pure P action and raise the gain until the system just starts to oscillate continuously, at the ultimate gain $K_u$ with period $T_u$. These two numbers are then plugged straight into a standard table to find $K_p$, $T_i$ and $T_d$.",
    f: [["K_p=0.6K_u,\\ T_i=\\dfrac{T_u}{2},\\ T_d=\\dfrac{T_u}{8}", "Ziegler-Nichols ultimate-gain method, PID table"]],
    legend: [["K_u", "ultimate (critical) gain", ""], ["T_u", "period at sustained oscillation", "s"]],
    ex: "$K_u=8$, $T_u=1.2$ s:\n$K_p=0.6\\cdot8=4.8$, $T_i=0.6$ s, $T_d=0.15$ s.",
    tip: "The formulas only apply right after you have found $K_u$ and $T_u$ – do not mix them with other tuning methods." } }
]);

// ================= ELFT2400 – enhet 2: Frekvensanalyse =================
TOPICS("ELFT2400", 2, [
{ id: "bode-diagram",
  fig: `<svg viewBox="0 0 240 140"><path d="M20 100H220M20 100V20" class="dim"/><path d="M20 40H110" class="d"/><path d="M110 40L200 100" class="d"/><path d="M110 40V110M20 40H110" class="dash"/><text x="25" y="33">|G|</text><text x="105" y="128">ω<tspan dy="4" font-size="10">c</tspan></text></svg>`,
  nb: { t: "Bodediagram",
    intro: "Et Bodediagram viser hvordan forsterkningen (i desibel) og fasen til et system endrer seg med frekvensen, begge plottet mot en logaritmisk frekvensakse. En enkelt pol gir en asymptote som faller 20 dB per dekade over knekkfrekvensen, mens et nullpunkt gir en tilsvarende stigning. Dette lar deg lese av systemets oppførsel uten å regne responsen i tidsplanet.",
    f: [["|G|_{dB}=20\\log_{10}|G|", "forsterkning i desibel"], ["\\omega_c=1/\\tau", "knekkfrekvens for en enkel pol"]],
    legend: [["|G|_{dB}", "forsterkning i desibel", "dB"], ["\\omega_c", "knekkfrekvens", "rad/s"]],
    ex: "$|G|=0{,}1$:\n$|G|_{dB}=20\\log_{10}(0{,}1)=-20$ dB.",
    tip: "En enkelt pol gir $-20$ dB/dekade over knekkfrekvensen; et nullpunkt gir $+20$ dB/dekade." },
  en: { t: "Bode Plot",
    intro: "A Bode plot shows how a system's gain (in decibels) and phase change with frequency, both plotted against a logarithmic frequency axis. A single pole gives an asymptote that falls 20 dB per decade above the corner frequency, while a zero gives a matching rise. This lets you read off the system's behavior without computing the response in the time domain.",
    f: [["|G|_{dB}=20\\log_{10}|G|", "gain in decibels"], ["\\omega_c=1/\\tau", "corner frequency of a single pole"]],
    legend: [["|G|_{dB}", "gain in decibels", "dB"], ["\\omega_c", "corner frequency", "rad/s"]],
    ex: "$|G|=0.1$:\n$|G|_{dB}=20\\log_{10}(0.1)=-20$ dB.",
    tip: "A single pole gives $-20$ dB/decade above the corner frequency; a zero gives $+20$ dB/decade." } },
{ id: "fasemargin",
  fig: `<svg viewBox="0 0 240 140"><path d="M20 100H220M20 100V20" class="dim"/><path d="M20 40C80 40 100 60 140 90S190 110 220 115" class="d"/><path d="M20 115H220" class="dash"/><path d="M140 90V115" class="d"/><text x="8" y="40">φ</text><text x="145" y="128">ω<tspan dy="4" font-size="10">c</tspan></text></svg>`,
  nb: { t: "Fasemargin",
    intro: "Fasemarginen forteller hvor mye ekstra faseforsinkelse den lukkede sløyfen tåler ved gjennomskjæringsfrekvensen (der forsterkningen er 0 dB) før systemet blir ustabilt. En typisk målsetting er 45–60°. Jo mindre fasemargin, desto nærmere er systemet ustabilitet og desto mer svinger det gjerne før det stabiliserer seg.",
    f: [["PM=180^\\circ+\\angle L(j\\omega_c)", "fasemargin ved gjennomskjæringsfrekvensen \\omega_c"]],
    legend: [["PM", "fasemargin", "°"], ["\\omega_c", "gjennomskjæringsfrekvens (der |L|=1)", "rad/s"], ["L", "sløyfeforsterkningen GH", ""]],
    ex: "Fasen ved $\\omega_c$ er $-120^\\circ$:\n$PM=180^\\circ-120^\\circ=60^\\circ$.",
    tip: "Fasemarginen leses av ved 0 dB (gjennomskjæringsfrekvensen), ikke ved $-180^\\circ$." },
  en: { t: "Phase Margin",
    intro: "The phase margin states how much extra phase lag the closed loop can tolerate at the crossover frequency (where the gain is 0 dB) before the system becomes unstable. A typical target is 45-60°. The smaller the phase margin, the closer the system is to instability and the more it tends to oscillate before settling.",
    f: [["PM=180^\\circ+\\angle L(j\\omega_c)", "phase margin at the crossover frequency \\omega_c"]],
    legend: [["PM", "phase margin", "°"], ["\\omega_c", "crossover frequency (where |L|=1)", "rad/s"], ["L", "the loop gain GH", ""]],
    ex: "The phase at $\\omega_c$ is $-120^\\circ$:\n$PM=180^\\circ-120^\\circ=60^\\circ$.",
    tip: "The phase margin is read at 0 dB (the crossover frequency), not at $-180^\\circ$." } },
{ id: "dodtid-fase",
  nb: { t: "Dødtid og fase",
    intro: "En ren tidsforsinkelse (dødtid) i et system endrer aldri forsterkningen, men gir en faseforsinkelse som vokser lineært med frekvensen. Ved lave frekvenser er dette ubetydelig, men ved høyere frekvenser kan dødtiden alene spise opp store deler av fasemarginen og gjøre en ellers stabil sløyfe ustabil.",
    f: [["\\varphi=-\\omega T", "faseforsinkelse fra dødtid T, i radianer"]],
    legend: [["T", "dødtid", "s"], ["\\omega", "frekvens", "rad/s"], ["\\varphi", "faseforsinkelse", "rad"]],
    ex: "$T=0{,}05$ s ved $\\omega=20$ rad/s:\n$\\varphi=-20\\cdot0{,}05=-1$ rad $\\approx-57{,}3^\\circ$.",
    tip: "Dødtid endrer bare fasen, aldri amplituden – ikke regn den inn i $|G|_{dB}$." },
  en: { t: "Dead Time and Phase",
    intro: "A pure time delay (dead time) in a system never changes the gain, but produces a phase lag that grows linearly with frequency. At low frequencies this is negligible, but at higher frequencies the dead time alone can eat up a large part of the phase margin and make an otherwise stable loop unstable.",
    f: [["\\varphi=-\\omega T", "phase lag from dead time T, in radians"]],
    legend: [["T", "dead time", "s"], ["\\omega", "frequency", "rad/s"], ["\\varphi", "phase lag", "rad"]],
    ex: "$T=0.05$ s at $\\omega=20$ rad/s:\n$\\varphi=-20\\cdot0.05=-1$ rad $\\approx-57.3^\\circ$.",
    tip: "Dead time only changes the phase, never the magnitude – do not fold it into $|G|_{dB}$." } }
]);

// ================= ELVE3610 – enhet 0: Rotasjoner og transformasjoner =================
TOPICS("ELVE3610", 0, [
{ id: "rotasjonsmatrise",
  fig: `<svg viewBox="0 0 240 140"><path d="M40 115H210M40 115V15" class="dim"/><path d="M40 115L150 45" class="a"/><path d="M150 45l-14 3 5 11z" class="af"/><path d="M40 115L170 115" class="d"/><path d="M78 115a38 38 0 0 1-8 -24" class="t"/><text x="83" y="72">v'</text><text x="84" y="106">θ</text></svg>`,
  nb: { t: "Rotasjonsmatrise",
    intro: "En rotasjonsmatrise dreier en vektor eller et punkt om origo uten å endre lengden. Den er ortogonal, slik at den inverse rotasjonen ganske enkelt er transponeringen. To rotasjoner kan settes sammen ved matrisemultiplikasjon, men i 3D spiller rekkefølgen som regel en rolle.",
    f: [["R(\\theta)=\\begin{pmatrix}\\cos\\theta&-\\sin\\theta\\\\\\sin\\theta&\\cos\\theta\\end{pmatrix}", "rotasjonsmatrise i planet"], ["R^{-1}=R^T,\\ \\det R=1", "rotasjonsmatriser er ortogonale"]],
    legend: [["\\theta", "rotasjonsvinkel", "°"], ["R", "rotasjonsmatrise", ""]],
    ex: "Punktet $(1,0)$ roteres $90°$ mot klokka:\n$(\\cos90^\\circ,\\sin90^\\circ)=(0,1)$.",
    tip: "$R^{-1}=R^T$ – transponering er en billig måte å finne den motsatte rotasjonen på." },
  en: { t: "Rotation Matrix",
    intro: "A rotation matrix turns a vector or a point about the origin without changing its length. It is orthogonal, so the inverse rotation is simply its transpose. Two rotations can be combined by matrix multiplication, but in 3D the order usually matters.",
    f: [["R(\\theta)=\\begin{pmatrix}\\cos\\theta&-\\sin\\theta\\\\\\sin\\theta&\\cos\\theta\\end{pmatrix}", "rotation matrix in the plane"], ["R^{-1}=R^T,\\ \\det R=1", "rotation matrices are orthogonal"]],
    legend: [["\\theta", "rotation angle", "°"], ["R", "rotation matrix", ""]],
    ex: "The point $(1,0)$ is rotated $90°$ counterclockwise:\n$(\\cos90^\\circ,\\sin90^\\circ)=(0,1)$.",
    tip: "$R^{-1}=R^T$ – transposing is a cheap way to find the opposite rotation." } },
{ id: "homogen-transformasjon",
  fig: `<svg viewBox="0 0 240 140"><path d="M40 110H90M40 110V60" class="dim"/><path d="M150 90H200M150 90V40" class="a"/><path d="M40 110L150 90" class="d"/><circle cx="185" cy="55" r="3" class="rf"/><text x="29" y="122">A</text><text x="155" y="35">B</text></svg>`,
  nb: { t: "Homogen transformasjon",
    intro: "En homogen transformasjonsmatrise kombinerer en rotasjon og en forflytning (translasjon) i én operasjon, og gjør det enkelt å regne koordinater om fra én ramme til en annen. Kjeder du sammen flere rammer, ledd for ledd langs en robotarm, multipliserer du transformasjonsmatrisene i riktig rekkefølge.",
    f: [["T=\\begin{pmatrix}R&\\vec p\\\\0&1\\end{pmatrix}", "homogen transformasjon: rotasjon R og translasjon \\vec p"], ["\\vec x_G=R\\vec x_L+\\vec p", "globale koordinater fra lokale"]],
    legend: [["R", "rotasjonsmatrise", ""], ["\\vec p", "origo til den nye rammen, i den gamle", ""], ["\\vec x_L,\\ \\vec x_G", "lokale og globale koordinater", ""]],
    ex: "Ramme B rotert $90°$ og forskjøvet $(5,0)$; punktet $(1,0)$ lokalt:\n$\\vec x_G=(\\cos90^\\circ\\cdot1,\\sin90^\\circ\\cdot1)+(5,0)=(5,1)$.",
    tip: "Rotasjon og translasjon i én matrise – husk å rotere først, deretter legge til $\\vec p$." },
  en: { t: "Homogeneous Transformation",
    intro: "A homogeneous transformation matrix combines a rotation and a translation in one operation, making it easy to convert coordinates from one frame to another. When you chain several frames, link by link along a robot arm, you multiply the transformation matrices in the right order.",
    f: [["T=\\begin{pmatrix}R&\\vec p\\\\0&1\\end{pmatrix}", "homogeneous transform: rotation R and translation \\vec p"], ["\\vec x_G=R\\vec x_L+\\vec p", "global coordinates from local ones"]],
    legend: [["R", "rotation matrix", ""], ["\\vec p", "origin of the new frame, in the old one", ""], ["\\vec x_L,\\ \\vec x_G", "local and global coordinates", ""]],
    ex: "Frame B rotated $90°$ and shifted $(5,0)$; the point $(1,0)$ locally:\n$\\vec x_G=(\\cos90^\\circ\\cdot1,\\sin90^\\circ\\cdot1)+(5,0)=(5,1)$.",
    tip: "Rotation and translation in one matrix – remember to rotate first, then add $\\vec p$." } },
{ id: "euler-kvaternion",
  nb: { t: "Euler-vinkler og kvaternioner",
    intro: "Euler-vinkler beskriver en orientering med tre påfølgende rotasjoner, men kan rammes av gimbal lock: to rotasjonsakser faller sammen, og én frihetsgrad går tapt. Kvaternioner bruker fire tall i stedet for tre, unngår denne singulariteten helt, og gir jevnere interpolasjon mellom to orienteringer.",
    f: [["\\text{Euler: 3 vinkler, kan gi gimbal lock}", "begrensning ved Euler-vinkler"], ["\\text{Kvaternion: 4 tall, ingen gimbal lock}", "fordel ved kvaternioner"]],
    legend: [["q", "kvaternion (4 tall)", ""]],
    ex: "En robotarms håndledd nærmer seg en Euler-singularitet:\nEt kvaternion unngår problemet helt.",
    tip: "Gimbal lock er en reell singularitet i Euler-vinkler, ikke bare en teoretisk kuriositet." },
  en: { t: "Euler Angles and Quaternions",
    intro: "Euler angles describe an orientation with three successive rotations, but can suffer from gimbal lock: two rotation axes line up and one degree of freedom is lost. Quaternions use four numbers instead of three, avoid this singularity entirely, and give smoother interpolation between two orientations.",
    f: [["\\text{Euler: 3 angles, can gimbal lock}", "limitation of Euler angles"], ["\\text{Quaternion: 4 numbers, no gimbal lock}", "advantage of quaternions"]],
    legend: [["q", "quaternion (4 numbers)", ""]],
    ex: "A robot arm's wrist approaches an Euler singularity:\nA quaternion avoids the problem entirely.",
    tip: "Gimbal lock is a real singularity in Euler angles, not just a theoretical curiosity." } }
]);

// ================= ELVE3610 – enhet 1: Kinematikk =================
TOPICS("ELVE3610", 1, [
{ id: "foroverkinematikk",
  fig: `<svg viewBox="0 0 240 140"><path d="M40 120H220" class="dim"/><circle cx="40" cy="120" r="3" class="d"/><path d="M40 120L120 60" class="b"/><circle cx="120" cy="60" r="3" class="d"/><path d="M120 60L190 90" class="b"/><circle cx="190" cy="90" r="3" class="af"/><text x="62" y="78">L<tspan dy="4" font-size="10">1</tspan></text><text x="152" y="62">L<tspan dy="4" font-size="10">2</tspan></text></svg>`,
  nb: { t: "Foroverkinematikk",
    intro: "Foroverkinematikk regner ut verktøyets posisjon og orientering direkte fra de kjente leddvinklene. For en planar 2-leddsarm summeres bidraget fra hvert ledd med enkel trigonometri. Dette er alltid entydig: gitt leddvinklene, er det bare én mulig verktøyposisjon.",
    f: [["x=L_1\\cos\\theta_1+L_2\\cos(\\theta_1+\\theta_2)", "x-koordinat for en planar 2-leddsarm"], ["y=L_1\\sin\\theta_1+L_2\\sin(\\theta_1+\\theta_2)", "y-koordinat for samme arm"]],
    legend: [["L_1,\\ L_2", "leddlengder", "m"], ["\\theta_1,\\ \\theta_2", "leddvinkler", "°"]],
    ex: "$L_1=L_2=1$ m, $\\theta_1=0$, $\\theta_2=90°$:\n$x=1+\\cos90°=1$, $y=0+\\sin90°=1$.",
    tip: "Foroverkinematikk har alltid nøyaktig én løsning – det er inverskinematikk som kan ha flere." },
  en: { t: "Forward Kinematics",
    intro: "Forward kinematics computes the tool's position and orientation directly from the known joint angles. For a planar 2-link arm the contribution from each link is summed with simple trigonometry. This is always unambiguous: given the joint angles, there is only one possible tool position.",
    f: [["x=L_1\\cos\\theta_1+L_2\\cos(\\theta_1+\\theta_2)", "x-coordinate for a planar 2-link arm"], ["y=L_1\\sin\\theta_1+L_2\\sin(\\theta_1+\\theta_2)", "y-coordinate for the same arm"]],
    legend: [["L_1,\\ L_2", "link lengths", "m"], ["\\theta_1,\\ \\theta_2", "joint angles", "°"]],
    ex: "$L_1=L_2=1$ m, $\\theta_1=0$, $\\theta_2=90°$:\n$x=1+\\cos90°=1$, $y=0+\\sin90°=1$.",
    tip: "Forward kinematics always has exactly one solution – it is inverse kinematics that can have several." } },
{ id: "inverskinematikk-2ledd",
  fig: `<svg viewBox="0 0 240 140"><path d="M40 120H220" class="dim"/><circle cx="40" cy="120" r="3" class="d"/><path d="M40 120L110 65" class="b"/><circle cx="110" cy="65" r="3" class="d"/><path d="M110 65L170 100" class="b"/><path d="M170 100l6 3-3-7z" class="rf"/><circle cx="170" cy="100" r="4" class="r"/><text x="179" y="98">P</text></svg>`,
  nb: { t: "Inverskinematikk (2 ledd)",
    intro: "Inverskinematikk går motsatt vei av foroverkinematikk: gitt en ønsket verktøyposisjon, finner vi leddvinklene som gir den. For en planar 2-leddsarm løses $\\theta_2$ med cosinussetningen, og løsningen kan gi to muligheter (albue opp eller albue ned) eller ingen løsning hvis målet ligger utenfor arbeidsområdet.",
    f: [["\\cos\\theta_2=\\dfrac{x^2+y^2-L_1^2-L_2^2}{2L_1L_2}", "cosinussetningen løst for \\theta_2"]],
    legend: [["x,\\ y", "ønsket verktøyposisjon", "m"], ["L_1,\\ L_2", "leddlengder", "m"], ["\\theta_2", "albuevinkel", "°"]],
    ex: "$L_1=1$ m, $L_2=0{,}6$ m, mål $(1{,}2,\\ 0{,}4)$ m:\n$\\cos\\theta_2\\approx0{,}200 \\Rightarrow \\theta_2\\approx78{,}5°$.",
    tip: "Sjekk alltid at målet ligger innenfor arbeidsområdet $|L_1-L_2|\\le r\\le L_1+L_2$ før du løser IK." },
  en: { t: "Inverse Kinematics (2 Links)",
    intro: "Inverse kinematics goes the opposite way of forward kinematics: given a desired tool position, we find the joint angles that produce it. For a planar 2-link arm, $\\theta_2$ is solved with the law of cosines, and the solution can give two possibilities (elbow up or elbow down) or no solution if the target lies outside the workspace.",
    f: [["\\cos\\theta_2=\\dfrac{x^2+y^2-L_1^2-L_2^2}{2L_1L_2}", "law of cosines solved for \\theta_2"]],
    legend: [["x,\\ y", "desired tool position", "m"], ["L_1,\\ L_2", "link lengths", "m"], ["\\theta_2", "elbow angle", "°"]],
    ex: "$L_1=1$ m, $L_2=0.6$ m, target $(1.2,\\ 0.4)$ m:\n$\\cos\\theta_2\\approx0.200 \\Rightarrow \\theta_2\\approx78.5°$.",
    tip: "Always check the target lies within the workspace $|L_1-L_2|\\le r\\le L_1+L_2$ before solving the IK." } },
{ id: "jacobi-singularitet",
  nb: { t: "Jacobimatrise og singularitet",
    intro: "Jacobimatrisen knytter leddhastighetene til verktøyets hastighet: en liten endring i leddvinklene gir en tilsvarende endring i verktøyets posisjon, skalert med $J$. En singularitet er en konfigurasjon der $J$ mister rang, slik at selv en liten ønsket verktøyhastighet krever urealistisk store leddhastigheter.",
    f: [["\\dot{\\mathbf x}=J(\\mathbf q)\\,\\dot{\\mathbf q}", "Jacobimatrisen relaterer leddhastighet til verktøyhastighet"]],
    legend: [["J(\\mathbf q)", "Jacobimatrisen", ""], ["\\dot{\\mathbf q}", "leddhastigheter", ""], ["\\dot{\\mathbf x}", "verktøyets hastighet", ""]],
    ex: "En 6-akset arm med 6 oppgavefrihetsgrader:\n$J$ er $6\\times6$; mister den rang, oppstår en singularitet.",
    tip: "Nær en singularitet blir leddhastighetene urealistisk store selv for en liten verktøyhastighet." },
  en: { t: "Jacobian and Singularity",
    intro: "The Jacobian relates the joint velocities to the tool's velocity: a small change in the joint angles produces a corresponding change in the tool's position, scaled by $J$. A singularity is a configuration where $J$ loses rank, so that even a small desired tool velocity requires unrealistically large joint velocities.",
    f: [["\\dot{\\mathbf x}=J(\\mathbf q)\\,\\dot{\\mathbf q}", "the Jacobian relates joint velocity to tool velocity"]],
    legend: [["J(\\mathbf q)", "the Jacobian", ""], ["\\dot{\\mathbf q}", "joint velocities", ""], ["\\dot{\\mathbf x}", "the tool's velocity", ""]],
    ex: "A 6-axis arm with 6 task degrees of freedom:\n$J$ is $6\\times6$; if it loses rank, a singularity occurs.",
    tip: "Near a singularity the joint velocities become unrealistically large even for a small tool velocity." } }
]);

// ================= ELVE3610 – enhet 2: Robotsystemer =================
TOPICS("ELVE3610", 2, [
{ id: "robotkonfigurasjoner",
  nb: { t: "Robotkonfigurasjoner",
    intro: "Ulike robottyper passer til ulike oppgaver. En leddarm (artikulert) har flest frihetsgrader og er svært fleksibel, en SCARA er stiv vertikalt og ettergivende horisontalt og derfor rask til plukk-og-plasser i et plan, mens en kartesisk (gantry) robot har rette, uavhengige akser som gjør den enkel å styre nøyaktig.",
    f: [["\\text{SCARA: rask plukk-og-plasser i et plan}", "typisk bruksområde"], ["\\text{Kartesisk: rette akser, høy nøyaktighet}", "typisk bruksområde"]],
    legend: [["R", "revolutt ledd (roterer)", ""], ["P", "prismatisk ledd (forskyves lineært)", ""]],
    ex: "En RRR-arm har tre revolutte ledd, alle roterende:\nEn typisk leddarm-konfigurasjon.",
    tip: "Flere frihetsgrader er ikke alltid bedre – en SCARA er ofte raskere og billigere for en oppgave i et plan." },
  en: { t: "Robot Configurations",
    intro: "Different robot types suit different tasks. An articulated arm has the most degrees of freedom and is very flexible, a SCARA is stiff vertically and compliant horizontally and therefore fast at pick-and-place in a plane, while a Cartesian (gantry) robot has straight, independent axes that make it simple to control accurately.",
    f: [["\\text{SCARA: fast pick-and-place in a plane}", "typical use case"], ["\\text{Cartesian: straight axes, high accuracy}", "typical use case"]],
    legend: [["R", "revolute joint (rotates)", ""], ["P", "prismatic joint (slides linearly)", ""]],
    ex: "An RRR arm has three revolute joints, all rotating:\nA typical articulated-arm configuration.",
    tip: "More degrees of freedom is not always better – a SCARA is often faster and cheaper for a planar task." } },
{ id: "enkodere",
  nb: { t: "Enkodere",
    intro: "En enkoder måler et robotledds vinkelposisjon. En inkrementell enkoder teller pulser fra et referansepunkt og må «hjemmes» etter hver oppstart, mens en absolutt enkoder gir vinkelen direkte, også rett etter et strømbrudd, men koster mer. Oppløsningen til en absolutt enkoder avhenger av hvor mange biter den har.",
    f: [["\\Delta\\theta=\\dfrac{360^\\circ}{2^n}", "minste vinkeloppløsning for en n-bits absolutt enkoder"]],
    legend: [["n", "antall biter", ""], ["\\Delta\\theta", "vinkeloppløsning", "°"]],
    ex: "$n=12$ bit:\n$\\Delta\\theta=360/2^{12}=360/4096\\approx0{,}088°$.",
    tip: "Inkrementelle enkodere må hjemmes etter strømbrudd – absolutte husker vinkelen direkte." },
  en: { t: "Encoders",
    intro: "An encoder measures a robot joint's angular position. An incremental encoder counts pulses from a reference point and must be homed after every start-up, while an absolute encoder gives the angle directly, even right after a power loss, but costs more. The resolution of an absolute encoder depends on how many bits it has.",
    f: [["\\Delta\\theta=\\dfrac{360^\\circ}{2^n}", "smallest angular resolution for an n-bit absolute encoder"]],
    legend: [["n", "number of bits", ""], ["\\Delta\\theta", "angular resolution", "°"]],
    ex: "$n=12$ bits:\n$\\Delta\\theta=360/2^{12}=360/4096\\approx0.088°$.",
    tip: "Incremental encoders must be homed after a power loss – absolute ones remember the angle directly." } },
{ id: "girkasse-moment",
  nb: { t: "Girkasse og moment",
    intro: "De fleste robotledd drives av en elektrisk motor gjennom en girkasse som øker momentet og reduserer hastigheten. Utgangsmomentet er motormomentet multiplisert med utvekslingen og virkningsgraden, som alltid er mindre enn 1 fordi noe energi går tapt som friksjon og varme i giret.",
    f: [["\\tau_{ut}=\\tau_{inn}\\cdot N\\cdot\\eta", "moment ut av en girkasse"]],
    legend: [["\\tau_{inn}", "motormoment inn på giret", "Nm"], ["N", "utveksling (girforhold)", ""], ["\\eta", "virkningsgrad", ""]],
    ex: "$\\tau_{inn}=0{,}6$ Nm, $N=100$, $\\eta=0{,}85$:\n$\\tau_{ut}=0{,}6\\cdot100\\cdot0{,}85=51$ Nm.",
    tip: "Ikke glem virkningsgraden $\\eta$ – det virkelige utgangsmomentet er alltid litt mindre enn $\\tau_{inn}\\cdot N$." },
  en: { t: "Gearbox and Torque",
    intro: "Most robot joints are driven by an electric motor through a gearbox that increases torque and reduces speed. The output torque is the motor torque multiplied by the gear ratio and the efficiency, which is always less than 1 because some energy is lost as friction and heat in the gearbox.",
    f: [["\\tau_{out}=\\tau_{in}\\cdot N\\cdot\\eta", "torque out of a gearbox"]],
    legend: [["\\tau_{in}", "motor torque into the gearbox", "Nm"], ["N", "gear ratio", ""], ["\\eta", "efficiency", ""]],
    ex: "$\\tau_{in}=0.6$ Nm, $N=100$, $\\eta=0.85$:\n$\\tau_{out}=0.6\\cdot100\\cdot0.85=51$ Nm.",
    tip: "Do not forget the efficiency $\\eta$ – the real output torque is always a bit less than $\\tau_{in}\\cdot N$." } }
]);
